In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'GHANA']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

GHANA    215
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    201
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [8]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [9]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [10]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
1646,Certified,194,19104,PENNSYLVANIA,10000.0,71686.0,GHANA,H-1B,Master's,1.0
4197,Certified,196,48859,MICHIGAN,2200.0,60000.0,GHANA,H-1B,Doctorate,1.0
4728,Certified,163,60606,ILLINOIS,932.0,140000.0,GHANA,H-1B,Master's,11.0
5126,Certified,202,47201,INDIANA,39800.0,80000.0,GHANA,H-1B,Doctorate,2.0
7837,Certified,512,26506,WEST VIRGINIA,8426.0,58000.0,GHANA,F-1,Master's,1.0

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

CALIFORNIA        30
TEXAS             21
NEW YORK          14
PENNSYLVANIA      12
NEW JERSEY        12
WASHINGTON        11
MARYLAND          10
OHIO               9
ILLINOIS           8
VIRGINIA           7
MASSACHUSETTS      6
INDIANA            6
MICHIGAN           5
WISCONSIN          4
GEORGIA            4
FLORIDA            4
ALABAMA            4
ARIZONA            3
CONNECTICUT        3
MAINE              2
MISSISSIPPI        2
NORTH DAKOTA       2
DELAWARE           2
NEW MEXICO         2
SOUTH CAROLINA     2
MISSOURI           2
SOUTH DAKOTA       1
KENTUCKY           1
OREGON             1
WEST VIRGINIA      1
IDAHO              1
UTAH               1
NEVADA             1
KANSAS             1
COLORADO           1
OKLAHOMA           1
TENNESSEE          1
LOUISIANA          1
MINNESOTA          1
ARKANSAS           1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
1646,Certified,194,19104,PENNSYLVANIA,10000.0,71686.0,GHANA,H-1B,Master's,1.0,PENNSYLVANIA
4197,Certified,196,48859,MICHIGAN,2200.0,60000.0,GHANA,H-1B,Doctorate,1.0,MICHIGAN
4728,Certified,163,60606,ILLINOIS,932.0,140000.0,GHANA,H-1B,Master's,11.0,ILLINOIS
5126,Certified,202,47201,INDIANA,39800.0,80000.0,GHANA,H-1B,Doctorate,2.0,INDIANA
7837,Certified,512,26506,WEST VIRGINIA,8426.0,58000.0,GHANA,F-1,Master's,1.0,WEST VIRGINIA

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

SOUTH        59
NORTHEAST    48
WEST         48
MIDWEST      39
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      194
DECISION_ELAPSED_DAYS            194
EMPLOYER_POSTAL_CODE             194
EMPLOYER_STATE                   194
EMPLOYER_NUM_EMPLOYEES           194
WAGE_OFFER_FROM_9089             194
COUNTRY_OF_CITIZENSHIP           194
CLASS_OF_ADMISSION               194
FOREIGN_WORKER_INFO_EDUCATION    194
CASE_RECEIVED_DATE_MONTH         194
EMPLOYER_STATES                  194
EMPLOYER_REGIONS                 194
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      81
0-90        64
181-365     35
366-3600    14
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

100000-500000    72
75001-100000     61
50001-75000      45
25001-50000      16
0-25000           0
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

10001-1000000000    76
1001-10000          54
101-500             20
0-50                19
501-1000            14
51-100              10
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      194
DECISION_ELAPSED_DAYS            194
EMPLOYER_POSTAL_CODE             194
EMPLOYER_STATE                   194
EMPLOYER_NUM_EMPLOYEES           194
WAGE_OFFER_FROM_9089             194
COUNTRY_OF_CITIZENSHIP           194
CLASS_OF_ADMISSION               194
FOREIGN_WORKER_INFO_EDUCATION    194
CASE_RECEIVED_DATE_MONTH         194
EMPLOYER_STATES                  194
EMPLOYER_REGIONS                 194
DAY_BINS                         194
WAGE_BINS                        194
EMPLOYEE_BINS                    193
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
1646,Certified,1001-10000,50001-75000,NORTHEAST,1.0,Master's,H-1B,181-365
4197,Certified,1001-10000,50001-75000,MIDWEST,1.0,Doctorate,H-1B,181-365
4728,Certified,501-1000,100000-500000,MIDWEST,11.0,Master's,H-1B,91-180
5126,Certified,10001-1000000000,75001-100000,MIDWEST,2.0,Doctorate,H-1B,181-365
7837,Certified,1001-10000,50001-75000,SOUTH,1.0,Master's,F-1,366-3600

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
1646,Certified,1001-10000,50001-75000,NORTHEAST,1.0,Master's,H-1B,181-365,2,4,2,1,1,2
4197,Certified,1001-10000,50001-75000,MIDWEST,1.0,Doctorate,H-1B,181-365,2,2,2,0,1,2
4728,Certified,501-1000,100000-500000,MIDWEST,11.0,Master's,H-1B,91-180,2,4,0,0,3,4
5126,Certified,10001-1000000000,75001-100000,MIDWEST,2.0,Doctorate,H-1B,181-365,2,2,3,0,1,1
7837,Certified,1001-10000,50001-75000,SOUTH,1.0,Master's,F-1,366-3600,0,4,2,2,2,2

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           194
EMPLOYEE_BINS                         194
WAGE_BINS                             194
EMPLOYER_REGIONS                      194
CASE_RECEIVED_DATE_MONTH              194
FOREIGN_WORKER_INFO_EDUCATION         194
CLASS_OF_ADMISSION                    194
DAY_BINS                              194
CLASS_OF_ADMISSION_CODE               194
FOREIGN_WORKER_INFO_EDUCATION_CODE    194
WAGE_BINS_CODE                        194
EMPLOYER_REGIONS_CODE                 194
DAY_BINS_CODE                         194
EMPLOYEE_BINS_CODE                    194
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
1646,Certified,2,2,1,4,2,1.0,1
4197,Certified,2,2,1,2,2,1.0,0
4728,Certified,4,0,3,4,2,11.0,0
5126,Certified,1,3,1,2,2,2.0,0
7837,Certified,2,2,2,4,0,1.0,2

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int32
WAGE_BINS_CODE                          int32
DAY_BINS_CODE                           int32
FOREIGN_WORKER_INFO_EDUCATION_CODE      int32
CLASS_OF_ADMISSION_CODE                 int32
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int32
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(194, 7) (194,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int32, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [53]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 1s - loss: 0.5985 - acc: 0.8828
Epoch 2/500
 - 0s - loss: 0.4279 - acc: 0.9241
Epoch 3/500
 - 0s - loss: 0.3290 - acc: 0.9241
Epoch 4/500
 - 0s - loss: 0.2847 - acc: 0.9241
Epoch 5/500
 - 0s - loss: 0.2799 - acc: 0.9241
Epoch 6/500
 - 0s - loss: 0.2762 - acc: 0.9241
Epoch 7/500
 - 0s - loss: 0.2715 - acc: 0.9241
Epoch 8/500
 - 0s - loss: 0.2656 - acc: 0.9241
Epoch 9/500
 - 0s - loss: 0.2582 - acc: 0.9241
Epoch 10/500
 - 0s - loss: 0.2518 - acc: 0.9241
Epoch 11/500
 - 0s - loss: 0.2501 - acc: 0.9241
Epoch 12/500
 - 0s - loss: 0.2452 - acc: 0.9241
Epoch 13/500
 - 0s - loss: 0.2401 - acc: 0.9241
Epoch 14/500
 - 0s - loss: 0.2351 - acc: 0.9241
Epoch 15/500
 - 0s - loss: 0.2326 - acc: 0.9241
Epoch 16/500
 - 0s - loss: 0.2283 - acc: 0.9241
Epoch 17/500
 - 0s - loss: 0.2242 - acc: 0.9241
Epoch 18/500
 - 0s - loss: 0.2206 - acc: 0.9241
Epoch 19/500
 - 0s - loss: 0.2173 - acc: 0.9241
Epoch 20/500
 - 0s - loss: 0.2150 - acc: 0.9241
Epoch 21/500
 - 0s - loss: 0.2111 - acc: 0.9241
Epoch 22/500
 - 0s - loss: 0.2076 - acc: 0.9241
Epoch 23/500
 - 0s - loss: 0.2036 - acc: 0.9241
Epoch 24/500
 - 0s - loss: 0.2001 - acc: 0.9241
Epoch 25/500
 - 0s - loss: 0.1958 - acc: 0.9241
Epoch 26/500
 - 0s - loss: 0.1939 - acc: 0.9241
Epoch 27/500
 - 0s - loss: 0.1883 - acc: 0.9241
Epoch 28/500
 - 0s - loss: 0.1859 - acc: 0.9241
Epoch 29/500
 - 0s - loss: 0.1802 - acc: 0.9241
Epoch 30/500
 - 0s - loss: 0.1777 - acc: 0.9241
Epoch 31/500
 - 0s - loss: 0.1742 - acc: 0.9241
Epoch 32/500
 - 0s - loss: 0.1700 - acc: 0.9241
Epoch 33/500
 - 0s - loss: 0.1666 - acc: 0.9241
Epoch 34/500
 - 0s - loss: 0.1649 - acc: 0.9241
Epoch 35/500
 - 0s - loss: 0.1595 - acc: 0.9241
Epoch 36/500
 - 0s - loss: 0.1568 - acc: 0.9241
Epoch 37/500
 - 0s - loss: 0.1536 - acc: 0.9241
Epoch 38/500
 - 0s - loss: 0.1503 - acc: 0.9310
Epoch 39/500
 - 0s - loss: 0.1471 - acc: 0.9310
Epoch 40/500
 - 0s - loss: 0.1429 - acc: 0.9310
Epoch 41/500
 - 0s - loss: 0.1393 - acc: 0.9310
Epoch 42/500
 - 0s - loss: 0.1372 - acc: 0.9310
Epoch 43/500
 - 0s - loss: 0.1335 - acc: 0.9310
Epoch 44/500
 - 0s - loss: 0.1293 - acc: 0.9310
Epoch 45/500
 - 0s - loss: 0.1265 - acc: 0.9310
Epoch 46/500
 - 0s - loss: 0.1230 - acc: 0.9448
Epoch 47/500
 - 0s - loss: 0.1215 - acc: 0.9448
Epoch 48/500
 - 0s - loss: 0.1157 - acc: 0.9448
Epoch 49/500
 - 0s - loss: 0.1122 - acc: 0.9448
Epoch 50/500
 - 0s - loss: 0.1088 - acc: 0.9448
Epoch 51/500
 - 0s - loss: 0.1060 - acc: 0.9448
Epoch 52/500
 - 0s - loss: 0.1029 - acc: 0.9448
Epoch 53/500
 - 0s - loss: 0.1015 - acc: 0.9448
Epoch 54/500
 - 0s - loss: 0.0983 - acc: 0.9448
Epoch 55/500
 - 0s - loss: 0.0945 - acc: 0.9448
Epoch 56/500
 - 0s - loss: 0.0930 - acc: 0.9448
Epoch 57/500
 - 0s - loss: 0.0891 - acc: 0.9448
Epoch 58/500
 - 0s - loss: 0.0890 - acc: 0.9448
Epoch 59/500
 - 0s - loss: 0.0853 - acc: 0.9448
Epoch 60/500
 - 0s - loss: 0.0842 - acc: 0.9793
Epoch 61/500
 - 0s - loss: 0.0802 - acc: 0.9586
Epoch 62/500
 - 0s - loss: 0.0795 - acc: 0.9448
Epoch 63/500
 - 0s - loss: 0.0769 - acc: 0.9655
Epoch 64/500
 - 0s - loss: 0.0749 - acc: 0.9724
Epoch 65/500
 - 0s - loss: 0.0694 - acc: 0.9793
Epoch 66/500
 - 0s - loss: 0.0674 - acc: 0.9793
Epoch 67/500
 - 0s - loss: 0.0655 - acc: 0.9724
Epoch 68/500
 - 0s - loss: 0.0636 - acc: 1.0000
Epoch 69/500
 - 0s - loss: 0.0620 - acc: 0.9862
Epoch 70/500
 - 0s - loss: 0.0620 - acc: 0.9931
Epoch 71/500
 - 0s - loss: 0.0575 - acc: 0.9931
Epoch 72/500
 - 0s - loss: 0.0592 - acc: 0.9793
Epoch 73/500
 - 0s - loss: 0.0547 - acc: 0.9862
Epoch 74/500
 - 0s - loss: 0.0541 - acc: 0.9931
Epoch 75/500
 - 0s - loss: 0.0526 - acc: 1.0000
Epoch 76/500
 - 0s - loss: 0.0486 - acc: 1.0000
Epoch 77/500
 - 0s - loss: 0.0482 - acc: 1.0000
Epoch 78/500
 - 0s - loss: 0.0453 - acc: 1.0000
Epoch 79/500
 - 0s - loss: 0.0444 - acc: 1.0000
Epoch 80/500
 - 0s - loss: 0.0425 - acc: 1.0000
Epoch 81/500
 - 0s - loss: 0.0409 - acc: 1.0000
Epoch 82/500
 - 0s - loss: 0.0400 - acc: 1.0000
Epoch 83/500
 - 0s - loss: 0.0386 - acc: 1.0000
Epoch 84/500
 - 0s - loss: 0.0392 - acc: 1.0000
Epoch 85/500
 - 0s - loss: 0.0384 - acc: 1.0000
Epoch 86/500
 - 0s - loss: 0.0362 - acc: 1.0000
Epoch 87/500
 - 0s - loss: 0.0351 - acc: 1.0000
Epoch 88/500
 - 0s - loss: 0.0327 - acc: 1.0000
Epoch 89/500
 - 0s - loss: 0.0332 - acc: 1.0000
Epoch 90/500
 - 0s - loss: 0.0313 - acc: 1.0000
Epoch 91/500
 - 0s - loss: 0.0324 - acc: 1.0000
Epoch 92/500
 - 0s - loss: 0.0290 - acc: 1.0000
Epoch 93/500
 - 0s - loss: 0.0295 - acc: 1.0000
Epoch 94/500
 - 0s - loss: 0.0281 - acc: 1.0000
Epoch 95/500
 - 0s - loss: 0.0265 - acc: 1.0000
Epoch 96/500
 - 0s - loss: 0.0268 - acc: 1.0000
Epoch 97/500
 - 0s - loss: 0.0251 - acc: 1.0000
Epoch 98/500
 - 0s - loss: 0.0249 - acc: 1.0000
Epoch 99/500
 - 0s - loss: 0.0235 - acc: 1.0000
Epoch 100/500
 - 0s - loss: 0.0228 - acc: 1.0000
Epoch 101/500
 - 0s - loss: 0.0222 - acc: 1.0000
Epoch 102/500
 - 0s - loss: 0.0217 - acc: 1.0000
Epoch 103/500
 - 0s - loss: 0.0210 - acc: 1.0000
Epoch 104/500
 - 0s - loss: 0.0200 - acc: 1.0000
Epoch 105/500
 - 0s - loss: 0.0195 - acc: 1.0000
Epoch 106/500
 - 0s - loss: 0.0190 - acc: 1.0000
Epoch 107/500
 - 0s - loss: 0.0186 - acc: 1.0000
Epoch 108/500
 - 0s - loss: 0.0181 - acc: 1.0000
Epoch 109/500
 - 0s - loss: 0.0176 - acc: 1.0000
Epoch 110/500
 - 0s - loss: 0.0169 - acc: 1.0000
Epoch 111/500
 - 0s - loss: 0.0177 - acc: 1.0000
Epoch 112/500
 - 0s - loss: 0.0164 - acc: 1.0000
Epoch 113/500
 - 0s - loss: 0.0161 - acc: 1.0000
Epoch 114/500
 - 0s - loss: 0.0153 - acc: 1.0000
Epoch 115/500
 - 0s - loss: 0.0153 - acc: 1.0000
Epoch 116/500
 - 0s - loss: 0.0145 - acc: 1.0000
Epoch 117/500
 - 0s - loss: 0.0145 - acc: 1.0000
Epoch 118/500
 - 0s - loss: 0.0137 - acc: 1.0000
Epoch 119/500
 - 0s - loss: 0.0134 - acc: 1.0000
Epoch 120/500
 - 0s - loss: 0.0132 - acc: 1.0000
Epoch 121/500
 - 0s - loss: 0.0125 - acc: 1.0000
Epoch 122/500
 - 0s - loss: 0.0126 - acc: 1.0000
Epoch 123/500
 - 0s - loss: 0.0120 - acc: 1.0000
Epoch 124/500
 - 0s - loss: 0.0117 - acc: 1.0000
Epoch 125/500
 - 0s - loss: 0.0123 - acc: 1.0000
Epoch 126/500
 - 0s - loss: 0.0113 - acc: 1.0000
Epoch 127/500
 - 0s - loss: 0.0120 - acc: 1.0000
Epoch 128/500
 - 0s - loss: 0.0110 - acc: 1.0000
Epoch 129/500
 - 0s - loss: 0.0109 - acc: 1.0000
Epoch 130/500
 - 0s - loss: 0.0103 - acc: 1.0000
Epoch 131/500
 - 0s - loss: 0.0100 - acc: 1.0000
Epoch 132/500
 - 0s - loss: 0.0098 - acc: 1.0000
Epoch 133/500
 - 0s - loss: 0.0094 - acc: 1.0000
Epoch 134/500
 - 0s - loss: 0.0092 - acc: 1.0000
Epoch 135/500
 - 0s - loss: 0.0090 - acc: 1.0000
Epoch 136/500
 - 0s - loss: 0.0088 - acc: 1.0000
Epoch 137/500
 - 0s - loss: 0.0085 - acc: 1.0000
Epoch 138/500
 - 0s - loss: 0.0089 - acc: 1.0000
Epoch 139/500
 - 0s - loss: 0.0083 - acc: 1.0000
Epoch 140/500
 - 0s - loss: 0.0081 - acc: 1.0000
Epoch 141/500
 - 0s - loss: 0.0079 - acc: 1.0000
Epoch 142/500
 - 0s - loss: 0.0078 - acc: 1.0000
Epoch 143/500
 - 0s - loss: 0.0075 - acc: 1.0000
Epoch 144/500
 - 0s - loss: 0.0074 - acc: 1.0000
Epoch 145/500
 - 0s - loss: 0.0073 - acc: 1.0000
Epoch 146/500
 - 0s - loss: 0.0071 - acc: 1.0000
Epoch 147/500
 - 0s - loss: 0.0070 - acc: 1.0000
Epoch 148/500
 - 0s - loss: 0.0069 - acc: 1.0000
Epoch 149/500
 - 0s - loss: 0.0068 - acc: 1.0000
Epoch 150/500
 - 0s - loss: 0.0065 - acc: 1.0000
Epoch 151/500
 - 0s - loss: 0.0067 - acc: 1.0000
Epoch 152/500
 - 0s - loss: 0.0063 - acc: 1.0000
Epoch 153/500
 - 0s - loss: 0.0062 - acc: 1.0000
Epoch 154/500
 - 0s - loss: 0.0061 - acc: 1.0000
Epoch 155/500
 - 0s - loss: 0.0058 - acc: 1.0000
Epoch 156/500
 - 0s - loss: 0.0058 - acc: 1.0000
Epoch 157/500
 - 0s - loss: 0.0063 - acc: 1.0000
Epoch 158/500
 - 0s - loss: 0.0057 - acc: 1.0000
Epoch 159/500
 - 0s - loss: 0.0055 - acc: 1.0000
Epoch 160/500
 - 0s - loss: 0.0054 - acc: 1.0000
Epoch 161/500
 - 0s - loss: 0.0054 - acc: 1.0000
Epoch 162/500
 - 0s - loss: 0.0051 - acc: 1.0000
Epoch 163/500
 - 0s - loss: 0.0050 - acc: 1.0000
Epoch 164/500
 - 0s - loss: 0.0049 - acc: 1.0000

Epoch 165/500
 - 0s - loss: 0.0049 - acc: 1.0000
Epoch 166/500
 - 0s - loss: 0.0050 - acc: 1.0000
Epoch 167/500
 - 0s - loss: 0.0047 - acc: 1.0000
Epoch 168/500
 - 0s - loss: 0.0046 - acc: 1.0000
Epoch 169/500
 - 0s - loss: 0.0045 - acc: 1.0000
Epoch 170/500
 - 0s - loss: 0.0044 - acc: 1.0000
Epoch 171/500
 - 0s - loss: 0.0043 - acc: 1.0000
Epoch 172/500
 - 0s - loss: 0.0042 - acc: 1.0000
Epoch 173/500
 - 0s - loss: 0.0042 - acc: 1.0000
Epoch 174/500
 - 0s - loss: 0.0041 - acc: 1.0000
Epoch 175/500
 - 0s - loss: 0.0041 - acc: 1.0000
Epoch 176/500
 - 0s - loss: 0.0040 - acc: 1.0000
Epoch 177/500
 - 0s - loss: 0.0039 - acc: 1.0000
Epoch 178/500
 - 0s - loss: 0.0039 - acc: 1.0000
Epoch 179/500
 - 0s - loss: 0.0041 - acc: 1.0000
Epoch 180/500
 - 0s - loss: 0.0038 - acc: 1.0000
Epoch 181/500
 - 0s - loss: 0.0038 - acc: 1.0000
Epoch 182/500
 - 0s - loss: 0.0037 - acc: 1.0000
Epoch 183/500
 - 0s - loss: 0.0037 - acc: 1.0000
Epoch 184/500
 - 0s - loss: 0.0035 - acc: 1.0000
Epoch 185/500
 - 0s - loss: 0.0035 - acc: 1.0000
Epoch 186/500
 - 0s - loss: 0.0034 - acc: 1.0000
Epoch 187/500
 - 0s - loss: 0.0033 - acc: 1.0000
Epoch 188/500
 - 0s - loss: 0.0033 - acc: 1.0000
Epoch 189/500
 - 0s - loss: 0.0032 - acc: 1.0000
Epoch 190/500
 - 0s - loss: 0.0032 - acc: 1.0000
Epoch 191/500
 - 0s - loss: 0.0032 - acc: 1.0000
Epoch 192/500
 - 0s - loss: 0.0031 - acc: 1.0000
Epoch 193/500
 - 0s - loss: 0.0031 - acc: 1.0000
Epoch 194/500
 - 0s - loss: 0.0030 - acc: 1.0000
Epoch 195/500
 - 0s - loss: 0.0029 - acc: 1.0000
Epoch 196/500
 - 0s - loss: 0.0029 - acc: 1.0000
Epoch 197/500
 - 0s - loss: 0.0028 - acc: 1.0000
Epoch 198/500
 - 0s - loss: 0.0028 - acc: 1.0000
Epoch 199/500
 - 0s - loss: 0.0028 - acc: 1.0000
Epoch 200/500
 - 0s - loss: 0.0028 - acc: 1.0000
Epoch 201/500
 - 0s - loss: 0.0027 - acc: 1.0000
Epoch 202/500
 - 0s - loss: 0.0027 - acc: 1.0000
Epoch 203/500
 - 0s - loss: 0.0026 - acc: 1.0000
Epoch 204/500
 - 0s - loss: 0.0026 - acc: 1.0000
Epoch 205/500
 - 0s - loss: 0.0025 - acc: 1.0000
Epoch 206/500
 - 0s - loss: 0.0025 - acc: 1.0000
Epoch 207/500
 - 0s - loss: 0.0024 - acc: 1.0000
Epoch 208/500
 - 0s - loss: 0.0026 - acc: 1.0000
Epoch 209/500
 - 0s - loss: 0.0024 - acc: 1.0000
Epoch 210/500
 - 0s - loss: 0.0024 - acc: 1.0000
Epoch 211/500
 - 0s - loss: 0.0024 - acc: 1.0000
Epoch 212/500
 - 0s - loss: 0.0023 - acc: 1.0000
Epoch 213/500
 - 0s - loss: 0.0023 - acc: 1.0000
Epoch 214/500
 - 0s - loss: 0.0022 - acc: 1.0000
Epoch 215/500
 - 0s - loss: 0.0022 - acc: 1.0000
Epoch 216/500
 - 0s - loss: 0.0021 - acc: 1.0000
Epoch 217/500
 - 0s - loss: 0.0022 - acc: 1.0000
Epoch 218/500
 - 0s - loss: 0.0021 - acc: 1.0000
Epoch 219/500
 - 0s - loss: 0.0021 - acc: 1.0000
Epoch 220/500
 - 0s - loss: 0.0020 - acc: 1.0000
Epoch 221/500
 - 0s - loss: 0.0020 - acc: 1.0000
Epoch 222/500
 - 0s - loss: 0.0020 - acc: 1.0000
Epoch 223/500
 - 0s - loss: 0.0020 - acc: 1.0000
Epoch 224/500
 - 0s - loss: 0.0019 - acc: 1.0000
Epoch 225/500
 - 0s - loss: 0.0020 - acc: 1.0000
Epoch 226/500
 - 0s - loss: 0.0020 - acc: 1.0000
Epoch 227/500
 - 0s - loss: 0.0019 - acc: 1.0000
Epoch 228/500
 - 0s - loss: 0.0018 - acc: 1.0000
Epoch 229/500
 - 0s - loss: 0.0018 - acc: 1.0000
Epoch 230/500
 - 0s - loss: 0.0018 - acc: 1.0000
Epoch 231/500
 - 0s - loss: 0.0018 - acc: 1.0000
Epoch 232/500
 - 0s - loss: 0.0018 - acc: 1.0000
Epoch 233/500
 - 0s - loss: 0.0017 - acc: 1.0000
Epoch 234/500
 - 0s - loss: 0.0017 - acc: 1.0000
Epoch 235/500
 - 0s - loss: 0.0017 - acc: 1.0000
Epoch 236/500
 - 0s - loss: 0.0017 - acc: 1.0000
Epoch 237/500
 - 0s - loss: 0.0017 - acc: 1.0000
Epoch 238/500
 - 0s - loss: 0.0017 - acc: 1.0000
Epoch 239/500
 - 0s - loss: 0.0017 - acc: 1.0000
Epoch 240/500
 - 0s - loss: 0.0016 - acc: 1.0000
Epoch 241/500
 - 0s - loss: 0.0016 - acc: 1.0000
Epoch 242/500
 - 0s - loss: 0.0016 - acc: 1.0000
Epoch 243/500
 - 0s - loss: 0.0016 - acc: 1.0000
Epoch 244/500
 - 0s - loss: 0.0016 - acc: 1.0000
Epoch 245/500
 - 0s - loss: 0.0015 - acc: 1.0000
Epoch 246/500
 - 0s - loss: 0.0016 - acc: 1.0000
Epoch 247/500
 - 0s - loss: 0.0015 - acc: 1.0000
Epoch 248/500
 - 0s - loss: 0.0015 - acc: 1.0000
Epoch 249/500
 - 0s - loss: 0.0015 - acc: 1.0000
Epoch 250/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 251/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 252/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 253/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 254/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 255/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 256/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 257/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 258/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 259/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 260/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 261/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 262/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 263/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 264/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 265/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 266/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 267/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 268/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 269/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 270/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 271/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 272/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 273/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 274/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 275/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 276/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 277/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 278/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 279/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 280/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 281/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 282/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 283/500
 - 0s - loss: 0.0010 - acc: 1.0000
Epoch 284/500
 - 0s - loss: 0.0010 - acc: 1.0000
Epoch 285/500
 - 0s - loss: 9.9750e-04 - acc: 1.0000
Epoch 286/500
 - 0s - loss: 9.8546e-04 - acc: 1.0000
Epoch 287/500
 - 0s - loss: 9.7247e-04 - acc: 1.0000
Epoch 288/500
 - 0s - loss: 9.7147e-04 - acc: 1.0000
Epoch 289/500
 - 0s - loss: 9.5673e-04 - acc: 1.0000
Epoch 290/500
 - 0s - loss: 9.9088e-04 - acc: 1.0000
Epoch 291/500
 - 0s - loss: 9.1521e-04 - acc: 1.0000
Epoch 292/500
 - 0s - loss: 9.7009e-04 - acc: 1.0000
Epoch 293/500
 - 0s - loss: 9.4618e-04 - acc: 1.0000
Epoch 294/500
 - 0s - loss: 9.0501e-04 - acc: 1.0000
Epoch 295/500
 - 0s - loss: 9.0940e-04 - acc: 1.0000
Epoch 296/500
 - 0s - loss: 9.1482e-04 - acc: 1.0000
Epoch 297/500
 - 0s - loss: 9.1701e-04 - acc: 1.0000
Epoch 298/500
 - 0s - loss: 9.0513e-04 - acc: 1.0000
Epoch 299/500
 - 0s - loss: 8.8686e-04 - acc: 1.0000
Epoch 300/500
 - 0s - loss: 8.7883e-04 - acc: 1.0000
Epoch 301/500
 - 0s - loss: 8.6437e-04 - acc: 1.0000
Epoch 302/500
 - 0s - loss: 8.5347e-04 - acc: 1.0000
Epoch 303/500
 - 0s - loss: 8.3983e-04 - acc: 1.0000
Epoch 304/500
 - 0s - loss: 8.4588e-04 - acc: 1.0000
Epoch 305/500
 - 0s - loss: 8.2855e-04 - acc: 1.0000
Epoch 306/500
 - 0s - loss: 8.2765e-04 - acc: 1.0000
Epoch 307/500
 - 0s - loss: 8.1569e-04 - acc: 1.0000
Epoch 308/500
 - 0s - loss: 8.2250e-04 - acc: 1.0000
Epoch 309/500
 - 0s - loss: 8.1024e-04 - acc: 1.0000
Epoch 310/500
 - 0s - loss: 7.9870e-04 - acc: 1.0000
Epoch 311/500
 - 0s - loss: 8.0026e-04 - acc: 1.0000
Epoch 312/500
 - 0s - loss: 7.9259e-04 - acc: 1.0000
Epoch 313/500
 - 0s - loss: 7.8222e-04 - acc: 1.0000
Epoch 314/500
 - 0s - loss: 7.8241e-04 - acc: 1.0000
Epoch 315/500
 - 0s - loss: 7.5953e-04 - acc: 1.0000
Epoch 316/500
 - 0s - loss: 7.5364e-04 - acc: 1.0000
Epoch 317/500
 - 0s - loss: 7.5387e-04 - acc: 1.0000
Epoch 318/500
 - 0s - loss: 7.6188e-04 - acc: 1.0000
Epoch 319/500
 - 0s - loss: 7.5531e-04 - acc: 1.0000
Epoch 320/500
 - 0s - loss: 7.3295e-04 - acc: 1.0000
Epoch 321/500
 - 0s - loss: 7.3442e-04 - acc: 1.0000
Epoch 322/500
 - 0s - loss: 7.3601e-04 - acc: 1.0000
Epoch 323/500
 - 0s - loss: 7.1827e-04 - acc: 1.0000
Epoch 324/500
 - 0s - loss: 7.1725e-04 - acc: 1.0000
Epoch 325/500
 - 0s - loss: 7.1012e-04 - acc: 1.0000
Epoch 326/500
 - 0s - loss: 6.9670e-04 - acc: 1.0000
Epoch 327/500
 - 0s - loss: 6.8889e-04 - acc: 1.0000
Epoch 328/500
 - 0s - loss: 6.8009e-04 - acc: 1.0000

Epoch 329/500
 - 0s - loss: 6.8545e-04 - acc: 1.0000
Epoch 330/500
 - 0s - loss: 6.6946e-04 - acc: 1.0000
Epoch 331/500
 - 0s - loss: 6.6476e-04 - acc: 1.0000
Epoch 332/500
 - 0s - loss: 6.6812e-04 - acc: 1.0000
Epoch 333/500
 - 0s - loss: 6.5682e-04 - acc: 1.0000
Epoch 334/500
 - 0s - loss: 6.5869e-04 - acc: 1.0000
Epoch 335/500
 - 0s - loss: 6.4196e-04 - acc: 1.0000
Epoch 336/500
 - 0s - loss: 6.5677e-04 - acc: 1.0000
Epoch 337/500
 - 0s - loss: 6.4384e-04 - acc: 1.0000
Epoch 338/500
 - 0s - loss: 6.3386e-04 - acc: 1.0000
Epoch 339/500
 - 0s - loss: 6.2857e-04 - acc: 1.0000
Epoch 340/500
 - 0s - loss: 6.2000e-04 - acc: 1.0000
Epoch 341/500
 - 0s - loss: 6.1339e-04 - acc: 1.0000
Epoch 342/500
 - 0s - loss: 6.1061e-04 - acc: 1.0000
Epoch 343/500
 - 0s - loss: 6.0313e-04 - acc: 1.0000
Epoch 344/500
 - 0s - loss: 5.9905e-04 - acc: 1.0000
Epoch 345/500
 - 0s - loss: 5.9599e-04 - acc: 1.0000
Epoch 346/500
 - 0s - loss: 5.9172e-04 - acc: 1.0000
Epoch 347/500
 - 0s - loss: 5.9133e-04 - acc: 1.0000
Epoch 348/500
 - 0s - loss: 5.8708e-04 - acc: 1.0000
Epoch 349/500
 - 0s - loss: 5.7567e-04 - acc: 1.0000
Epoch 350/500
 - 0s - loss: 5.7734e-04 - acc: 1.0000
Epoch 351/500
 - 0s - loss: 5.7285e-04 - acc: 1.0000
Epoch 352/500
 - 0s - loss: 5.6650e-04 - acc: 1.0000
Epoch 353/500
 - 0s - loss: 5.6194e-04 - acc: 1.0000
Epoch 354/500
 - 0s - loss: 5.5796e-04 - acc: 1.0000
Epoch 355/500
 - 0s - loss: 5.5452e-04 - acc: 1.0000
Epoch 356/500
 - 0s - loss: 5.4697e-04 - acc: 1.0000
Epoch 357/500
 - 0s - loss: 5.4502e-04 - acc: 1.0000
Epoch 358/500
 - 0s - loss: 5.4541e-04 - acc: 1.0000
Epoch 359/500
 - 0s - loss: 5.3600e-04 - acc: 1.0000
Epoch 360/500
 - 0s - loss: 5.3624e-04 - acc: 1.0000
Epoch 361/500
 - 0s - loss: 5.3578e-04 - acc: 1.0000
Epoch 362/500
 - 0s - loss: 5.2540e-04 - acc: 1.0000
Epoch 363/500
 - 0s - loss: 5.1919e-04 - acc: 1.0000
Epoch 364/500
 - 0s - loss: 5.1418e-04 - acc: 1.0000
Epoch 365/500
 - 0s - loss: 5.1133e-04 - acc: 1.0000
Epoch 366/500
 - 0s - loss: 5.0953e-04 - acc: 1.0000
Epoch 367/500
 - 0s - loss: 5.0673e-04 - acc: 1.0000
Epoch 368/500
 - 0s - loss: 5.0304e-04 - acc: 1.0000
Epoch 369/500
 - 0s - loss: 5.0007e-04 - acc: 1.0000
Epoch 370/500
 - 0s - loss: 4.9582e-04 - acc: 1.0000
Epoch 371/500
 - 0s - loss: 5.0232e-04 - acc: 1.0000
Epoch 372/500
 - 0s - loss: 4.9351e-04 - acc: 1.0000
Epoch 373/500
 - 0s - loss: 4.8534e-04 - acc: 1.0000
Epoch 374/500
 - 0s - loss: 4.8142e-04 - acc: 1.0000
Epoch 375/500
 - 0s - loss: 4.7713e-04 - acc: 1.0000
Epoch 376/500
 - 0s - loss: 4.7320e-04 - acc: 1.0000
Epoch 377/500
 - 0s - loss: 4.7126e-04 - acc: 1.0000
Epoch 378/500
 - 0s - loss: 4.7426e-04 - acc: 1.0000
Epoch 379/500
 - 0s - loss: 4.6764e-04 - acc: 1.0000
Epoch 380/500
 - 0s - loss: 4.6028e-04 - acc: 1.0000
Epoch 381/500
 - 0s - loss: 4.5580e-04 - acc: 1.0000
Epoch 382/500
 - 0s - loss: 4.5522e-04 - acc: 1.0000
Epoch 383/500
 - 0s - loss: 4.4997e-04 - acc: 1.0000
Epoch 384/500
 - 0s - loss: 4.5200e-04 - acc: 1.0000
Epoch 385/500
 - 0s - loss: 4.4122e-04 - acc: 1.0000
Epoch 386/500
 - 0s - loss: 4.4873e-04 - acc: 1.0000
Epoch 387/500
 - 0s - loss: 4.5024e-04 - acc: 1.0000
Epoch 388/500
 - 0s - loss: 4.3811e-04 - acc: 1.0000
Epoch 389/500
 - 0s - loss: 4.3371e-04 - acc: 1.0000
Epoch 390/500
 - 0s - loss: 4.3650e-04 - acc: 1.0000
Epoch 391/500
 - 0s - loss: 4.3068e-04 - acc: 1.0000
Epoch 392/500
 - 0s - loss: 4.2597e-04 - acc: 1.0000
Epoch 393/500
 - 0s - loss: 4.2638e-04 - acc: 1.0000
Epoch 394/500
 - 0s - loss: 4.1882e-04 - acc: 1.0000
Epoch 395/500
 - 0s - loss: 4.1618e-04 - acc: 1.0000
Epoch 396/500
 - 0s - loss: 4.1756e-04 - acc: 1.0000
Epoch 397/500
 - 0s - loss: 4.1443e-04 - acc: 1.0000
Epoch 398/500
 - 0s - loss: 4.1205e-04 - acc: 1.0000
Epoch 399/500
 - 0s - loss: 4.0999e-04 - acc: 1.0000
Epoch 400/500
 - 0s - loss: 4.0125e-04 - acc: 1.0000
Epoch 401/500
 - 0s - loss: 4.0498e-04 - acc: 1.0000
Epoch 402/500
 - 0s - loss: 3.9684e-04 - acc: 1.0000
Epoch 403/500
 - 0s - loss: 3.9904e-04 - acc: 1.0000
Epoch 404/500
 - 0s - loss: 3.9204e-04 - acc: 1.0000
Epoch 405/500
 - 0s - loss: 3.8638e-04 - acc: 1.0000
Epoch 406/500
 - 0s - loss: 3.8933e-04 - acc: 1.0000
Epoch 407/500
 - 0s - loss: 3.8583e-04 - acc: 1.0000
Epoch 408/500
 - 0s - loss: 3.7982e-04 - acc: 1.0000
Epoch 409/500
 - 0s - loss: 3.7392e-04 - acc: 1.0000
Epoch 410/500
 - 0s - loss: 3.8385e-04 - acc: 1.0000
Epoch 411/500
 - 0s - loss: 3.7113e-04 - acc: 1.0000
Epoch 412/500
 - 0s - loss: 3.6921e-04 - acc: 1.0000
Epoch 413/500
 - 0s - loss: 3.8193e-04 - acc: 1.0000
Epoch 414/500
 - 0s - loss: 3.7188e-04 - acc: 1.0000
Epoch 415/500
 - 0s - loss: 3.6482e-04 - acc: 1.0000
Epoch 416/500
 - 0s - loss: 3.6624e-04 - acc: 1.0000
Epoch 417/500
 - 0s - loss: 3.7367e-04 - acc: 1.0000
Epoch 418/500
 - 0s - loss: 3.6247e-04 - acc: 1.0000
Epoch 419/500
 - 0s - loss: 3.5299e-04 - acc: 1.0000
Epoch 420/500
 - 0s - loss: 3.5708e-04 - acc: 1.0000
Epoch 421/500
 - 0s - loss: 3.4988e-04 - acc: 1.0000
Epoch 422/500
 - 0s - loss: 3.4614e-04 - acc: 1.0000
Epoch 423/500
 - 0s - loss: 3.4724e-04 - acc: 1.0000
Epoch 424/500
 - 0s - loss: 3.4163e-04 - acc: 1.0000
Epoch 425/500
 - 0s - loss: 3.4035e-04 - acc: 1.0000
Epoch 426/500
 - 0s - loss: 3.4251e-04 - acc: 1.0000
Epoch 427/500
 - 0s - loss: 3.4589e-04 - acc: 1.0000
Epoch 428/500
 - 0s - loss: 3.3549e-04 - acc: 1.0000
Epoch 429/500
 - 0s - loss: 3.3043e-04 - acc: 1.0000
Epoch 430/500
 - 0s - loss: 3.3019e-04 - acc: 1.0000
Epoch 431/500
 - 0s - loss: 3.2845e-04 - acc: 1.0000
Epoch 432/500
 - 0s - loss: 3.2543e-04 - acc: 1.0000
Epoch 433/500
 - 0s - loss: 3.2322e-04 - acc: 1.0000
Epoch 434/500
 - 0s - loss: 3.2044e-04 - acc: 1.0000
Epoch 435/500
 - 0s - loss: 3.2084e-04 - acc: 1.0000
Epoch 436/500
 - 0s - loss: 3.1717e-04 - acc: 1.0000
Epoch 437/500
 - 0s - loss: 3.1637e-04 - acc: 1.0000
Epoch 438/500
 - 0s - loss: 3.1473e-04 - acc: 1.0000
Epoch 439/500
 - 0s - loss: 3.1323e-04 - acc: 1.0000
Epoch 440/500
 - 0s - loss: 3.1763e-04 - acc: 1.0000
Epoch 441/500
 - 0s - loss: 3.1151e-04 - acc: 1.0000
Epoch 442/500
 - 0s - loss: 3.0954e-04 - acc: 1.0000
Epoch 443/500
 - 0s - loss: 3.0823e-04 - acc: 1.0000
Epoch 444/500
 - 0s - loss: 3.0178e-04 - acc: 1.0000
Epoch 445/500
 - 0s - loss: 3.0002e-04 - acc: 1.0000
Epoch 446/500
 - 0s - loss: 3.0029e-04 - acc: 1.0000
Epoch 447/500
 - 0s - loss: 2.9639e-04 - acc: 1.0000
Epoch 448/500
 - 0s - loss: 2.9516e-04 - acc: 1.0000
Epoch 449/500
 - 0s - loss: 3.0258e-04 - acc: 1.0000
Epoch 450/500
 - 0s - loss: 2.9392e-04 - acc: 1.0000
Epoch 451/500
 - 0s - loss: 2.9460e-04 - acc: 1.0000
Epoch 452/500
 - 0s - loss: 2.9139e-04 - acc: 1.0000
Epoch 453/500
 - 0s - loss: 2.8756e-04 - acc: 1.0000
Epoch 454/500
 - 0s - loss: 2.8396e-04 - acc: 1.0000
Epoch 455/500
 - 0s - loss: 2.8125e-04 - acc: 1.0000
Epoch 456/500
 - 0s - loss: 2.8151e-04 - acc: 1.0000
Epoch 457/500
 - 0s - loss: 2.8043e-04 - acc: 1.0000
Epoch 458/500
 - 0s - loss: 2.7723e-04 - acc: 1.0000
Epoch 459/500
 - 0s - loss: 2.7483e-04 - acc: 1.0000
Epoch 460/500
 - 0s - loss: 2.7446e-04 - acc: 1.0000
Epoch 461/500
 - 0s - loss: 2.7199e-04 - acc: 1.0000
Epoch 462/500
 - 0s - loss: 2.7089e-04 - acc: 1.0000
Epoch 463/500
 - 0s - loss: 2.6871e-04 - acc: 1.0000
Epoch 464/500
 - 0s - loss: 2.6762e-04 - acc: 1.0000
Epoch 465/500
 - 0s - loss: 2.6684e-04 - acc: 1.0000
Epoch 466/500
 - 0s - loss: 2.6324e-04 - acc: 1.0000
Epoch 467/500
 - 0s - loss: 2.6335e-04 - acc: 1.0000
Epoch 468/500
 - 0s - loss: 2.6082e-04 - acc: 1.0000
Epoch 469/500
 - 0s - loss: 2.6242e-04 - acc: 1.0000
Epoch 470/500
 - 0s - loss: 2.5879e-04 - acc: 1.0000
Epoch 471/500
 - 0s - loss: 2.5919e-04 - acc: 1.0000
Epoch 472/500
 - 0s - loss: 2.5560e-04 - acc: 1.0000
Epoch 473/500
 - 0s - loss: 2.5549e-04 - acc: 1.0000
Epoch 474/500
 - 0s - loss: 2.5395e-04 - acc: 1.0000
Epoch 475/500
 - 0s - loss: 2.5191e-04 - acc: 1.0000
Epoch 476/500
 - 0s - loss: 2.4989e-04 - acc: 1.0000
Epoch 477/500
 - 0s - loss: 2.5191e-04 - acc: 1.0000
Epoch 478/500
 - 0s - loss: 2.5075e-04 - acc: 1.0000
Epoch 479/500
 - 0s - loss: 2.4487e-04 - acc: 1.0000
Epoch 480/500
 - 0s - loss: 2.4610e-04 - acc: 1.0000
Epoch 481/500
 - 0s - loss: 2.5353e-04 - acc: 1.0000
Epoch 482/500
 - 0s - loss: 2.4745e-04 - acc: 1.0000
Epoch 483/500
 - 0s - loss: 2.4141e-04 - acc: 1.0000

Epoch 484/500
 - 0s - loss: 2.3872e-04 - acc: 1.0000
Epoch 485/500
 - 0s - loss: 2.4216e-04 - acc: 1.0000
Epoch 486/500
 - 0s - loss: 2.3719e-04 - acc: 1.0000
Epoch 487/500
 - 0s - loss: 2.3549e-04 - acc: 1.0000
Epoch 488/500
 - 0s - loss: 2.3388e-04 - acc: 1.0000
Epoch 489/500
 - 0s - loss: 2.3363e-04 - acc: 1.0000
Epoch 490/500
 - 0s - loss: 2.3142e-04 - acc: 1.0000
Epoch 491/500
 - 0s - loss: 2.2968e-04 - acc: 1.0000
Epoch 492/500
 - 0s - loss: 2.2944e-04 - acc: 1.0000
Epoch 493/500
 - 0s - loss: 2.3312e-04 - acc: 1.0000
Epoch 494/500
 - 0s - loss: 2.2657e-04 - acc: 1.0000
Epoch 495/500
 - 0s - loss: 2.2860e-04 - acc: 1.0000
Epoch 496/500
 - 0s - loss: 2.2376e-04 - acc: 1.0000
Epoch 497/500
 - 0s - loss: 2.2199e-04 - acc: 1.0000
Epoch 498/500
 - 0s - loss: 2.2102e-04 - acc: 1.0000
Epoch 499/500
 - 0s - loss: 2.1964e-04 - acc: 1.0000
Epoch 500/500
 - 0s - loss: 2.1975e-04 - acc: 1.0000

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 0.5448 - acc: 0.9184
Normal Neural Network - Loss: 0.5447700558876505, Accuracy: 0.918367326259613

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Certified' 'Certified' 'Certified' 'Certified' 'Certified'
 'Certified' 'Certified' 'Certified' 'Certified']
Actual Labels: ['Certified', 'Denied', 'Certified', 'Certified', 'Certified', 'Certified', 'Denied', 'Certified', 'Certified', 'Certified']