In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'HONG KONG']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

HONG KONG    402
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    332
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [8]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [9]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [10]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
1186,Certified,203,94104,CALIFORNIA,400.0,110000.0,HONG KONG,H-1B,Bachelor's,2.0
1207,Certified,211,60654,ILLINOIS,12443.0,88254.0,HONG KONG,H-1B,Bachelor's,1.0
2915,Certified,525,15205,PENNSYLVANIA,54500.0,108534.0,HONG KONG,H-1B,Master's,1.0
3443,Certified,198,49355,MICHIGAN,20000.0,76500.0,HONG KONG,H-1B,Master's,1.0
4178,Certified,186,07094,NEW JERSEY,31000.0,75000.0,HONG KONG,H-1B,Bachelor's,2.0

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

CALIFORNIA        133
NEW YORK           43
TEXAS              37
FLORIDA            22
WASHINGTON         17
PENNSYLVANIA       11
NEW JERSEY         11
ILLINOIS            9
NORTH CAROLINA      6
MASSACHUSETTS       5
GEORGIA             5
TENNESSEE           5
DELAWARE            4
MICHIGAN            3
MINNESOTA           2
MARYLAND            2
NEW HAMPSHIRE       2
UTAH                1
SOUTH CAROLINA      1
NEVADA              1
CONNECTICUT         1
MISSISSIPPI         1
LOUISIANA           1
OHIO                1
INDIANA             1
WYOMING             1
RHODE ISLAND        1
COLORADO            1
WISCONSIN           1
HAWAII              1
MISSOURI            1
VIRGINIA            1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
1186,Certified,203,94104,CALIFORNIA,400.0,110000.0,HONG KONG,H-1B,Bachelor's,2.0,CALIFORNIA
1207,Certified,211,60654,ILLINOIS,12443.0,88254.0,HONG KONG,H-1B,Bachelor's,1.0,ILLINOIS
2915,Certified,525,15205,PENNSYLVANIA,54500.0,108534.0,HONG KONG,H-1B,Master's,1.0,PENNSYLVANIA
3443,Certified,198,49355,MICHIGAN,20000.0,76500.0,HONG KONG,H-1B,Master's,1.0,MICHIGAN
4178,Certified,186,07094,NEW JERSEY,31000.0,75000.0,HONG KONG,H-1B,Bachelor's,2.0,NEW JERSEY

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

WEST         150
NORTHEAST     72
SOUTH         43
MIDWEST       18
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      283
DECISION_ELAPSED_DAYS            283
EMPLOYER_POSTAL_CODE             283
EMPLOYER_STATE                   283
EMPLOYER_NUM_EMPLOYEES           283
WAGE_OFFER_FROM_9089             283
COUNTRY_OF_CITIZENSHIP           283
CLASS_OF_ADMISSION               283
FOREIGN_WORKER_INFO_EDUCATION    283
CASE_RECEIVED_DATE_MONTH         283
EMPLOYER_STATES                  283
EMPLOYER_REGIONS                 283
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      113
0-90         81
181-365      63
366-3600     26
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

100000-500000    109
75001-100000      72
50001-75000       59
25001-50000       29
0-25000           14
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

10001-1000000000    95
0-50                74
1001-10000          55
101-500             33
51-100              19
501-1000             7
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      283
DECISION_ELAPSED_DAYS            283
EMPLOYER_POSTAL_CODE             283
EMPLOYER_STATE                   283
EMPLOYER_NUM_EMPLOYEES           283
WAGE_OFFER_FROM_9089             283
COUNTRY_OF_CITIZENSHIP           283
CLASS_OF_ADMISSION               283
FOREIGN_WORKER_INFO_EDUCATION    283
CASE_RECEIVED_DATE_MONTH         283
EMPLOYER_STATES                  283
EMPLOYER_REGIONS                 283
DAY_BINS                         283
WAGE_BINS                        283
EMPLOYEE_BINS                    283
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
1186,Certified,101-500,100000-500000,WEST,2.0,Bachelor's,H-1B,181-365
1207,Certified,10001-1000000000,75001-100000,MIDWEST,1.0,Bachelor's,H-1B,181-365
2915,Certified,10001-1000000000,100000-500000,NORTHEAST,1.0,Master's,H-1B,366-3600
3443,Certified,10001-1000000000,75001-100000,MIDWEST,1.0,Master's,H-1B,181-365
4178,Certified,10001-1000000000,50001-75000,NORTHEAST,2.0,Bachelor's,H-1B,181-365

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
1186,Certified,101-500,100000-500000,WEST,2.0,Bachelor's,H-1B,181-365,5,1,1,3,1,3
1207,Certified,10001-1000000000,75001-100000,MIDWEST,1.0,Bachelor's,H-1B,181-365,5,1,4,0,1,1
2915,Certified,10001-1000000000,100000-500000,NORTHEAST,1.0,Master's,H-1B,366-3600,5,4,1,1,2,1
3443,Certified,10001-1000000000,75001-100000,MIDWEST,1.0,Master's,H-1B,181-365,5,4,4,0,1,1
4178,Certified,10001-1000000000,50001-75000,NORTHEAST,2.0,Bachelor's,H-1B,181-365,5,1,3,1,1,1

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           283
EMPLOYEE_BINS                         283
WAGE_BINS                             283
EMPLOYER_REGIONS                      283
CASE_RECEIVED_DATE_MONTH              283
FOREIGN_WORKER_INFO_EDUCATION         283
CLASS_OF_ADMISSION                    283
DAY_BINS                              283
CLASS_OF_ADMISSION_CODE               283
FOREIGN_WORKER_INFO_EDUCATION_CODE    283
WAGE_BINS_CODE                        283
EMPLOYER_REGIONS_CODE                 283
DAY_BINS_CODE                         283
EMPLOYEE_BINS_CODE                    283
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
1186,Certified,3,1,1,1,5,2.0,3
1207,Certified,1,4,1,1,5,1.0,0
2915,Certified,1,1,2,4,5,1.0,1
3443,Certified,1,4,1,4,5,1.0,0
4178,Certified,1,3,1,1,5,2.0,1

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int64
WAGE_BINS_CODE                          int64
DAY_BINS_CODE                           int64
FOREIGN_WORKER_INFO_EDUCATION_CODE      int64
CLASS_OF_ADMISSION_CODE                 int64
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int64
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(283, 7) (283,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [53]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 1s - loss: 0.6069 - acc: 0.7453
Epoch 2/500
 - 0s - loss: 0.4045 - acc: 0.9104
Epoch 3/500
 - 0s - loss: 0.3152 - acc: 0.9104
Epoch 4/500
 - 0s - loss: 0.3123 - acc: 0.9104
Epoch 5/500
 - 0s - loss: 0.3129 - acc: 0.9104
Epoch 6/500
 - 0s - loss: 0.3091 - acc: 0.9104
Epoch 7/500
 - 0s - loss: 0.3066 - acc: 0.9104
Epoch 8/500
 - 0s - loss: 0.2997 - acc: 0.9104
Epoch 9/500
 - 0s - loss: 0.2975 - acc: 0.9104
Epoch 10/500
 - 0s - loss: 0.2936 - acc: 0.9104
Epoch 11/500
 - 0s - loss: 0.2904 - acc: 0.9104
Epoch 12/500
 - 0s - loss: 0.2885 - acc: 0.9104
Epoch 13/500
 - 0s - loss: 0.2840 - acc: 0.9104
Epoch 14/500
 - 0s - loss: 0.2804 - acc: 0.9104
Epoch 15/500
 - 0s - loss: 0.2775 - acc: 0.9104
Epoch 16/500
 - 0s - loss: 0.2735 - acc: 0.9104
Epoch 17/500
 - 0s - loss: 0.2714 - acc: 0.9104
Epoch 18/500
 - 0s - loss: 0.2664 - acc: 0.9104
Epoch 19/500
 - 0s - loss: 0.2651 - acc: 0.9104
Epoch 20/500
 - 0s - loss: 0.2605 - acc: 0.9104
Epoch 21/500
 - 0s - loss: 0.2568 - acc: 0.9104
Epoch 22/500
 - 0s - loss: 0.2532 - acc: 0.9104
Epoch 23/500
 - 0s - loss: 0.2500 - acc: 0.9104
Epoch 24/500
 - 0s - loss: 0.2459 - acc: 0.9104
Epoch 25/500
 - 0s - loss: 0.2438 - acc: 0.9104
Epoch 26/500
 - 0s - loss: 0.2407 - acc: 0.9104
Epoch 27/500
 - 0s - loss: 0.2380 - acc: 0.9104
Epoch 28/500
 - 0s - loss: 0.2343 - acc: 0.9104
Epoch 29/500
 - 0s - loss: 0.2309 - acc: 0.9104
Epoch 30/500
 - 0s - loss: 0.2278 - acc: 0.9104
Epoch 31/500
 - 0s - loss: 0.2239 - acc: 0.9104
Epoch 32/500
 - 0s - loss: 0.2220 - acc: 0.9104
Epoch 33/500
 - 0s - loss: 0.2188 - acc: 0.9104
Epoch 34/500
 - 0s - loss: 0.2145 - acc: 0.9104
Epoch 35/500
 - 0s - loss: 0.2142 - acc: 0.9104
Epoch 36/500
 - 0s - loss: 0.2111 - acc: 0.9104
Epoch 37/500
 - 0s - loss: 0.2135 - acc: 0.9104
Epoch 38/500
 - 0s - loss: 0.2035 - acc: 0.9104
Epoch 39/500
 - 0s - loss: 0.2028 - acc: 0.9104
Epoch 40/500
 - 0s - loss: 0.2007 - acc: 0.9104
Epoch 41/500
 - 0s - loss: 0.1955 - acc: 0.9104
Epoch 42/500
 - 0s - loss: 0.1935 - acc: 0.9104
Epoch 43/500
 - 0s - loss: 0.1903 - acc: 0.9104
Epoch 44/500
 - 0s - loss: 0.1864 - acc: 0.9104
Epoch 45/500
 - 0s - loss: 0.1869 - acc: 0.9104
Epoch 46/500
 - 0s - loss: 0.1829 - acc: 0.9057
Epoch 47/500
 - 0s - loss: 0.1794 - acc: 0.9151
Epoch 48/500
 - 0s - loss: 0.1821 - acc: 0.9104
Epoch 49/500
 - 0s - loss: 0.1775 - acc: 0.9104
Epoch 50/500
 - 0s - loss: 0.1767 - acc: 0.9151
Epoch 51/500
 - 0s - loss: 0.1716 - acc: 0.9151
Epoch 52/500
 - 0s - loss: 0.1661 - acc: 0.9198
Epoch 53/500
 - 0s - loss: 0.1639 - acc: 0.9151
Epoch 54/500
 - 0s - loss: 0.1597 - acc: 0.9198
Epoch 55/500
 - 0s - loss: 0.1571 - acc: 0.9198
Epoch 56/500
 - 0s - loss: 0.1551 - acc: 0.9198
Epoch 57/500
 - 0s - loss: 0.1522 - acc: 0.9198
Epoch 58/500
 - 0s - loss: 0.1496 - acc: 0.9245
Epoch 59/500
 - 0s - loss: 0.1475 - acc: 0.9198
Epoch 60/500
 - 0s - loss: 0.1476 - acc: 0.9340
Epoch 61/500
 - 0s - loss: 0.1401 - acc: 0.9292
Epoch 62/500
 - 0s - loss: 0.1403 - acc: 0.9292
Epoch 63/500
 - 0s - loss: 0.1387 - acc: 0.9387
Epoch 64/500
 - 0s - loss: 0.1327 - acc: 0.9434
Epoch 65/500
 - 0s - loss: 0.1340 - acc: 0.9245
Epoch 66/500
 - 0s - loss: 0.1308 - acc: 0.9340
Epoch 67/500
 - 0s - loss: 0.1303 - acc: 0.9481
Epoch 68/500
 - 0s - loss: 0.1249 - acc: 0.9481
Epoch 69/500
 - 0s - loss: 0.1256 - acc: 0.9387
Epoch 70/500
 - 0s - loss: 0.1186 - acc: 0.9434
Epoch 71/500
 - 0s - loss: 0.1177 - acc: 0.9528
Epoch 72/500
 - 0s - loss: 0.1182 - acc: 0.9434
Epoch 73/500
 - 0s - loss: 0.1116 - acc: 0.9434
Epoch 74/500
 - 0s - loss: 0.1148 - acc: 0.9575
Epoch 75/500
 - 0s - loss: 0.1085 - acc: 0.9481
Epoch 76/500
 - 0s - loss: 0.1047 - acc: 0.9575
Epoch 77/500
 - 0s - loss: 0.1032 - acc: 0.9575
Epoch 78/500
 - 0s - loss: 0.1030 - acc: 0.9575
Epoch 79/500
 - 0s - loss: 0.1009 - acc: 0.9528
Epoch 80/500
 - 0s - loss: 0.0989 - acc: 0.9575
Epoch 81/500
 - 0s - loss: 0.0978 - acc: 0.9575
Epoch 82/500
 - 0s - loss: 0.0966 - acc: 0.9528
Epoch 83/500
 - 0s - loss: 0.0944 - acc: 0.9670
Epoch 84/500
 - 0s - loss: 0.0938 - acc: 0.9623
Epoch 85/500
 - 0s - loss: 0.0891 - acc: 0.9670
Epoch 86/500
 - 0s - loss: 0.0910 - acc: 0.9623
Epoch 87/500
 - 0s - loss: 0.0852 - acc: 0.9717
Epoch 88/500
 - 0s - loss: 0.0862 - acc: 0.9575
Epoch 89/500
 - 0s - loss: 0.0842 - acc: 0.9858
Epoch 90/500
 - 0s - loss: 0.0797 - acc: 0.9717
Epoch 91/500
 - 0s - loss: 0.0816 - acc: 0.9623
Epoch 92/500
 - 0s - loss: 0.0797 - acc: 0.9858
Epoch 93/500
 - 0s - loss: 0.0774 - acc: 0.9623
Epoch 94/500
 - 0s - loss: 0.0725 - acc: 0.9717
Epoch 95/500
 - 0s - loss: 0.0740 - acc: 0.9906
Epoch 96/500
 - 0s - loss: 0.0719 - acc: 0.9670
Epoch 97/500
 - 0s - loss: 0.0707 - acc: 0.9764
Epoch 98/500
 - 0s - loss: 0.0687 - acc: 0.9717
Epoch 99/500
 - 0s - loss: 0.0689 - acc: 0.9858
Epoch 100/500
 - 0s - loss: 0.0644 - acc: 0.9811
Epoch 101/500
 - 0s - loss: 0.0658 - acc: 0.9717
Epoch 102/500
 - 0s - loss: 0.0695 - acc: 0.9906
Epoch 103/500
 - 0s - loss: 0.0686 - acc: 0.9670
Epoch 104/500
 - 0s - loss: 0.0642 - acc: 0.9858
Epoch 105/500
 - 0s - loss: 0.0603 - acc: 0.9953
Epoch 106/500
 - 0s - loss: 0.0704 - acc: 0.9575
Epoch 107/500
 - 0s - loss: 0.0608 - acc: 0.9953
Epoch 108/500
 - 0s - loss: 0.0586 - acc: 0.9906
Epoch 109/500
 - 0s - loss: 0.0561 - acc: 0.9906
Epoch 110/500
 - 0s - loss: 0.0539 - acc: 0.9953
Epoch 111/500
 - 0s - loss: 0.0548 - acc: 0.9906
Epoch 112/500
 - 0s - loss: 0.0513 - acc: 0.9953
Epoch 113/500
 - 0s - loss: 0.0490 - acc: 0.9953
Epoch 114/500
 - 0s - loss: 0.0493 - acc: 0.9953
Epoch 115/500
 - 0s - loss: 0.0471 - acc: 0.9953
Epoch 116/500
 - 0s - loss: 0.0482 - acc: 0.9906
Epoch 117/500
 - 0s - loss: 0.0456 - acc: 0.9953
Epoch 118/500
 - 0s - loss: 0.0437 - acc: 0.9953
Epoch 119/500
 - 0s - loss: 0.0432 - acc: 0.9953
Epoch 120/500
 - 0s - loss: 0.0432 - acc: 0.9953
Epoch 121/500
 - 0s - loss: 0.0418 - acc: 0.9953
Epoch 122/500
 - 0s - loss: 0.0409 - acc: 0.9953
Epoch 123/500
 - 0s - loss: 0.0401 - acc: 0.9953
Epoch 124/500
 - 0s - loss: 0.0407 - acc: 0.9953
Epoch 125/500
 - 0s - loss: 0.0384 - acc: 0.9953
Epoch 126/500
 - 0s - loss: 0.0372 - acc: 0.9953
Epoch 127/500
 - 0s - loss: 0.0374 - acc: 0.9953
Epoch 128/500
 - 0s - loss: 0.0374 - acc: 0.9953
Epoch 129/500
 - 0s - loss: 0.0374 - acc: 0.9953
Epoch 130/500
 - 0s - loss: 0.0362 - acc: 0.9953
Epoch 131/500
 - 0s - loss: 0.0338 - acc: 0.9953
Epoch 132/500
 - 0s - loss: 0.0330 - acc: 0.9953
Epoch 133/500
 - 0s - loss: 0.0321 - acc: 0.9953
Epoch 134/500
 - 0s - loss: 0.0315 - acc: 0.9953
Epoch 135/500
 - 0s - loss: 0.0308 - acc: 0.9953
Epoch 136/500
 - 0s - loss: 0.0296 - acc: 0.9953
Epoch 137/500
 - 0s - loss: 0.0294 - acc: 0.9953
Epoch 138/500
 - 0s - loss: 0.0285 - acc: 0.9953
Epoch 139/500
 - 0s - loss: 0.0280 - acc: 0.9953
Epoch 140/500
 - 0s - loss: 0.0285 - acc: 0.9953
Epoch 141/500
 - 0s - loss: 0.0273 - acc: 0.9953
Epoch 142/500
 - 0s - loss: 0.0266 - acc: 0.9953
Epoch 143/500
 - 0s - loss: 0.0260 - acc: 0.9953
Epoch 144/500
 - 0s - loss: 0.0256 - acc: 0.9953
Epoch 145/500
 - 0s - loss: 0.0251 - acc: 0.9953
Epoch 146/500
 - 0s - loss: 0.0247 - acc: 0.9953
Epoch 147/500
 - 0s - loss: 0.0246 - acc: 1.0000
Epoch 148/500
 - 0s - loss: 0.0240 - acc: 0.9953
Epoch 149/500
 - 0s - loss: 0.0223 - acc: 1.0000
Epoch 150/500
 - 0s - loss: 0.0218 - acc: 1.0000
Epoch 151/500
 - 0s - loss: 0.0223 - acc: 0.9953
Epoch 152/500
 - 0s - loss: 0.0225 - acc: 1.0000
Epoch 153/500
 - 0s - loss: 0.0225 - acc: 0.9953
Epoch 154/500
 - 0s - loss: 0.0212 - acc: 1.0000
Epoch 155/500
 - 0s - loss: 0.0200 - acc: 1.0000
Epoch 156/500
 - 0s - loss: 0.0188 - acc: 1.0000
Epoch 157/500
 - 0s - loss: 0.0183 - acc: 1.0000
Epoch 158/500
 - 0s - loss: 0.0179 - acc: 1.0000
Epoch 159/500
 - 0s - loss: 0.0179 - acc: 1.0000
Epoch 160/500
 - 0s - loss: 0.0168 - acc: 1.0000
Epoch 161/500
 - 0s - loss: 0.0168 - acc: 1.0000
Epoch 162/500
 - 0s - loss: 0.0164 - acc: 1.0000
Epoch 163/500
 - 0s - loss: 0.0159 - acc: 1.0000
Epoch 164/500
 - 0s - loss: 0.0156 - acc: 1.0000

Epoch 165/500
 - 0s - loss: 0.0159 - acc: 1.0000
Epoch 166/500
 - 0s - loss: 0.0148 - acc: 1.0000
Epoch 167/500
 - 0s - loss: 0.0151 - acc: 1.0000
Epoch 168/500
 - 0s - loss: 0.0144 - acc: 1.0000
Epoch 169/500
 - 0s - loss: 0.0146 - acc: 1.0000
Epoch 170/500
 - 0s - loss: 0.0146 - acc: 1.0000
Epoch 171/500
 - 0s - loss: 0.0131 - acc: 1.0000
Epoch 172/500
 - 0s - loss: 0.0141 - acc: 1.0000
Epoch 173/500
 - 0s - loss: 0.0130 - acc: 1.0000
Epoch 174/500
 - 0s - loss: 0.0128 - acc: 1.0000
Epoch 175/500
 - 0s - loss: 0.0123 - acc: 1.0000
Epoch 176/500
 - 0s - loss: 0.0121 - acc: 1.0000
Epoch 177/500
 - 0s - loss: 0.0121 - acc: 1.0000
Epoch 178/500
 - 0s - loss: 0.0122 - acc: 1.0000
Epoch 179/500
 - 0s - loss: 0.0121 - acc: 1.0000
Epoch 180/500
 - 0s - loss: 0.0112 - acc: 1.0000
Epoch 181/500
 - 0s - loss: 0.0112 - acc: 1.0000
Epoch 182/500
 - 0s - loss: 0.0113 - acc: 1.0000
Epoch 183/500
 - 0s - loss: 0.0104 - acc: 1.0000
Epoch 184/500
 - 0s - loss: 0.0107 - acc: 1.0000
Epoch 185/500
 - 0s - loss: 0.0105 - acc: 1.0000
Epoch 186/500
 - 0s - loss: 0.0100 - acc: 1.0000
Epoch 187/500
 - 0s - loss: 0.0097 - acc: 1.0000
Epoch 188/500
 - 0s - loss: 0.0094 - acc: 1.0000
Epoch 189/500
 - 0s - loss: 0.0094 - acc: 1.0000
Epoch 190/500
 - 0s - loss: 0.0093 - acc: 1.0000
Epoch 191/500
 - 0s - loss: 0.0089 - acc: 1.0000
Epoch 192/500
 - 0s - loss: 0.0088 - acc: 1.0000
Epoch 193/500
 - 0s - loss: 0.0089 - acc: 1.0000
Epoch 194/500
 - 0s - loss: 0.0088 - acc: 1.0000
Epoch 195/500
 - 0s - loss: 0.0087 - acc: 1.0000
Epoch 196/500
 - 0s - loss: 0.0082 - acc: 1.0000
Epoch 197/500
 - 0s - loss: 0.0082 - acc: 1.0000
Epoch 198/500
 - 0s - loss: 0.0080 - acc: 1.0000
Epoch 199/500
 - 0s - loss: 0.0079 - acc: 1.0000
Epoch 200/500
 - 0s - loss: 0.0077 - acc: 1.0000
Epoch 201/500
 - 0s - loss: 0.0072 - acc: 1.0000
Epoch 202/500
 - 0s - loss: 0.0075 - acc: 1.0000
Epoch 203/500
 - 0s - loss: 0.0070 - acc: 1.0000
Epoch 204/500
 - 0s - loss: 0.0069 - acc: 1.0000
Epoch 205/500
 - 0s - loss: 0.0068 - acc: 1.0000
Epoch 206/500
 - 0s - loss: 0.0070 - acc: 1.0000
Epoch 207/500
 - 0s - loss: 0.0066 - acc: 1.0000
Epoch 208/500
 - 0s - loss: 0.0064 - acc: 1.0000
Epoch 209/500
 - 0s - loss: 0.0064 - acc: 1.0000
Epoch 210/500
 - 0s - loss: 0.0064 - acc: 1.0000
Epoch 211/500
 - 0s - loss: 0.0061 - acc: 1.0000
Epoch 212/500
 - 0s - loss: 0.0061 - acc: 1.0000
Epoch 213/500
 - 0s - loss: 0.0061 - acc: 1.0000
Epoch 214/500
 - 0s - loss: 0.0057 - acc: 1.0000
Epoch 215/500
 - 0s - loss: 0.0057 - acc: 1.0000
Epoch 216/500
 - 0s - loss: 0.0057 - acc: 1.0000
Epoch 217/500
 - 0s - loss: 0.0055 - acc: 1.0000
Epoch 218/500
 - 0s - loss: 0.0055 - acc: 1.0000
Epoch 219/500
 - 0s - loss: 0.0054 - acc: 1.0000
Epoch 220/500
 - 0s - loss: 0.0053 - acc: 1.0000
Epoch 221/500
 - 0s - loss: 0.0052 - acc: 1.0000
Epoch 222/500
 - 0s - loss: 0.0052 - acc: 1.0000
Epoch 223/500
 - 0s - loss: 0.0050 - acc: 1.0000
Epoch 224/500
 - 0s - loss: 0.0050 - acc: 1.0000
Epoch 225/500
 - 0s - loss: 0.0049 - acc: 1.0000
Epoch 226/500
 - 0s - loss: 0.0049 - acc: 1.0000
Epoch 227/500
 - 0s - loss: 0.0047 - acc: 1.0000
Epoch 228/500
 - 0s - loss: 0.0046 - acc: 1.0000
Epoch 229/500
 - 0s - loss: 0.0045 - acc: 1.0000
Epoch 230/500
 - 0s - loss: 0.0045 - acc: 1.0000
Epoch 231/500
 - 0s - loss: 0.0044 - acc: 1.0000
Epoch 232/500
 - 0s - loss: 0.0045 - acc: 1.0000
Epoch 233/500
 - 0s - loss: 0.0043 - acc: 1.0000
Epoch 234/500
 - 0s - loss: 0.0042 - acc: 1.0000
Epoch 235/500
 - 0s - loss: 0.0042 - acc: 1.0000
Epoch 236/500
 - 0s - loss: 0.0041 - acc: 1.0000
Epoch 237/500
 - 0s - loss: 0.0039 - acc: 1.0000
Epoch 238/500
 - 0s - loss: 0.0039 - acc: 1.0000
Epoch 239/500
 - 0s - loss: 0.0039 - acc: 1.0000
Epoch 240/500
 - 0s - loss: 0.0038 - acc: 1.0000
Epoch 241/500
 - 0s - loss: 0.0039 - acc: 1.0000
Epoch 242/500
 - 0s - loss: 0.0038 - acc: 1.0000
Epoch 243/500
 - 0s - loss: 0.0037 - acc: 1.0000
Epoch 244/500
 - 0s - loss: 0.0037 - acc: 1.0000
Epoch 245/500
 - 0s - loss: 0.0036 - acc: 1.0000
Epoch 246/500
 - 0s - loss: 0.0037 - acc: 1.0000
Epoch 247/500
 - 0s - loss: 0.0035 - acc: 1.0000
Epoch 248/500
 - 0s - loss: 0.0034 - acc: 1.0000
Epoch 249/500
 - 0s - loss: 0.0034 - acc: 1.0000
Epoch 250/500
 - 0s - loss: 0.0033 - acc: 1.0000
Epoch 251/500
 - 0s - loss: 0.0034 - acc: 1.0000
Epoch 252/500
 - 0s - loss: 0.0032 - acc: 1.0000
Epoch 253/500
 - 0s - loss: 0.0033 - acc: 1.0000
Epoch 254/500
 - 0s - loss: 0.0033 - acc: 1.0000
Epoch 255/500
 - 0s - loss: 0.0032 - acc: 1.0000
Epoch 256/500
 - 0s - loss: 0.0032 - acc: 1.0000
Epoch 257/500
 - 0s - loss: 0.0031 - acc: 1.0000
Epoch 258/500
 - 0s - loss: 0.0030 - acc: 1.0000
Epoch 259/500
 - 0s - loss: 0.0031 - acc: 1.0000
Epoch 260/500
 - 0s - loss: 0.0029 - acc: 1.0000
Epoch 261/500
 - 0s - loss: 0.0030 - acc: 1.0000
Epoch 262/500
 - 0s - loss: 0.0028 - acc: 1.0000
Epoch 263/500
 - 0s - loss: 0.0028 - acc: 1.0000
Epoch 264/500
 - 0s - loss: 0.0028 - acc: 1.0000
Epoch 265/500
 - 0s - loss: 0.0027 - acc: 1.0000
Epoch 266/500
 - 0s - loss: 0.0027 - acc: 1.0000
Epoch 267/500
 - 0s - loss: 0.0027 - acc: 1.0000
Epoch 268/500
 - 0s - loss: 0.0027 - acc: 1.0000
Epoch 269/500
 - 0s - loss: 0.0028 - acc: 1.0000
Epoch 270/500
 - 0s - loss: 0.0028 - acc: 1.0000
Epoch 271/500
 - 0s - loss: 0.0026 - acc: 1.0000
Epoch 272/500
 - 0s - loss: 0.0025 - acc: 1.0000
Epoch 273/500
 - 0s - loss: 0.0025 - acc: 1.0000
Epoch 274/500
 - 0s - loss: 0.0025 - acc: 1.0000
Epoch 275/500
 - 0s - loss: 0.0024 - acc: 1.0000
Epoch 276/500
 - 0s - loss: 0.0024 - acc: 1.0000
Epoch 277/500
 - 0s - loss: 0.0024 - acc: 1.0000
Epoch 278/500
 - 0s - loss: 0.0023 - acc: 1.0000
Epoch 279/500
 - 0s - loss: 0.0023 - acc: 1.0000
Epoch 280/500
 - 0s - loss: 0.0023 - acc: 1.0000
Epoch 281/500
 - 0s - loss: 0.0022 - acc: 1.0000
Epoch 282/500
 - 0s - loss: 0.0022 - acc: 1.0000
Epoch 283/500
 - 0s - loss: 0.0021 - acc: 1.0000
Epoch 284/500
 - 0s - loss: 0.0022 - acc: 1.0000
Epoch 285/500
 - 0s - loss: 0.0021 - acc: 1.0000
Epoch 286/500
 - 0s - loss: 0.0022 - acc: 1.0000
Epoch 287/500
 - 0s - loss: 0.0022 - acc: 1.0000
Epoch 288/500
 - 0s - loss: 0.0021 - acc: 1.0000
Epoch 289/500
 - 0s - loss: 0.0020 - acc: 1.0000
Epoch 290/500
 - 0s - loss: 0.0020 - acc: 1.0000
Epoch 291/500
 - 0s - loss: 0.0020 - acc: 1.0000
Epoch 292/500
 - 0s - loss: 0.0019 - acc: 1.0000
Epoch 293/500
 - 0s - loss: 0.0019 - acc: 1.0000
Epoch 294/500
 - 0s - loss: 0.0019 - acc: 1.0000
Epoch 295/500
 - 0s - loss: 0.0019 - acc: 1.0000
Epoch 296/500
 - 0s - loss: 0.0019 - acc: 1.0000
Epoch 297/500
 - 0s - loss: 0.0018 - acc: 1.0000
Epoch 298/500
 - 0s - loss: 0.0018 - acc: 1.0000
Epoch 299/500
 - 0s - loss: 0.0018 - acc: 1.0000
Epoch 300/500
 - 0s - loss: 0.0018 - acc: 1.0000
Epoch 301/500
 - 0s - loss: 0.0017 - acc: 1.0000
Epoch 302/500
 - 0s - loss: 0.0018 - acc: 1.0000
Epoch 303/500
 - 0s - loss: 0.0017 - acc: 1.0000
Epoch 304/500
 - 0s - loss: 0.0018 - acc: 1.0000
Epoch 305/500
 - 0s - loss: 0.0018 - acc: 1.0000
Epoch 306/500
 - 0s - loss: 0.0017 - acc: 1.0000
Epoch 307/500
 - 0s - loss: 0.0018 - acc: 1.0000
Epoch 308/500
 - 0s - loss: 0.0017 - acc: 1.0000
Epoch 309/500
 - 0s - loss: 0.0016 - acc: 1.0000
Epoch 310/500
 - 0s - loss: 0.0016 - acc: 1.0000
Epoch 311/500
 - 0s - loss: 0.0016 - acc: 1.0000
Epoch 312/500
 - 0s - loss: 0.0016 - acc: 1.0000
Epoch 313/500
 - 0s - loss: 0.0015 - acc: 1.0000
Epoch 314/500
 - 0s - loss: 0.0015 - acc: 1.0000
Epoch 315/500
 - 0s - loss: 0.0015 - acc: 1.0000
Epoch 316/500
 - 0s - loss: 0.0015 - acc: 1.0000
Epoch 317/500
 - 0s - loss: 0.0015 - acc: 1.0000
Epoch 318/500
 - 0s - loss: 0.0016 - acc: 1.0000
Epoch 319/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 320/500
 - 0s - loss: 0.0015 - acc: 1.0000
Epoch 321/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 322/500
 - 0s - loss: 0.0015 - acc: 1.0000
Epoch 323/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 324/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 325/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 326/500
 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 327/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 328/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 329/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 330/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 331/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 332/500
 - 0s - loss: 0.0013 - acc: 1.0000

Epoch 333/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 334/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 335/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 336/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 337/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 338/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 339/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 340/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 341/500
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 342/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 343/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 344/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 345/500
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 346/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 347/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 348/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 349/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 350/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 351/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 352/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 353/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 354/500
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 355/500
 - 0s - loss: 0.0010 - acc: 1.0000
Epoch 356/500
 - 0s - loss: 0.0010 - acc: 1.0000
Epoch 357/500
 - 0s - loss: 0.0010 - acc: 1.0000
Epoch 358/500
 - 0s - loss: 9.9254e-04 - acc: 1.0000
Epoch 359/500
 - 0s - loss: 0.0010 - acc: 1.0000
Epoch 360/500
 - 0s - loss: 9.9006e-04 - acc: 1.0000
Epoch 361/500
 - 0s - loss: 9.8606e-04 - acc: 1.0000
Epoch 362/500
 - 0s - loss: 9.6803e-04 - acc: 1.0000
Epoch 363/500
 - 0s - loss: 9.4949e-04 - acc: 1.0000
Epoch 364/500
 - 0s - loss: 9.4049e-04 - acc: 1.0000
Epoch 365/500
 - 0s - loss: 9.6776e-04 - acc: 1.0000
Epoch 366/500
 - 0s - loss: 9.2382e-04 - acc: 1.0000
Epoch 367/500
 - 0s - loss: 9.2276e-04 - acc: 1.0000
Epoch 368/500
 - 0s - loss: 9.2279e-04 - acc: 1.0000
Epoch 369/500
 - 0s - loss: 9.0772e-04 - acc: 1.0000
Epoch 370/500
 - 0s - loss: 9.0352e-04 - acc: 1.0000
Epoch 371/500
 - 0s - loss: 8.8781e-04 - acc: 1.0000
Epoch 372/500
 - 0s - loss: 8.8906e-04 - acc: 1.0000
Epoch 373/500
 - 0s - loss: 8.7222e-04 - acc: 1.0000
Epoch 374/500
 - 0s - loss: 8.6270e-04 - acc: 1.0000
Epoch 375/500
 - 0s - loss: 8.5475e-04 - acc: 1.0000
Epoch 376/500
 - 0s - loss: 8.4752e-04 - acc: 1.0000
Epoch 377/500
 - 0s - loss: 8.5463e-04 - acc: 1.0000
Epoch 378/500
 - 0s - loss: 8.3160e-04 - acc: 1.0000
Epoch 379/500
 - 0s - loss: 8.3205e-04 - acc: 1.0000
Epoch 380/500
 - 0s - loss: 8.2401e-04 - acc: 1.0000
Epoch 381/500
 - 0s - loss: 8.0850e-04 - acc: 1.0000
Epoch 382/500
 - 0s - loss: 8.3453e-04 - acc: 1.0000
Epoch 383/500
 - 0s - loss: 8.1096e-04 - acc: 1.0000
Epoch 384/500
 - 0s - loss: 8.2951e-04 - acc: 1.0000
Epoch 385/500
 - 0s - loss: 7.7189e-04 - acc: 1.0000
Epoch 386/500
 - 0s - loss: 7.9015e-04 - acc: 1.0000
Epoch 387/500
 - 0s - loss: 7.7597e-04 - acc: 1.0000
Epoch 388/500
 - 0s - loss: 7.7190e-04 - acc: 1.0000
Epoch 389/500
 - 0s - loss: 7.5255e-04 - acc: 1.0000
Epoch 390/500
 - 0s - loss: 7.5464e-04 - acc: 1.0000
Epoch 391/500
 - 0s - loss: 7.4948e-04 - acc: 1.0000
Epoch 392/500
 - 0s - loss: 7.3823e-04 - acc: 1.0000
Epoch 393/500
 - 0s - loss: 7.2962e-04 - acc: 1.0000
Epoch 394/500
 - 0s - loss: 7.2939e-04 - acc: 1.0000
Epoch 395/500
 - 0s - loss: 7.3203e-04 - acc: 1.0000
Epoch 396/500
 - 0s - loss: 7.3677e-04 - acc: 1.0000
Epoch 397/500
 - 0s - loss: 7.0980e-04 - acc: 1.0000
Epoch 398/500
 - 0s - loss: 7.0486e-04 - acc: 1.0000
Epoch 399/500
 - 0s - loss: 7.1053e-04 - acc: 1.0000
Epoch 400/500
 - 0s - loss: 6.9628e-04 - acc: 1.0000
Epoch 401/500
 - 0s - loss: 6.8621e-04 - acc: 1.0000
Epoch 402/500
 - 0s - loss: 6.7572e-04 - acc: 1.0000
Epoch 403/500
 - 0s - loss: 6.7574e-04 - acc: 1.0000
Epoch 404/500
 - 0s - loss: 6.7063e-04 - acc: 1.0000
Epoch 405/500
 - 0s - loss: 6.6175e-04 - acc: 1.0000
Epoch 406/500
 - 0s - loss: 6.7506e-04 - acc: 1.0000
Epoch 407/500
 - 0s - loss: 6.5176e-04 - acc: 1.0000
Epoch 408/500
 - 0s - loss: 6.6748e-04 - acc: 1.0000
Epoch 409/500
 - 0s - loss: 6.4895e-04 - acc: 1.0000
Epoch 410/500
 - 0s - loss: 6.5720e-04 - acc: 1.0000
Epoch 411/500
 - 0s - loss: 6.3062e-04 - acc: 1.0000
Epoch 412/500
 - 0s - loss: 6.3140e-04 - acc: 1.0000
Epoch 413/500
 - 0s - loss: 6.2102e-04 - acc: 1.0000
Epoch 414/500
 - 0s - loss: 6.4787e-04 - acc: 1.0000
Epoch 415/500
 - 0s - loss: 6.2005e-04 - acc: 1.0000
Epoch 416/500
 - 0s - loss: 6.2659e-04 - acc: 1.0000
Epoch 417/500
 - 0s - loss: 6.0894e-04 - acc: 1.0000
Epoch 418/500
 - 0s - loss: 5.9758e-04 - acc: 1.0000
Epoch 419/500
 - 0s - loss: 6.0375e-04 - acc: 1.0000
Epoch 420/500
 - 0s - loss: 5.9766e-04 - acc: 1.0000
Epoch 421/500
 - 0s - loss: 5.8999e-04 - acc: 1.0000
Epoch 422/500
 - 0s - loss: 5.7877e-04 - acc: 1.0000
Epoch 423/500
 - 0s - loss: 5.7877e-04 - acc: 1.0000
Epoch 424/500
 - 0s - loss: 5.6944e-04 - acc: 1.0000
Epoch 425/500
 - 0s - loss: 5.6654e-04 - acc: 1.0000
Epoch 426/500
 - 0s - loss: 5.6756e-04 - acc: 1.0000
Epoch 427/500
 - 0s - loss: 5.6618e-04 - acc: 1.0000
Epoch 428/500
 - 0s - loss: 5.4749e-04 - acc: 1.0000
Epoch 429/500
 - 0s - loss: 5.5953e-04 - acc: 1.0000
Epoch 430/500
 - 0s - loss: 5.4721e-04 - acc: 1.0000
Epoch 431/500
 - 0s - loss: 5.8035e-04 - acc: 1.0000
Epoch 432/500
 - 0s - loss: 5.5354e-04 - acc: 1.0000
Epoch 433/500
 - 0s - loss: 5.3926e-04 - acc: 1.0000
Epoch 434/500
 - 0s - loss: 5.3655e-04 - acc: 1.0000
Epoch 435/500
 - 0s - loss: 5.2519e-04 - acc: 1.0000
Epoch 436/500
 - 0s - loss: 5.2855e-04 - acc: 1.0000
Epoch 437/500
 - 0s - loss: 5.2042e-04 - acc: 1.0000
Epoch 438/500
 - 0s - loss: 5.1480e-04 - acc: 1.0000
Epoch 439/500
 - 0s - loss: 5.1600e-04 - acc: 1.0000
Epoch 440/500
 - 0s - loss: 5.0725e-04 - acc: 1.0000
Epoch 441/500
 - 0s - loss: 4.9681e-04 - acc: 1.0000
Epoch 442/500
 - 0s - loss: 5.1318e-04 - acc: 1.0000
Epoch 443/500
 - 0s - loss: 4.9969e-04 - acc: 1.0000
Epoch 444/500
 - 0s - loss: 4.8920e-04 - acc: 1.0000
Epoch 445/500
 - 0s - loss: 4.9369e-04 - acc: 1.0000
Epoch 446/500
 - 0s - loss: 4.8548e-04 - acc: 1.0000
Epoch 447/500
 - 0s - loss: 4.8230e-04 - acc: 1.0000
Epoch 448/500
 - 0s - loss: 4.8516e-04 - acc: 1.0000
Epoch 449/500
 - 0s - loss: 4.7591e-04 - acc: 1.0000
Epoch 450/500
 - 0s - loss: 4.7376e-04 - acc: 1.0000
Epoch 451/500
 - 0s - loss: 4.6881e-04 - acc: 1.0000
Epoch 452/500
 - 0s - loss: 4.6919e-04 - acc: 1.0000
Epoch 453/500
 - 0s - loss: 4.6067e-04 - acc: 1.0000
Epoch 454/500
 - 0s - loss: 4.5635e-04 - acc: 1.0000
Epoch 455/500
 - 0s - loss: 4.5758e-04 - acc: 1.0000
Epoch 456/500
 - 0s - loss: 4.4836e-04 - acc: 1.0000
Epoch 457/500
 - 0s - loss: 4.4772e-04 - acc: 1.0000
Epoch 458/500
 - 0s - loss: 4.4876e-04 - acc: 1.0000
Epoch 459/500
 - 0s - loss: 4.3995e-04 - acc: 1.0000
Epoch 460/500
 - 0s - loss: 4.4049e-04 - acc: 1.0000
Epoch 461/500
 - 0s - loss: 4.3730e-04 - acc: 1.0000
Epoch 462/500
 - 0s - loss: 4.3117e-04 - acc: 1.0000
Epoch 463/500
 - 0s - loss: 4.3347e-04 - acc: 1.0000
Epoch 464/500
 - 0s - loss: 4.3329e-04 - acc: 1.0000
Epoch 465/500
 - 0s - loss: 4.2185e-04 - acc: 1.0000
Epoch 466/500
 - 0s - loss: 4.3677e-04 - acc: 1.0000
Epoch 467/500
 - 0s - loss: 4.2767e-04 - acc: 1.0000
Epoch 468/500
 - 0s - loss: 4.1854e-04 - acc: 1.0000
Epoch 469/500
 - 0s - loss: 4.1152e-04 - acc: 1.0000
Epoch 470/500
 - 0s - loss: 4.0837e-04 - acc: 1.0000
Epoch 471/500
 - 0s - loss: 4.0998e-04 - acc: 1.0000
Epoch 472/500
 - 0s - loss: 4.0493e-04 - acc: 1.0000
Epoch 473/500
 - 0s - loss: 4.0400e-04 - acc: 1.0000
Epoch 474/500
 - 0s - loss: 3.9429e-04 - acc: 1.0000
Epoch 475/500
 - 0s - loss: 4.0257e-04 - acc: 1.0000
Epoch 476/500
 - 0s - loss: 3.8982e-04 - acc: 1.0000
Epoch 477/500
 - 0s - loss: 3.9143e-04 - acc: 1.0000
Epoch 478/500
 - 0s - loss: 3.8973e-04 - acc: 1.0000
Epoch 479/500
 - 0s - loss: 3.8542e-04 - acc: 1.0000
Epoch 480/500
 - 0s - loss: 3.8026e-04 - acc: 1.0000
Epoch 481/500
 - 0s - loss: 3.8331e-04 - acc: 1.0000
Epoch 482/500
 - 0s - loss: 3.7735e-04 - acc: 1.0000
Epoch 483/500
 - 0s - loss: 3.7812e-04 - acc: 1.0000
Epoch 484/500
 - 0s - loss: 3.7016e-04 - acc: 1.0000
Epoch 485/500
 - 0s - loss: 3.7104e-04 - acc: 1.0000
Epoch 486/500
 - 0s - loss: 3.6163e-04 - acc: 1.0000
Epoch 487/500
 - 0s - loss: 3.7426e-04 - acc: 1.0000
Epoch 488/500
 - 0s - loss: 3.5809e-04 - acc: 1.0000
Epoch 489/500
 - 0s - loss: 3.6353e-04 - acc: 1.0000

Epoch 490/500
 - 0s - loss: 3.5377e-04 - acc: 1.0000
Epoch 491/500
 - 0s - loss: 3.6417e-04 - acc: 1.0000
Epoch 492/500
 - 0s - loss: 3.6154e-04 - acc: 1.0000
Epoch 493/500
 - 0s - loss: 3.4765e-04 - acc: 1.0000
Epoch 494/500
 - 0s - loss: 3.4684e-04 - acc: 1.0000
Epoch 495/500
 - 0s - loss: 3.4445e-04 - acc: 1.0000
Epoch 496/500
 - 0s - loss: 3.3869e-04 - acc: 1.0000
Epoch 497/500
 - 0s - loss: 3.4548e-04 - acc: 1.0000
Epoch 498/500
 - 0s - loss: 3.3862e-04 - acc: 1.0000
Epoch 499/500
 - 0s - loss: 3.3396e-04 - acc: 1.0000
Epoch 500/500
 - 0s - loss: 3.3456e-04 - acc: 1.0000

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 1.0249 - acc: 0.8873
Normal Neural Network - Loss: 1.0249275501770734, Accuracy: 0.8873239159584045

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Certified' 'Certified' 'Certified' 'Certified' 'Certified'
 'Certified' 'Certified' 'Certified' 'Certified']
Actual Labels: ['Certified', 'Certified', 'Denied', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified']