In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'NEPAL']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

NEPAL    1847
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    1794
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [8]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [9]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [10]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
82,Certified,567,20852,MARYLAND,45.0,65395.0,NEPAL,H-1B,Master's,11.0
130,Certified,585,21230,MARYLAND,222.0,120016.0,NEPAL,H-1B,Bachelor's,8.0
219,Certified,557,68144,NEBRASKA,25.0,26000.0,NEPAL,F-1,Other,11.0
222,Certified,455,80306,COLORADO,10.0,25000.0,NEPAL,NaN,None,4.0
264,Certified,441,22043,VIRGINIA,6.0,75670.0,NEPAL,H-1B,Master's,5.0

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

TEXAS                   311
CALIFORNIA              166
VIRGINIA                138
NEW JERSEY              133
MASSACHUSETTS            94
NEW YORK                 92
ILLINOIS                 76
MARYLAND                 72
COLORADO                 58
PENNSYLVANIA             52
MINNESOTA                49
WASHINGTON               44
OHIO                     40
FLORIDA                  39
GEORGIA                  36
MICHIGAN                 30
MISSOURI                 30
OKLAHOMA                 26
NORTH CAROLINA           25
NEBRASKA                 24
CONNECTICUT              23
KENTUCKY                 19
IOWA                     19
KANSAS                   18
WISCONSIN                17
LOUISIANA                16
TENNESSEE                13
ARIZONA                  12
INDIANA                  11
ALABAMA                   9
SOUTH DAKOTA              9
OREGON                    9
UTAH                      9
RHODE ISLAND              8
DISTRICT OF COLUMBIA      7
ARKANSAS                  7
WEST VIRGINIA             6
MAINE                     6
VERMONT                   5
SOUTH CAROLINA            5
NORTH DAKOTA              5
NEW HAMPSHIRE             4
MONTANA                   4
UNKNOWN                   3
NEVADA                    3
NEW MEXICO                3
HAWAII                    2
IDAHO                     2
WYOMING                   2
DELAWARE                  2
MISSISSIPPI               1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
82,Certified,567,20852,MARYLAND,45.0,65395.0,NEPAL,H-1B,Master's,11.0,MARYLAND
130,Certified,585,21230,MARYLAND,222.0,120016.0,NEPAL,H-1B,Bachelor's,8.0,MARYLAND
219,Certified,557,68144,NEBRASKA,25.0,26000.0,NEPAL,F-1,Other,11.0,NEBRASKA
264,Certified,441,22043,VIRGINIA,6.0,75670.0,NEPAL,H-1B,Master's,5.0,VIRGINIA
327,Certified,476,20151,VIRGINIA,14.0,47174.0,NEPAL,H-1B,Bachelor's,3.0,VIRGINIA

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

SOUTH        681
NORTHEAST    398
MIDWEST      299
WEST         299
UNKNOWN        3
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      1680
DECISION_ELAPSED_DAYS            1680
EMPLOYER_POSTAL_CODE             1680
EMPLOYER_STATE                   1680
EMPLOYER_NUM_EMPLOYEES           1680
WAGE_OFFER_FROM_9089             1680
COUNTRY_OF_CITIZENSHIP           1680
CLASS_OF_ADMISSION               1680
FOREIGN_WORKER_INFO_EDUCATION    1680
CASE_RECEIVED_DATE_MONTH         1680
EMPLOYER_STATES                  1680
EMPLOYER_REGIONS                 1680
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      687
0-90        456
181-365     404
366-3600    131
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

75001-100000     605
50001-75000      537
100000-500000    342
25001-50000      168
0-25000           27
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

0-50                507
101-500             401
1001-10000          301
10001-1000000000    222
51-100              158
501-1000             89
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      1680
DECISION_ELAPSED_DAYS            1680
EMPLOYER_POSTAL_CODE             1680
EMPLOYER_STATE                   1680
EMPLOYER_NUM_EMPLOYEES           1680
WAGE_OFFER_FROM_9089             1680
COUNTRY_OF_CITIZENSHIP           1680
CLASS_OF_ADMISSION               1680
FOREIGN_WORKER_INFO_EDUCATION    1680
CASE_RECEIVED_DATE_MONTH         1680
EMPLOYER_STATES                  1680
EMPLOYER_REGIONS                 1680
DAY_BINS                         1678
WAGE_BINS                        1679
EMPLOYEE_BINS                    1678
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
82,Certified,0-50,50001-75000,SOUTH,11.0,Master's,H-1B,366-3600
130,Certified,101-500,100000-500000,SOUTH,8.0,Bachelor's,H-1B,366-3600
219,Certified,0-50,25001-50000,MIDWEST,11.0,Other,F-1,366-3600
264,Certified,0-50,75001-100000,SOUTH,5.0,Master's,H-1B,366-3600
327,Certified,0-50,25001-50000,SOUTH,3.0,Bachelor's,H-1B,366-3600

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
82,Certified,0-50,50001-75000,SOUTH,11.0,Master's,H-1B,366-3600,7,4,3,2,2,0
130,Certified,101-500,100000-500000,SOUTH,8.0,Bachelor's,H-1B,366-3600,7,1,1,2,2,3
219,Certified,0-50,25001-50000,MIDWEST,11.0,Other,F-1,366-3600,4,6,2,0,2,0
264,Certified,0-50,75001-100000,SOUTH,5.0,Master's,H-1B,366-3600,7,4,4,2,2,0
327,Certified,0-50,25001-50000,SOUTH,3.0,Bachelor's,H-1B,366-3600,7,1,2,2,2,0

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           1680
EMPLOYEE_BINS                         1680
WAGE_BINS                             1680
EMPLOYER_REGIONS                      1680
CASE_RECEIVED_DATE_MONTH              1680
FOREIGN_WORKER_INFO_EDUCATION         1680
CLASS_OF_ADMISSION                    1680
DAY_BINS                              1680
CLASS_OF_ADMISSION_CODE               1680
FOREIGN_WORKER_INFO_EDUCATION_CODE    1680
WAGE_BINS_CODE                        1680
EMPLOYER_REGIONS_CODE                 1680
DAY_BINS_CODE                         1680
EMPLOYEE_BINS_CODE                    1680
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
82,Certified,0,3,2,4,7,11.0,2
130,Certified,3,1,2,1,7,8.0,2
219,Certified,0,2,2,6,4,11.0,0
264,Certified,0,4,2,4,7,5.0,2
327,Certified,0,2,2,1,7,3.0,2

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int64
WAGE_BINS_CODE                          int64
DAY_BINS_CODE                           int64
FOREIGN_WORKER_INFO_EDUCATION_CODE      int64
CLASS_OF_ADMISSION_CODE                 int64
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int64
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(1680, 7) (1680,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [53]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 1s - loss: 0.3489 - acc: 0.9111
Epoch 2/500
 - 0s - loss: 0.2655 - acc: 0.9246
Epoch 3/500
 - 0s - loss: 0.2652 - acc: 0.9246
Epoch 4/500
 - 0s - loss: 0.2614 - acc: 0.9246
Epoch 5/500
 - 0s - loss: 0.2601 - acc: 0.9246
Epoch 6/500
 - 0s - loss: 0.2617 - acc: 0.9246
Epoch 7/500
 - 0s - loss: 0.2549 - acc: 0.9246
Epoch 8/500
 - 0s - loss: 0.2521 - acc: 0.9246
Epoch 9/500
 - 0s - loss: 0.2501 - acc: 0.9246
Epoch 10/500
 - 0s - loss: 0.2461 - acc: 0.9246
Epoch 11/500
 - 0s - loss: 0.2437 - acc: 0.9246
Epoch 12/500
 - 0s - loss: 0.2395 - acc: 0.9246
Epoch 13/500
 - 0s - loss: 0.2392 - acc: 0.9246
Epoch 14/500
 - 0s - loss: 0.2328 - acc: 0.9246
Epoch 15/500
 - 0s - loss: 0.2297 - acc: 0.9246
Epoch 16/500
 - 0s - loss: 0.2285 - acc: 0.9246
Epoch 17/500
 - 0s - loss: 0.2243 - acc: 0.9246
Epoch 18/500
 - 0s - loss: 0.2238 - acc: 0.9246
Epoch 19/500
 - 0s - loss: 0.2207 - acc: 0.9254
Epoch 20/500
 - 0s - loss: 0.2181 - acc: 0.9246
Epoch 21/500
 - 0s - loss: 0.2166 - acc: 0.9262
Epoch 22/500
 - 0s - loss: 0.2174 - acc: 0.9254
Epoch 23/500
 - 0s - loss: 0.2117 - acc: 0.9262
Epoch 24/500
 - 0s - loss: 0.2078 - acc: 0.9262
Epoch 25/500
 - 0s - loss: 0.2046 - acc: 0.9270
Epoch 26/500
 - 0s - loss: 0.2040 - acc: 0.9286
Epoch 27/500
 - 0s - loss: 0.2042 - acc: 0.9270
Epoch 28/500
 - 0s - loss: 0.2012 - acc: 0.9294
Epoch 29/500
 - 0s - loss: 0.2001 - acc: 0.9294
Epoch 30/500
 - 0s - loss: 0.1958 - acc: 0.9310
Epoch 31/500
 - 0s - loss: 0.2007 - acc: 0.9286
Epoch 32/500
 - 0s - loss: 0.1921 - acc: 0.9278
Epoch 33/500
 - 0s - loss: 0.1898 - acc: 0.9310
Epoch 34/500
 - 0s - loss: 0.1939 - acc: 0.9286
Epoch 35/500
 - 0s - loss: 0.1907 - acc: 0.9317
Epoch 36/500
 - 0s - loss: 0.1880 - acc: 0.9286
Epoch 37/500
 - 0s - loss: 0.1831 - acc: 0.9294
Epoch 38/500
 - 0s - loss: 0.1850 - acc: 0.9302
Epoch 39/500
 - 0s - loss: 0.1826 - acc: 0.9333
Epoch 40/500
 - 0s - loss: 0.1774 - acc: 0.9325
Epoch 41/500
 - 0s - loss: 0.1763 - acc: 0.9302
Epoch 42/500
 - 0s - loss: 0.1745 - acc: 0.9310
Epoch 43/500
 - 0s - loss: 0.1726 - acc: 0.9325
Epoch 44/500
 - 0s - loss: 0.1712 - acc: 0.9365
Epoch 45/500
 - 0s - loss: 0.1760 - acc: 0.9325
Epoch 46/500
 - 0s - loss: 0.1697 - acc: 0.9389
Epoch 47/500
 - 0s - loss: 0.1624 - acc: 0.9341
Epoch 48/500
 - 0s - loss: 0.1705 - acc: 0.9381
Epoch 49/500
 - 0s - loss: 0.1623 - acc: 0.9373
Epoch 50/500
 - 0s - loss: 0.1600 - acc: 0.9397
Epoch 51/500
 - 0s - loss: 0.1621 - acc: 0.9405
Epoch 52/500
 - 0s - loss: 0.1590 - acc: 0.9397
Epoch 53/500
 - 0s - loss: 0.1588 - acc: 0.9405
Epoch 54/500
 - 0s - loss: 0.1572 - acc: 0.9460
Epoch 55/500
 - 0s - loss: 0.1555 - acc: 0.9357
Epoch 56/500
 - 0s - loss: 0.1556 - acc: 0.9389
Epoch 57/500
 - 0s - loss: 0.1501 - acc: 0.9437
Epoch 58/500
 - 0s - loss: 0.1504 - acc: 0.9452
Epoch 59/500
 - 0s - loss: 0.1510 - acc: 0.9437
Epoch 60/500
 - 0s - loss: 0.1457 - acc: 0.9468
Epoch 61/500
 - 0s - loss: 0.1426 - acc: 0.9444
Epoch 62/500
 - 0s - loss: 0.1541 - acc: 0.9373
Epoch 63/500
 - 0s - loss: 0.1446 - acc: 0.9476
Epoch 64/500
 - 0s - loss: 0.1436 - acc: 0.9476
Epoch 65/500
 - 0s - loss: 0.1403 - acc: 0.9484
Epoch 66/500
 - 0s - loss: 0.1381 - acc: 0.9468
Epoch 67/500
 - 0s - loss: 0.1369 - acc: 0.9437
Epoch 68/500
 - 0s - loss: 0.1326 - acc: 0.9524
Epoch 69/500
 - 0s - loss: 0.1362 - acc: 0.9508
Epoch 70/500
 - 0s - loss: 0.1333 - acc: 0.9500
Epoch 71/500
 - 0s - loss: 0.1344 - acc: 0.9492
Epoch 72/500
 - 0s - loss: 0.1356 - acc: 0.9492
Epoch 73/500
 - 0s - loss: 0.1258 - acc: 0.9540
Epoch 74/500
 - 0s - loss: 0.1282 - acc: 0.9508
Epoch 75/500
 - 0s - loss: 0.1275 - acc: 0.9524
Epoch 76/500
 - 0s - loss: 0.1247 - acc: 0.9516
Epoch 77/500
 - 0s - loss: 0.1263 - acc: 0.9508
Epoch 78/500
 - 0s - loss: 0.1232 - acc: 0.9548
Epoch 79/500
 - 0s - loss: 0.1249 - acc: 0.9548
Epoch 80/500
 - 0s - loss: 0.1218 - acc: 0.9524
Epoch 81/500
 - 0s - loss: 0.1185 - acc: 0.9556
Epoch 82/500
 - 0s - loss: 0.1188 - acc: 0.9556
Epoch 83/500
 - 0s - loss: 0.1193 - acc: 0.9579
Epoch 84/500
 - 0s - loss: 0.1151 - acc: 0.9563
Epoch 85/500
 - 0s - loss: 0.1140 - acc: 0.9556
Epoch 86/500
 - 0s - loss: 0.1197 - acc: 0.9548
Epoch 87/500
 - 0s - loss: 0.1150 - acc: 0.9516
Epoch 88/500
 - 0s - loss: 0.1094 - acc: 0.9611
Epoch 89/500
 - 0s - loss: 0.1104 - acc: 0.9595
Epoch 90/500
 - 0s - loss: 0.1123 - acc: 0.9595
Epoch 91/500
 - 0s - loss: 0.1092 - acc: 0.9563
Epoch 92/500
 - 0s - loss: 0.1130 - acc: 0.9532
Epoch 93/500
 - 0s - loss: 0.1095 - acc: 0.9595
Epoch 94/500
 - 0s - loss: 0.1056 - acc: 0.9603
Epoch 95/500
 - 0s - loss: 0.1024 - acc: 0.9619
Epoch 96/500
 - 0s - loss: 0.1121 - acc: 0.9571
Epoch 97/500
 - 0s - loss: 0.1028 - acc: 0.9595
Epoch 98/500
 - 0s - loss: 0.1021 - acc: 0.9603
Epoch 99/500
 - 0s - loss: 0.0981 - acc: 0.9651
Epoch 100/500
 - 0s - loss: 0.0985 - acc: 0.9595
Epoch 101/500
 - 0s - loss: 0.1007 - acc: 0.9643
Epoch 102/500
 - 0s - loss: 0.0981 - acc: 0.9651
Epoch 103/500
 - 0s - loss: 0.0981 - acc: 0.9635
Epoch 104/500
 - 0s - loss: 0.0939 - acc: 0.9627
Epoch 105/500
 - 0s - loss: 0.0999 - acc: 0.9651
Epoch 106/500
 - 0s - loss: 0.0979 - acc: 0.9611
Epoch 107/500
 - 0s - loss: 0.0931 - acc: 0.9659
Epoch 108/500
 - 0s - loss: 0.0907 - acc: 0.9627
Epoch 109/500
 - 0s - loss: 0.0919 - acc: 0.9611
Epoch 110/500
 - 0s - loss: 0.0911 - acc: 0.9643
Epoch 111/500
 - 0s - loss: 0.0894 - acc: 0.9675
Epoch 112/500
 - 0s - loss: 0.0901 - acc: 0.9667
Epoch 113/500
 - 0s - loss: 0.0933 - acc: 0.9619
Epoch 114/500
 - 0s - loss: 0.0912 - acc: 0.9651
Epoch 115/500
 - 0s - loss: 0.0951 - acc: 0.9635
Epoch 116/500
 - 0s - loss: 0.0966 - acc: 0.9643
Epoch 117/500
 - 0s - loss: 0.0868 - acc: 0.9675
Epoch 118/500
 - 0s - loss: 0.0865 - acc: 0.9675
Epoch 119/500
 - 0s - loss: 0.0867 - acc: 0.9698
Epoch 120/500
 - 0s - loss: 0.0834 - acc: 0.9706
Epoch 121/500
 - 0s - loss: 0.0843 - acc: 0.9683
Epoch 122/500
 - 0s - loss: 0.0896 - acc: 0.9683
Epoch 123/500
 - 0s - loss: 0.0870 - acc: 0.9714
Epoch 124/500
 - 0s - loss: 0.0835 - acc: 0.9690
Epoch 125/500
 - 0s - loss: 0.0829 - acc: 0.9706
Epoch 126/500
 - 0s - loss: 0.0820 - acc: 0.9675
Epoch 127/500
 - 0s - loss: 0.0798 - acc: 0.9706
Epoch 128/500
 - 0s - loss: 0.0815 - acc: 0.9714
Epoch 129/500
 - 0s - loss: 0.0790 - acc: 0.9706
Epoch 130/500
 - 0s - loss: 0.0833 - acc: 0.9698
Epoch 131/500
 - 0s - loss: 0.0785 - acc: 0.9698
Epoch 132/500
 - 0s - loss: 0.0785 - acc: 0.9714
Epoch 133/500
 - 0s - loss: 0.0831 - acc: 0.9675
Epoch 134/500
 - 0s - loss: 0.0804 - acc: 0.9690
Epoch 135/500
 - 0s - loss: 0.0824 - acc: 0.9706
Epoch 136/500
 - 0s - loss: 0.0781 - acc: 0.9738
Epoch 137/500
 - 0s - loss: 0.0771 - acc: 0.9722
Epoch 138/500
 - 0s - loss: 0.0813 - acc: 0.9675
Epoch 139/500
 - 0s - loss: 0.0737 - acc: 0.9722
Epoch 140/500
 - 0s - loss: 0.0756 - acc: 0.9730
Epoch 141/500
 - 0s - loss: 0.0810 - acc: 0.9690
Epoch 142/500
 - 0s - loss: 0.0762 - acc: 0.9698
Epoch 143/500
 - 0s - loss: 0.0739 - acc: 0.9698
Epoch 144/500
 - 0s - loss: 0.0716 - acc: 0.9746
Epoch 145/500
 - 0s - loss: 0.0772 - acc: 0.9619
Epoch 146/500
 - 0s - loss: 0.0723 - acc: 0.9722
Epoch 147/500
 - 0s - loss: 0.0710 - acc: 0.9746
Epoch 148/500
 - 0s - loss: 0.0744 - acc: 0.9722
Epoch 149/500
 - 0s - loss: 0.0764 - acc: 0.9730
Epoch 150/500
 - 0s - loss: 0.0696 - acc: 0.9738
Epoch 151/500
 - 0s - loss: 0.0696 - acc: 0.9754
Epoch 152/500
 - 0s - loss: 0.0674 - acc: 0.9746
Epoch 153/500
 - 0s - loss: 0.0686 - acc: 0.9754
Epoch 154/500
 - 0s - loss: 0.0670 - acc: 0.9738
Epoch 155/500
 - 0s - loss: 0.0674 - acc: 0.9706
Epoch 156/500
 - 0s - loss: 0.0664 - acc: 0.9738
Epoch 157/500
 - 0s - loss: 0.0656 - acc: 0.9746
Epoch 158/500
 - 0s - loss: 0.0667 - acc: 0.9746
Epoch 159/500
 - 0s - loss: 0.0747 - acc: 0.9698
Epoch 160/500
 - 0s - loss: 0.0691 - acc: 0.9754
Epoch 161/500
 - 0s - loss: 0.0664 - acc: 0.9738
Epoch 162/500
 - 0s - loss: 0.0658 - acc: 0.9746
Epoch 163/500
 - 0s - loss: 0.0658 - acc: 0.9762
Epoch 164/500
 - 0s - loss: 0.0651 - acc: 0.9754

Epoch 165/500
 - 0s - loss: 0.0677 - acc: 0.9770
Epoch 166/500
 - 0s - loss: 0.0632 - acc: 0.9738
Epoch 167/500
 - 0s - loss: 0.0623 - acc: 0.9762
Epoch 168/500
 - 0s - loss: 0.0665 - acc: 0.9762
Epoch 169/500
 - 0s - loss: 0.0618 - acc: 0.9762
Epoch 170/500
 - 0s - loss: 0.0586 - acc: 0.9802
Epoch 171/500
 - 0s - loss: 0.0678 - acc: 0.9722
Epoch 172/500
 - 0s - loss: 0.0641 - acc: 0.9738
Epoch 173/500
 - 0s - loss: 0.0577 - acc: 0.9786
Epoch 174/500
 - 0s - loss: 0.0712 - acc: 0.9706
Epoch 175/500
 - 0s - loss: 0.0617 - acc: 0.9762
Epoch 176/500
 - 0s - loss: 0.0618 - acc: 0.9730
Epoch 177/500
 - 0s - loss: 0.0604 - acc: 0.9770
Epoch 178/500
 - 0s - loss: 0.0560 - acc: 0.9817
Epoch 179/500
 - 0s - loss: 0.0597 - acc: 0.9738
Epoch 180/500
 - 0s - loss: 0.0582 - acc: 0.9770
Epoch 181/500
 - 0s - loss: 0.0564 - acc: 0.9778
Epoch 182/500
 - 0s - loss: 0.0560 - acc: 0.9770
Epoch 183/500
 - 0s - loss: 0.0587 - acc: 0.9738
Epoch 184/500
 - 0s - loss: 0.0572 - acc: 0.9810
Epoch 185/500
 - 0s - loss: 0.0615 - acc: 0.9778
Epoch 186/500
 - 0s - loss: 0.0569 - acc: 0.9794
Epoch 187/500
 - 0s - loss: 0.0579 - acc: 0.9778
Epoch 188/500
 - 0s - loss: 0.0560 - acc: 0.9802
Epoch 189/500
 - 0s - loss: 0.0552 - acc: 0.9770
Epoch 190/500
 - 0s - loss: 0.0547 - acc: 0.9770
Epoch 191/500
 - 0s - loss: 0.0531 - acc: 0.9810
Epoch 192/500
 - 0s - loss: 0.0589 - acc: 0.9794
Epoch 193/500
 - 0s - loss: 0.0595 - acc: 0.9754
Epoch 194/500
 - 0s - loss: 0.0575 - acc: 0.9770
Epoch 195/500
 - 0s - loss: 0.0526 - acc: 0.9802
Epoch 196/500
 - 0s - loss: 0.0514 - acc: 0.9841
Epoch 197/500
 - 0s - loss: 0.0565 - acc: 0.9794
Epoch 198/500
 - 0s - loss: 0.0521 - acc: 0.9778
Epoch 199/500
 - 0s - loss: 0.0513 - acc: 0.9794
Epoch 200/500
 - 0s - loss: 0.0520 - acc: 0.9786
Epoch 201/500
 - 0s - loss: 0.0550 - acc: 0.9794
Epoch 202/500
 - 0s - loss: 0.0536 - acc: 0.9810
Epoch 203/500
 - 0s - loss: 0.0538 - acc: 0.9762
Epoch 204/500
 - 0s - loss: 0.0543 - acc: 0.9810
Epoch 205/500
 - 0s - loss: 0.0546 - acc: 0.9778
Epoch 206/500
 - 0s - loss: 0.0527 - acc: 0.9770
Epoch 207/500
 - 0s - loss: 0.0550 - acc: 0.9778
Epoch 208/500
 - 0s - loss: 0.0504 - acc: 0.9762
Epoch 209/500
 - 0s - loss: 0.0508 - acc: 0.9794
Epoch 210/500
 - 0s - loss: 0.0506 - acc: 0.9770
Epoch 211/500
 - 0s - loss: 0.0492 - acc: 0.9817
Epoch 212/500
 - 0s - loss: 0.0485 - acc: 0.9817
Epoch 213/500
 - 0s - loss: 0.0492 - acc: 0.9778
Epoch 214/500
 - 0s - loss: 0.0500 - acc: 0.9833
Epoch 215/500
 - 0s - loss: 0.0495 - acc: 0.9802
Epoch 216/500
 - 0s - loss: 0.0490 - acc: 0.9810
Epoch 217/500
 - 0s - loss: 0.0570 - acc: 0.9794
Epoch 218/500
 - 0s - loss: 0.0518 - acc: 0.9770
Epoch 219/500
 - 0s - loss: 0.0477 - acc: 0.9770
Epoch 220/500
 - 0s - loss: 0.0525 - acc: 0.9802
Epoch 221/500
 - 0s - loss: 0.0455 - acc: 0.9810
Epoch 222/500
 - 0s - loss: 0.0450 - acc: 0.9794
Epoch 223/500
 - 0s - loss: 0.0469 - acc: 0.9802
Epoch 224/500
 - 0s - loss: 0.0466 - acc: 0.9794
Epoch 225/500
 - 0s - loss: 0.0473 - acc: 0.9802
Epoch 226/500
 - 0s - loss: 0.0465 - acc: 0.9817
Epoch 227/500
 - 0s - loss: 0.0453 - acc: 0.9833
Epoch 228/500
 - 0s - loss: 0.0493 - acc: 0.9817
Epoch 229/500
 - 0s - loss: 0.0480 - acc: 0.9841
Epoch 230/500
 - 0s - loss: 0.0491 - acc: 0.9802
Epoch 231/500
 - 0s - loss: 0.0452 - acc: 0.9825
Epoch 232/500
 - 0s - loss: 0.0439 - acc: 0.9810
Epoch 233/500
 - 0s - loss: 0.0423 - acc: 0.9825
Epoch 234/500
 - 0s - loss: 0.0505 - acc: 0.9754
Epoch 235/500
 - 0s - loss: 0.0490 - acc: 0.9802
Epoch 236/500
 - 0s - loss: 0.0482 - acc: 0.9817
Epoch 237/500
 - 0s - loss: 0.0408 - acc: 0.9841
Epoch 238/500
 - 0s - loss: 0.0406 - acc: 0.9841
Epoch 239/500
 - 0s - loss: 0.0414 - acc: 0.9825
Epoch 240/500
 - 0s - loss: 0.0454 - acc: 0.9778
Epoch 241/500
 - 0s - loss: 0.0437 - acc: 0.9794
Epoch 242/500
 - 0s - loss: 0.0433 - acc: 0.9802
Epoch 243/500
 - 0s - loss: 0.0521 - acc: 0.9786
Epoch 244/500
 - 0s - loss: 0.0516 - acc: 0.9794
Epoch 245/500
 - 0s - loss: 0.0444 - acc: 0.9802
Epoch 246/500
 - 0s - loss: 0.0427 - acc: 0.9833
Epoch 247/500
 - 0s - loss: 0.0408 - acc: 0.9865
Epoch 248/500
 - 0s - loss: 0.0387 - acc: 0.9849
Epoch 249/500
 - 0s - loss: 0.0424 - acc: 0.9833
Epoch 250/500
 - 0s - loss: 0.0433 - acc: 0.9825
Epoch 251/500
 - 0s - loss: 0.0429 - acc: 0.9833
Epoch 252/500
 - 0s - loss: 0.0497 - acc: 0.9786
Epoch 253/500
 - 0s - loss: 0.0430 - acc: 0.9841
Epoch 254/500
 - 0s - loss: 0.0411 - acc: 0.9810
Epoch 255/500
 - 0s - loss: 0.0436 - acc: 0.9841
Epoch 256/500
 - 0s - loss: 0.0430 - acc: 0.9833
Epoch 257/500
 - 0s - loss: 0.0392 - acc: 0.9825
Epoch 258/500
 - 0s - loss: 0.0481 - acc: 0.9802
Epoch 259/500
 - 0s - loss: 0.0399 - acc: 0.9833
Epoch 260/500
 - 0s - loss: 0.0425 - acc: 0.9849
Epoch 261/500
 - 0s - loss: 0.0393 - acc: 0.9841
Epoch 262/500
 - 0s - loss: 0.0410 - acc: 0.9857
Epoch 263/500
 - 0s - loss: 0.0441 - acc: 0.9825
Epoch 264/500
 - 0s - loss: 0.0415 - acc: 0.9833
Epoch 265/500
 - 0s - loss: 0.0402 - acc: 0.9817
Epoch 266/500
 - 0s - loss: 0.0439 - acc: 0.9833
Epoch 267/500
 - 0s - loss: 0.0403 - acc: 0.9841
Epoch 268/500
 - 0s - loss: 0.0355 - acc: 0.9849
Epoch 269/500
 - 0s - loss: 0.0359 - acc: 0.9873
Epoch 270/500
 - 0s - loss: 0.0384 - acc: 0.9857
Epoch 271/500
 - 0s - loss: 0.0420 - acc: 0.9810
Epoch 272/500
 - 0s - loss: 0.0359 - acc: 0.9841
Epoch 273/500
 - 0s - loss: 0.0415 - acc: 0.9833
Epoch 274/500
 - 0s - loss: 0.0397 - acc: 0.9817
Epoch 275/500
 - 0s - loss: 0.0419 - acc: 0.9833
Epoch 276/500
 - 0s - loss: 0.0368 - acc: 0.9841
Epoch 277/500
 - 0s - loss: 0.0420 - acc: 0.9849
Epoch 278/500
 - 0s - loss: 0.0431 - acc: 0.9849
Epoch 279/500
 - 0s - loss: 0.0402 - acc: 0.9825
Epoch 280/500
 - 0s - loss: 0.0370 - acc: 0.9873
Epoch 281/500
 - 0s - loss: 0.0397 - acc: 0.9825
Epoch 282/500
 - 0s - loss: 0.0346 - acc: 0.9889
Epoch 283/500
 - 0s - loss: 0.0345 - acc: 0.9849
Epoch 284/500
 - 0s - loss: 0.0355 - acc: 0.9849
Epoch 285/500
 - 0s - loss: 0.0386 - acc: 0.9865
Epoch 286/500
 - 0s - loss: 0.0366 - acc: 0.9817
Epoch 287/500
 - 0s - loss: 0.0332 - acc: 0.9865
Epoch 288/500
 - 0s - loss: 0.0393 - acc: 0.9849
Epoch 289/500
 - 0s - loss: 0.0357 - acc: 0.9865
Epoch 290/500
 - 0s - loss: 0.0416 - acc: 0.9857
Epoch 291/500
 - 0s - loss: 0.0395 - acc: 0.9786
Epoch 292/500
 - 0s - loss: 0.0358 - acc: 0.9857
Epoch 293/500
 - 0s - loss: 0.0329 - acc: 0.9873
Epoch 294/500
 - 0s - loss: 0.0368 - acc: 0.9881
Epoch 295/500
 - 0s - loss: 0.0409 - acc: 0.9802
Epoch 296/500
 - 0s - loss: 0.0421 - acc: 0.9849
Epoch 297/500
 - 0s - loss: 0.0376 - acc: 0.9833
Epoch 298/500
 - 0s - loss: 0.0425 - acc: 0.9810
Epoch 299/500
 - 0s - loss: 0.0364 - acc: 0.9857
Epoch 300/500
 - 0s - loss: 0.0347 - acc: 0.9881
Epoch 301/500
 - 0s - loss: 0.0344 - acc: 0.9857
Epoch 302/500
 - 0s - loss: 0.0393 - acc: 0.9841
Epoch 303/500
 - 0s - loss: 0.0377 - acc: 0.9833
Epoch 304/500
 - 0s - loss: 0.0353 - acc: 0.9865
Epoch 305/500
 - 0s - loss: 0.0347 - acc: 0.9849
Epoch 306/500
 - 0s - loss: 0.0333 - acc: 0.9841
Epoch 307/500
 - 0s - loss: 0.0324 - acc: 0.9841
Epoch 308/500
 - 0s - loss: 0.0327 - acc: 0.9889
Epoch 309/500
 - 0s - loss: 0.0326 - acc: 0.9873
Epoch 310/500
 - 0s - loss: 0.0386 - acc: 0.9873
Epoch 311/500
 - 0s - loss: 0.0328 - acc: 0.9873
Epoch 312/500
 - 0s - loss: 0.0329 - acc: 0.9873
Epoch 313/500
 - 0s - loss: 0.0400 - acc: 0.9833
Epoch 314/500
 - 0s - loss: 0.0319 - acc: 0.9849
Epoch 315/500
 - 0s - loss: 0.0350 - acc: 0.9841
Epoch 316/500
 - 0s - loss: 0.0346 - acc: 0.9873
Epoch 317/500
 - 0s - loss: 0.0354 - acc: 0.9865
Epoch 318/500
 - 0s - loss: 0.0314 - acc: 0.9881
Epoch 319/500
 - 0s - loss: 0.0327 - acc: 0.9865
Epoch 320/500
 - 0s - loss: 0.0320 - acc: 0.9865
Epoch 321/500
 - 0s - loss: 0.0332 - acc: 0.9857
Epoch 322/500
 - 0s - loss: 0.0337 - acc: 0.9865
Epoch 323/500
 - 0s - loss: 0.0311 - acc: 0.9841
Epoch 324/500
 - 0s - loss: 0.0315 - acc: 0.9865
Epoch 325/500
 - 0s - loss: 0.0295 - acc: 0.9889
Epoch 326/500
 - 0s - loss: 0.0314 - acc: 0.9873
Epoch 327/500
 - 0s - loss: 0.0338 - acc: 0.9817
Epoch 328/500
 - 0s - loss: 0.0303 - acc: 0.9849
Epoch 329/500
 - 0s - loss: 0.0293 - acc: 0.9873
Epoch 330/500
 - 0s - loss: 0.0351 - acc: 0.9849
Epoch 331/500
 - 0s - loss: 0.0358 - acc: 0.9833
Epoch 332/500

 - 0s - loss: 0.0289 - acc: 0.9881
Epoch 333/500
 - 0s - loss: 0.0313 - acc: 0.9865
Epoch 334/500
 - 0s - loss: 0.0439 - acc: 0.9849
Epoch 335/500
 - 0s - loss: 0.0383 - acc: 0.9841
Epoch 336/500
 - 0s - loss: 0.0293 - acc: 0.9889
Epoch 337/500
 - 0s - loss: 0.0317 - acc: 0.9881
Epoch 338/500
 - 0s - loss: 0.0305 - acc: 0.9881
Epoch 339/500
 - 0s - loss: 0.0277 - acc: 0.9873
Epoch 340/500
 - 0s - loss: 0.0274 - acc: 0.9865
Epoch 341/500
 - 0s - loss: 0.0288 - acc: 0.9897
Epoch 342/500
 - 0s - loss: 0.0303 - acc: 0.9905
Epoch 343/500
 - 0s - loss: 0.0295 - acc: 0.9873
Epoch 344/500
 - 0s - loss: 0.0287 - acc: 0.9873
Epoch 345/500
 - 0s - loss: 0.0300 - acc: 0.9857
Epoch 346/500
 - 0s - loss: 0.0287 - acc: 0.9873
Epoch 347/500
 - 0s - loss: 0.0336 - acc: 0.9849
Epoch 348/500
 - 0s - loss: 0.0307 - acc: 0.9857
Epoch 349/500
 - 0s - loss: 0.0271 - acc: 0.9881
Epoch 350/500
 - 0s - loss: 0.0332 - acc: 0.9849
Epoch 351/500
 - 0s - loss: 0.0370 - acc: 0.9849
Epoch 352/500
 - 0s - loss: 0.0329 - acc: 0.9873
Epoch 353/500
 - 0s - loss: 0.0328 - acc: 0.9865
Epoch 354/500
 - 0s - loss: 0.0347 - acc: 0.9857
Epoch 355/500
 - 0s - loss: 0.0279 - acc: 0.9873
Epoch 356/500
 - 0s - loss: 0.0303 - acc: 0.9873
Epoch 357/500
 - 0s - loss: 0.0316 - acc: 0.9849
Epoch 358/500
 - 0s - loss: 0.0466 - acc: 0.9794
Epoch 359/500
 - 0s - loss: 0.0339 - acc: 0.9873
Epoch 360/500
 - 0s - loss: 0.0265 - acc: 0.9905
Epoch 361/500
 - 0s - loss: 0.0261 - acc: 0.9913
Epoch 362/500
 - 0s - loss: 0.0290 - acc: 0.9905
Epoch 363/500
 - 0s - loss: 0.0281 - acc: 0.9897
Epoch 364/500
 - 0s - loss: 0.0311 - acc: 0.9865
Epoch 365/500
 - 0s - loss: 0.0272 - acc: 0.9889
Epoch 366/500
 - 0s - loss: 0.0280 - acc: 0.9897
Epoch 367/500
 - 0s - loss: 0.0274 - acc: 0.9873
Epoch 368/500
 - 0s - loss: 0.0307 - acc: 0.9897
Epoch 369/500
 - 0s - loss: 0.0292 - acc: 0.9889
Epoch 370/500
 - 0s - loss: 0.0374 - acc: 0.9833
Epoch 371/500
 - 0s - loss: 0.0273 - acc: 0.9889
Epoch 372/500
 - 0s - loss: 0.0274 - acc: 0.9881
Epoch 373/500
 - 0s - loss: 0.0259 - acc: 0.9881
Epoch 374/500
 - 0s - loss: 0.0285 - acc: 0.9881
Epoch 375/500
 - 0s - loss: 0.0266 - acc: 0.9905
Epoch 376/500
 - 0s - loss: 0.0326 - acc: 0.9849
Epoch 377/500
 - 0s - loss: 0.0305 - acc: 0.9889
Epoch 378/500
 - 0s - loss: 0.0285 - acc: 0.9881
Epoch 379/500
 - 0s - loss: 0.0280 - acc: 0.9889
Epoch 380/500
 - 0s - loss: 0.0326 - acc: 0.9865
Epoch 381/500
 - 0s - loss: 0.0262 - acc: 0.9873
Epoch 382/500
 - 0s - loss: 0.0260 - acc: 0.9897
Epoch 383/500
 - 0s - loss: 0.0374 - acc: 0.9857
Epoch 384/500
 - 0s - loss: 0.0339 - acc: 0.9865
Epoch 385/500
 - 0s - loss: 0.0323 - acc: 0.9865
Epoch 386/500
 - 0s - loss: 0.0320 - acc: 0.9897
Epoch 387/500
 - 0s - loss: 0.0253 - acc: 0.9873
Epoch 388/500
 - 0s - loss: 0.0249 - acc: 0.9889
Epoch 389/500
 - 0s - loss: 0.0250 - acc: 0.9889
Epoch 390/500
 - 0s - loss: 0.0247 - acc: 0.9913
Epoch 391/500
 - 0s - loss: 0.0243 - acc: 0.9897
Epoch 392/500
 - 0s - loss: 0.0237 - acc: 0.9889
Epoch 393/500
 - 0s - loss: 0.0250 - acc: 0.9889
Epoch 394/500
 - 0s - loss: 0.0268 - acc: 0.9889
Epoch 395/500
 - 0s - loss: 0.0238 - acc: 0.9913
Epoch 396/500
 - 0s - loss: 0.0248 - acc: 0.9865
Epoch 397/500
 - 0s - loss: 0.0261 - acc: 0.9897
Epoch 398/500
 - 0s - loss: 0.0260 - acc: 0.9889
Epoch 399/500
 - 0s - loss: 0.0293 - acc: 0.9857
Epoch 400/500
 - 0s - loss: 0.0280 - acc: 0.9873
Epoch 401/500
 - 0s - loss: 0.0279 - acc: 0.9889
Epoch 402/500
 - 0s - loss: 0.0294 - acc: 0.9881
Epoch 403/500
 - 0s - loss: 0.0299 - acc: 0.9881
Epoch 404/500
 - 0s - loss: 0.0267 - acc: 0.9897
Epoch 405/500
 - 0s - loss: 0.0276 - acc: 0.9873
Epoch 406/500
 - 0s - loss: 0.0327 - acc: 0.9897
Epoch 407/500
 - 0s - loss: 0.0310 - acc: 0.9865
Epoch 408/500
 - 0s - loss: 0.0246 - acc: 0.9905
Epoch 409/500
 - 0s - loss: 0.0257 - acc: 0.9889
Epoch 410/500
 - 0s - loss: 0.0224 - acc: 0.9921
Epoch 411/500
 - 0s - loss: 0.0272 - acc: 0.9889
Epoch 412/500
 - 0s - loss: 0.0363 - acc: 0.9849
Epoch 413/500
 - 0s - loss: 0.0290 - acc: 0.9849
Epoch 414/500
 - 0s - loss: 0.0286 - acc: 0.9865
Epoch 415/500
 - 0s - loss: 0.0256 - acc: 0.9873
Epoch 416/500
 - 0s - loss: 0.0270 - acc: 0.9889
Epoch 417/500
 - 0s - loss: 0.0328 - acc: 0.9849
Epoch 418/500
 - 0s - loss: 0.0227 - acc: 0.9897
Epoch 419/500
 - 0s - loss: 0.0265 - acc: 0.9881
Epoch 420/500
 - 0s - loss: 0.0342 - acc: 0.9865
Epoch 421/500
 - 0s - loss: 0.0409 - acc: 0.9817
Epoch 422/500
 - 0s - loss: 0.0275 - acc: 0.9889
Epoch 423/500
 - 0s - loss: 0.0367 - acc: 0.9873
Epoch 424/500
 - 0s - loss: 0.0397 - acc: 0.9841
Epoch 425/500
 - 0s - loss: 0.0286 - acc: 0.9897
Epoch 426/500
 - 0s - loss: 0.0256 - acc: 0.9897
Epoch 427/500
 - 0s - loss: 0.0305 - acc: 0.9873
Epoch 428/500
 - 0s - loss: 0.0233 - acc: 0.9913
Epoch 429/500
 - 0s - loss: 0.0242 - acc: 0.9881
Epoch 430/500
 - 0s - loss: 0.0245 - acc: 0.9889
Epoch 431/500
 - 0s - loss: 0.0230 - acc: 0.9913
Epoch 432/500
 - 0s - loss: 0.0227 - acc: 0.9921
Epoch 433/500
 - 0s - loss: 0.0233 - acc: 0.9897
Epoch 434/500
 - 0s - loss: 0.0233 - acc: 0.9881
Epoch 435/500
 - 0s - loss: 0.0211 - acc: 0.9897
Epoch 436/500
 - 0s - loss: 0.0209 - acc: 0.9921
Epoch 437/500
 - 0s - loss: 0.0236 - acc: 0.9889
Epoch 438/500
 - 0s - loss: 0.0255 - acc: 0.9889
Epoch 439/500
 - 0s - loss: 0.0265 - acc: 0.9913
Epoch 440/500
 - 0s - loss: 0.0231 - acc: 0.9913
Epoch 441/500
 - 0s - loss: 0.0219 - acc: 0.9921
Epoch 442/500
 - 0s - loss: 0.0201 - acc: 0.9905
Epoch 443/500
 - 0s - loss: 0.0230 - acc: 0.9889
Epoch 444/500
 - 0s - loss: 0.0226 - acc: 0.9881
Epoch 445/500
 - 0s - loss: 0.0224 - acc: 0.9897
Epoch 446/500
 - 0s - loss: 0.0216 - acc: 0.9905
Epoch 447/500
 - 0s - loss: 0.0223 - acc: 0.9897
Epoch 448/500
 - 0s - loss: 0.0235 - acc: 0.9913
Epoch 449/500
 - 0s - loss: 0.0232 - acc: 0.9905
Epoch 450/500
 - 0s - loss: 0.0291 - acc: 0.9881
Epoch 451/500
 - 0s - loss: 0.0215 - acc: 0.9905
Epoch 452/500
 - 0s - loss: 0.0216 - acc: 0.9913
Epoch 453/500
 - 0s - loss: 0.0220 - acc: 0.9889
Epoch 454/500
 - 0s - loss: 0.0223 - acc: 0.9905
Epoch 455/500
 - 0s - loss: 0.0244 - acc: 0.9897
Epoch 456/500
 - 0s - loss: 0.0212 - acc: 0.9913
Epoch 457/500
 - 0s - loss: 0.0203 - acc: 0.9913
Epoch 458/500
 - 0s - loss: 0.0240 - acc: 0.9905
Epoch 459/500
 - 0s - loss: 0.0215 - acc: 0.9905
Epoch 460/500
 - 0s - loss: 0.0231 - acc: 0.9913
Epoch 461/500
 - 0s - loss: 0.0225 - acc: 0.9913
Epoch 462/500
 - 0s - loss: 0.0206 - acc: 0.9905
Epoch 463/500
 - 0s - loss: 0.0191 - acc: 0.9913
Epoch 464/500
 - 0s - loss: 0.0219 - acc: 0.9913
Epoch 465/500
 - 0s - loss: 0.0223 - acc: 0.9897
Epoch 466/500
 - 0s - loss: 0.0248 - acc: 0.9881
Epoch 467/500
 - 0s - loss: 0.0253 - acc: 0.9897
Epoch 468/500
 - 0s - loss: 0.0360 - acc: 0.9857
Epoch 469/500
 - 0s - loss: 0.0378 - acc: 0.9833
Epoch 470/500
 - 0s - loss: 0.0632 - acc: 0.9817
Epoch 471/500
 - 0s - loss: 0.0445 - acc: 0.9794
Epoch 472/500
 - 0s - loss: 0.0319 - acc: 0.9889
Epoch 473/500
 - 0s - loss: 0.0221 - acc: 0.9905
Epoch 474/500
 - 0s - loss: 0.0199 - acc: 0.9921
Epoch 475/500
 - 0s - loss: 0.0221 - acc: 0.9889
Epoch 476/500
 - 0s - loss: 0.0211 - acc: 0.9921
Epoch 477/500
 - 0s - loss: 0.0219 - acc: 0.9913
Epoch 478/500
 - 0s - loss: 0.0213 - acc: 0.9913
Epoch 479/500
 - 0s - loss: 0.0213 - acc: 0.9921
Epoch 480/500
 - 0s - loss: 0.0207 - acc: 0.9905
Epoch 481/500
 - 0s - loss: 0.0205 - acc: 0.9905
Epoch 482/500
 - 0s - loss: 0.0209 - acc: 0.9921
Epoch 483/500
 - 0s - loss: 0.0275 - acc: 0.9889
Epoch 484/500
 - 0s - loss: 0.0252 - acc: 0.9905
Epoch 485/500
 - 0s - loss: 0.0248 - acc: 0.9921
Epoch 486/500
 - 0s - loss: 0.0265 - acc: 0.9881
Epoch 487/500
 - 0s - loss: 0.0252 - acc: 0.9889
Epoch 488/500
 - 0s - loss: 0.0242 - acc: 0.9897
Epoch 489/500
 - 0s - loss: 0.0249 - acc: 0.9897
Epoch 490/500
 - 0s - loss: 0.0238 - acc: 0.9905
Epoch 491/500
 - 0s - loss: 0.0263 - acc: 0.9889
Epoch 492/500
 - 0s - loss: 0.0256 - acc: 0.9873
Epoch 493/500
 - 0s - loss: 0.0251 - acc: 0.9873
Epoch 494/500
 - 0s - loss: 0.0235 - acc: 0.9905
Epoch 495/500
 - 0s - loss: 0.0228 - acc: 0.9913
Epoch 496/500
 - 0s - loss: 0.0224 - acc: 0.9889
Epoch 497/500
 - 0s - loss: 0.0183 - acc: 0.9921
Epoch 498/500
 - 0s - loss: 0.0194 - acc: 0.9913
Epoch 499/500
 - 0s - loss: 0.0229 - acc: 0.9897

Epoch 500/500
 - 0s - loss: 0.0204 - acc: 0.9905

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 0.7304 - acc: 0.8881
Normal Neural Network - Loss: 0.7303986129306611, Accuracy: 0.8880952596664429

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Certified' 'Certified' 'Certified' 'Certified' 'Certified'
 'Certified' 'Certified' 'Certified' 'Certified']
Actual Labels: ['Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified']