In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'RUSSIA']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

RUSSIA    1622
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    1601
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [8]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [9]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [10]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
51,Certified,804,20878,MARYLAND,10.0,100000.0,RUSSIA,H-1B,Master's,6.0
300,Certified,473,10022,NEW YORK,7000.0,150000.0,RUSSIA,H-1B,Master's,4.0
884,Certified,177,19611,PENNSYLVANIA,7000.0,187199.0,RUSSIA,H-1B,Doctorate,3.0
991,Certified,185,10022,NEW YORK,17.0,126422.0,RUSSIA,L-1,Master's,12.0
1209,Certified,205,94043,CALIFORNIA,47756.0,91104.0,RUSSIA,H-1B,Master's,1.0

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

CALIFORNIA              588
NEW YORK                179
WASHINGTON              160
PENNSYLVANIA            118
MASSACHUSETTS            70
FLORIDA                  62
TEXAS                    61
ILLINOIS                 57
NEW JERSEY               44
VIRGINIA                 36
DISTRICT OF COLUMBIA     34
MARYLAND                 20
NORTH CAROLINA           15
CONNECTICUT              15
GEORGIA                  13
OHIO                     12
MICHIGAN                 11
COLORADO                 10
UTAH                      9
NEVADA                    8
ARIZONA                   7
MINNESOTA                 7
MISSOURI                  7
WISCONSIN                 6
DELAWARE                  5
ALABAMA                   5
KANSAS                    4
SOUTH CAROLINA            4
ALASKA                    4
TENNESSEE                 3
KENTUCKY                  3
VERMONT                   3
IOWA                      3
OREGON                    2
ARKANSAS                  2
MISSISSIPPI               2
LOUISIANA                 2
RHODE ISLAND              2
WEST VIRGINIA             2
NEW HAMPSHIRE             1
INDIANA                   1
UNKNOWN                   1
GUAM                      1
HAWAII                    1
OKLAHOMA                  1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
51,Certified,804,20878,MARYLAND,10.0,100000.0,RUSSIA,H-1B,Master's,6.0,MARYLAND
300,Certified,473,10022,NEW YORK,7000.0,150000.0,RUSSIA,H-1B,Master's,4.0,NEW YORK
884,Certified,177,19611,PENNSYLVANIA,7000.0,187199.0,RUSSIA,H-1B,Doctorate,3.0,PENNSYLVANIA
991,Certified,185,10022,NEW YORK,17.0,126422.0,RUSSIA,L-1,Master's,12.0,NEW YORK
1209,Certified,205,94043,CALIFORNIA,47756.0,91104.0,RUSSIA,H-1B,Master's,1.0,CALIFORNIA

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

WEST         751
NORTHEAST    406
SOUTH        238
MIDWEST      100
OTHER          1
UNKNOWN        1
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      1497
DECISION_ELAPSED_DAYS            1497
EMPLOYER_POSTAL_CODE             1497
EMPLOYER_STATE                   1497
EMPLOYER_NUM_EMPLOYEES           1497
WAGE_OFFER_FROM_9089             1497
COUNTRY_OF_CITIZENSHIP           1497
CLASS_OF_ADMISSION               1497
FOREIGN_WORKER_INFO_EDUCATION    1497
CASE_RECEIVED_DATE_MONTH         1497
EMPLOYER_STATES                  1497
EMPLOYER_REGIONS                 1497
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      643
0-90        485
181-365     273
366-3600     95
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

100000-500000    842
75001-100000     386
50001-75000      175
25001-50000       83
0-25000           11
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

10001-1000000000    390
0-50                372
1001-10000          346
101-500             223
51-100               98
501-1000             67
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      1497
DECISION_ELAPSED_DAYS            1497
EMPLOYER_POSTAL_CODE             1497
EMPLOYER_STATE                   1497
EMPLOYER_NUM_EMPLOYEES           1497
WAGE_OFFER_FROM_9089             1497
COUNTRY_OF_CITIZENSHIP           1497
CLASS_OF_ADMISSION               1497
FOREIGN_WORKER_INFO_EDUCATION    1497
CASE_RECEIVED_DATE_MONTH         1497
EMPLOYER_STATES                  1497
EMPLOYER_REGIONS                 1497
DAY_BINS                         1496
WAGE_BINS                        1497
EMPLOYEE_BINS                    1496
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
51,Certified,0-50,75001-100000,SOUTH,6.0,Master's,H-1B,366-3600
300,Certified,1001-10000,100000-500000,NORTHEAST,4.0,Master's,H-1B,366-3600
884,Certified,1001-10000,100000-500000,NORTHEAST,3.0,Doctorate,H-1B,91-180
991,Certified,0-50,100000-500000,NORTHEAST,12.0,Master's,L-1,181-365
1209,Certified,10001-1000000000,75001-100000,WEST,1.0,Master's,H-1B,181-365

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
51,Certified,0-50,75001-100000,SOUTH,6.0,Master's,H-1B,366-3600,7,4,4,3,2,0
300,Certified,1001-10000,100000-500000,NORTHEAST,4.0,Master's,H-1B,366-3600,7,4,1,1,2,2
884,Certified,1001-10000,100000-500000,NORTHEAST,3.0,Doctorate,H-1B,91-180,7,2,1,1,3,2
991,Certified,0-50,100000-500000,NORTHEAST,12.0,Master's,L-1,181-365,12,4,1,1,1,0
1209,Certified,10001-1000000000,75001-100000,WEST,1.0,Master's,H-1B,181-365,7,4,4,5,1,1

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           1497
EMPLOYEE_BINS                         1497
WAGE_BINS                             1497
EMPLOYER_REGIONS                      1497
CASE_RECEIVED_DATE_MONTH              1497
FOREIGN_WORKER_INFO_EDUCATION         1497
CLASS_OF_ADMISSION                    1497
DAY_BINS                              1497
CLASS_OF_ADMISSION_CODE               1497
FOREIGN_WORKER_INFO_EDUCATION_CODE    1497
WAGE_BINS_CODE                        1497
EMPLOYER_REGIONS_CODE                 1497
DAY_BINS_CODE                         1497
EMPLOYEE_BINS_CODE                    1497
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
51,Certified,0,4,2,4,7,6.0,3
300,Certified,2,1,2,4,7,4.0,1
884,Certified,2,1,3,2,7,3.0,1
991,Certified,0,1,1,4,12,12.0,1
1209,Certified,1,4,1,4,7,1.0,5

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int64
WAGE_BINS_CODE                          int64
DAY_BINS_CODE                           int64
FOREIGN_WORKER_INFO_EDUCATION_CODE      int64
CLASS_OF_ADMISSION_CODE                 int64
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int64
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(1497, 7) (1497,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [53]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 1s - loss: 0.4065 - acc: 0.8280
Epoch 2/500
 - 0s - loss: 0.2360 - acc: 0.9376
Epoch 3/500
 - 0s - loss: 0.2268 - acc: 0.9376
Epoch 4/500
 - 0s - loss: 0.2209 - acc: 0.9376
Epoch 5/500
 - 0s - loss: 0.2161 - acc: 0.9376
Epoch 6/500
 - 0s - loss: 0.2143 - acc: 0.9376
Epoch 7/500
 - 0s - loss: 0.2100 - acc: 0.9376
Epoch 8/500
 - 0s - loss: 0.2077 - acc: 0.9376
Epoch 9/500
 - 0s - loss: 0.2052 - acc: 0.9376
Epoch 10/500
 - 0s - loss: 0.2033 - acc: 0.9376
Epoch 11/500
 - 0s - loss: 0.2016 - acc: 0.9376
Epoch 12/500
 - 0s - loss: 0.1988 - acc: 0.9376
Epoch 13/500
 - 0s - loss: 0.2003 - acc: 0.9376
Epoch 14/500
 - 0s - loss: 0.2031 - acc: 0.9376
Epoch 15/500
 - 0s - loss: 0.1931 - acc: 0.9376
Epoch 16/500
 - 0s - loss: 0.1903 - acc: 0.9376
Epoch 17/500
 - 0s - loss: 0.1895 - acc: 0.9376
Epoch 18/500
 - 0s - loss: 0.1868 - acc: 0.9376
Epoch 19/500
 - 0s - loss: 0.1879 - acc: 0.9376
Epoch 20/500
 - 0s - loss: 0.1846 - acc: 0.9376
Epoch 21/500
 - 0s - loss: 0.1800 - acc: 0.9376
Epoch 22/500
 - 0s - loss: 0.1868 - acc: 0.9385
Epoch 23/500
 - 0s - loss: 0.1779 - acc: 0.9376
Epoch 24/500
 - 0s - loss: 0.1748 - acc: 0.9376
Epoch 25/500
 - 0s - loss: 0.1721 - acc: 0.9376
Epoch 26/500
 - 0s - loss: 0.1692 - acc: 0.9367
Epoch 27/500
 - 0s - loss: 0.1858 - acc: 0.9367
Epoch 28/500
 - 0s - loss: 0.1698 - acc: 0.9376
Epoch 29/500
 - 0s - loss: 0.1673 - acc: 0.9376
Epoch 30/500
 - 0s - loss: 0.1636 - acc: 0.9367
Epoch 31/500
 - 0s - loss: 0.1587 - acc: 0.9385
Epoch 32/500
 - 0s - loss: 0.1590 - acc: 0.9394
Epoch 33/500
 - 0s - loss: 0.1630 - acc: 0.9376
Epoch 34/500
 - 0s - loss: 0.1556 - acc: 0.9412
Epoch 35/500
 - 0s - loss: 0.1548 - acc: 0.9412
Epoch 36/500
 - 0s - loss: 0.1573 - acc: 0.9376
Epoch 37/500
 - 0s - loss: 0.1496 - acc: 0.9403
Epoch 38/500
 - 0s - loss: 0.1507 - acc: 0.9394
Epoch 39/500
 - 0s - loss: 0.1500 - acc: 0.9430
Epoch 40/500
 - 0s - loss: 0.1475 - acc: 0.9403
Epoch 41/500
 - 0s - loss: 0.1439 - acc: 0.9421
Epoch 42/500
 - 0s - loss: 0.1485 - acc: 0.9421
Epoch 43/500
 - 0s - loss: 0.1475 - acc: 0.9403
Epoch 44/500
 - 0s - loss: 0.1439 - acc: 0.9465
Epoch 45/500
 - 0s - loss: 0.1492 - acc: 0.9412
Epoch 46/500
 - 0s - loss: 0.1458 - acc: 0.9421
Epoch 47/500
 - 0s - loss: 0.1407 - acc: 0.9430
Epoch 48/500
 - 0s - loss: 0.1354 - acc: 0.9474
Epoch 49/500
 - 0s - loss: 0.1357 - acc: 0.9456
Epoch 50/500
 - 0s - loss: 0.1552 - acc: 0.9376
Epoch 51/500
 - 0s - loss: 0.1422 - acc: 0.9430
Epoch 52/500
 - 0s - loss: 0.1399 - acc: 0.9394
Epoch 53/500
 - 0s - loss: 0.1316 - acc: 0.9474
Epoch 54/500
 - 0s - loss: 0.1567 - acc: 0.9403
Epoch 55/500
 - 0s - loss: 0.1384 - acc: 0.9447
Epoch 56/500
 - 0s - loss: 0.1298 - acc: 0.9501
Epoch 57/500
 - 0s - loss: 0.1292 - acc: 0.9465
Epoch 58/500
 - 0s - loss: 0.1266 - acc: 0.9447
Epoch 59/500
 - 0s - loss: 0.1258 - acc: 0.9483
Epoch 60/500
 - 0s - loss: 0.1270 - acc: 0.9483
Epoch 61/500
 - 0s - loss: 0.1240 - acc: 0.9465
Epoch 62/500
 - 0s - loss: 0.1252 - acc: 0.9483
Epoch 63/500
 - 0s - loss: 0.1237 - acc: 0.9528
Epoch 64/500
 - 0s - loss: 0.1244 - acc: 0.9492
Epoch 65/500
 - 0s - loss: 0.1227 - acc: 0.9465
Epoch 66/500
 - 0s - loss: 0.1266 - acc: 0.9456
Epoch 67/500
 - 0s - loss: 0.1219 - acc: 0.9483
Epoch 68/500
 - 0s - loss: 0.1199 - acc: 0.9510
Epoch 69/500
 - 0s - loss: 0.1177 - acc: 0.9545
Epoch 70/500
 - 0s - loss: 0.1188 - acc: 0.9545
Epoch 71/500
 - 0s - loss: 0.1168 - acc: 0.9528
Epoch 72/500
 - 0s - loss: 0.1157 - acc: 0.9554
Epoch 73/500
 - 0s - loss: 0.1168 - acc: 0.9501
Epoch 74/500
 - 0s - loss: 0.1112 - acc: 0.9581
Epoch 75/500
 - 0s - loss: 0.1113 - acc: 0.9537
Epoch 76/500
 - 0s - loss: 0.1123 - acc: 0.9545
Epoch 77/500
 - 0s - loss: 0.1100 - acc: 0.9554
Epoch 78/500
 - 0s - loss: 0.1096 - acc: 0.9599
Epoch 79/500
 - 0s - loss: 0.1122 - acc: 0.9572
Epoch 80/500
 - 0s - loss: 0.1235 - acc: 0.9483
Epoch 81/500
 - 0s - loss: 0.1143 - acc: 0.9554
Epoch 82/500
 - 0s - loss: 0.1212 - acc: 0.9483
Epoch 83/500
 - 0s - loss: 0.1135 - acc: 0.9563
Epoch 84/500
 - 0s - loss: 0.1066 - acc: 0.9572
Epoch 85/500
 - 0s - loss: 0.1053 - acc: 0.9554
Epoch 86/500
 - 0s - loss: 0.1027 - acc: 0.9581
Epoch 87/500
 - 0s - loss: 0.1074 - acc: 0.9581
Epoch 88/500
 - 0s - loss: 0.1046 - acc: 0.9590
Epoch 89/500
 - 0s - loss: 0.1077 - acc: 0.9554
Epoch 90/500
 - 0s - loss: 0.1111 - acc: 0.9519
Epoch 91/500
 - 0s - loss: 0.1023 - acc: 0.9572
Epoch 92/500
 - 0s - loss: 0.0977 - acc: 0.9635
Epoch 93/500
 - 0s - loss: 0.0971 - acc: 0.9608
Epoch 94/500
 - 0s - loss: 0.1023 - acc: 0.9590
Epoch 95/500
 - 0s - loss: 0.1021 - acc: 0.9626
Epoch 96/500
 - 0s - loss: 0.1009 - acc: 0.9581
Epoch 97/500
 - 0s - loss: 0.0944 - acc: 0.9617
Epoch 98/500
 - 0s - loss: 0.0918 - acc: 0.9599
Epoch 99/500
 - 0s - loss: 0.0942 - acc: 0.9635
Epoch 100/500
 - 0s - loss: 0.1468 - acc: 0.9358
Epoch 101/500
 - 0s - loss: 0.1045 - acc: 0.9599
Epoch 102/500
 - 0s - loss: 0.0959 - acc: 0.9635
Epoch 103/500
 - 0s - loss: 0.1005 - acc: 0.9643
Epoch 104/500
 - 0s - loss: 0.0909 - acc: 0.9643
Epoch 105/500
 - 0s - loss: 0.0980 - acc: 0.9581
Epoch 106/500
 - 0s - loss: 0.0897 - acc: 0.9670
Epoch 107/500
 - 0s - loss: 0.0873 - acc: 0.9652
Epoch 108/500
 - 0s - loss: 0.1018 - acc: 0.9608
Epoch 109/500
 - 0s - loss: 0.0989 - acc: 0.9626
Epoch 110/500
 - 0s - loss: 0.0915 - acc: 0.9635
Epoch 111/500
 - 0s - loss: 0.0841 - acc: 0.9697
Epoch 112/500
 - 0s - loss: 0.0867 - acc: 0.9661
Epoch 113/500
 - 0s - loss: 0.0857 - acc: 0.9652
Epoch 114/500
 - 0s - loss: 0.0860 - acc: 0.9643
Epoch 115/500
 - 0s - loss: 0.0831 - acc: 0.9715
Epoch 116/500
 - 0s - loss: 0.0842 - acc: 0.9643
Epoch 117/500
 - 0s - loss: 0.0840 - acc: 0.9679
Epoch 118/500
 - 0s - loss: 0.0788 - acc: 0.9706
Epoch 119/500
 - 0s - loss: 0.0822 - acc: 0.9670
Epoch 120/500
 - 0s - loss: 0.0796 - acc: 0.9697
Epoch 121/500
 - 0s - loss: 0.0794 - acc: 0.9688
Epoch 122/500
 - 0s - loss: 0.0776 - acc: 0.9697
Epoch 123/500
 - 0s - loss: 0.0783 - acc: 0.9733
Epoch 124/500
 - 0s - loss: 0.0791 - acc: 0.9724
Epoch 125/500
 - 0s - loss: 0.0824 - acc: 0.9697
Epoch 126/500
 - 0s - loss: 0.0798 - acc: 0.9670
Epoch 127/500
 - 0s - loss: 0.0727 - acc: 0.9733
Epoch 128/500
 - 0s - loss: 0.0761 - acc: 0.9715
Epoch 129/500
 - 0s - loss: 0.0769 - acc: 0.9706
Epoch 130/500
 - 0s - loss: 0.0815 - acc: 0.9715
Epoch 131/500
 - 0s - loss: 0.0755 - acc: 0.9697
Epoch 132/500
 - 0s - loss: 0.0931 - acc: 0.9599
Epoch 133/500
 - 0s - loss: 0.0760 - acc: 0.9733
Epoch 134/500
 - 0s - loss: 0.0708 - acc: 0.9750
Epoch 135/500
 - 0s - loss: 0.0697 - acc: 0.9715
Epoch 136/500
 - 0s - loss: 0.0718 - acc: 0.9706
Epoch 137/500
 - 0s - loss: 0.0666 - acc: 0.9750
Epoch 138/500
 - 0s - loss: 0.0691 - acc: 0.9742
Epoch 139/500
 - 0s - loss: 0.0679 - acc: 0.9759
Epoch 140/500
 - 0s - loss: 0.0672 - acc: 0.9742
Epoch 141/500
 - 0s - loss: 0.0729 - acc: 0.9715
Epoch 142/500
 - 0s - loss: 0.0727 - acc: 0.9733
Epoch 143/500
 - 0s - loss: 0.0653 - acc: 0.9724
Epoch 144/500
 - 0s - loss: 0.0659 - acc: 0.9786
Epoch 145/500
 - 0s - loss: 0.0626 - acc: 0.9759
Epoch 146/500
 - 0s - loss: 0.0670 - acc: 0.9742
Epoch 147/500
 - 0s - loss: 0.0644 - acc: 0.9759
Epoch 148/500
 - 0s - loss: 0.0648 - acc: 0.9724
Epoch 149/500
 - 0s - loss: 0.0628 - acc: 0.9795
Epoch 150/500
 - 0s - loss: 0.0599 - acc: 0.9777
Epoch 151/500
 - 0s - loss: 0.0582 - acc: 0.9786
Epoch 152/500
 - 0s - loss: 0.0589 - acc: 0.9768
Epoch 153/500
 - 0s - loss: 0.0601 - acc: 0.9777
Epoch 154/500
 - 0s - loss: 0.0634 - acc: 0.9786
Epoch 155/500
 - 0s - loss: 0.1300 - acc: 0.9447
Epoch 156/500
 - 0s - loss: 0.0766 - acc: 0.9688
Epoch 157/500
 - 0s - loss: 0.0679 - acc: 0.9706
Epoch 158/500
 - 0s - loss: 0.0625 - acc: 0.9750
Epoch 159/500
 - 0s - loss: 0.0626 - acc: 0.9724
Epoch 160/500
 - 0s - loss: 0.0596 - acc: 0.9786
Epoch 161/500
 - 0s - loss: 0.0602 - acc: 0.9768
Epoch 162/500
 - 0s - loss: 0.0641 - acc: 0.9786
Epoch 163/500
 - 0s - loss: 0.0592 - acc: 0.9786
Epoch 164/500
 - 0s - loss: 0.0554 - acc: 0.9804

Epoch 165/500
 - 0s - loss: 0.0660 - acc: 0.9750
Epoch 166/500
 - 0s - loss: 0.0552 - acc: 0.9831
Epoch 167/500
 - 0s - loss: 0.0564 - acc: 0.9777
Epoch 168/500
 - 0s - loss: 0.0542 - acc: 0.9813
Epoch 169/500
 - 0s - loss: 0.0531 - acc: 0.9804
Epoch 170/500
 - 0s - loss: 0.0534 - acc: 0.9777
Epoch 171/500
 - 0s - loss: 0.0520 - acc: 0.9795
Epoch 172/500
 - 0s - loss: 0.0537 - acc: 0.9795
Epoch 173/500
 - 0s - loss: 0.0511 - acc: 0.9813
Epoch 174/500
 - 0s - loss: 0.0599 - acc: 0.9795
Epoch 175/500
 - 0s - loss: 0.0564 - acc: 0.9813
Epoch 176/500
 - 0s - loss: 0.0496 - acc: 0.9813
Epoch 177/500
 - 0s - loss: 0.0524 - acc: 0.9777
Epoch 178/500
 - 0s - loss: 0.0496 - acc: 0.9822
Epoch 179/500
 - 0s - loss: 0.0641 - acc: 0.9715
Epoch 180/500
 - 0s - loss: 0.0561 - acc: 0.9759
Epoch 181/500
 - 0s - loss: 0.0480 - acc: 0.9813
Epoch 182/500
 - 0s - loss: 0.0504 - acc: 0.9804
Epoch 183/500
 - 0s - loss: 0.0485 - acc: 0.9804
Epoch 184/500
 - 0s - loss: 0.0481 - acc: 0.9831
Epoch 185/500
 - 0s - loss: 0.1079 - acc: 0.9599
Epoch 186/500
 - 0s - loss: 0.0646 - acc: 0.9768
Epoch 187/500
 - 0s - loss: 0.0542 - acc: 0.9804
Epoch 188/500
 - 0s - loss: 0.0488 - acc: 0.9786
Epoch 189/500
 - 0s - loss: 0.0465 - acc: 0.9822
Epoch 190/500
 - 0s - loss: 0.0440 - acc: 0.9840
Epoch 191/500
 - 0s - loss: 0.0435 - acc: 0.9848
Epoch 192/500
 - 0s - loss: 0.0449 - acc: 0.9840
Epoch 193/500
 - 0s - loss: 0.0428 - acc: 0.9866
Epoch 194/500
 - 0s - loss: 0.0492 - acc: 0.9804
Epoch 195/500
 - 0s - loss: 0.0423 - acc: 0.9857
Epoch 196/500
 - 0s - loss: 0.0515 - acc: 0.9795
Epoch 197/500
 - 0s - loss: 0.0447 - acc: 0.9831
Epoch 198/500
 - 0s - loss: 0.0450 - acc: 0.9840
Epoch 199/500
 - 0s - loss: 0.0438 - acc: 0.9813
Epoch 200/500
 - 0s - loss: 0.0431 - acc: 0.9831
Epoch 201/500
 - 0s - loss: 0.0453 - acc: 0.9831
Epoch 202/500
 - 0s - loss: 0.0416 - acc: 0.9840
Epoch 203/500
 - 0s - loss: 0.0435 - acc: 0.9848
Epoch 204/500
 - 0s - loss: 0.0416 - acc: 0.9840
Epoch 205/500
 - 0s - loss: 0.0423 - acc: 0.9840
Epoch 206/500
 - 0s - loss: 0.0398 - acc: 0.9840
Epoch 207/500
 - 0s - loss: 0.0399 - acc: 0.9857
Epoch 208/500
 - 0s - loss: 0.0410 - acc: 0.9875
Epoch 209/500
 - 0s - loss: 0.0385 - acc: 0.9875
Epoch 210/500
 - 0s - loss: 0.0383 - acc: 0.9893
Epoch 211/500
 - 0s - loss: 0.0386 - acc: 0.9840
Epoch 212/500
 - 0s - loss: 0.0384 - acc: 0.9884
Epoch 213/500
 - 0s - loss: 0.0394 - acc: 0.9884
Epoch 214/500
 - 0s - loss: 0.0384 - acc: 0.9884
Epoch 215/500
 - 0s - loss: 0.0389 - acc: 0.9857
Epoch 216/500
 - 0s - loss: 0.0379 - acc: 0.9893
Epoch 217/500
 - 0s - loss: 0.0459 - acc: 0.9804
Epoch 218/500
 - 0s - loss: 0.0428 - acc: 0.9840
Epoch 219/500
 - 0s - loss: 0.0393 - acc: 0.9857
Epoch 220/500
 - 0s - loss: 0.0361 - acc: 0.9884
Epoch 221/500
 - 0s - loss: 0.0360 - acc: 0.9866
Epoch 222/500
 - 0s - loss: 0.0380 - acc: 0.9857
Epoch 223/500
 - 0s - loss: 0.0350 - acc: 0.9893
Epoch 224/500
 - 0s - loss: 0.0374 - acc: 0.9875
Epoch 225/500
 - 0s - loss: 0.0364 - acc: 0.9857
Epoch 226/500
 - 0s - loss: 0.0394 - acc: 0.9866
Epoch 227/500
 - 0s - loss: 0.0344 - acc: 0.9866
Epoch 228/500
 - 0s - loss: 0.0370 - acc: 0.9831
Epoch 229/500
 - 0s - loss: 0.0413 - acc: 0.9848
Epoch 230/500
 - 0s - loss: 0.0472 - acc: 0.9813
Epoch 231/500
 - 0s - loss: 0.0376 - acc: 0.9875
Epoch 232/500
 - 0s - loss: 0.0334 - acc: 0.9920
Epoch 233/500
 - 0s - loss: 0.0357 - acc: 0.9884
Epoch 234/500
 - 0s - loss: 0.0447 - acc: 0.9813
Epoch 235/500
 - 0s - loss: 0.0372 - acc: 0.9875
Epoch 236/500
 - 0s - loss: 0.0348 - acc: 0.9902
Epoch 237/500
 - 0s - loss: 0.0366 - acc: 0.9857
Epoch 238/500
 - 0s - loss: 0.0294 - acc: 0.9911
Epoch 239/500
 - 0s - loss: 0.0323 - acc: 0.9902
Epoch 240/500
 - 0s - loss: 0.0390 - acc: 0.9848
Epoch 241/500
 - 0s - loss: 0.0369 - acc: 0.9840
Epoch 242/500
 - 0s - loss: 0.0338 - acc: 0.9848
Epoch 243/500
 - 0s - loss: 0.0313 - acc: 0.9884
Epoch 244/500
 - 0s - loss: 0.0385 - acc: 0.9848
Epoch 245/500
 - 0s - loss: 0.0330 - acc: 0.9866
Epoch 246/500
 - 0s - loss: 0.0350 - acc: 0.9848
Epoch 247/500
 - 0s - loss: 0.0364 - acc: 0.9840
Epoch 248/500
 - 0s - loss: 0.0726 - acc: 0.9768
Epoch 249/500
 - 0s - loss: 0.0592 - acc: 0.9795
Epoch 250/500
 - 0s - loss: 0.0433 - acc: 0.9875
Epoch 251/500
 - 0s - loss: 0.0359 - acc: 0.9884
Epoch 252/500
 - 0s - loss: 0.0332 - acc: 0.9911
Epoch 253/500
 - 0s - loss: 0.0359 - acc: 0.9857
Epoch 254/500
 - 0s - loss: 0.0327 - acc: 0.9893
Epoch 255/500
 - 0s - loss: 0.0344 - acc: 0.9893
Epoch 256/500
 - 0s - loss: 0.0311 - acc: 0.9929
Epoch 257/500
 - 0s - loss: 0.0372 - acc: 0.9857
Epoch 258/500
 - 0s - loss: 0.0331 - acc: 0.9866
Epoch 259/500
 - 0s - loss: 0.0323 - acc: 0.9875
Epoch 260/500
 - 0s - loss: 0.0302 - acc: 0.9893
Epoch 261/500
 - 0s - loss: 0.0306 - acc: 0.9893
Epoch 262/500
 - 0s - loss: 0.0299 - acc: 0.9893
Epoch 263/500
 - 0s - loss: 0.0329 - acc: 0.9902
Epoch 264/500
 - 0s - loss: 0.0304 - acc: 0.9911
Epoch 265/500
 - 0s - loss: 0.0264 - acc: 0.9911
Epoch 266/500
 - 0s - loss: 0.0262 - acc: 0.9902
Epoch 267/500
 - 0s - loss: 0.0265 - acc: 0.9911
Epoch 268/500
 - 0s - loss: 0.0347 - acc: 0.9848
Epoch 269/500
 - 0s - loss: 0.0298 - acc: 0.9902
Epoch 270/500
 - 0s - loss: 0.0285 - acc: 0.9920
Epoch 271/500
 - 0s - loss: 0.0245 - acc: 0.9955
Epoch 272/500
 - 0s - loss: 0.0262 - acc: 0.9938
Epoch 273/500
 - 0s - loss: 0.0262 - acc: 0.9902
Epoch 274/500
 - 0s - loss: 0.0278 - acc: 0.9902
Epoch 275/500
 - 0s - loss: 0.0284 - acc: 0.9884
Epoch 276/500
 - 0s - loss: 0.0275 - acc: 0.9920
Epoch 277/500
 - 0s - loss: 0.0254 - acc: 0.9902
Epoch 278/500
 - 0s - loss: 0.0250 - acc: 0.9920
Epoch 279/500
 - 0s - loss: 0.0277 - acc: 0.9884
Epoch 280/500
 - 0s - loss: 0.0264 - acc: 0.9929
Epoch 281/500
 - 0s - loss: 0.0287 - acc: 0.9893
Epoch 282/500
 - 0s - loss: 0.0347 - acc: 0.9840
Epoch 283/500
 - 0s - loss: 0.0284 - acc: 0.9884
Epoch 284/500
 - 0s - loss: 0.0254 - acc: 0.9911
Epoch 285/500
 - 0s - loss: 0.0242 - acc: 0.9875
Epoch 286/500
 - 0s - loss: 0.0256 - acc: 0.9929
Epoch 287/500
 - 0s - loss: 0.0306 - acc: 0.9893
Epoch 288/500
 - 0s - loss: 0.0829 - acc: 0.9661
Epoch 289/500
 - 0s - loss: 0.0619 - acc: 0.9750
Epoch 290/500
 - 0s - loss: 0.0404 - acc: 0.9840
Epoch 291/500
 - 0s - loss: 0.0310 - acc: 0.9893
Epoch 292/500
 - 0s - loss: 0.0288 - acc: 0.9902
Epoch 293/500
 - 0s - loss: 0.0308 - acc: 0.9884
Epoch 294/500
 - 0s - loss: 0.0441 - acc: 0.9866
Epoch 295/500
 - 0s - loss: 0.0287 - acc: 0.9893
Epoch 296/500
 - 0s - loss: 0.0371 - acc: 0.9875
Epoch 297/500
 - 0s - loss: 0.0282 - acc: 0.9875
Epoch 298/500
 - 0s - loss: 0.0282 - acc: 0.9893
Epoch 299/500
 - 0s - loss: 0.0261 - acc: 0.9911
Epoch 300/500
 - 0s - loss: 0.0245 - acc: 0.9911
Epoch 301/500
 - 0s - loss: 0.0253 - acc: 0.9938
Epoch 302/500
 - 0s - loss: 0.0289 - acc: 0.9875
Epoch 303/500
 - 0s - loss: 0.0240 - acc: 0.9929
Epoch 304/500
 - 0s - loss: 0.0251 - acc: 0.9902
Epoch 305/500
 - 0s - loss: 0.0309 - acc: 0.9884
Epoch 306/500
 - 0s - loss: 0.0310 - acc: 0.9875
Epoch 307/500
 - 0s - loss: 0.0257 - acc: 0.9893
Epoch 308/500
 - 0s - loss: 0.0382 - acc: 0.9840
Epoch 309/500
 - 0s - loss: 0.0277 - acc: 0.9911
Epoch 310/500
 - 0s - loss: 0.0247 - acc: 0.9911
Epoch 311/500
 - 0s - loss: 0.0276 - acc: 0.9875
Epoch 312/500
 - 0s - loss: 0.0310 - acc: 0.9857
Epoch 313/500
 - 0s - loss: 0.0264 - acc: 0.9920
Epoch 314/500
 - 0s - loss: 0.0263 - acc: 0.9920
Epoch 315/500
 - 0s - loss: 0.0342 - acc: 0.9875
Epoch 316/500
 - 0s - loss: 0.0284 - acc: 0.9893
Epoch 317/500
 - 0s - loss: 0.0238 - acc: 0.9920
Epoch 318/500
 - 0s - loss: 0.0259 - acc: 0.9902
Epoch 319/500
 - 0s - loss: 0.0232 - acc: 0.9911
Epoch 320/500
 - 0s - loss: 0.0264 - acc: 0.9911
Epoch 321/500
 - 0s - loss: 0.0302 - acc: 0.9875
Epoch 322/500
 - 0s - loss: 0.0248 - acc: 0.9893
Epoch 323/500
 - 0s - loss: 0.0279 - acc: 0.9884
Epoch 324/500
 - 0s - loss: 0.0222 - acc: 0.9911
Epoch 325/500
 - 0s - loss: 0.0232 - acc: 0.9929
Epoch 326/500
 - 0s - loss: 0.0250 - acc: 0.9893
Epoch 327/500
 - 0s - loss: 0.0974 - acc: 0.9626
Epoch 328/500
 - 0s - loss: 0.0579 - acc: 0.9822
Epoch 329/500
 - 0s - loss: 0.0322 - acc: 0.9902
Epoch 330/500
 - 0s - loss: 0.0298 - acc: 0.9866
Epoch 331/500
 - 0s - loss: 0.0249 - acc: 0.9938
Epoch 332/500

 - 0s - loss: 0.0250 - acc: 0.9929
Epoch 333/500
 - 0s - loss: 0.0234 - acc: 0.9929
Epoch 334/500
 - 0s - loss: 0.0218 - acc: 0.9929
Epoch 335/500
 - 0s - loss: 0.0223 - acc: 0.9920
Epoch 336/500
 - 0s - loss: 0.0227 - acc: 0.9938
Epoch 337/500
 - 0s - loss: 0.0220 - acc: 0.9929
Epoch 338/500
 - 0s - loss: 0.0233 - acc: 0.9947
Epoch 339/500
 - 0s - loss: 0.0226 - acc: 0.9929
Epoch 340/500
 - 0s - loss: 0.0256 - acc: 0.9911
Epoch 341/500
 - 0s - loss: 0.0266 - acc: 0.9902
Epoch 342/500
 - 0s - loss: 0.0207 - acc: 0.9929
Epoch 343/500
 - 0s - loss: 0.0231 - acc: 0.9929
Epoch 344/500
 - 0s - loss: 0.0205 - acc: 0.9938
Epoch 345/500
 - 0s - loss: 0.0200 - acc: 0.9929
Epoch 346/500
 - 0s - loss: 0.0241 - acc: 0.9884
Epoch 347/500
 - 0s - loss: 0.0210 - acc: 0.9938
Epoch 348/500
 - 0s - loss: 0.0233 - acc: 0.9929
Epoch 349/500
 - 0s - loss: 0.0273 - acc: 0.9893
Epoch 350/500
 - 0s - loss: 0.0212 - acc: 0.9902
Epoch 351/500
 - 0s - loss: 0.0210 - acc: 0.9920
Epoch 352/500
 - 0s - loss: 0.0237 - acc: 0.9902
Epoch 353/500
 - 0s - loss: 0.0250 - acc: 0.9920
Epoch 354/500
 - 0s - loss: 0.0246 - acc: 0.9893
Epoch 355/500
 - 0s - loss: 0.0220 - acc: 0.9920
Epoch 356/500
 - 0s - loss: 0.0253 - acc: 0.9929
Epoch 357/500
 - 0s - loss: 0.0249 - acc: 0.9902
Epoch 358/500
 - 0s - loss: 0.0285 - acc: 0.9884
Epoch 359/500
 - 0s - loss: 0.0235 - acc: 0.9929
Epoch 360/500
 - 0s - loss: 0.0204 - acc: 0.9902
Epoch 361/500
 - 0s - loss: 0.0241 - acc: 0.9911
Epoch 362/500
 - 0s - loss: 0.0257 - acc: 0.9893
Epoch 363/500
 - 0s - loss: 0.0198 - acc: 0.9902
Epoch 364/500
 - 0s - loss: 0.0232 - acc: 0.9902
Epoch 365/500
 - 0s - loss: 0.0210 - acc: 0.9929
Epoch 366/500
 - 0s - loss: 0.0215 - acc: 0.9911
Epoch 367/500
 - 0s - loss: 0.0212 - acc: 0.9938
Epoch 368/500
 - 0s - loss: 0.0218 - acc: 0.9911
Epoch 369/500
 - 0s - loss: 0.0222 - acc: 0.9911
Epoch 370/500
 - 0s - loss: 0.0235 - acc: 0.9920
Epoch 371/500
 - 0s - loss: 0.0205 - acc: 0.9920
Epoch 372/500
 - 0s - loss: 0.0192 - acc: 0.9911
Epoch 373/500
 - 0s - loss: 0.0183 - acc: 0.9938
Epoch 374/500
 - 0s - loss: 0.0209 - acc: 0.9911
Epoch 375/500
 - 0s - loss: 0.0191 - acc: 0.9929
Epoch 376/500
 - 0s - loss: 0.1127 - acc: 0.9670
Epoch 377/500
 - 0s - loss: 0.0599 - acc: 0.9795
Epoch 378/500
 - 0s - loss: 0.1139 - acc: 0.9643
Epoch 379/500
 - 0s - loss: 0.0407 - acc: 0.9857
Epoch 380/500
 - 0s - loss: 0.0312 - acc: 0.9884
Epoch 381/500
 - 0s - loss: 0.0275 - acc: 0.9893
Epoch 382/500
 - 0s - loss: 0.0218 - acc: 0.9920
Epoch 383/500
 - 0s - loss: 0.0212 - acc: 0.9911
Epoch 384/500
 - 0s - loss: 0.0211 - acc: 0.9929
Epoch 385/500
 - 0s - loss: 0.0219 - acc: 0.9929
Epoch 386/500
 - 0s - loss: 0.0195 - acc: 0.9920
Epoch 387/500
 - 0s - loss: 0.0218 - acc: 0.9920
Epoch 388/500
 - 0s - loss: 0.0184 - acc: 0.9929
Epoch 389/500
 - 0s - loss: 0.0191 - acc: 0.9955
Epoch 390/500
 - 0s - loss: 0.0196 - acc: 0.9929
Epoch 391/500
 - 0s - loss: 0.0196 - acc: 0.9929
Epoch 392/500
 - 0s - loss: 0.0196 - acc: 0.9893
Epoch 393/500
 - 0s - loss: 0.0253 - acc: 0.9893
Epoch 394/500
 - 0s - loss: 0.0229 - acc: 0.9893
Epoch 395/500
 - 0s - loss: 0.0203 - acc: 0.9955
Epoch 396/500
 - 0s - loss: 0.0382 - acc: 0.9884
Epoch 397/500
 - 0s - loss: 0.0725 - acc: 0.9679
Epoch 398/500
 - 0s - loss: 0.0393 - acc: 0.9795
Epoch 399/500
 - 0s - loss: 0.0295 - acc: 0.9893
Epoch 400/500
 - 0s - loss: 0.0246 - acc: 0.9929
Epoch 401/500
 - 0s - loss: 0.0257 - acc: 0.9893
Epoch 402/500
 - 0s - loss: 0.0275 - acc: 0.9893
Epoch 403/500
 - 0s - loss: 0.0215 - acc: 0.9938
Epoch 404/500
 - 0s - loss: 0.0190 - acc: 0.9947
Epoch 405/500
 - 0s - loss: 0.0226 - acc: 0.9920
Epoch 406/500
 - 0s - loss: 0.0213 - acc: 0.9902
Epoch 407/500
 - 0s - loss: 0.0213 - acc: 0.9929
Epoch 408/500
 - 0s - loss: 0.0175 - acc: 0.9947
Epoch 409/500
 - 0s - loss: 0.0200 - acc: 0.9938
Epoch 410/500
 - 0s - loss: 0.0189 - acc: 0.9929
Epoch 411/500
 - 0s - loss: 0.0199 - acc: 0.9920
Epoch 412/500
 - 0s - loss: 0.0167 - acc: 0.9947
Epoch 413/500
 - 0s - loss: 0.0177 - acc: 0.9955
Epoch 414/500
 - 0s - loss: 0.0172 - acc: 0.9929
Epoch 415/500
 - 0s - loss: 0.0174 - acc: 0.9947
Epoch 416/500
 - 0s - loss: 0.0281 - acc: 0.9884
Epoch 417/500
 - 0s - loss: 0.0210 - acc: 0.9911
Epoch 418/500
 - 0s - loss: 0.0186 - acc: 0.9911
Epoch 419/500
 - 0s - loss: 0.0171 - acc: 0.9947
Epoch 420/500
 - 0s - loss: 0.0191 - acc: 0.9929
Epoch 421/500
 - 0s - loss: 0.0164 - acc: 0.9947
Epoch 422/500
 - 0s - loss: 0.0211 - acc: 0.9964
Epoch 423/500
 - 0s - loss: 0.0185 - acc: 0.9929
Epoch 424/500
 - 0s - loss: 0.0193 - acc: 0.9929
Epoch 425/500
 - 0s - loss: 0.0192 - acc: 0.9938
Epoch 426/500
 - 0s - loss: 0.0198 - acc: 0.9929
Epoch 427/500
 - 0s - loss: 0.0224 - acc: 0.9920
Epoch 428/500
 - 0s - loss: 0.0201 - acc: 0.9938
Epoch 429/500
 - 0s - loss: 0.0182 - acc: 0.9938
Epoch 430/500
 - 0s - loss: 0.0199 - acc: 0.9911
Epoch 431/500
 - 0s - loss: 0.0162 - acc: 0.9947
Epoch 432/500
 - 0s - loss: 0.0177 - acc: 0.9929
Epoch 433/500
 - 0s - loss: 0.0170 - acc: 0.9938
Epoch 434/500
 - 0s - loss: 0.0174 - acc: 0.9938
Epoch 435/500
 - 0s - loss: 0.0217 - acc: 0.9920
Epoch 436/500
 - 0s - loss: 0.0244 - acc: 0.9902
Epoch 437/500
 - 0s - loss: 0.0177 - acc: 0.9929
Epoch 438/500
 - 0s - loss: 0.0204 - acc: 0.9938
Epoch 439/500
 - 0s - loss: 0.0182 - acc: 0.9920
Epoch 440/500
 - 0s - loss: 0.0269 - acc: 0.9911
Epoch 441/500
 - 0s - loss: 0.0223 - acc: 0.9920
Epoch 442/500
 - 0s - loss: 0.0230 - acc: 0.9920
Epoch 443/500
 - 0s - loss: 0.0211 - acc: 0.9920
Epoch 444/500
 - 0s - loss: 0.0172 - acc: 0.9929
Epoch 445/500
 - 0s - loss: 0.0169 - acc: 0.9938
Epoch 446/500
 - 0s - loss: 0.0184 - acc: 0.9947
Epoch 447/500
 - 0s - loss: 0.0205 - acc: 0.9911
Epoch 448/500
 - 0s - loss: 0.0168 - acc: 0.9955
Epoch 449/500
 - 0s - loss: 0.0181 - acc: 0.9938
Epoch 450/500
 - 0s - loss: 0.0264 - acc: 0.9893
Epoch 451/500
 - 0s - loss: 0.0208 - acc: 0.9938
Epoch 452/500
 - 0s - loss: 0.0170 - acc: 0.9938
Epoch 453/500
 - 0s - loss: 0.0171 - acc: 0.9947
Epoch 454/500
 - 0s - loss: 0.0185 - acc: 0.9929
Epoch 455/500
 - 0s - loss: 0.0241 - acc: 0.9911
Epoch 456/500
 - 0s - loss: 0.0189 - acc: 0.9947
Epoch 457/500
 - 0s - loss: 0.0209 - acc: 0.9929
Epoch 458/500
 - 0s - loss: 0.0175 - acc: 0.9947
Epoch 459/500
 - 0s - loss: 0.0206 - acc: 0.9920
Epoch 460/500
 - 0s - loss: 0.0433 - acc: 0.9822
Epoch 461/500
 - 0s - loss: 0.0270 - acc: 0.9920
Epoch 462/500
 - 0s - loss: 0.0211 - acc: 0.9902
Epoch 463/500
 - 0s - loss: 0.0218 - acc: 0.9911
Epoch 464/500
 - 0s - loss: 0.0175 - acc: 0.9947
Epoch 465/500
 - 0s - loss: 0.0174 - acc: 0.9938
Epoch 466/500
 - 0s - loss: 0.0159 - acc: 0.9947
Epoch 467/500
 - 0s - loss: 0.0206 - acc: 0.9911
Epoch 468/500
 - 0s - loss: 0.0193 - acc: 0.9938
Epoch 469/500
 - 0s - loss: 0.0171 - acc: 0.9947
Epoch 470/500
 - 0s - loss: 0.0193 - acc: 0.9955
Epoch 471/500
 - 0s - loss: 0.0189 - acc: 0.9929
Epoch 472/500
 - 0s - loss: 0.0182 - acc: 0.9929
Epoch 473/500
 - 0s - loss: 0.0206 - acc: 0.9911
Epoch 474/500
 - 0s - loss: 0.0159 - acc: 0.9938
Epoch 475/500
 - 0s - loss: 0.0170 - acc: 0.9929
Epoch 476/500
 - 0s - loss: 0.0409 - acc: 0.9804
Epoch 477/500
 - 0s - loss: 0.0267 - acc: 0.9875
Epoch 478/500
 - 0s - loss: 0.0189 - acc: 0.9938
Epoch 479/500
 - 0s - loss: 0.0249 - acc: 0.9893
Epoch 480/500
 - 0s - loss: 0.0264 - acc: 0.9893
Epoch 481/500
 - 0s - loss: 0.0185 - acc: 0.9929
Epoch 482/500
 - 0s - loss: 0.0646 - acc: 0.9750
Epoch 483/500
 - 0s - loss: 0.0422 - acc: 0.9840
Epoch 484/500
 - 0s - loss: 0.0253 - acc: 0.9938
Epoch 485/500
 - 0s - loss: 0.0236 - acc: 0.9911
Epoch 486/500
 - 0s - loss: 0.0175 - acc: 0.9955
Epoch 487/500
 - 0s - loss: 0.0189 - acc: 0.9938
Epoch 488/500
 - 0s - loss: 0.0348 - acc: 0.9875
Epoch 489/500
 - 0s - loss: 0.0226 - acc: 0.9902
Epoch 490/500
 - 0s - loss: 0.0176 - acc: 0.9902
Epoch 491/500
 - 0s - loss: 0.0192 - acc: 0.9911
Epoch 492/500
 - 0s - loss: 0.0179 - acc: 0.9955
Epoch 493/500
 - 0s - loss: 0.0173 - acc: 0.9955
Epoch 494/500
 - 0s - loss: 0.0210 - acc: 0.9938
Epoch 495/500
 - 0s - loss: 0.0161 - acc: 0.9955
Epoch 496/500
 - 0s - loss: 0.0180 - acc: 0.9929
Epoch 497/500
 - 0s - loss: 0.0167 - acc: 0.9929
Epoch 498/500
 - 0s - loss: 0.0157 - acc: 0.9955
Epoch 499/500
 - 0s - loss: 0.0154 - acc: 0.9955

Epoch 500/500
 - 0s - loss: 0.0192 - acc: 0.9955

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 0.6320 - acc: 0.9227
Normal Neural Network - Loss: 0.6319567318257565, Accuracy: 0.9226666688919067

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Certified' 'Certified' 'Certified' 'Certified' 'Certified'
 'Certified' 'Certified' 'Certified' 'Certified']
Actual Labels: ['Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified']