In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'SINGAPORE']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

SINGAPORE    474
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    473
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [8]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [9]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [10]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
340,Certified,505,98052,WASHINGTON,58000.0,102500.0,SINGAPORE,H-1B,Master's,2.0
592,Certified,266,10019,NEW YORK,3691.0,175000.0,SINGAPORE,H-1B,Master's,11.0
1428,Certified,193,22209,VIRGINIA,115.0,90000.0,SINGAPORE,H-1B,Bachelor's,2.0
2352,Certified,208,77056,TEXAS,14.0,64002.0,SINGAPORE,H-1B,Master's,3.0
2494,Certified,207,75201,TEXAS,152000.0,76336.0,SINGAPORE,H-1B,Master's,3.0

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

CALIFORNIA        199
WASHINGTON         63
NEW YORK           48
TEXAS              31
ILLINOIS           16
NEW JERSEY         16
PENNSYLVANIA       14
MASSACHUSETTS      13
MICHIGAN            9
UTAH                8
IDAHO               7
VIRGINIA            6
NORTH CAROLINA      5
CONNECTICUT         4
MARYLAND            4
OHIO                4
FLORIDA             4
WISCONSIN           3
INDIANA             3
IOWA                2
COLORADO            2
HAWAII              2
GEORGIA             2
ARIZONA             2
TENNESSEE           1
MINNESOTA           1
OREGON              1
NEVADA              1
SOUTH CAROLINA      1
WEST VIRGINIA       1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
340,Certified,505,98052,WASHINGTON,58000.0,102500.0,SINGAPORE,H-1B,Master's,2.0,WASHINGTON
592,Certified,266,10019,NEW YORK,3691.0,175000.0,SINGAPORE,H-1B,Master's,11.0,NEW YORK
1428,Certified,193,22209,VIRGINIA,115.0,90000.0,SINGAPORE,H-1B,Bachelor's,2.0,VIRGINIA
2352,Certified,208,77056,TEXAS,14.0,64002.0,SINGAPORE,H-1B,Master's,3.0,TEXAS
2494,Certified,207,75201,TEXAS,152000.0,76336.0,SINGAPORE,H-1B,Master's,3.0,TEXAS

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

WEST         282
NORTHEAST     90
SOUTH         53
MIDWEST       37
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      462
DECISION_ELAPSED_DAYS            462
EMPLOYER_POSTAL_CODE             462
EMPLOYER_STATE                   462
EMPLOYER_NUM_EMPLOYEES           462
WAGE_OFFER_FROM_9089             462
COUNTRY_OF_CITIZENSHIP           462
CLASS_OF_ADMISSION               462
FOREIGN_WORKER_INFO_EDUCATION    462
CASE_RECEIVED_DATE_MONTH         462
EMPLOYER_STATES                  462
EMPLOYER_REGIONS                 462
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      215
0-90        147
181-365      71
366-3600     29
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

100000-500000    320
75001-100000      99
50001-75000       37
25001-50000        5
0-25000            1
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

10001-1000000000    204
1001-10000          111
101-500              56
0-50                 54
51-100               20
501-1000             17
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      462
DECISION_ELAPSED_DAYS            462
EMPLOYER_POSTAL_CODE             462
EMPLOYER_STATE                   462
EMPLOYER_NUM_EMPLOYEES           462
WAGE_OFFER_FROM_9089             462
COUNTRY_OF_CITIZENSHIP           462
CLASS_OF_ADMISSION               462
FOREIGN_WORKER_INFO_EDUCATION    462
CASE_RECEIVED_DATE_MONTH         462
EMPLOYER_STATES                  462
EMPLOYER_REGIONS                 462
DAY_BINS                         462
WAGE_BINS                        462
EMPLOYEE_BINS                    462
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
340,Certified,10001-1000000000,100000-500000,WEST,2.0,Master's,H-1B,366-3600
592,Certified,1001-10000,100000-500000,NORTHEAST,11.0,Master's,H-1B,181-365
1428,Certified,101-500,75001-100000,SOUTH,2.0,Bachelor's,H-1B,181-365
2352,Certified,0-50,50001-75000,SOUTH,3.0,Master's,H-1B,181-365
2494,Certified,10001-1000000000,75001-100000,SOUTH,3.0,Master's,H-1B,181-365

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
340,Certified,10001-1000000000,100000-500000,WEST,2.0,Master's,H-1B,366-3600,4,4,1,3,2,1
592,Certified,1001-10000,100000-500000,NORTHEAST,11.0,Master's,H-1B,181-365,4,4,1,1,1,2
1428,Certified,101-500,75001-100000,SOUTH,2.0,Bachelor's,H-1B,181-365,4,1,4,2,1,3
2352,Certified,0-50,50001-75000,SOUTH,3.0,Master's,H-1B,181-365,4,4,3,2,1,0
2494,Certified,10001-1000000000,75001-100000,SOUTH,3.0,Master's,H-1B,181-365,4,4,4,2,1,1

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           462
EMPLOYEE_BINS                         462
WAGE_BINS                             462
EMPLOYER_REGIONS                      462
CASE_RECEIVED_DATE_MONTH              462
FOREIGN_WORKER_INFO_EDUCATION         462
CLASS_OF_ADMISSION                    462
DAY_BINS                              462
CLASS_OF_ADMISSION_CODE               462
FOREIGN_WORKER_INFO_EDUCATION_CODE    462
WAGE_BINS_CODE                        462
EMPLOYER_REGIONS_CODE                 462
DAY_BINS_CODE                         462
EMPLOYEE_BINS_CODE                    462
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
340,Certified,1,1,2,4,4,2.0,3
592,Certified,2,1,1,4,4,11.0,1
1428,Certified,3,4,1,1,4,2.0,2
2352,Certified,0,3,1,4,4,3.0,2
2494,Certified,1,4,1,4,4,3.0,2

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int32
WAGE_BINS_CODE                          int32
DAY_BINS_CODE                           int32
FOREIGN_WORKER_INFO_EDUCATION_CODE      int32
CLASS_OF_ADMISSION_CODE                 int32
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int32
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(462, 7) (462,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int32, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [57]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

Epoch 1/500
 - 0s - loss: 4.4895e-04 - acc: 1.0000
Epoch 2/500
 - 0s - loss: 4.3560e-04 - acc: 1.0000
Epoch 3/500
 - 0s - loss: 4.3581e-04 - acc: 1.0000
Epoch 4/500
 - 0s - loss: 4.4440e-04 - acc: 1.0000
Epoch 5/500
 - 0s - loss: 4.4697e-04 - acc: 1.0000
Epoch 6/500
 - 0s - loss: 4.3334e-04 - acc: 1.0000
Epoch 7/500
 - 0s - loss: 4.8474e-04 - acc: 1.0000
Epoch 8/500
 - 0s - loss: 4.0120e-04 - acc: 1.0000
Epoch 9/500
 - 0s - loss: 4.3738e-04 - acc: 1.0000
Epoch 10/500
 - 0s - loss: 4.2265e-04 - acc: 1.0000
Epoch 11/500
 - 0s - loss: 4.0992e-04 - acc: 1.0000
Epoch 12/500
 - 0s - loss: 4.0095e-04 - acc: 1.0000
Epoch 13/500
 - 0s - loss: 3.8946e-04 - acc: 1.0000
Epoch 14/500
 - 0s - loss: 3.7498e-04 - acc: 1.0000
Epoch 15/500
 - 0s - loss: 3.7564e-04 - acc: 1.0000
Epoch 16/500
 - 0s - loss: 3.7231e-04 - acc: 1.0000
Epoch 17/500
 - 0s - loss: 3.7181e-04 - acc: 1.0000
Epoch 18/500
 - 0s - loss: 3.8378e-04 - acc: 1.0000
Epoch 19/500
 - 0s - loss: 4.1407e-04 - acc: 1.0000
Epoch 20/500
 - 0s - loss: 3.7806e-04 - acc: 1.0000
Epoch 21/500
 - 0s - loss: 3.6775e-04 - acc: 1.0000
Epoch 22/500
 - 0s - loss: 3.5567e-04 - acc: 1.0000
Epoch 23/500
 - 0s - loss: 3.4274e-04 - acc: 1.0000
Epoch 24/500
 - 0s - loss: 3.5706e-04 - acc: 1.0000
Epoch 25/500
 - 0s - loss: 3.3909e-04 - acc: 1.0000
Epoch 26/500
 - 0s - loss: 3.2439e-04 - acc: 1.0000
Epoch 27/500
 - 0s - loss: 3.2900e-04 - acc: 1.0000
Epoch 28/500
 - 0s - loss: 3.3351e-04 - acc: 1.0000
Epoch 29/500
 - 0s - loss: 3.3383e-04 - acc: 1.0000
Epoch 30/500
 - 0s - loss: 3.2567e-04 - acc: 1.0000
Epoch 31/500
 - 0s - loss: 3.3742e-04 - acc: 1.0000
Epoch 32/500
 - 0s - loss: 3.5550e-04 - acc: 1.0000
Epoch 33/500
 - 0s - loss: 3.0891e-04 - acc: 1.0000
Epoch 34/500
 - 0s - loss: 3.0785e-04 - acc: 1.0000
Epoch 35/500
 - 0s - loss: 3.0413e-04 - acc: 1.0000
Epoch 36/500
 - 0s - loss: 3.1276e-04 - acc: 1.0000
Epoch 37/500
 - 0s - loss: 2.8974e-04 - acc: 1.0000
Epoch 38/500
 - 0s - loss: 2.9724e-04 - acc: 1.0000
Epoch 39/500
 - 0s - loss: 2.8974e-04 - acc: 1.0000
Epoch 40/500
 - 0s - loss: 2.9625e-04 - acc: 1.0000
Epoch 41/500
 - 0s - loss: 2.9098e-04 - acc: 1.0000
Epoch 42/500
 - 0s - loss: 2.9556e-04 - acc: 1.0000
Epoch 43/500
 - 0s - loss: 2.6903e-04 - acc: 1.0000
Epoch 44/500
 - 0s - loss: 3.0327e-04 - acc: 1.0000
Epoch 45/500
 - 0s - loss: 2.8662e-04 - acc: 1.0000
Epoch 46/500
 - 0s - loss: 2.6881e-04 - acc: 1.0000
Epoch 47/500
 - 0s - loss: 2.6218e-04 - acc: 1.0000
Epoch 48/500
 - 0s - loss: 2.5493e-04 - acc: 1.0000
Epoch 49/500
 - 0s - loss: 2.7368e-04 - acc: 1.0000
Epoch 50/500
 - 0s - loss: 2.5586e-04 - acc: 1.0000
Epoch 51/500
 - 0s - loss: 2.5127e-04 - acc: 1.0000
Epoch 52/500
 - 0s - loss: 2.5321e-04 - acc: 1.0000
Epoch 53/500
 - 0s - loss: 2.4343e-04 - acc: 1.0000
Epoch 54/500
 - 0s - loss: 2.3995e-04 - acc: 1.0000
Epoch 55/500
 - 0s - loss: 2.4946e-04 - acc: 1.0000
Epoch 56/500
 - 0s - loss: 2.7253e-04 - acc: 1.0000
Epoch 57/500
 - 0s - loss: 2.3947e-04 - acc: 1.0000
Epoch 58/500
 - 0s - loss: 2.3963e-04 - acc: 1.0000
Epoch 59/500
 - 0s - loss: 2.3429e-04 - acc: 1.0000
Epoch 60/500
 - 0s - loss: 2.2727e-04 - acc: 1.0000
Epoch 61/500
 - 0s - loss: 2.2689e-04 - acc: 1.0000
Epoch 62/500
 - 0s - loss: 2.2327e-04 - acc: 1.0000
Epoch 63/500
 - 0s - loss: 2.2284e-04 - acc: 1.0000
Epoch 64/500
 - 0s - loss: 2.2454e-04 - acc: 1.0000
Epoch 65/500
 - 0s - loss: 2.2054e-04 - acc: 1.0000
Epoch 66/500
 - 0s - loss: 2.1810e-04 - acc: 1.0000
Epoch 67/500
 - 0s - loss: 2.1783e-04 - acc: 1.0000
Epoch 68/500
 - 0s - loss: 2.0832e-04 - acc: 1.0000
Epoch 69/500
 - 0s - loss: 2.1662e-04 - acc: 1.0000
Epoch 70/500
 - 0s - loss: 2.1828e-04 - acc: 1.0000
Epoch 71/500
 - 0s - loss: 2.2842e-04 - acc: 1.0000
Epoch 72/500
 - 0s - loss: 2.4192e-04 - acc: 1.0000
Epoch 73/500
 - 0s - loss: 2.1235e-04 - acc: 1.0000
Epoch 74/500
 - 0s - loss: 2.1416e-04 - acc: 1.0000
Epoch 75/500
 - 0s - loss: 2.0259e-04 - acc: 1.0000
Epoch 76/500
 - 0s - loss: 1.9613e-04 - acc: 1.0000
Epoch 77/500
 - 0s - loss: 2.0234e-04 - acc: 1.0000
Epoch 78/500
 - 0s - loss: 1.8541e-04 - acc: 1.0000
Epoch 79/500
 - 0s - loss: 2.0004e-04 - acc: 1.0000
Epoch 80/500
 - 0s - loss: 1.8684e-04 - acc: 1.0000
Epoch 81/500
 - 0s - loss: 1.8414e-04 - acc: 1.0000
Epoch 82/500
 - 0s - loss: 1.9535e-04 - acc: 1.0000
Epoch 83/500
 - 0s - loss: 1.8894e-04 - acc: 1.0000
Epoch 84/500
 - 0s - loss: 1.7866e-04 - acc: 1.0000
Epoch 85/500
 - 0s - loss: 2.0638e-04 - acc: 1.0000
Epoch 86/500
 - 0s - loss: 2.0260e-04 - acc: 1.0000
Epoch 87/500
 - 0s - loss: 1.8088e-04 - acc: 1.0000
Epoch 88/500
 - 0s - loss: 1.7756e-04 - acc: 1.0000
Epoch 89/500
 - 0s - loss: 1.8015e-04 - acc: 1.0000
Epoch 90/500
 - 0s - loss: 1.6855e-04 - acc: 1.0000
Epoch 91/500
 - 0s - loss: 1.7009e-04 - acc: 1.0000
Epoch 92/500
 - 0s - loss: 1.6971e-04 - acc: 1.0000
Epoch 93/500
 - 0s - loss: 1.6509e-04 - acc: 1.0000
Epoch 94/500
 - 0s - loss: 1.6937e-04 - acc: 1.0000
Epoch 95/500
 - 0s - loss: 1.6027e-04 - acc: 1.0000
Epoch 96/500
 - 0s - loss: 1.5945e-04 - acc: 1.0000
Epoch 97/500
 - 0s - loss: 1.5848e-04 - acc: 1.0000
Epoch 98/500
 - 0s - loss: 1.6628e-04 - acc: 1.0000
Epoch 99/500
 - 0s - loss: 1.6496e-04 - acc: 1.0000
Epoch 100/500
 - 0s - loss: 1.5528e-04 - acc: 1.0000
Epoch 101/500
 - 0s - loss: 1.7076e-04 - acc: 1.0000
Epoch 102/500
 - 0s - loss: 1.6006e-04 - acc: 1.0000
Epoch 103/500
 - 0s - loss: 1.5630e-04 - acc: 1.0000
Epoch 104/500
 - 0s - loss: 1.7259e-04 - acc: 1.0000
Epoch 105/500
 - 0s - loss: 1.8543e-04 - acc: 1.0000
Epoch 106/500
 - 0s - loss: 1.5249e-04 - acc: 1.0000
Epoch 107/500
 - 0s - loss: 1.6553e-04 - acc: 1.0000
Epoch 108/500
 - 0s - loss: 1.5466e-04 - acc: 1.0000
Epoch 109/500
 - 0s - loss: 1.4668e-04 - acc: 1.0000
Epoch 110/500
 - 0s - loss: 1.4866e-04 - acc: 1.0000
Epoch 111/500
 - 0s - loss: 1.3556e-04 - acc: 1.0000
Epoch 112/500
 - 0s - loss: 1.4700e-04 - acc: 1.0000
Epoch 113/500
 - 0s - loss: 1.5385e-04 - acc: 1.0000
Epoch 114/500
 - 0s - loss: 1.4941e-04 - acc: 1.0000
Epoch 115/500
 - 0s - loss: 1.4066e-04 - acc: 1.0000
Epoch 116/500
 - 0s - loss: 1.3786e-04 - acc: 1.0000
Epoch 117/500
 - 0s - loss: 1.3384e-04 - acc: 1.0000
Epoch 118/500
 - 0s - loss: 1.3796e-04 - acc: 1.0000
Epoch 119/500
 - 0s - loss: 1.2972e-04 - acc: 1.0000
Epoch 120/500
 - 0s - loss: 1.2956e-04 - acc: 1.0000
Epoch 121/500
 - 0s - loss: 1.3680e-04 - acc: 1.0000
Epoch 122/500
 - 0s - loss: 1.2484e-04 - acc: 1.0000
Epoch 123/500
 - 0s - loss: 1.2680e-04 - acc: 1.0000
Epoch 124/500
 - 0s - loss: 1.2577e-04 - acc: 1.0000
Epoch 125/500
 - 0s - loss: 1.2137e-04 - acc: 1.0000
Epoch 126/500
 - 0s - loss: 1.2314e-04 - acc: 1.0000
Epoch 127/500
 - 0s - loss: 1.2366e-04 - acc: 1.0000
Epoch 128/500
 - 0s - loss: 1.1995e-04 - acc: 1.0000
Epoch 129/500
 - 0s - loss: 1.2845e-04 - acc: 1.0000
Epoch 130/500
 - 0s - loss: 1.1649e-04 - acc: 1.0000
Epoch 131/500
 - 0s - loss: 1.1742e-04 - acc: 1.0000
Epoch 132/500
 - 0s - loss: 1.1316e-04 - acc: 1.0000
Epoch 133/500
 - 0s - loss: 1.1342e-04 - acc: 1.0000
Epoch 134/500
 - 0s - loss: 1.1473e-04 - acc: 1.0000
Epoch 135/500
 - 0s - loss: 1.1528e-04 - acc: 1.0000
Epoch 136/500
 - 0s - loss: 1.1974e-04 - acc: 1.0000
Epoch 137/500
 - 0s - loss: 1.1481e-04 - acc: 1.0000
Epoch 138/500
 - 0s - loss: 1.0988e-04 - acc: 1.0000
Epoch 139/500
 - 0s - loss: 1.1159e-04 - acc: 1.0000
Epoch 140/500
 - 0s - loss: 1.0489e-04 - acc: 1.0000
Epoch 141/500
 - 0s - loss: 1.1215e-04 - acc: 1.0000
Epoch 142/500
 - 0s - loss: 1.0925e-04 - acc: 1.0000
Epoch 143/500
 - 0s - loss: 1.0714e-04 - acc: 1.0000
Epoch 144/500
 - 0s - loss: 1.0634e-04 - acc: 1.0000
Epoch 145/500
 - 0s - loss: 1.0150e-04 - acc: 1.0000
Epoch 146/500
 - 0s - loss: 1.0351e-04 - acc: 1.0000
Epoch 147/500
 - 0s - loss: 1.1110e-04 - acc: 1.0000
Epoch 148/500
 - 0s - loss: 1.0807e-04 - acc: 1.0000
Epoch 149/500
 - 0s - loss: 9.8094e-05 - acc: 1.0000
Epoch 150/500
 - 0s - loss: 1.0179e-04 - acc: 1.0000
Epoch 151/500
 - 0s - loss: 1.0271e-04 - acc: 1.0000
Epoch 152/500
 - 0s - loss: 9.9541e-05 - acc: 1.0000
Epoch 153/500
 - 0s - loss: 9.6729e-05 - acc: 1.0000
Epoch 154/500
 - 0s - loss: 9.4154e-05 - acc: 1.0000
Epoch 155/500
 - 0s - loss: 9.4146e-05 - acc: 1.0000
Epoch 156/500
 - 0s - loss: 9.4578e-05 - acc: 1.0000
Epoch 157/500
 - 0s - loss: 9.5973e-05 - acc: 1.0000

Epoch 158/500
 - 0s - loss: 9.6475e-05 - acc: 1.0000
Epoch 159/500
 - 0s - loss: 9.3700e-05 - acc: 1.0000
Epoch 160/500
 - 0s - loss: 9.6840e-05 - acc: 1.0000
Epoch 161/500
 - 0s - loss: 8.9128e-05 - acc: 1.0000
Epoch 162/500
 - 0s - loss: 9.0178e-05 - acc: 1.0000
Epoch 163/500
 - 0s - loss: 9.2617e-05 - acc: 1.0000
Epoch 164/500
 - 0s - loss: 8.8443e-05 - acc: 1.0000
Epoch 165/500
 - 0s - loss: 8.9239e-05 - acc: 1.0000
Epoch 166/500
 - 0s - loss: 8.7535e-05 - acc: 1.0000
Epoch 167/500
 - 0s - loss: 8.9715e-05 - acc: 1.0000
Epoch 168/500
 - 0s - loss: 8.8516e-05 - acc: 1.0000
Epoch 169/500
 - 0s - loss: 8.7419e-05 - acc: 1.0000
Epoch 170/500
 - 0s - loss: 8.3983e-05 - acc: 1.0000
Epoch 171/500
 - 0s - loss: 8.4342e-05 - acc: 1.0000
Epoch 172/500
 - 0s - loss: 8.3255e-05 - acc: 1.0000
Epoch 173/500
 - 0s - loss: 8.6884e-05 - acc: 1.0000
Epoch 174/500
 - 0s - loss: 8.5618e-05 - acc: 1.0000
Epoch 175/500
 - 0s - loss: 8.1678e-05 - acc: 1.0000
Epoch 176/500
 - 0s - loss: 8.0593e-05 - acc: 1.0000
Epoch 177/500
 - 0s - loss: 7.8023e-05 - acc: 1.0000
Epoch 178/500
 - 0s - loss: 7.9392e-05 - acc: 1.0000
Epoch 179/500
 - 0s - loss: 7.6942e-05 - acc: 1.0000
Epoch 180/500
 - 0s - loss: 7.6831e-05 - acc: 1.0000
Epoch 181/500
 - 0s - loss: 7.6968e-05 - acc: 1.0000
Epoch 182/500
 - 0s - loss: 7.6269e-05 - acc: 1.0000
Epoch 183/500
 - 0s - loss: 7.6289e-05 - acc: 1.0000
Epoch 184/500
 - 0s - loss: 7.5981e-05 - acc: 1.0000
Epoch 185/500
 - 0s - loss: 7.4008e-05 - acc: 1.0000
Epoch 186/500
 - 0s - loss: 7.4601e-05 - acc: 1.0000
Epoch 187/500
 - 0s - loss: 7.1762e-05 - acc: 1.0000
Epoch 188/500
 - 0s - loss: 7.5289e-05 - acc: 1.0000
Epoch 189/500
 - 0s - loss: 7.1981e-05 - acc: 1.0000
Epoch 190/500
 - 0s - loss: 7.1223e-05 - acc: 1.0000
Epoch 191/500
 - 0s - loss: 7.3595e-05 - acc: 1.0000
Epoch 192/500
 - 0s - loss: 7.0957e-05 - acc: 1.0000
Epoch 193/500
 - 0s - loss: 8.0434e-05 - acc: 1.0000
Epoch 194/500
 - 0s - loss: 7.1122e-05 - acc: 1.0000
Epoch 195/500
 - 0s - loss: 7.2387e-05 - acc: 1.0000
Epoch 196/500
 - 0s - loss: 6.8486e-05 - acc: 1.0000
Epoch 197/500
 - 0s - loss: 6.8826e-05 - acc: 1.0000
Epoch 198/500
 - 0s - loss: 6.9048e-05 - acc: 1.0000
Epoch 199/500
 - 0s - loss: 7.0350e-05 - acc: 1.0000
Epoch 200/500
 - 0s - loss: 7.0335e-05 - acc: 1.0000
Epoch 201/500
 - 0s - loss: 6.5113e-05 - acc: 1.0000
Epoch 202/500
 - 0s - loss: 6.6498e-05 - acc: 1.0000
Epoch 203/500
 - 0s - loss: 7.0611e-05 - acc: 1.0000
Epoch 204/500
 - 0s - loss: 6.4277e-05 - acc: 1.0000
Epoch 205/500
 - 0s - loss: 6.3254e-05 - acc: 1.0000
Epoch 206/500
 - 0s - loss: 6.4612e-05 - acc: 1.0000
Epoch 207/500
 - 0s - loss: 6.3133e-05 - acc: 1.0000
Epoch 208/500
 - 0s - loss: 6.3815e-05 - acc: 1.0000
Epoch 209/500
 - 0s - loss: 6.4887e-05 - acc: 1.0000
Epoch 210/500
 - 0s - loss: 6.1693e-05 - acc: 1.0000
Epoch 211/500
 - 0s - loss: 6.2387e-05 - acc: 1.0000
Epoch 212/500
 - 0s - loss: 5.9437e-05 - acc: 1.0000
Epoch 213/500
 - 0s - loss: 5.8804e-05 - acc: 1.0000
Epoch 214/500
 - 0s - loss: 5.9822e-05 - acc: 1.0000
Epoch 215/500
 - 0s - loss: 5.6999e-05 - acc: 1.0000
Epoch 216/500
 - 0s - loss: 6.0064e-05 - acc: 1.0000
Epoch 217/500
 - 0s - loss: 5.6600e-05 - acc: 1.0000
Epoch 218/500
 - 0s - loss: 5.7714e-05 - acc: 1.0000
Epoch 219/500
 - 0s - loss: 5.5798e-05 - acc: 1.0000
Epoch 220/500
 - 0s - loss: 5.5261e-05 - acc: 1.0000
Epoch 221/500
 - 0s - loss: 5.8231e-05 - acc: 1.0000
Epoch 222/500
 - 0s - loss: 5.4453e-05 - acc: 1.0000
Epoch 223/500
 - 0s - loss: 5.8350e-05 - acc: 1.0000
Epoch 224/500
 - 0s - loss: 5.4601e-05 - acc: 1.0000
Epoch 225/500
 - 0s - loss: 5.3650e-05 - acc: 1.0000
Epoch 226/500
 - 0s - loss: 5.3511e-05 - acc: 1.0000
Epoch 227/500
 - 0s - loss: 5.2537e-05 - acc: 1.0000
Epoch 228/500
 - 0s - loss: 5.3385e-05 - acc: 1.0000
Epoch 229/500
 - 0s - loss: 5.2550e-05 - acc: 1.0000
Epoch 230/500
 - 0s - loss: 5.6863e-05 - acc: 1.0000
Epoch 231/500
 - 0s - loss: 5.0577e-05 - acc: 1.0000
Epoch 232/500
 - 0s - loss: 5.0771e-05 - acc: 1.0000
Epoch 233/500
 - 0s - loss: 5.1277e-05 - acc: 1.0000
Epoch 234/500
 - 0s - loss: 5.1628e-05 - acc: 1.0000
Epoch 235/500
 - 0s - loss: 4.7857e-05 - acc: 1.0000
Epoch 236/500
 - 0s - loss: 5.1670e-05 - acc: 1.0000
Epoch 237/500
 - 0s - loss: 4.9578e-05 - acc: 1.0000
Epoch 238/500
 - 0s - loss: 4.8679e-05 - acc: 1.0000
Epoch 239/500
 - 0s - loss: 4.7619e-05 - acc: 1.0000
Epoch 240/500
 - 0s - loss: 4.8676e-05 - acc: 1.0000
Epoch 241/500
 - 0s - loss: 4.7935e-05 - acc: 1.0000
Epoch 242/500
 - 0s - loss: 4.5835e-05 - acc: 1.0000
Epoch 243/500
 - 0s - loss: 4.7158e-05 - acc: 1.0000
Epoch 244/500
 - 0s - loss: 4.7818e-05 - acc: 1.0000
Epoch 245/500
 - 0s - loss: 4.7695e-05 - acc: 1.0000
Epoch 246/500
 - 0s - loss: 4.5972e-05 - acc: 1.0000
Epoch 247/500
 - 0s - loss: 4.5248e-05 - acc: 1.0000
Epoch 248/500
 - 0s - loss: 4.5675e-05 - acc: 1.0000
Epoch 249/500
 - 0s - loss: 4.4746e-05 - acc: 1.0000
Epoch 250/500
 - 0s - loss: 4.3398e-05 - acc: 1.0000
Epoch 251/500
 - 0s - loss: 4.3489e-05 - acc: 1.0000
Epoch 252/500
 - 0s - loss: 4.4326e-05 - acc: 1.0000
Epoch 253/500
 - 0s - loss: 4.3399e-05 - acc: 1.0000
Epoch 254/500
 - 0s - loss: 4.3049e-05 - acc: 1.0000
Epoch 255/500
 - 0s - loss: 4.2630e-05 - acc: 1.0000
Epoch 256/500
 - 0s - loss: 4.1710e-05 - acc: 1.0000
Epoch 257/500
 - 0s - loss: 4.2510e-05 - acc: 1.0000
Epoch 258/500
 - 0s - loss: 4.1649e-05 - acc: 1.0000
Epoch 259/500
 - 0s - loss: 4.1437e-05 - acc: 1.0000
Epoch 260/500
 - 0s - loss: 4.1776e-05 - acc: 1.0000
Epoch 261/500
 - 0s - loss: 4.0971e-05 - acc: 1.0000
Epoch 262/500
 - 0s - loss: 4.0609e-05 - acc: 1.0000
Epoch 263/500
 - 0s - loss: 4.2343e-05 - acc: 1.0000
Epoch 264/500
 - 0s - loss: 4.1740e-05 - acc: 1.0000
Epoch 265/500
 - 0s - loss: 4.0617e-05 - acc: 1.0000
Epoch 266/500
 - 0s - loss: 3.9266e-05 - acc: 1.0000
Epoch 267/500
 - 0s - loss: 3.8764e-05 - acc: 1.0000
Epoch 268/500
 - 0s - loss: 3.8465e-05 - acc: 1.0000
Epoch 269/500
 - 0s - loss: 3.9141e-05 - acc: 1.0000
Epoch 270/500
 - 0s - loss: 3.7664e-05 - acc: 1.0000
Epoch 271/500
 - 0s - loss: 4.0130e-05 - acc: 1.0000
Epoch 272/500
 - 0s - loss: 3.6298e-05 - acc: 1.0000
Epoch 273/500
 - 0s - loss: 4.1177e-05 - acc: 1.0000
Epoch 274/500
 - 0s - loss: 4.0893e-05 - acc: 1.0000
Epoch 275/500
 - 0s - loss: 4.2199e-05 - acc: 1.0000
Epoch 276/500
 - 0s - loss: 4.1088e-05 - acc: 1.0000
Epoch 277/500
 - 0s - loss: 4.0585e-05 - acc: 1.0000
Epoch 278/500
 - 0s - loss: 4.0918e-05 - acc: 1.0000
Epoch 279/500
 - 0s - loss: 3.5478e-05 - acc: 1.0000
Epoch 280/500
 - 0s - loss: 3.5784e-05 - acc: 1.0000
Epoch 281/500
 - 0s - loss: 3.5839e-05 - acc: 1.0000
Epoch 282/500
 - 0s - loss: 3.4467e-05 - acc: 1.0000
Epoch 283/500
 - 0s - loss: 3.4932e-05 - acc: 1.0000
Epoch 284/500
 - 0s - loss: 3.4641e-05 - acc: 1.0000
Epoch 285/500
 - 0s - loss: 3.3587e-05 - acc: 1.0000
Epoch 286/500
 - 0s - loss: 3.3518e-05 - acc: 1.0000
Epoch 287/500
 - 0s - loss: 3.3523e-05 - acc: 1.0000
Epoch 288/500
 - 0s - loss: 3.3534e-05 - acc: 1.0000
Epoch 289/500
 - 0s - loss: 3.2824e-05 - acc: 1.0000
Epoch 290/500
 - 0s - loss: 3.3009e-05 - acc: 1.0000
Epoch 291/500
 - 0s - loss: 3.2006e-05 - acc: 1.0000
Epoch 292/500
 - 0s - loss: 3.2862e-05 - acc: 1.0000
Epoch 293/500
 - 0s - loss: 3.2086e-05 - acc: 1.0000
Epoch 294/500
 - 0s - loss: 3.1579e-05 - acc: 1.0000
Epoch 295/500
 - 0s - loss: 3.1181e-05 - acc: 1.0000
Epoch 296/500
 - 0s - loss: 3.2306e-05 - acc: 1.0000
Epoch 297/500
 - 0s - loss: 3.1206e-05 - acc: 1.0000
Epoch 298/500
 - 0s - loss: 3.1044e-05 - acc: 1.0000
Epoch 299/500
 - 0s - loss: 3.1448e-05 - acc: 1.0000
Epoch 300/500
 - 0s - loss: 3.0723e-05 - acc: 1.0000
Epoch 301/500
 - 0s - loss: 3.0389e-05 - acc: 1.0000
Epoch 302/500
 - 0s - loss: 3.1509e-05 - acc: 1.0000
Epoch 303/500
 - 0s - loss: 3.0722e-05 - acc: 1.0000
Epoch 304/500
 - 0s - loss: 2.9498e-05 - acc: 1.0000
Epoch 305/500
 - 0s - loss: 2.8875e-05 - acc: 1.0000
Epoch 306/500
 - 0s - loss: 3.0244e-05 - acc: 1.0000
Epoch 307/500
 - 0s - loss: 2.8156e-05 - acc: 1.0000
Epoch 308/500
 - 0s - loss: 3.0153e-05 - acc: 1.0000
Epoch 309/500
 - 0s - loss: 2.8785e-05 - acc: 1.0000
Epoch 310/500
 - 0s - loss: 2.8754e-05 - acc: 1.0000
Epoch 311/500
 - 0s - loss: 2.8137e-05 - acc: 1.0000
Epoch 312/500
 - 0s - loss: 2.7477e-05 - acc: 1.0000

Epoch 313/500
 - 0s - loss: 2.7442e-05 - acc: 1.0000
Epoch 314/500
 - 0s - loss: 2.8277e-05 - acc: 1.0000
Epoch 315/500
 - 0s - loss: 2.7692e-05 - acc: 1.0000
Epoch 316/500
 - 0s - loss: 2.6621e-05 - acc: 1.0000
Epoch 317/500
 - 0s - loss: 2.6216e-05 - acc: 1.0000
Epoch 318/500
 - 0s - loss: 2.7400e-05 - acc: 1.0000
Epoch 319/500
 - 0s - loss: 2.7356e-05 - acc: 1.0000
Epoch 320/500
 - 0s - loss: 2.7491e-05 - acc: 1.0000
Epoch 321/500
 - 0s - loss: 2.5916e-05 - acc: 1.0000
Epoch 322/500
 - 0s - loss: 2.5643e-05 - acc: 1.0000
Epoch 323/500
 - 0s - loss: 2.4808e-05 - acc: 1.0000
Epoch 324/500
 - 0s - loss: 2.4566e-05 - acc: 1.0000
Epoch 325/500
 - 0s - loss: 2.4862e-05 - acc: 1.0000
Epoch 326/500
 - 0s - loss: 2.4614e-05 - acc: 1.0000
Epoch 327/500
 - 0s - loss: 2.4241e-05 - acc: 1.0000
Epoch 328/500
 - 0s - loss: 2.4123e-05 - acc: 1.0000
Epoch 329/500
 - 0s - loss: 2.4118e-05 - acc: 1.0000
Epoch 330/500
 - 0s - loss: 2.4122e-05 - acc: 1.0000
Epoch 331/500
 - 0s - loss: 2.4149e-05 - acc: 1.0000
Epoch 332/500
 - 0s - loss: 2.3702e-05 - acc: 1.0000
Epoch 333/500
 - 0s - loss: 2.4562e-05 - acc: 1.0000
Epoch 334/500
 - 0s - loss: 2.3289e-05 - acc: 1.0000
Epoch 335/500
 - 0s - loss: 2.3499e-05 - acc: 1.0000
Epoch 336/500
 - 0s - loss: 2.3901e-05 - acc: 1.0000
Epoch 337/500
 - 0s - loss: 2.3715e-05 - acc: 1.0000
Epoch 338/500
 - 0s - loss: 2.3271e-05 - acc: 1.0000
Epoch 339/500
 - 0s - loss: 2.2565e-05 - acc: 1.0000
Epoch 340/500
 - 0s - loss: 2.2810e-05 - acc: 1.0000
Epoch 341/500
 - 0s - loss: 2.2150e-05 - acc: 1.0000
Epoch 342/500
 - 0s - loss: 2.2945e-05 - acc: 1.0000
Epoch 343/500
 - 0s - loss: 2.5039e-05 - acc: 1.0000
Epoch 344/500
 - 0s - loss: 2.3370e-05 - acc: 1.0000
Epoch 345/500
 - 0s - loss: 2.3267e-05 - acc: 1.0000
Epoch 346/500
 - 0s - loss: 2.2592e-05 - acc: 1.0000
Epoch 347/500
 - 0s - loss: 2.1110e-05 - acc: 1.0000
Epoch 348/500
 - 0s - loss: 2.1511e-05 - acc: 1.0000
Epoch 349/500
 - 0s - loss: 2.1604e-05 - acc: 1.0000
Epoch 350/500
 - 0s - loss: 2.1560e-05 - acc: 1.0000
Epoch 351/500
 - 0s - loss: 2.2218e-05 - acc: 1.0000
Epoch 352/500
 - 0s - loss: 2.0997e-05 - acc: 1.0000
Epoch 353/500
 - 0s - loss: 2.0575e-05 - acc: 1.0000
Epoch 354/500
 - 0s - loss: 2.0234e-05 - acc: 1.0000
Epoch 355/500
 - 0s - loss: 2.0990e-05 - acc: 1.0000
Epoch 356/500
 - 0s - loss: 2.2620e-05 - acc: 1.0000
Epoch 357/500
 - 0s - loss: 2.1411e-05 - acc: 1.0000
Epoch 358/500
 - 0s - loss: 1.9956e-05 - acc: 1.0000
Epoch 359/500
 - 0s - loss: 2.0729e-05 - acc: 1.0000
Epoch 360/500
 - 0s - loss: 1.9775e-05 - acc: 1.0000
Epoch 361/500
 - 0s - loss: 1.8853e-05 - acc: 1.0000
Epoch 362/500
 - 0s - loss: 1.9766e-05 - acc: 1.0000
Epoch 363/500
 - 0s - loss: 1.9683e-05 - acc: 1.0000
Epoch 364/500
 - 0s - loss: 1.8581e-05 - acc: 1.0000
Epoch 365/500
 - 0s - loss: 1.8793e-05 - acc: 1.0000
Epoch 366/500
 - 0s - loss: 1.8321e-05 - acc: 1.0000
Epoch 367/500
 - 0s - loss: 1.8263e-05 - acc: 1.0000
Epoch 368/500
 - 0s - loss: 1.7823e-05 - acc: 1.0000
Epoch 369/500
 - 0s - loss: 1.7774e-05 - acc: 1.0000
Epoch 370/500
 - 0s - loss: 1.7563e-05 - acc: 1.0000
Epoch 371/500
 - 0s - loss: 1.8368e-05 - acc: 1.0000
Epoch 372/500
 - 0s - loss: 1.7698e-05 - acc: 1.0000
Epoch 373/500
 - 0s - loss: 1.7528e-05 - acc: 1.0000
Epoch 374/500
 - 0s - loss: 1.7598e-05 - acc: 1.0000
Epoch 375/500
 - 0s - loss: 1.7545e-05 - acc: 1.0000
Epoch 376/500
 - 0s - loss: 1.7568e-05 - acc: 1.0000
Epoch 377/500
 - 0s - loss: 1.7273e-05 - acc: 1.0000
Epoch 378/500
 - 0s - loss: 1.6922e-05 - acc: 1.0000
Epoch 379/500
 - 0s - loss: 1.6793e-05 - acc: 1.0000
Epoch 380/500
 - 0s - loss: 1.8415e-05 - acc: 1.0000
Epoch 381/500
 - 0s - loss: 1.6324e-05 - acc: 1.0000
Epoch 382/500
 - 0s - loss: 1.6420e-05 - acc: 1.0000
Epoch 383/500
 - 0s - loss: 1.6213e-05 - acc: 1.0000
Epoch 384/500
 - 0s - loss: 1.5772e-05 - acc: 1.0000
Epoch 385/500
 - 0s - loss: 1.6157e-05 - acc: 1.0000
Epoch 386/500
 - 0s - loss: 1.5448e-05 - acc: 1.0000
Epoch 387/500
 - 0s - loss: 1.5996e-05 - acc: 1.0000
Epoch 388/500
 - 0s - loss: 1.6058e-05 - acc: 1.0000
Epoch 389/500
 - 0s - loss: 1.6029e-05 - acc: 1.0000
Epoch 390/500
 - 0s - loss: 1.5355e-05 - acc: 1.0000
Epoch 391/500
 - 0s - loss: 1.5294e-05 - acc: 1.0000
Epoch 392/500
 - 0s - loss: 1.5140e-05 - acc: 1.0000
Epoch 393/500
 - 0s - loss: 1.5088e-05 - acc: 1.0000
Epoch 394/500
 - 0s - loss: 1.5043e-05 - acc: 1.0000
Epoch 395/500
 - 0s - loss: 1.5078e-05 - acc: 1.0000
Epoch 396/500
 - 0s - loss: 1.4938e-05 - acc: 1.0000
Epoch 397/500
 - 0s - loss: 1.5220e-05 - acc: 1.0000
Epoch 398/500
 - 0s - loss: 1.4505e-05 - acc: 1.0000
Epoch 399/500
 - 0s - loss: 1.4239e-05 - acc: 1.0000
Epoch 400/500
 - 0s - loss: 1.4965e-05 - acc: 1.0000
Epoch 401/500
 - 0s - loss: 1.4141e-05 - acc: 1.0000
Epoch 402/500
 - 0s - loss: 1.4712e-05 - acc: 1.0000
Epoch 403/500
 - 0s - loss: 1.4002e-05 - acc: 1.0000
Epoch 404/500
 - 0s - loss: 1.4650e-05 - acc: 1.0000
Epoch 405/500
 - 0s - loss: 1.3494e-05 - acc: 1.0000
Epoch 406/500
 - 0s - loss: 1.4051e-05 - acc: 1.0000
Epoch 407/500
 - 0s - loss: 1.3997e-05 - acc: 1.0000
Epoch 408/500
 - 0s - loss: 1.4046e-05 - acc: 1.0000
Epoch 409/500
 - 0s - loss: 1.3465e-05 - acc: 1.0000
Epoch 410/500
 - 0s - loss: 1.3538e-05 - acc: 1.0000
Epoch 411/500
 - 0s - loss: 1.3695e-05 - acc: 1.0000
Epoch 412/500
 - 0s - loss: 1.3597e-05 - acc: 1.0000
Epoch 413/500
 - 0s - loss: 1.3188e-05 - acc: 1.0000
Epoch 414/500
 - 0s - loss: 1.3309e-05 - acc: 1.0000
Epoch 415/500
 - 0s - loss: 1.2667e-05 - acc: 1.0000
Epoch 416/500
 - 0s - loss: 1.3533e-05 - acc: 1.0000
Epoch 417/500
 - 0s - loss: 1.3036e-05 - acc: 1.0000
Epoch 418/500
 - 0s - loss: 1.2620e-05 - acc: 1.0000
Epoch 419/500
 - 0s - loss: 1.2576e-05 - acc: 1.0000
Epoch 420/500
 - 0s - loss: 1.2879e-05 - acc: 1.0000
Epoch 421/500
 - 0s - loss: 1.2227e-05 - acc: 1.0000
Epoch 422/500
 - 0s - loss: 1.2888e-05 - acc: 1.0000
Epoch 423/500
 - 0s - loss: 1.2109e-05 - acc: 1.0000
Epoch 424/500
 - 0s - loss: 1.2200e-05 - acc: 1.0000
Epoch 425/500
 - 0s - loss: 1.1922e-05 - acc: 1.0000
Epoch 426/500
 - 0s - loss: 1.1877e-05 - acc: 1.0000
Epoch 427/500
 - 0s - loss: 1.2091e-05 - acc: 1.0000
Epoch 428/500
 - 0s - loss: 1.2422e-05 - acc: 1.0000
Epoch 429/500
 - 0s - loss: 1.1598e-05 - acc: 1.0000
Epoch 430/500
 - 0s - loss: 1.2600e-05 - acc: 1.0000
Epoch 431/500
 - 0s - loss: 1.3064e-05 - acc: 1.0000
Epoch 432/500
 - 0s - loss: 1.1102e-05 - acc: 1.0000
Epoch 433/500
 - 0s - loss: 1.2005e-05 - acc: 1.0000
Epoch 434/500
 - 0s - loss: 1.1320e-05 - acc: 1.0000
Epoch 435/500
 - 0s - loss: 1.1222e-05 - acc: 1.0000
Epoch 436/500
 - 0s - loss: 1.1171e-05 - acc: 1.0000
Epoch 437/500
 - 0s - loss: 1.1758e-05 - acc: 1.0000
Epoch 438/500
 - 0s - loss: 1.1848e-05 - acc: 1.0000
Epoch 439/500
 - 0s - loss: 1.1252e-05 - acc: 1.0000
Epoch 440/500
 - 0s - loss: 1.1564e-05 - acc: 1.0000
Epoch 441/500
 - 0s - loss: 1.1120e-05 - acc: 1.0000
Epoch 442/500
 - 0s - loss: 1.0923e-05 - acc: 1.0000
Epoch 443/500
 - 0s - loss: 1.0395e-05 - acc: 1.0000
Epoch 444/500
 - 0s - loss: 1.0488e-05 - acc: 1.0000
Epoch 445/500
 - 0s - loss: 1.0472e-05 - acc: 1.0000
Epoch 446/500
 - 0s - loss: 1.0543e-05 - acc: 1.0000
Epoch 447/500
 - 0s - loss: 1.0201e-05 - acc: 1.0000
Epoch 448/500
 - 0s - loss: 1.0088e-05 - acc: 1.0000
Epoch 449/500
 - 0s - loss: 1.0314e-05 - acc: 1.0000
Epoch 450/500
 - 0s - loss: 1.1080e-05 - acc: 1.0000
Epoch 451/500
 - 0s - loss: 9.8603e-06 - acc: 1.0000
Epoch 452/500
 - 0s - loss: 1.0302e-05 - acc: 1.0000
Epoch 453/500
 - 0s - loss: 9.8093e-06 - acc: 1.0000
Epoch 454/500
 - 0s - loss: 9.9676e-06 - acc: 1.0000
Epoch 455/500
 - 0s - loss: 9.8044e-06 - acc: 1.0000
Epoch 456/500
 - 0s - loss: 9.9387e-06 - acc: 1.0000
Epoch 457/500
 - 0s - loss: 9.5279e-06 - acc: 1.0000
Epoch 458/500
 - 0s - loss: 9.3775e-06 - acc: 1.0000
Epoch 459/500
 - 0s - loss: 9.2989e-06 - acc: 1.0000
Epoch 460/500
 - 0s - loss: 9.6574e-06 - acc: 1.0000
Epoch 461/500
 - 0s - loss: 8.9887e-06 - acc: 1.0000
Epoch 462/500
 - 0s - loss: 9.7729e-06 - acc: 1.0000
Epoch 463/500
 - 0s - loss: 1.0271e-05 - acc: 1.0000
Epoch 464/500
 - 0s - loss: 9.5909e-06 - acc: 1.0000
Epoch 465/500
 - 0s - loss: 9.2086e-06 - acc: 1.0000
Epoch 466/500
 - 0s - loss: 9.1528e-06 - acc: 1.0000
Epoch 467/500
 - 0s - loss: 9.2935e-06 - acc: 1.0000

Epoch 468/500
 - 0s - loss: 9.1589e-06 - acc: 1.0000
Epoch 469/500
 - 0s - loss: 8.8647e-06 - acc: 1.0000
Epoch 470/500
 - 0s - loss: 9.2280e-06 - acc: 1.0000
Epoch 471/500
 - 0s - loss: 9.8828e-06 - acc: 1.0000
Epoch 472/500
 - 0s - loss: 8.8705e-06 - acc: 1.0000
Epoch 473/500
 - 0s - loss: 9.0764e-06 - acc: 1.0000
Epoch 474/500
 - 0s - loss: 8.4501e-06 - acc: 1.0000
Epoch 475/500
 - 0s - loss: 8.9586e-06 - acc: 1.0000
Epoch 476/500
 - 0s - loss: 8.4722e-06 - acc: 1.0000
Epoch 477/500
 - 0s - loss: 8.5668e-06 - acc: 1.0000
Epoch 478/500
 - 0s - loss: 9.3265e-06 - acc: 1.0000
Epoch 479/500
 - 0s - loss: 9.2104e-06 - acc: 1.0000
Epoch 480/500
 - 0s - loss: 8.2852e-06 - acc: 1.0000
Epoch 481/500
 - 0s - loss: 8.3367e-06 - acc: 1.0000
Epoch 482/500
 - 0s - loss: 7.9568e-06 - acc: 1.0000
Epoch 483/500
 - 0s - loss: 8.1753e-06 - acc: 1.0000
Epoch 484/500
 - 0s - loss: 9.3137e-06 - acc: 1.0000
Epoch 485/500
 - 0s - loss: 8.1995e-06 - acc: 1.0000
Epoch 486/500
 - 0s - loss: 8.0345e-06 - acc: 1.0000
Epoch 487/500
 - 0s - loss: 7.9054e-06 - acc: 1.0000
Epoch 488/500
 - 0s - loss: 8.3308e-06 - acc: 1.0000
Epoch 489/500
 - 0s - loss: 7.7305e-06 - acc: 1.0000
Epoch 490/500
 - 0s - loss: 7.6679e-06 - acc: 1.0000
Epoch 491/500
 - 0s - loss: 7.6483e-06 - acc: 1.0000
Epoch 492/500
 - 0s - loss: 7.5010e-06 - acc: 1.0000
Epoch 493/500
 - 0s - loss: 7.3724e-06 - acc: 1.0000
Epoch 494/500
 - 0s - loss: 7.3682e-06 - acc: 1.0000
Epoch 495/500
 - 0s - loss: 7.4687e-06 - acc: 1.0000
Epoch 496/500
 - 0s - loss: 7.1374e-06 - acc: 1.0000
Epoch 497/500
 - 0s - loss: 7.8790e-06 - acc: 1.0000
Epoch 498/500
 - 0s - loss: 7.5520e-06 - acc: 1.0000
Epoch 499/500
 - 0s - loss: 7.0766e-06 - acc: 1.0000
Epoch 500/500
 - 0s - loss: 7.1643e-06 - acc: 1.0000

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 0.4909 - acc: 0.9569
Normal Neural Network - Loss: 0.4909485536145753, Accuracy: 0.9568965435028076

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Certified' 'Certified' 'Certified' 'Certified' 'Certified'
 'Certified' 'Certified' 'Certified' 'Certified']
Actual Labels: ['Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified']