In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'SRI LANKA']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

SRI LANKA    463
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    445
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [8]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [9]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [10]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
713,Certified,436,77381,TEXAS,0.0,27851.0,SRI LANKA,A-3,None,7.0
1204,Certified,192,20850,MARYLAND,20.0,41205.0,SRI LANKA,H-1B,Bachelor's,1.0
1206,Certified,189,30338,GEORGIA,800.0,144331.0,SRI LANKA,Not in USA,Master's,12.0
2144,Certified,168,64117,MISSOURI,15000.0,60258.0,SRI LANKA,H-1B,Master's,11.0
2931,Certified,521,94043,CALIFORNIA,53861.0,95000.0,SRI LANKA,H-1B,Bachelor's,12.0

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

CALIFORNIA              99
NEW YORK                45
MASSACHUSETTS           35
TEXAS                   35
MARYLAND                25
ILLINOIS                22
NEW JERSEY              19
FLORIDA                 14
DISTRICT OF COLUMBIA    13
GEORGIA                 12
VIRGINIA                12
PENNSYLVANIA            11
OHIO                    10
WASHINGTON               9
MICHIGAN                 7
INDIANA                  7
NORTH CAROLINA           6
KANSAS                   6
CONNECTICUT              6
MINNESOTA                6
COLORADO                 5
MISSOURI                 5
ARKANSAS                 3
WISCONSIN                3
OKLAHOMA                 3
OREGON                   3
IOWA                     3
LOUISIANA                2
UTAH                     2
ALABAMA                  2
NORTH DAKOTA             2
RHODE ISLAND             2
KENTUCKY                 2
ARIZONA                  2
DELAWARE                 2
MAINE                    1
GUAM                     1
MONTANA                  1
WYOMING                  1
VERMONT                  1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
713,Certified,436,77381,TEXAS,0.0,27851.0,SRI LANKA,A-3,None,7.0,TEXAS
1204,Certified,192,20850,MARYLAND,20.0,41205.0,SRI LANKA,H-1B,Bachelor's,1.0,MARYLAND
1206,Certified,189,30338,GEORGIA,800.0,144331.0,SRI LANKA,Not in USA,Master's,12.0,GEORGIA
2144,Certified,168,64117,MISSOURI,15000.0,60258.0,SRI LANKA,H-1B,Master's,11.0,MISSOURI
2931,Certified,521,94043,CALIFORNIA,53861.0,95000.0,SRI LANKA,H-1B,Bachelor's,12.0,CALIFORNIA

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

SOUTH        119
WEST         115
NORTHEAST    110
MIDWEST       68
OTHER          1
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      413
DECISION_ELAPSED_DAYS            413
EMPLOYER_POSTAL_CODE             413
EMPLOYER_STATE                   413
EMPLOYER_NUM_EMPLOYEES           413
WAGE_OFFER_FROM_9089             413
COUNTRY_OF_CITIZENSHIP           413
CLASS_OF_ADMISSION               413
FOREIGN_WORKER_INFO_EDUCATION    413
CASE_RECEIVED_DATE_MONTH         413
EMPLOYER_STATES                  413
EMPLOYER_REGIONS                 413
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      151
0-90        117
181-365      96
366-3600     49
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

75001-100000     119
100000-500000    106
50001-75000      102
25001-50000       58
0-25000           28
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

0-50                132
1001-10000          101
10001-1000000000     77
101-500              60
501-1000             27
51-100               15
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      413
DECISION_ELAPSED_DAYS            413
EMPLOYER_POSTAL_CODE             413
EMPLOYER_STATE                   413
EMPLOYER_NUM_EMPLOYEES           413
WAGE_OFFER_FROM_9089             413
COUNTRY_OF_CITIZENSHIP           413
CLASS_OF_ADMISSION               413
FOREIGN_WORKER_INFO_EDUCATION    413
CASE_RECEIVED_DATE_MONTH         413
EMPLOYER_STATES                  413
EMPLOYER_REGIONS                 413
DAY_BINS                         413
WAGE_BINS                        413
EMPLOYEE_BINS                    412
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
713,Certified,NaN,25001-50000,SOUTH,7.0,None,A-3,366-3600
1204,Certified,0-50,25001-50000,SOUTH,1.0,Bachelor's,H-1B,181-365
1206,Certified,501-1000,100000-500000,SOUTH,12.0,Master's,Not in USA,181-365
2144,Certified,10001-1000000000,50001-75000,MIDWEST,11.0,Master's,H-1B,91-180
2931,Certified,10001-1000000000,75001-100000,WEST,12.0,Bachelor's,H-1B,366-3600

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
713,Certified,nan,25001-50000,SOUTH,7.0,None,A-3,366-3600,0,5,2,3,2,6
1204,Certified,0-50,25001-50000,SOUTH,1.0,Bachelor's,H-1B,181-365,9,1,2,3,1,0
1206,Certified,501-1000,100000-500000,SOUTH,12.0,Master's,Not in USA,181-365,14,4,1,3,1,4
2144,Certified,10001-1000000000,50001-75000,MIDWEST,11.0,Master's,H-1B,91-180,9,4,3,0,3,1
2931,Certified,10001-1000000000,75001-100000,WEST,12.0,Bachelor's,H-1B,366-3600,9,1,4,4,2,1

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           413
EMPLOYEE_BINS                         413
WAGE_BINS                             413
EMPLOYER_REGIONS                      413
CASE_RECEIVED_DATE_MONTH              413
FOREIGN_WORKER_INFO_EDUCATION         413
CLASS_OF_ADMISSION                    413
DAY_BINS                              413
CLASS_OF_ADMISSION_CODE               413
FOREIGN_WORKER_INFO_EDUCATION_CODE    413
WAGE_BINS_CODE                        413
EMPLOYER_REGIONS_CODE                 413
DAY_BINS_CODE                         413
EMPLOYEE_BINS_CODE                    413
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
713,Certified,6,2,2,5,0,7.0,3
1204,Certified,0,2,1,1,9,1.0,3
1206,Certified,4,1,1,4,14,12.0,3
2144,Certified,1,3,3,4,9,11.0,0
2931,Certified,1,4,2,1,9,12.0,4

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int32
WAGE_BINS_CODE                          int32
DAY_BINS_CODE                           int32
FOREIGN_WORKER_INFO_EDUCATION_CODE      int32
CLASS_OF_ADMISSION_CODE                 int32
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int32
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(413, 7) (413,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int32, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [53]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 1s - loss: 0.5043 - acc: 0.8932
Epoch 2/500
 - 0s - loss: 0.3399 - acc: 0.8964
Epoch 3/500
 - 0s - loss: 0.3393 - acc: 0.8964
Epoch 4/500
 - 0s - loss: 0.3354 - acc: 0.8964
Epoch 5/500
 - 0s - loss: 0.3242 - acc: 0.8964
Epoch 6/500
 - 0s - loss: 0.3212 - acc: 0.8964
Epoch 7/500
 - 0s - loss: 0.3163 - acc: 0.8964
Epoch 8/500
 - 0s - loss: 0.3122 - acc: 0.8964
Epoch 9/500
 - 0s - loss: 0.3079 - acc: 0.8964
Epoch 10/500
 - 0s - loss: 0.3025 - acc: 0.8964
Epoch 11/500
 - 0s - loss: 0.2979 - acc: 0.8964
Epoch 12/500
 - 0s - loss: 0.2953 - acc: 0.8964
Epoch 13/500
 - 0s - loss: 0.2906 - acc: 0.8964
Epoch 14/500
 - 0s - loss: 0.2860 - acc: 0.8964
Epoch 15/500
 - 0s - loss: 0.2809 - acc: 0.8964
Epoch 16/500
 - 0s - loss: 0.2780 - acc: 0.8964
Epoch 17/500
 - 0s - loss: 0.2742 - acc: 0.8964
Epoch 18/500
 - 0s - loss: 0.2720 - acc: 0.8964
Epoch 19/500
 - 0s - loss: 0.2659 - acc: 0.8964
Epoch 20/500
 - 0s - loss: 0.2623 - acc: 0.8964
Epoch 21/500
 - 0s - loss: 0.2594 - acc: 0.8964
Epoch 22/500
 - 0s - loss: 0.2562 - acc: 0.8964
Epoch 23/500
 - 0s - loss: 0.2540 - acc: 0.8964
Epoch 24/500
 - 0s - loss: 0.2491 - acc: 0.8964
Epoch 25/500
 - 0s - loss: 0.2481 - acc: 0.8964
Epoch 26/500
 - 0s - loss: 0.2433 - acc: 0.8964
Epoch 27/500
 - 0s - loss: 0.2417 - acc: 0.8964
Epoch 28/500
 - 0s - loss: 0.2365 - acc: 0.8964
Epoch 29/500
 - 0s - loss: 0.2346 - acc: 0.9061
Epoch 30/500
 - 0s - loss: 0.2324 - acc: 0.8964
Epoch 31/500
 - 0s - loss: 0.2280 - acc: 0.8997
Epoch 32/500
 - 0s - loss: 0.2291 - acc: 0.9061
Epoch 33/500
 - 0s - loss: 0.2224 - acc: 0.9094
Epoch 34/500
 - 0s - loss: 0.2228 - acc: 0.9061
Epoch 35/500
 - 0s - loss: 0.2192 - acc: 0.9061
Epoch 36/500
 - 0s - loss: 0.2168 - acc: 0.9094
Epoch 37/500
 - 0s - loss: 0.2172 - acc: 0.9061
Epoch 38/500
 - 0s - loss: 0.2106 - acc: 0.9126
Epoch 39/500
 - 0s - loss: 0.2101 - acc: 0.9126
Epoch 40/500
 - 0s - loss: 0.2069 - acc: 0.9126
Epoch 41/500
 - 0s - loss: 0.2094 - acc: 0.9126
Epoch 42/500
 - 0s - loss: 0.2068 - acc: 0.9191
Epoch 43/500
 - 0s - loss: 0.2055 - acc: 0.9191
Epoch 44/500
 - 0s - loss: 0.2027 - acc: 0.9191
Epoch 45/500
 - 0s - loss: 0.2006 - acc: 0.9094
Epoch 46/500
 - 0s - loss: 0.1950 - acc: 0.9159
Epoch 47/500
 - 0s - loss: 0.1940 - acc: 0.9223
Epoch 48/500
 - 0s - loss: 0.1904 - acc: 0.9223
Epoch 49/500
 - 0s - loss: 0.1892 - acc: 0.9256
Epoch 50/500
 - 0s - loss: 0.1889 - acc: 0.9223
Epoch 51/500
 - 0s - loss: 0.1882 - acc: 0.9256
Epoch 52/500
 - 0s - loss: 0.1797 - acc: 0.9353
Epoch 53/500
 - 0s - loss: 0.1797 - acc: 0.9256
Epoch 54/500
 - 0s - loss: 0.1824 - acc: 0.9223
Epoch 55/500
 - 0s - loss: 0.1773 - acc: 0.9256
Epoch 56/500
 - 0s - loss: 0.1722 - acc: 0.9353
Epoch 57/500
 - 0s - loss: 0.1715 - acc: 0.9385
Epoch 58/500
 - 0s - loss: 0.1755 - acc: 0.9385
Epoch 59/500
 - 0s - loss: 0.1672 - acc: 0.9320
Epoch 60/500
 - 0s - loss: 0.1672 - acc: 0.9320
Epoch 61/500
 - 0s - loss: 0.1740 - acc: 0.9353
Epoch 62/500
 - 0s - loss: 0.1796 - acc: 0.9256
Epoch 63/500
 - 0s - loss: 0.1701 - acc: 0.9417
Epoch 64/500
 - 0s - loss: 0.1627 - acc: 0.9320
Epoch 65/500
 - 0s - loss: 0.1607 - acc: 0.9385
Epoch 66/500
 - 0s - loss: 0.1576 - acc: 0.9353
Epoch 67/500
 - 0s - loss: 0.1576 - acc: 0.9385
Epoch 68/500
 - 0s - loss: 0.1563 - acc: 0.9320
Epoch 69/500
 - 0s - loss: 0.1529 - acc: 0.9515
Epoch 70/500
 - 0s - loss: 0.1503 - acc: 0.9385
Epoch 71/500
 - 0s - loss: 0.1452 - acc: 0.9450
Epoch 72/500
 - 0s - loss: 0.1445 - acc: 0.9547
Epoch 73/500
 - 0s - loss: 0.1462 - acc: 0.9515
Epoch 74/500
 - 0s - loss: 0.1390 - acc: 0.9515
Epoch 75/500
 - 0s - loss: 0.1376 - acc: 0.9450
Epoch 76/500
 - 0s - loss: 0.1375 - acc: 0.9450
Epoch 77/500
 - 0s - loss: 0.1348 - acc: 0.9547
Epoch 78/500
 - 0s - loss: 0.1334 - acc: 0.9547
Epoch 79/500
 - 0s - loss: 0.1311 - acc: 0.9482
Epoch 80/500
 - 0s - loss: 0.1333 - acc: 0.9644
Epoch 81/500
 - 0s - loss: 0.1321 - acc: 0.9450
Epoch 82/500
 - 0s - loss: 0.1310 - acc: 0.9515
Epoch 83/500
 - 0s - loss: 0.1267 - acc: 0.9547
Epoch 84/500
 - 0s - loss: 0.1258 - acc: 0.9612
Epoch 85/500
 - 0s - loss: 0.1197 - acc: 0.9612
Epoch 86/500
 - 0s - loss: 0.1202 - acc: 0.9515
Epoch 87/500
 - 0s - loss: 0.1260 - acc: 0.9579
Epoch 88/500
 - 0s - loss: 0.1241 - acc: 0.9515
Epoch 89/500
 - 0s - loss: 0.1180 - acc: 0.9676
Epoch 90/500
 - 0s - loss: 0.1234 - acc: 0.9450
Epoch 91/500
 - 0s - loss: 0.1146 - acc: 0.9676
Epoch 92/500
 - 0s - loss: 0.1165 - acc: 0.9482
Epoch 93/500
 - 0s - loss: 0.1094 - acc: 0.9676
Epoch 94/500
 - 0s - loss: 0.1105 - acc: 0.9612
Epoch 95/500
 - 0s - loss: 0.1082 - acc: 0.9676
Epoch 96/500
 - 0s - loss: 0.1085 - acc: 0.9547
Epoch 97/500
 - 0s - loss: 0.1047 - acc: 0.9709
Epoch 98/500
 - 0s - loss: 0.1038 - acc: 0.9612
Epoch 99/500
 - 0s - loss: 0.1026 - acc: 0.9644
Epoch 100/500
 - 0s - loss: 0.1030 - acc: 0.9515
Epoch 101/500
 - 0s - loss: 0.0966 - acc: 0.9709
Epoch 102/500
 - 0s - loss: 0.0985 - acc: 0.9644
Epoch 103/500
 - 0s - loss: 0.0960 - acc: 0.9612
Epoch 104/500
 - 0s - loss: 0.0997 - acc: 0.9741
Epoch 105/500
 - 0s - loss: 0.0934 - acc: 0.9612
Epoch 106/500
 - 0s - loss: 0.0934 - acc: 0.9741
Epoch 107/500
 - 0s - loss: 0.0923 - acc: 0.9676
Epoch 108/500
 - 0s - loss: 0.0890 - acc: 0.9709
Epoch 109/500
 - 0s - loss: 0.0914 - acc: 0.9644
Epoch 110/500
 - 0s - loss: 0.0882 - acc: 0.9806
Epoch 111/500
 - 0s - loss: 0.0950 - acc: 0.9547
Epoch 112/500
 - 0s - loss: 0.0872 - acc: 0.9838
Epoch 113/500
 - 0s - loss: 0.0860 - acc: 0.9741
Epoch 114/500
 - 0s - loss: 0.0863 - acc: 0.9806
Epoch 115/500
 - 0s - loss: 0.0853 - acc: 0.9709
Epoch 116/500
 - 0s - loss: 0.0806 - acc: 0.9773
Epoch 117/500
 - 0s - loss: 0.0785 - acc: 0.9773
Epoch 118/500
 - 0s - loss: 0.0782 - acc: 0.9741
Epoch 119/500
 - 0s - loss: 0.0740 - acc: 0.9838
Epoch 120/500
 - 0s - loss: 0.0768 - acc: 0.9871
Epoch 121/500
 - 0s - loss: 0.0762 - acc: 0.9676
Epoch 122/500
 - 0s - loss: 0.0738 - acc: 0.9838
Epoch 123/500
 - 0s - loss: 0.0721 - acc: 0.9741
Epoch 124/500
 - 0s - loss: 0.0698 - acc: 0.9838
Epoch 125/500
 - 0s - loss: 0.0702 - acc: 0.9838
Epoch 126/500
 - 0s - loss: 0.0720 - acc: 0.9806
Epoch 127/500
 - 0s - loss: 0.0801 - acc: 0.9773
Epoch 128/500
 - 0s - loss: 0.0696 - acc: 0.9806
Epoch 129/500
 - 0s - loss: 0.0673 - acc: 0.9838
Epoch 130/500
 - 0s - loss: 0.0676 - acc: 0.9838
Epoch 131/500
 - 0s - loss: 0.0664 - acc: 0.9871
Epoch 132/500
 - 0s - loss: 0.0647 - acc: 0.9806
Epoch 133/500
 - 0s - loss: 0.0646 - acc: 0.9773
Epoch 134/500
 - 0s - loss: 0.0604 - acc: 0.9903
Epoch 135/500
 - 0s - loss: 0.0586 - acc: 0.9871
Epoch 136/500
 - 0s - loss: 0.0567 - acc: 0.9903
Epoch 137/500
 - 0s - loss: 0.0593 - acc: 0.9871
Epoch 138/500
 - 0s - loss: 0.0601 - acc: 0.9838
Epoch 139/500
 - 0s - loss: 0.0540 - acc: 0.9903
Epoch 140/500
 - 0s - loss: 0.0540 - acc: 0.9903
Epoch 141/500
 - 0s - loss: 0.0562 - acc: 0.9903
Epoch 142/500
 - 0s - loss: 0.0556 - acc: 0.9871
Epoch 143/500
 - 0s - loss: 0.0543 - acc: 0.9903
Epoch 144/500
 - 0s - loss: 0.0515 - acc: 0.9903
Epoch 145/500
 - 0s - loss: 0.0509 - acc: 0.9935
Epoch 146/500
 - 0s - loss: 0.0490 - acc: 0.9935
Epoch 147/500
 - 0s - loss: 0.0485 - acc: 0.9903
Epoch 148/500
 - 0s - loss: 0.0499 - acc: 0.9871
Epoch 149/500
 - 0s - loss: 0.0493 - acc: 0.9871
Epoch 150/500
 - 0s - loss: 0.0485 - acc: 0.9903
Epoch 151/500
 - 0s - loss: 0.0457 - acc: 0.9903
Epoch 152/500
 - 0s - loss: 0.0461 - acc: 0.9935
Epoch 153/500
 - 0s - loss: 0.0460 - acc: 0.9903
Epoch 154/500
 - 0s - loss: 0.0475 - acc: 0.9903
Epoch 155/500
 - 0s - loss: 0.0427 - acc: 0.9968
Epoch 156/500
 - 0s - loss: 0.0452 - acc: 0.9903
Epoch 157/500
 - 0s - loss: 0.0421 - acc: 0.9935
Epoch 158/500
 - 0s - loss: 0.0412 - acc: 0.9968
Epoch 159/500
 - 0s - loss: 0.0426 - acc: 0.9935
Epoch 160/500
 - 0s - loss: 0.0402 - acc: 0.9903
Epoch 161/500
 - 0s - loss: 0.0413 - acc: 0.9968
Epoch 162/500
 - 0s - loss: 0.0396 - acc: 0.9968
Epoch 163/500
 - 0s - loss: 0.0402 - acc: 0.9935
Epoch 164/500
 - 0s - loss: 0.0394 - acc: 0.9968

Epoch 165/500
 - 0s - loss: 0.0415 - acc: 0.9903
Epoch 166/500
 - 0s - loss: 0.0382 - acc: 0.9935
Epoch 167/500
 - 0s - loss: 0.0383 - acc: 0.9935
Epoch 168/500
 - 0s - loss: 0.0355 - acc: 0.9968
Epoch 169/500
 - 0s - loss: 0.0380 - acc: 0.9968
Epoch 170/500
 - 0s - loss: 0.0341 - acc: 0.9968
Epoch 171/500
 - 0s - loss: 0.0378 - acc: 0.9935
Epoch 172/500
 - 0s - loss: 0.0388 - acc: 0.9871
Epoch 173/500
 - 0s - loss: 0.0352 - acc: 0.9935
Epoch 174/500
 - 0s - loss: 0.0361 - acc: 0.9968
Epoch 175/500
 - 0s - loss: 0.0318 - acc: 0.9968
Epoch 176/500
 - 0s - loss: 0.0314 - acc: 0.9968
Epoch 177/500
 - 0s - loss: 0.0320 - acc: 0.9968
Epoch 178/500
 - 0s - loss: 0.0300 - acc: 0.9968
Epoch 179/500
 - 0s - loss: 0.0305 - acc: 0.9968
Epoch 180/500
 - 0s - loss: 0.0286 - acc: 0.9968
Epoch 181/500
 - 0s - loss: 0.0290 - acc: 0.9968
Epoch 182/500
 - 0s - loss: 0.0305 - acc: 0.9968
Epoch 183/500
 - 0s - loss: 0.0290 - acc: 0.9968
Epoch 184/500
 - 0s - loss: 0.0296 - acc: 0.9968
Epoch 185/500
 - 0s - loss: 0.0275 - acc: 0.9968
Epoch 186/500
 - 0s - loss: 0.0266 - acc: 0.9968
Epoch 187/500
 - 0s - loss: 0.0261 - acc: 0.9968
Epoch 188/500
 - 0s - loss: 0.0262 - acc: 0.9968
Epoch 189/500
 - 0s - loss: 0.0267 - acc: 0.9968
Epoch 190/500
 - 0s - loss: 0.0266 - acc: 0.9968
Epoch 191/500
 - 0s - loss: 0.0260 - acc: 0.9968
Epoch 192/500
 - 0s - loss: 0.0243 - acc: 0.9968
Epoch 193/500
 - 0s - loss: 0.0239 - acc: 0.9968
Epoch 194/500
 - 0s - loss: 0.0246 - acc: 0.9968
Epoch 195/500
 - 0s - loss: 0.0250 - acc: 0.9968
Epoch 196/500
 - 0s - loss: 0.0254 - acc: 0.9968
Epoch 197/500
 - 0s - loss: 0.0245 - acc: 0.9968
Epoch 198/500
 - 0s - loss: 0.0235 - acc: 0.9968
Epoch 199/500
 - 0s - loss: 0.0230 - acc: 0.9968
Epoch 200/500
 - 0s - loss: 0.0218 - acc: 0.9968
Epoch 201/500
 - 0s - loss: 0.0225 - acc: 0.9968
Epoch 202/500
 - 0s - loss: 0.0240 - acc: 0.9935
Epoch 203/500
 - 0s - loss: 0.0225 - acc: 0.9968
Epoch 204/500
 - 0s - loss: 0.0236 - acc: 0.9968
Epoch 205/500
 - 0s - loss: 0.0217 - acc: 0.9968
Epoch 206/500
 - 0s - loss: 0.0214 - acc: 0.9935
Epoch 207/500
 - 0s - loss: 0.0202 - acc: 0.9968
Epoch 208/500
 - 0s - loss: 0.0212 - acc: 0.9968
Epoch 209/500
 - 0s - loss: 0.0193 - acc: 0.9968
Epoch 210/500
 - 0s - loss: 0.0213 - acc: 0.9968
Epoch 211/500
 - 0s - loss: 0.0242 - acc: 0.9968
Epoch 212/500
 - 0s - loss: 0.0210 - acc: 0.9968
Epoch 213/500
 - 0s - loss: 0.0190 - acc: 0.9935
Epoch 214/500
 - 0s - loss: 0.0191 - acc: 0.9968
Epoch 215/500
 - 0s - loss: 0.0243 - acc: 0.9935
Epoch 216/500
 - 0s - loss: 0.0247 - acc: 0.9968
Epoch 217/500
 - 0s - loss: 0.0201 - acc: 0.9935
Epoch 218/500
 - 0s - loss: 0.0192 - acc: 0.9968
Epoch 219/500
 - 0s - loss: 0.0189 - acc: 0.9968
Epoch 220/500
 - 0s - loss: 0.0183 - acc: 0.9968
Epoch 221/500
 - 0s - loss: 0.0169 - acc: 0.9968
Epoch 222/500
 - 0s - loss: 0.0176 - acc: 0.9968
Epoch 223/500
 - 0s - loss: 0.0171 - acc: 0.9968
Epoch 224/500
 - 0s - loss: 0.0181 - acc: 0.9968
Epoch 225/500
 - 0s - loss: 0.0183 - acc: 0.9935
Epoch 226/500
 - 0s - loss: 0.0170 - acc: 0.9968
Epoch 227/500
 - 0s - loss: 0.0167 - acc: 0.9935
Epoch 228/500
 - 0s - loss: 0.0168 - acc: 0.9935
Epoch 229/500
 - 0s - loss: 0.0168 - acc: 0.9935
Epoch 230/500
 - 0s - loss: 0.0158 - acc: 0.9935
Epoch 231/500
 - 0s - loss: 0.0156 - acc: 0.9935
Epoch 232/500
 - 0s - loss: 0.0160 - acc: 0.9968
Epoch 233/500
 - 0s - loss: 0.0159 - acc: 0.9935
Epoch 234/500
 - 0s - loss: 0.0154 - acc: 0.9968
Epoch 235/500
 - 0s - loss: 0.0183 - acc: 0.9935
Epoch 236/500
 - 0s - loss: 0.0166 - acc: 0.9968
Epoch 237/500
 - 0s - loss: 0.0148 - acc: 0.9968
Epoch 238/500
 - 0s - loss: 0.0155 - acc: 0.9935
Epoch 239/500
 - 0s - loss: 0.0139 - acc: 0.9968
Epoch 240/500
 - 0s - loss: 0.0151 - acc: 0.9935
Epoch 241/500
 - 0s - loss: 0.0149 - acc: 0.9968
Epoch 242/500
 - 0s - loss: 0.0138 - acc: 0.9968
Epoch 243/500
 - 0s - loss: 0.0133 - acc: 0.9968
Epoch 244/500
 - 0s - loss: 0.0145 - acc: 0.9968
Epoch 245/500
 - 0s - loss: 0.0147 - acc: 0.9968
Epoch 246/500
 - 0s - loss: 0.0131 - acc: 0.9968
Epoch 247/500
 - 0s - loss: 0.0137 - acc: 0.9968
Epoch 248/500
 - 0s - loss: 0.0135 - acc: 0.9968
Epoch 249/500
 - 0s - loss: 0.0131 - acc: 0.9935
Epoch 250/500
 - 0s - loss: 0.0137 - acc: 0.9968
Epoch 251/500
 - 0s - loss: 0.0136 - acc: 0.9968
Epoch 252/500
 - 0s - loss: 0.0142 - acc: 0.9968
Epoch 253/500
 - 0s - loss: 0.0151 - acc: 0.9968
Epoch 254/500
 - 0s - loss: 0.0143 - acc: 0.9968
Epoch 255/500
 - 0s - loss: 0.0161 - acc: 0.9968
Epoch 256/500
 - 0s - loss: 0.0185 - acc: 0.9968
Epoch 257/500
 - 0s - loss: 0.0154 - acc: 0.9935
Epoch 258/500
 - 0s - loss: 0.0136 - acc: 0.9968
Epoch 259/500
 - 0s - loss: 0.0120 - acc: 0.9968
Epoch 260/500
 - 0s - loss: 0.0142 - acc: 0.9968
Epoch 261/500
 - 0s - loss: 0.0135 - acc: 0.9968
Epoch 262/500
 - 0s - loss: 0.0142 - acc: 0.9968
Epoch 263/500
 - 0s - loss: 0.0117 - acc: 0.9968
Epoch 264/500
 - 0s - loss: 0.0117 - acc: 0.9968
Epoch 265/500
 - 0s - loss: 0.0141 - acc: 0.9968
Epoch 266/500
 - 0s - loss: 0.0162 - acc: 0.9935
Epoch 267/500
 - 0s - loss: 0.0149 - acc: 0.9935
Epoch 268/500
 - 0s - loss: 0.0140 - acc: 0.9935
Epoch 269/500
 - 0s - loss: 0.0147 - acc: 0.9968
Epoch 270/500
 - 0s - loss: 0.0156 - acc: 0.9935
Epoch 271/500
 - 0s - loss: 0.0126 - acc: 0.9935
Epoch 272/500
 - 0s - loss: 0.0112 - acc: 0.9968
Epoch 273/500
 - 0s - loss: 0.0107 - acc: 0.9968
Epoch 274/500
 - 0s - loss: 0.0108 - acc: 0.9968
Epoch 275/500
 - 0s - loss: 0.0114 - acc: 0.9968
Epoch 276/500
 - 0s - loss: 0.0104 - acc: 0.9968
Epoch 277/500
 - 0s - loss: 0.0102 - acc: 0.9968
Epoch 278/500
 - 0s - loss: 0.0102 - acc: 0.9935
Epoch 279/500
 - 0s - loss: 0.0109 - acc: 0.9968
Epoch 280/500
 - 0s - loss: 0.0126 - acc: 0.9968
Epoch 281/500
 - 0s - loss: 0.0116 - acc: 0.9968
Epoch 282/500
 - 0s - loss: 0.0114 - acc: 0.9968
Epoch 283/500
 - 0s - loss: 0.0119 - acc: 0.9935
Epoch 284/500
 - 0s - loss: 0.0118 - acc: 0.9935
Epoch 285/500
 - 0s - loss: 0.0125 - acc: 0.9935
Epoch 286/500
 - 0s - loss: 0.0110 - acc: 0.9968
Epoch 287/500
 - 0s - loss: 0.0099 - acc: 0.9935
Epoch 288/500
 - 0s - loss: 0.0095 - acc: 0.9968
Epoch 289/500
 - 0s - loss: 0.0090 - acc: 0.9968
Epoch 290/500
 - 0s - loss: 0.0099 - acc: 0.9968
Epoch 291/500
 - 0s - loss: 0.0091 - acc: 0.9968
Epoch 292/500
 - 0s - loss: 0.0100 - acc: 0.9968
Epoch 293/500
 - 0s - loss: 0.0096 - acc: 0.9935
Epoch 294/500
 - 0s - loss: 0.0102 - acc: 0.9935
Epoch 295/500
 - 0s - loss: 0.0100 - acc: 0.9935
Epoch 296/500
 - 0s - loss: 0.0087 - acc: 0.9968
Epoch 297/500
 - 0s - loss: 0.0105 - acc: 0.9968
Epoch 298/500
 - 0s - loss: 0.0105 - acc: 0.9968
Epoch 299/500
 - 0s - loss: 0.0105 - acc: 0.9935
Epoch 300/500
 - 0s - loss: 0.0096 - acc: 0.9968
Epoch 301/500
 - 0s - loss: 0.0109 - acc: 0.9968
Epoch 302/500
 - 0s - loss: 0.0091 - acc: 0.9935
Epoch 303/500
 - 0s - loss: 0.0089 - acc: 0.9968
Epoch 304/500
 - 0s - loss: 0.0109 - acc: 0.9968
Epoch 305/500
 - 0s - loss: 0.0100 - acc: 0.9935
Epoch 306/500
 - 0s - loss: 0.0089 - acc: 0.9968
Epoch 307/500
 - 0s - loss: 0.0087 - acc: 0.9968
Epoch 308/500
 - 0s - loss: 0.0091 - acc: 0.9935
Epoch 309/500
 - 0s - loss: 0.0097 - acc: 0.9935
Epoch 310/500
 - 0s - loss: 0.0099 - acc: 0.9935
Epoch 311/500
 - 0s - loss: 0.0082 - acc: 0.9968
Epoch 312/500
 - 0s - loss: 0.0087 - acc: 0.9968
Epoch 313/500
 - 0s - loss: 0.0087 - acc: 0.9968
Epoch 314/500
 - 0s - loss: 0.0084 - acc: 0.9968
Epoch 315/500
 - 0s - loss: 0.0087 - acc: 0.9968
Epoch 316/500
 - 0s - loss: 0.0084 - acc: 0.9935
Epoch 317/500
 - 0s - loss: 0.0092 - acc: 0.9968
Epoch 318/500
 - 0s - loss: 0.0083 - acc: 0.9935
Epoch 319/500
 - 0s - loss: 0.0095 - acc: 0.9935
Epoch 320/500
 - 0s - loss: 0.0092 - acc: 0.9968
Epoch 321/500
 - 0s - loss: 0.0156 - acc: 0.9935
Epoch 322/500
 - 0s - loss: 0.0124 - acc: 0.9968
Epoch 323/500
 - 0s - loss: 0.0109 - acc: 0.9935
Epoch 324/500
 - 0s - loss: 0.0099 - acc: 0.9935
Epoch 325/500
 - 0s - loss: 0.0090 - acc: 0.9935
Epoch 326/500
 - 0s - loss: 0.0099 - acc: 0.9968
Epoch 327/500
 - 0s - loss: 0.0095 - acc: 0.9968
Epoch 328/500
 - 0s - loss: 0.0078 - acc: 0.9968
Epoch 329/500
 - 0s - loss: 0.0079 - acc: 0.9935
Epoch 330/500
 - 0s - loss: 0.0085 - acc: 0.9935
Epoch 331/500
 - 0s - loss: 0.0092 - acc: 0.9935
Epoch 332/500

 - 0s - loss: 0.0075 - acc: 0.9968
Epoch 333/500
 - 0s - loss: 0.0082 - acc: 0.9968
Epoch 334/500
 - 0s - loss: 0.0077 - acc: 0.9935
Epoch 335/500
 - 0s - loss: 0.0082 - acc: 0.9935
Epoch 336/500
 - 0s - loss: 0.0086 - acc: 0.9968
Epoch 337/500
 - 0s - loss: 0.0076 - acc: 0.9968
Epoch 338/500
 - 0s - loss: 0.0075 - acc: 0.9968
Epoch 339/500
 - 0s - loss: 0.0086 - acc: 0.9935
Epoch 340/500
 - 0s - loss: 0.0091 - acc: 0.9968
Epoch 341/500
 - 0s - loss: 0.0106 - acc: 0.9935
Epoch 342/500
 - 0s - loss: 0.0116 - acc: 0.9935
Epoch 343/500
 - 0s - loss: 0.0106 - acc: 0.9968
Epoch 344/500
 - 0s - loss: 0.0102 - acc: 0.9968
Epoch 345/500
 - 0s - loss: 0.0080 - acc: 0.9968
Epoch 346/500
 - 0s - loss: 0.0078 - acc: 0.9935
Epoch 347/500
 - 0s - loss: 0.0078 - acc: 0.9968
Epoch 348/500
 - 0s - loss: 0.0090 - acc: 0.9935
Epoch 349/500
 - 0s - loss: 0.0106 - acc: 0.9935
Epoch 350/500
 - 0s - loss: 0.0106 - acc: 0.9935
Epoch 351/500
 - 0s - loss: 0.0099 - acc: 0.9935
Epoch 352/500
 - 0s - loss: 0.0078 - acc: 0.9968
Epoch 353/500
 - 0s - loss: 0.0084 - acc: 0.9968
Epoch 354/500
 - 0s - loss: 0.0083 - acc: 0.9968
Epoch 355/500
 - 0s - loss: 0.0079 - acc: 0.9935
Epoch 356/500
 - 0s - loss: 0.0088 - acc: 0.9935
Epoch 357/500
 - 0s - loss: 0.0069 - acc: 0.9968
Epoch 358/500
 - 0s - loss: 0.0078 - acc: 0.9935
Epoch 359/500
 - 0s - loss: 0.0077 - acc: 0.9968
Epoch 360/500
 - 0s - loss: 0.0072 - acc: 0.9968
Epoch 361/500
 - 0s - loss: 0.0082 - acc: 0.9935
Epoch 362/500
 - 0s - loss: 0.0077 - acc: 0.9935
Epoch 363/500
 - 0s - loss: 0.0091 - acc: 0.9935
Epoch 364/500
 - 0s - loss: 0.0078 - acc: 0.9968
Epoch 365/500
 - 0s - loss: 0.0079 - acc: 0.9968
Epoch 366/500
 - 0s - loss: 0.0076 - acc: 0.9968
Epoch 367/500
 - 0s - loss: 0.0081 - acc: 0.9968
Epoch 368/500
 - 0s - loss: 0.0091 - acc: 0.9935
Epoch 369/500
 - 0s - loss: 0.0094 - acc: 0.9935
Epoch 370/500
 - 0s - loss: 0.0082 - acc: 0.9968
Epoch 371/500
 - 0s - loss: 0.0067 - acc: 0.9935
Epoch 372/500
 - 0s - loss: 0.0071 - acc: 0.9935
Epoch 373/500
 - 0s - loss: 0.0065 - acc: 0.9968
Epoch 374/500
 - 0s - loss: 0.0082 - acc: 0.9935
Epoch 375/500
 - 0s - loss: 0.0070 - acc: 0.9968
Epoch 376/500
 - 0s - loss: 0.0075 - acc: 0.9968
Epoch 377/500
 - 0s - loss: 0.0063 - acc: 0.9968
Epoch 378/500
 - 0s - loss: 0.0083 - acc: 0.9935
Epoch 379/500
 - 0s - loss: 0.0094 - acc: 0.9935
Epoch 380/500
 - 0s - loss: 0.0071 - acc: 0.9968
Epoch 381/500
 - 0s - loss: 0.0076 - acc: 0.9968
Epoch 382/500
 - 0s - loss: 0.0073 - acc: 0.9935
Epoch 383/500
 - 0s - loss: 0.0073 - acc: 0.9935
Epoch 384/500
 - 0s - loss: 0.0084 - acc: 0.9968
Epoch 385/500
 - 0s - loss: 0.0116 - acc: 0.9935
Epoch 386/500
 - 0s - loss: 0.0065 - acc: 0.9968
Epoch 387/500
 - 0s - loss: 0.0068 - acc: 0.9968
Epoch 388/500
 - 0s - loss: 0.0074 - acc: 0.9968
Epoch 389/500
 - 0s - loss: 0.0079 - acc: 0.9968
Epoch 390/500
 - 0s - loss: 0.0065 - acc: 0.9968
Epoch 391/500
 - 0s - loss: 0.0083 - acc: 0.9968
Epoch 392/500
 - 0s - loss: 0.0072 - acc: 0.9935
Epoch 393/500
 - 0s - loss: 0.0083 - acc: 0.9968
Epoch 394/500
 - 0s - loss: 0.0065 - acc: 0.9968
Epoch 395/500
 - 0s - loss: 0.0072 - acc: 0.9968
Epoch 396/500
 - 0s - loss: 0.0081 - acc: 0.9968
Epoch 397/500
 - 0s - loss: 0.0068 - acc: 0.9968
Epoch 398/500
 - 0s - loss: 0.0079 - acc: 0.9968
Epoch 399/500
 - 0s - loss: 0.0085 - acc: 0.9968
Epoch 400/500
 - 0s - loss: 0.0108 - acc: 0.9935
Epoch 401/500
 - 0s - loss: 0.0058 - acc: 0.9968
Epoch 402/500
 - 0s - loss: 0.0084 - acc: 0.9968
Epoch 403/500
 - 0s - loss: 0.0082 - acc: 0.9968
Epoch 404/500
 - 0s - loss: 0.0064 - acc: 0.9968
Epoch 405/500
 - 0s - loss: 0.0070 - acc: 0.9968
Epoch 406/500
 - 0s - loss: 0.0092 - acc: 0.9968
Epoch 407/500
 - 0s - loss: 0.0070 - acc: 0.9968
Epoch 408/500
 - 0s - loss: 0.0107 - acc: 0.9935
Epoch 409/500
 - 0s - loss: 0.0104 - acc: 0.9935
Epoch 410/500
 - 0s - loss: 0.0108 - acc: 0.9935
Epoch 411/500
 - 0s - loss: 0.0076 - acc: 0.9968
Epoch 412/500
 - 0s - loss: 0.0064 - acc: 0.9968
Epoch 413/500
 - 0s - loss: 0.0062 - acc: 0.9968
Epoch 414/500
 - 0s - loss: 0.0067 - acc: 0.9935
Epoch 415/500
 - 0s - loss: 0.0072 - acc: 0.9935
Epoch 416/500
 - 0s - loss: 0.0060 - acc: 0.9968
Epoch 417/500
 - 0s - loss: 0.0068 - acc: 0.9935
Epoch 418/500
 - 0s - loss: 0.0061 - acc: 0.9968
Epoch 419/500
 - 0s - loss: 0.0059 - acc: 0.9968
Epoch 420/500
 - 0s - loss: 0.0058 - acc: 0.9968
Epoch 421/500
 - 0s - loss: 0.0070 - acc: 0.9935
Epoch 422/500
 - 0s - loss: 0.0078 - acc: 0.9968
Epoch 423/500
 - 0s - loss: 0.0063 - acc: 0.9968
Epoch 424/500
 - 0s - loss: 0.0085 - acc: 0.9968
Epoch 425/500
 - 0s - loss: 0.0065 - acc: 0.9968
Epoch 426/500
 - 0s - loss: 0.0080 - acc: 0.9968
Epoch 427/500
 - 0s - loss: 0.0088 - acc: 0.9935
Epoch 428/500
 - 0s - loss: 0.0063 - acc: 0.9968
Epoch 429/500
 - 0s - loss: 0.0078 - acc: 0.9968
Epoch 430/500
 - 0s - loss: 0.0062 - acc: 0.9968
Epoch 431/500
 - 0s - loss: 0.0066 - acc: 0.9968
Epoch 432/500
 - 0s - loss: 0.0066 - acc: 0.9935
Epoch 433/500
 - 0s - loss: 0.0064 - acc: 0.9935
Epoch 434/500
 - 0s - loss: 0.0067 - acc: 0.9968
Epoch 435/500
 - 0s - loss: 0.0064 - acc: 0.9968
Epoch 436/500
 - 0s - loss: 0.0059 - acc: 0.9968
Epoch 437/500
 - 0s - loss: 0.0073 - acc: 0.9968
Epoch 438/500
 - 0s - loss: 0.0075 - acc: 0.9935
Epoch 439/500
 - 0s - loss: 0.0066 - acc: 0.9968
Epoch 440/500
 - 0s - loss: 0.0074 - acc: 0.9935
Epoch 441/500
 - 0s - loss: 0.0063 - acc: 0.9968
Epoch 442/500
 - 0s - loss: 0.0069 - acc: 0.9935
Epoch 443/500
 - 0s - loss: 0.0083 - acc: 0.9968
Epoch 444/500
 - 0s - loss: 0.0065 - acc: 0.9935
Epoch 445/500
 - 0s - loss: 0.0072 - acc: 0.9935
Epoch 446/500
 - 0s - loss: 0.0060 - acc: 0.9968
Epoch 447/500
 - 0s - loss: 0.0068 - acc: 0.9935
Epoch 448/500
 - 0s - loss: 0.0058 - acc: 0.9968
Epoch 449/500
 - 0s - loss: 0.0079 - acc: 0.9968
Epoch 450/500
 - 0s - loss: 0.0061 - acc: 0.9968
Epoch 451/500
 - 0s - loss: 0.0068 - acc: 0.9968
Epoch 452/500
 - 0s - loss: 0.0061 - acc: 0.9968
Epoch 453/500
 - 0s - loss: 0.0066 - acc: 0.9935
Epoch 454/500
 - 0s - loss: 0.0073 - acc: 0.9968
Epoch 455/500
 - 0s - loss: 0.0060 - acc: 0.9968
Epoch 456/500
 - 0s - loss: 0.0056 - acc: 0.9968
Epoch 457/500
 - 0s - loss: 0.0075 - acc: 0.9935
Epoch 458/500
 - 0s - loss: 0.0059 - acc: 0.9968
Epoch 459/500
 - 0s - loss: 0.0066 - acc: 0.9968
Epoch 460/500
 - 0s - loss: 0.0099 - acc: 0.9935
Epoch 461/500
 - 0s - loss: 0.0063 - acc: 0.9935
Epoch 462/500
 - 0s - loss: 0.0066 - acc: 0.9935
Epoch 463/500
 - 0s - loss: 0.0060 - acc: 0.9968
Epoch 464/500
 - 0s - loss: 0.0068 - acc: 0.9935
Epoch 465/500
 - 0s - loss: 0.0054 - acc: 0.9968
Epoch 466/500
 - 0s - loss: 0.0089 - acc: 0.9968
Epoch 467/500
 - 0s - loss: 0.0091 - acc: 0.9935
Epoch 468/500
 - 0s - loss: 0.0072 - acc: 0.9968
Epoch 469/500
 - 0s - loss: 0.0074 - acc: 0.9968
Epoch 470/500
 - 0s - loss: 0.0066 - acc: 0.9968
Epoch 471/500
 - 0s - loss: 0.0073 - acc: 0.9968
Epoch 472/500
 - 0s - loss: 0.0063 - acc: 0.9968
Epoch 473/500
 - 0s - loss: 0.0056 - acc: 0.9968
Epoch 474/500
 - 0s - loss: 0.0060 - acc: 0.9968
Epoch 475/500
 - 0s - loss: 0.0062 - acc: 0.9935
Epoch 476/500
 - 0s - loss: 0.0063 - acc: 0.9935
Epoch 477/500
 - 0s - loss: 0.0058 - acc: 0.9935
Epoch 478/500
 - 0s - loss: 0.0064 - acc: 0.9968
Epoch 479/500
 - 0s - loss: 0.0060 - acc: 0.9968
Epoch 480/500
 - 0s - loss: 0.0084 - acc: 0.9968
Epoch 481/500
 - 0s - loss: 0.0071 - acc: 0.9935
Epoch 482/500
 - 0s - loss: 0.0082 - acc: 0.9968
Epoch 483/500
 - 0s - loss: 0.0078 - acc: 0.9935
Epoch 484/500
 - 0s - loss: 0.0072 - acc: 0.9968
Epoch 485/500
 - 0s - loss: 0.0058 - acc: 0.9935
Epoch 486/500
 - 0s - loss: 0.0057 - acc: 0.9968
Epoch 487/500
 - 0s - loss: 0.0057 - acc: 0.9968
Epoch 488/500
 - 0s - loss: 0.0063 - acc: 0.9968
Epoch 489/500
 - 0s - loss: 0.0085 - acc: 0.9968
Epoch 490/500
 - 0s - loss: 0.0059 - acc: 0.9968
Epoch 491/500
 - 0s - loss: 0.0057 - acc: 0.9935
Epoch 492/500
 - 0s - loss: 0.0067 - acc: 0.9935
Epoch 493/500
 - 0s - loss: 0.0069 - acc: 0.9935
Epoch 494/500
 - 0s - loss: 0.0054 - acc: 0.9968
Epoch 495/500
 - 0s - loss: 0.0073 - acc: 0.9935
Epoch 496/500
 - 0s - loss: 0.0053 - acc: 0.9968
Epoch 497/500
 - 0s - loss: 0.0064 - acc: 0.9968
Epoch 498/500
 - 0s - loss: 0.0064 - acc: 0.9968
Epoch 499/500
 - 0s - loss: 0.0079 - acc: 0.9935

Epoch 500/500
 - 0s - loss: 0.0110 - acc: 0.9968

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 1.1375 - acc: 0.8462
Normal Neural Network - Loss: 1.1375261820279634, Accuracy: 0.8461538553237915

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Denied' 'Certified' 'Certified' 'Certified' 'Certified'
 'Certified' 'Certified' 'Certified' 'Certified']
Actual Labels: ['Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified']