In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'TAIWAN']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

TAIWAN    2486
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    2407
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [8]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [9]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [10]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
107,Certified,627,10018,NEW YORK,24.0,59738.0,TAIWAN,H-1B,Master's,9.0
255,Certified,489,95035,CALIFORNIA,1316.0,112860.0,TAIWAN,H-1B,Doctorate,4.0
304,Certified,475,11356,NEW YORK,0.0,34050.0,TAIWAN,NaN,None,4.0
338,Certified,526,94043,CALIFORNIA,53861.0,130000.0,TAIWAN,H-1B,Master's,11.0
392,Certified,499,60069-4302,ILLINOIS,59000.0,76086.0,TAIWAN,H-1B,Master's,1.0

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

CALIFORNIA              1286
NEW YORK                 196
TEXAS                    177
WASHINGTON               131
NEW JERSEY                62
ILLINOIS                  55
MASSACHUSETTS             54
FLORIDA                   50
GEORGIA                   36
PENNSYLVANIA              35
MICHIGAN                  35
MARYLAND                  27
VIRGINIA                  26
MINNESOTA                 20
WISCONSIN                 16
NORTH CAROLINA            16
ARIZONA                   16
INDIANA                   12
OREGON                    11
COLORADO                  11
CONNECTICUT               11
SOUTH CAROLINA            10
OHIO                       9
MISSOURI                   9
LOUISIANA                  8
IDAHO                      7
NEW MEXICO                 6
NEVADA                     6
TENNESSEE                  6
DISTRICT OF COLUMBIA       6
UTAH                       6
ARKANSAS                   5
IOWA                       5
KANSAS                     5
ALABAMA                    4
HAWAII                     4
VERMONT                    4
OKLAHOMA                   4
MISSISSIPPI                4
RHODE ISLAND               3
KENTUCKY                   3
WEST VIRGINIA              2
DELAWARE                   2
NEBRASKA                   2
SOUTH DAKOTA               1
GUAM                       1
MAINE                      1
WYOMING                    1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
107,Certified,627,10018,NEW YORK,24.0,59738.0,TAIWAN,H-1B,Master's,9.0,NEW YORK
255,Certified,489,95035,CALIFORNIA,1316.0,112860.0,TAIWAN,H-1B,Doctorate,4.0,CALIFORNIA
338,Certified,526,94043,CALIFORNIA,53861.0,130000.0,TAIWAN,H-1B,Master's,11.0,CALIFORNIA
392,Certified,499,60069-4302,ILLINOIS,59000.0,76086.0,TAIWAN,H-1B,Master's,1.0,ILLINOIS
546,Certified,176,84108,UTAH,47.0,64970.0,TAIWAN,H-1B,Bachelor's,10.0,UTAH

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

WEST         1418
NORTHEAST     352
SOUTH         341
MIDWEST       162
OTHER           1
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      2274
DECISION_ELAPSED_DAYS            2274
EMPLOYER_POSTAL_CODE             2274
EMPLOYER_STATE                   2274
EMPLOYER_NUM_EMPLOYEES           2274
WAGE_OFFER_FROM_9089             2274
COUNTRY_OF_CITIZENSHIP           2274
CLASS_OF_ADMISSION               2274
FOREIGN_WORKER_INFO_EDUCATION    2274
CASE_RECEIVED_DATE_MONTH         2274
EMPLOYER_STATES                  2274
EMPLOYER_REGIONS                 2274
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      974
0-90        639
181-365     451
366-3600    207
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

100000-500000    847
75001-100000     581
50001-75000      576
25001-50000      245
0-25000           25
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

0-50                623
10001-1000000000    595
1001-10000          425
101-500             359
51-100              152
501-1000            120
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      2274
DECISION_ELAPSED_DAYS            2274
EMPLOYER_POSTAL_CODE             2274
EMPLOYER_STATE                   2274
EMPLOYER_NUM_EMPLOYEES           2274
WAGE_OFFER_FROM_9089             2274
COUNTRY_OF_CITIZENSHIP           2274
CLASS_OF_ADMISSION               2274
FOREIGN_WORKER_INFO_EDUCATION    2274
CASE_RECEIVED_DATE_MONTH         2274
EMPLOYER_STATES                  2274
EMPLOYER_REGIONS                 2274
DAY_BINS                         2271
WAGE_BINS                        2274
EMPLOYEE_BINS                    2274
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
107,Certified,0-50,50001-75000,NORTHEAST,9.0,Master's,H-1B,366-3600
255,Certified,1001-10000,100000-500000,WEST,4.0,Doctorate,H-1B,366-3600
338,Certified,10001-1000000000,100000-500000,WEST,11.0,Master's,H-1B,366-3600
392,Certified,10001-1000000000,75001-100000,MIDWEST,1.0,Master's,H-1B,366-3600
546,Certified,0-50,50001-75000,WEST,10.0,Bachelor's,H-1B,91-180

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
107,Certified,0-50,50001-75000,NORTHEAST,9.0,Master's,H-1B,366-3600,7,4,3,1,2,0
255,Certified,1001-10000,100000-500000,WEST,4.0,Doctorate,H-1B,366-3600,7,2,1,4,2,2
338,Certified,10001-1000000000,100000-500000,WEST,11.0,Master's,H-1B,366-3600,7,4,1,4,2,1
392,Certified,10001-1000000000,75001-100000,MIDWEST,1.0,Master's,H-1B,366-3600,7,4,4,0,2,1
546,Certified,0-50,50001-75000,WEST,10.0,Bachelor's,H-1B,91-180,7,1,3,4,3,0

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           2274
EMPLOYEE_BINS                         2274
WAGE_BINS                             2274
EMPLOYER_REGIONS                      2274
CASE_RECEIVED_DATE_MONTH              2274
FOREIGN_WORKER_INFO_EDUCATION         2274
CLASS_OF_ADMISSION                    2274
DAY_BINS                              2274
CLASS_OF_ADMISSION_CODE               2274
FOREIGN_WORKER_INFO_EDUCATION_CODE    2274
WAGE_BINS_CODE                        2274
EMPLOYER_REGIONS_CODE                 2274
DAY_BINS_CODE                         2274
EMPLOYEE_BINS_CODE                    2274
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
107,Certified,0,3,2,4,7,9.0,1
255,Certified,2,1,2,2,7,4.0,4
338,Certified,1,1,2,4,7,11.0,4
392,Certified,1,4,2,4,7,1.0,0
546,Certified,0,3,3,1,7,10.0,4

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int64
WAGE_BINS_CODE                          int64
DAY_BINS_CODE                           int64
FOREIGN_WORKER_INFO_EDUCATION_CODE      int64
CLASS_OF_ADMISSION_CODE                 int64
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int64
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(2274, 7) (2274,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [53]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 1s - loss: 0.3817 - acc: 0.8645
Epoch 2/500
 - 0s - loss: 0.2929 - acc: 0.9132
Epoch 3/500
 - 0s - loss: 0.2844 - acc: 0.9132
Epoch 4/500
 - 0s - loss: 0.2757 - acc: 0.9132
Epoch 5/500
 - 0s - loss: 0.2681 - acc: 0.9132
Epoch 6/500
 - 0s - loss: 0.2606 - acc: 0.9132
Epoch 7/500
 - 0s - loss: 0.2487 - acc: 0.9132
Epoch 8/500
 - 0s - loss: 0.2422 - acc: 0.9132
Epoch 9/500
 - 0s - loss: 0.2373 - acc: 0.9132
Epoch 10/500
 - 0s - loss: 0.2289 - acc: 0.9138
Epoch 11/500
 - 0s - loss: 0.2227 - acc: 0.9138
Epoch 12/500
 - 0s - loss: 0.2190 - acc: 0.9144
Epoch 13/500
 - 0s - loss: 0.2128 - acc: 0.9150
Epoch 14/500
 - 0s - loss: 0.2125 - acc: 0.9167
Epoch 15/500
 - 0s - loss: 0.2095 - acc: 0.9167
Epoch 16/500
 - 0s - loss: 0.2033 - acc: 0.9220
Epoch 17/500
 - 0s - loss: 0.2007 - acc: 0.9226
Epoch 18/500
 - 0s - loss: 0.1995 - acc: 0.9202
Epoch 19/500
 - 0s - loss: 0.2009 - acc: 0.9226
Epoch 20/500
 - 0s - loss: 0.1964 - acc: 0.9243
Epoch 21/500
 - 0s - loss: 0.1906 - acc: 0.9279
Epoch 22/500
 - 0s - loss: 0.1912 - acc: 0.9279
Epoch 23/500
 - 0s - loss: 0.1914 - acc: 0.9261
Epoch 24/500
 - 0s - loss: 0.1892 - acc: 0.9284
Epoch 25/500
 - 0s - loss: 0.1902 - acc: 0.9284
Epoch 26/500
 - 0s - loss: 0.1894 - acc: 0.9255
Epoch 27/500
 - 0s - loss: 0.1867 - acc: 0.9314
Epoch 28/500
 - 0s - loss: 0.1821 - acc: 0.9290
Epoch 29/500
 - 0s - loss: 0.1814 - acc: 0.9343
Epoch 30/500
 - 0s - loss: 0.1805 - acc: 0.9326
Epoch 31/500
 - 0s - loss: 0.1795 - acc: 0.9331
Epoch 32/500
 - 0s - loss: 0.1759 - acc: 0.9331
Epoch 33/500
 - 0s - loss: 0.1753 - acc: 0.9320
Epoch 34/500
 - 0s - loss: 0.1784 - acc: 0.9331
Epoch 35/500
 - 0s - loss: 0.1753 - acc: 0.9343
Epoch 36/500
 - 0s - loss: 0.1730 - acc: 0.9384
Epoch 37/500
 - 0s - loss: 0.1705 - acc: 0.9331
Epoch 38/500
 - 0s - loss: 0.1719 - acc: 0.9343
Epoch 39/500
 - 0s - loss: 0.1689 - acc: 0.9355
Epoch 40/500
 - 0s - loss: 0.1714 - acc: 0.9355
Epoch 41/500
 - 0s - loss: 0.1645 - acc: 0.9372
Epoch 42/500
 - 0s - loss: 0.1657 - acc: 0.9378
Epoch 43/500
 - 0s - loss: 0.1664 - acc: 0.9396
Epoch 44/500
 - 0s - loss: 0.1650 - acc: 0.9355
Epoch 45/500
 - 0s - loss: 0.1645 - acc: 0.9349
Epoch 46/500
 - 0s - loss: 0.1624 - acc: 0.9355
Epoch 47/500
 - 0s - loss: 0.1648 - acc: 0.9314
Epoch 48/500
 - 0s - loss: 0.1626 - acc: 0.9367
Epoch 49/500
 - 0s - loss: 0.1605 - acc: 0.9425
Epoch 50/500
 - 0s - loss: 0.1597 - acc: 0.9372
Epoch 51/500
 - 0s - loss: 0.1551 - acc: 0.9425
Epoch 52/500
 - 0s - loss: 0.1559 - acc: 0.9372
Epoch 53/500
 - 0s - loss: 0.1551 - acc: 0.9390
Epoch 54/500
 - 0s - loss: 0.1545 - acc: 0.9367
Epoch 55/500
 - 0s - loss: 0.1556 - acc: 0.9431
Epoch 56/500
 - 0s - loss: 0.1542 - acc: 0.9367
Epoch 57/500
 - 0s - loss: 0.1516 - acc: 0.9402
Epoch 58/500
 - 0s - loss: 0.1502 - acc: 0.9419
Epoch 59/500
 - 0s - loss: 0.1468 - acc: 0.9466
Epoch 60/500
 - 0s - loss: 0.1478 - acc: 0.9455
Epoch 61/500
 - 0s - loss: 0.1442 - acc: 0.9419
Epoch 62/500
 - 0s - loss: 0.1459 - acc: 0.9425
Epoch 63/500
 - 0s - loss: 0.1442 - acc: 0.9413
Epoch 64/500
 - 0s - loss: 0.1449 - acc: 0.9413
Epoch 65/500
 - 0s - loss: 0.1400 - acc: 0.9437
Epoch 66/500
 - 0s - loss: 0.1370 - acc: 0.9472
Epoch 67/500
 - 0s - loss: 0.1400 - acc: 0.9460
Epoch 68/500
 - 0s - loss: 0.1374 - acc: 0.9472
Epoch 69/500
 - 0s - loss: 0.1344 - acc: 0.9490
Epoch 70/500
 - 0s - loss: 0.1325 - acc: 0.9501
Epoch 71/500
 - 0s - loss: 0.1388 - acc: 0.9490
Epoch 72/500
 - 0s - loss: 0.1348 - acc: 0.9507
Epoch 73/500
 - 0s - loss: 0.1358 - acc: 0.9490
Epoch 74/500
 - 0s - loss: 0.1338 - acc: 0.9455
Epoch 75/500
 - 0s - loss: 0.1313 - acc: 0.9460
Epoch 76/500
 - 0s - loss: 0.1311 - acc: 0.9466
Epoch 77/500
 - 0s - loss: 0.1283 - acc: 0.9496
Epoch 78/500
 - 0s - loss: 0.1353 - acc: 0.9419
Epoch 79/500
 - 0s - loss: 0.1268 - acc: 0.9531
Epoch 80/500
 - 0s - loss: 0.1268 - acc: 0.9478
Epoch 81/500
 - 0s - loss: 0.1320 - acc: 0.9455
Epoch 82/500
 - 0s - loss: 0.1307 - acc: 0.9472
Epoch 83/500
 - 0s - loss: 0.1246 - acc: 0.9519
Epoch 84/500
 - 0s - loss: 0.1237 - acc: 0.9525
Epoch 85/500
 - 0s - loss: 0.1233 - acc: 0.9548
Epoch 86/500
 - 0s - loss: 0.1214 - acc: 0.9531
Epoch 87/500
 - 0s - loss: 0.1210 - acc: 0.9519
Epoch 88/500
 - 0s - loss: 0.1217 - acc: 0.9501
Epoch 89/500
 - 0s - loss: 0.1245 - acc: 0.9496
Epoch 90/500
 - 0s - loss: 0.1188 - acc: 0.9507
Epoch 91/500
 - 0s - loss: 0.1159 - acc: 0.9537
Epoch 92/500
 - 0s - loss: 0.1159 - acc: 0.9507
Epoch 93/500
 - 0s - loss: 0.1213 - acc: 0.9496
Epoch 94/500
 - 0s - loss: 0.1147 - acc: 0.9490
Epoch 95/500
 - 0s - loss: 0.1167 - acc: 0.9566
Epoch 96/500
 - 0s - loss: 0.1180 - acc: 0.9531
Epoch 97/500
 - 0s - loss: 0.1168 - acc: 0.9513
Epoch 98/500
 - 0s - loss: 0.1151 - acc: 0.9525
Epoch 99/500
 - 0s - loss: 0.1193 - acc: 0.9554
Epoch 100/500
 - 0s - loss: 0.1161 - acc: 0.9519
Epoch 101/500
 - 0s - loss: 0.1137 - acc: 0.9543
Epoch 102/500
 - 0s - loss: 0.1098 - acc: 0.9578
Epoch 103/500
 - 0s - loss: 0.1111 - acc: 0.9566
Epoch 104/500
 - 0s - loss: 0.1105 - acc: 0.9548
Epoch 105/500
 - 0s - loss: 0.1133 - acc: 0.9519
Epoch 106/500
 - 0s - loss: 0.1080 - acc: 0.9578
Epoch 107/500
 - 0s - loss: 0.1071 - acc: 0.9589
Epoch 108/500
 - 0s - loss: 0.1059 - acc: 0.9548
Epoch 109/500
 - 0s - loss: 0.1093 - acc: 0.9584
Epoch 110/500
 - 0s - loss: 0.1022 - acc: 0.9642
Epoch 111/500
 - 0s - loss: 0.1030 - acc: 0.9613
Epoch 112/500
 - 0s - loss: 0.1019 - acc: 0.9619
Epoch 113/500
 - 0s - loss: 0.1040 - acc: 0.9630
Epoch 114/500
 - 0s - loss: 0.1065 - acc: 0.9572
Epoch 115/500
 - 0s - loss: 0.0989 - acc: 0.9636
Epoch 116/500
 - 0s - loss: 0.1019 - acc: 0.9625
Epoch 117/500
 - 0s - loss: 0.0973 - acc: 0.9613
Epoch 118/500
 - 0s - loss: 0.1021 - acc: 0.9607
Epoch 119/500
 - 0s - loss: 0.0960 - acc: 0.9619
Epoch 120/500
 - 0s - loss: 0.0989 - acc: 0.9642
Epoch 121/500
 - 0s - loss: 0.0993 - acc: 0.9589
Epoch 122/500
 - 0s - loss: 0.0975 - acc: 0.9648
Epoch 123/500
 - 0s - loss: 0.0958 - acc: 0.9648
Epoch 124/500
 - 0s - loss: 0.0979 - acc: 0.9642
Epoch 125/500
 - 0s - loss: 0.0975 - acc: 0.9654
Epoch 126/500
 - 0s - loss: 0.0926 - acc: 0.9636
Epoch 127/500
 - 0s - loss: 0.0937 - acc: 0.9630
Epoch 128/500
 - 0s - loss: 0.0957 - acc: 0.9648
Epoch 129/500
 - 0s - loss: 0.0874 - acc: 0.9660
Epoch 130/500
 - 0s - loss: 0.1020 - acc: 0.9613
Epoch 131/500
 - 0s - loss: 0.0915 - acc: 0.9666
Epoch 132/500
 - 0s - loss: 0.0890 - acc: 0.9666
Epoch 133/500
 - 0s - loss: 0.0899 - acc: 0.9648
Epoch 134/500
 - 0s - loss: 0.0901 - acc: 0.9666
Epoch 135/500
 - 0s - loss: 0.0913 - acc: 0.9660
Epoch 136/500
 - 0s - loss: 0.0912 - acc: 0.9619
Epoch 137/500
 - 0s - loss: 0.0901 - acc: 0.9689
Epoch 138/500
 - 0s - loss: 0.0886 - acc: 0.9672
Epoch 139/500
 - 0s - loss: 0.0924 - acc: 0.9636
Epoch 140/500
 - 0s - loss: 0.0892 - acc: 0.9601
Epoch 141/500
 - 0s - loss: 0.0909 - acc: 0.9672
Epoch 142/500
 - 0s - loss: 0.0906 - acc: 0.9666
Epoch 143/500
 - 0s - loss: 0.0855 - acc: 0.9695
Epoch 144/500
 - 0s - loss: 0.0855 - acc: 0.9672
Epoch 145/500
 - 0s - loss: 0.0829 - acc: 0.9713
Epoch 146/500
 - 0s - loss: 0.0836 - acc: 0.9660
Epoch 147/500
 - 0s - loss: 0.0862 - acc: 0.9701
Epoch 148/500
 - 0s - loss: 0.0910 - acc: 0.9689
Epoch 149/500
 - 0s - loss: 0.0860 - acc: 0.9713
Epoch 150/500
 - 0s - loss: 0.0804 - acc: 0.9701
Epoch 151/500
 - 0s - loss: 0.0976 - acc: 0.9572
Epoch 152/500
 - 0s - loss: 0.0860 - acc: 0.9642
Epoch 153/500
 - 0s - loss: 0.0832 - acc: 0.9666
Epoch 154/500
 - 0s - loss: 0.0809 - acc: 0.9689
Epoch 155/500
 - 0s - loss: 0.0856 - acc: 0.9695
Epoch 156/500
 - 0s - loss: 0.0794 - acc: 0.9695
Epoch 157/500
 - 0s - loss: 0.0853 - acc: 0.9666
Epoch 158/500
 - 0s - loss: 0.0786 - acc: 0.9742
Epoch 159/500
 - 0s - loss: 0.0763 - acc: 0.9718
Epoch 160/500
 - 0s - loss: 0.0778 - acc: 0.9730
Epoch 161/500
 - 0s - loss: 0.0818 - acc: 0.9701
Epoch 162/500
 - 0s - loss: 0.0769 - acc: 0.9707
Epoch 163/500
 - 0s - loss: 0.0787 - acc: 0.9689
Epoch 164/500
 - 0s - loss: 0.0795 - acc: 0.9718

Epoch 165/500
 - 0s - loss: 0.0766 - acc: 0.9701
Epoch 166/500
 - 0s - loss: 0.0746 - acc: 0.9724
Epoch 167/500
 - 0s - loss: 0.0767 - acc: 0.9736
Epoch 168/500
 - 0s - loss: 0.0755 - acc: 0.9730
Epoch 169/500
 - 0s - loss: 0.0789 - acc: 0.9718
Epoch 170/500
 - 0s - loss: 0.0774 - acc: 0.9718
Epoch 171/500
 - 0s - loss: 0.0733 - acc: 0.9742
Epoch 172/500
 - 0s - loss: 0.0758 - acc: 0.9660
Epoch 173/500
 - 0s - loss: 0.0807 - acc: 0.9713
Epoch 174/500
 - 0s - loss: 0.0716 - acc: 0.9765
Epoch 175/500
 - 0s - loss: 0.0737 - acc: 0.9748
Epoch 176/500
 - 0s - loss: 0.0775 - acc: 0.9742
Epoch 177/500
 - 0s - loss: 0.0757 - acc: 0.9760
Epoch 178/500
 - 0s - loss: 0.0714 - acc: 0.9748
Epoch 179/500
 - 0s - loss: 0.0736 - acc: 0.9736
Epoch 180/500
 - 0s - loss: 0.0694 - acc: 0.9736
Epoch 181/500
 - 0s - loss: 0.0667 - acc: 0.9777
Epoch 182/500
 - 0s - loss: 0.0693 - acc: 0.9748
Epoch 183/500
 - 0s - loss: 0.0747 - acc: 0.9736
Epoch 184/500
 - 0s - loss: 0.0712 - acc: 0.9736
Epoch 185/500
 - 0s - loss: 0.0709 - acc: 0.9742
Epoch 186/500
 - 0s - loss: 0.0671 - acc: 0.9754
Epoch 187/500
 - 0s - loss: 0.0702 - acc: 0.9748
Epoch 188/500
 - 0s - loss: 0.0649 - acc: 0.9777
Epoch 189/500
 - 0s - loss: 0.0689 - acc: 0.9760
Epoch 190/500
 - 0s - loss: 0.0683 - acc: 0.9765
Epoch 191/500
 - 0s - loss: 0.0663 - acc: 0.9771
Epoch 192/500
 - 0s - loss: 0.0808 - acc: 0.9695
Epoch 193/500
 - 0s - loss: 0.0661 - acc: 0.9783
Epoch 194/500
 - 0s - loss: 0.0641 - acc: 0.9777
Epoch 195/500
 - 0s - loss: 0.0645 - acc: 0.9783
Epoch 196/500
 - 0s - loss: 0.0624 - acc: 0.9789
Epoch 197/500
 - 0s - loss: 0.0621 - acc: 0.9748
Epoch 198/500
 - 0s - loss: 0.0638 - acc: 0.9795
Epoch 199/500
 - 0s - loss: 0.0619 - acc: 0.9777
Epoch 200/500
 - 0s - loss: 0.0653 - acc: 0.9771
Epoch 201/500
 - 0s - loss: 0.0597 - acc: 0.9801
Epoch 202/500
 - 0s - loss: 0.0649 - acc: 0.9771
Epoch 203/500
 - 0s - loss: 0.0613 - acc: 0.9789
Epoch 204/500
 - 0s - loss: 0.0662 - acc: 0.9760
Epoch 205/500
 - 0s - loss: 0.0619 - acc: 0.9783
Epoch 206/500
 - 0s - loss: 0.0628 - acc: 0.9789
Epoch 207/500
 - 0s - loss: 0.0737 - acc: 0.9718
Epoch 208/500
 - 0s - loss: 0.0600 - acc: 0.9806
Epoch 209/500
 - 0s - loss: 0.0582 - acc: 0.9771
Epoch 210/500
 - 0s - loss: 0.0587 - acc: 0.9765
Epoch 211/500
 - 0s - loss: 0.0688 - acc: 0.9730
Epoch 212/500
 - 0s - loss: 0.0642 - acc: 0.9754
Epoch 213/500
 - 0s - loss: 0.0588 - acc: 0.9789
Epoch 214/500
 - 0s - loss: 0.0617 - acc: 0.9754
Epoch 215/500
 - 0s - loss: 0.0619 - acc: 0.9771
Epoch 216/500
 - 0s - loss: 0.0605 - acc: 0.9801
Epoch 217/500
 - 0s - loss: 0.0620 - acc: 0.9771
Epoch 218/500
 - 0s - loss: 0.0563 - acc: 0.9789
Epoch 219/500
 - 0s - loss: 0.0541 - acc: 0.9818
Epoch 220/500
 - 0s - loss: 0.0545 - acc: 0.9818
Epoch 221/500
 - 0s - loss: 0.0577 - acc: 0.9789
Epoch 222/500
 - 0s - loss: 0.0638 - acc: 0.9765
Epoch 223/500
 - 0s - loss: 0.0577 - acc: 0.9777
Epoch 224/500
 - 0s - loss: 0.0537 - acc: 0.9824
Epoch 225/500
 - 0s - loss: 0.0578 - acc: 0.9777
Epoch 226/500
 - 0s - loss: 0.0543 - acc: 0.9801
Epoch 227/500
 - 0s - loss: 0.0533 - acc: 0.9812
Epoch 228/500
 - 0s - loss: 0.0543 - acc: 0.9806
Epoch 229/500
 - 0s - loss: 0.0580 - acc: 0.9795
Epoch 230/500
 - 0s - loss: 0.0669 - acc: 0.9760
Epoch 231/500
 - 0s - loss: 0.0574 - acc: 0.9795
Epoch 232/500
 - 0s - loss: 0.0524 - acc: 0.9830
Epoch 233/500
 - 0s - loss: 0.0503 - acc: 0.9812
Epoch 234/500
 - 0s - loss: 0.0557 - acc: 0.9801
Epoch 235/500
 - 0s - loss: 0.0581 - acc: 0.9783
Epoch 236/500
 - 0s - loss: 0.0528 - acc: 0.9812
Epoch 237/500
 - 0s - loss: 0.0517 - acc: 0.9830
Epoch 238/500
 - 0s - loss: 0.0531 - acc: 0.9806
Epoch 239/500
 - 0s - loss: 0.0493 - acc: 0.9859
Epoch 240/500
 - 0s - loss: 0.0506 - acc: 0.9789
Epoch 241/500
 - 0s - loss: 0.0499 - acc: 0.9812
Epoch 242/500
 - 0s - loss: 0.0545 - acc: 0.9801
Epoch 243/500
 - 0s - loss: 0.0587 - acc: 0.9801
Epoch 244/500
 - 0s - loss: 0.0507 - acc: 0.9824
Epoch 245/500
 - 0s - loss: 0.0530 - acc: 0.9818
Epoch 246/500
 - 0s - loss: 0.0470 - acc: 0.9842
Epoch 247/500
 - 0s - loss: 0.0513 - acc: 0.9836
Epoch 248/500
 - 0s - loss: 0.0536 - acc: 0.9824
Epoch 249/500
 - 0s - loss: 0.0500 - acc: 0.9818
Epoch 250/500
 - 0s - loss: 0.0577 - acc: 0.9801
Epoch 251/500
 - 0s - loss: 0.0560 - acc: 0.9801
Epoch 252/500
 - 0s - loss: 0.0594 - acc: 0.9742
Epoch 253/500
 - 0s - loss: 0.0577 - acc: 0.9783
Epoch 254/500
 - 0s - loss: 0.0587 - acc: 0.9771
Epoch 255/500
 - 0s - loss: 0.0527 - acc: 0.9789
Epoch 256/500
 - 0s - loss: 0.0509 - acc: 0.9812
Epoch 257/500
 - 0s - loss: 0.0482 - acc: 0.9836
Epoch 258/500
 - 0s - loss: 0.0519 - acc: 0.9795
Epoch 259/500
 - 0s - loss: 0.0501 - acc: 0.9818
Epoch 260/500
 - 0s - loss: 0.0528 - acc: 0.9818
Epoch 261/500
 - 0s - loss: 0.0504 - acc: 0.9812
Epoch 262/500
 - 0s - loss: 0.0485 - acc: 0.9812
Epoch 263/500
 - 0s - loss: 0.0436 - acc: 0.9836
Epoch 264/500
 - 0s - loss: 0.0472 - acc: 0.9836
Epoch 265/500
 - 0s - loss: 0.0494 - acc: 0.9830
Epoch 266/500
 - 0s - loss: 0.0519 - acc: 0.9801
Epoch 267/500
 - 0s - loss: 0.0449 - acc: 0.9818
Epoch 268/500
 - 0s - loss: 0.0611 - acc: 0.9771
Epoch 269/500
 - 0s - loss: 0.0556 - acc: 0.9771
Epoch 270/500
 - 0s - loss: 0.0469 - acc: 0.9836
Epoch 271/500
 - 0s - loss: 0.0468 - acc: 0.9842
Epoch 272/500
 - 0s - loss: 0.0450 - acc: 0.9848
Epoch 273/500
 - 0s - loss: 0.0467 - acc: 0.9836
Epoch 274/500
 - 0s - loss: 0.0443 - acc: 0.9812
Epoch 275/500
 - 0s - loss: 0.0434 - acc: 0.9818
Epoch 276/500
 - 0s - loss: 0.0461 - acc: 0.9830
Epoch 277/500
 - 0s - loss: 0.0521 - acc: 0.9812
Epoch 278/500
 - 0s - loss: 0.0470 - acc: 0.9824
Epoch 279/500
 - 0s - loss: 0.0476 - acc: 0.9824
Epoch 280/500
 - 0s - loss: 0.0453 - acc: 0.9801
Epoch 281/500
 - 0s - loss: 0.0500 - acc: 0.9801
Epoch 282/500
 - 0s - loss: 0.0460 - acc: 0.9836
Epoch 283/500
 - 0s - loss: 0.0444 - acc: 0.9818
Epoch 284/500
 - 0s - loss: 0.0461 - acc: 0.9830
Epoch 285/500
 - 0s - loss: 0.0469 - acc: 0.9801
Epoch 286/500
 - 0s - loss: 0.0484 - acc: 0.9824
Epoch 287/500
 - 0s - loss: 0.0469 - acc: 0.9830
Epoch 288/500
 - 0s - loss: 0.0444 - acc: 0.9806
Epoch 289/500
 - 0s - loss: 0.0480 - acc: 0.9836
Epoch 290/500
 - 0s - loss: 0.0422 - acc: 0.9865
Epoch 291/500
 - 0s - loss: 0.0433 - acc: 0.9848
Epoch 292/500
 - 0s - loss: 0.0410 - acc: 0.9853
Epoch 293/500
 - 0s - loss: 0.0439 - acc: 0.9812
Epoch 294/500
 - 0s - loss: 0.0434 - acc: 0.9848
Epoch 295/500
 - 0s - loss: 0.0446 - acc: 0.9836
Epoch 296/500
 - 0s - loss: 0.0404 - acc: 0.9871
Epoch 297/500
 - 0s - loss: 0.0437 - acc: 0.9812
Epoch 298/500
 - 0s - loss: 0.0562 - acc: 0.9795
Epoch 299/500
 - 0s - loss: 0.0478 - acc: 0.9818
Epoch 300/500
 - 0s - loss: 0.0464 - acc: 0.9801
Epoch 301/500
 - 0s - loss: 0.0438 - acc: 0.9818
Epoch 302/500
 - 0s - loss: 0.0447 - acc: 0.9836
Epoch 303/500
 - 0s - loss: 0.0443 - acc: 0.9824
Epoch 304/500
 - 0s - loss: 0.0447 - acc: 0.9812
Epoch 305/500
 - 0s - loss: 0.0405 - acc: 0.9842
Epoch 306/500
 - 0s - loss: 0.0466 - acc: 0.9842
Epoch 307/500
 - 0s - loss: 0.0452 - acc: 0.9830
Epoch 308/500
 - 0s - loss: 0.0420 - acc: 0.9848
Epoch 309/500
 - 0s - loss: 0.0455 - acc: 0.9836
Epoch 310/500
 - 0s - loss: 0.0393 - acc: 0.9842
Epoch 311/500
 - 0s - loss: 0.0397 - acc: 0.9871
Epoch 312/500
 - 0s - loss: 0.0391 - acc: 0.9836
Epoch 313/500
 - 0s - loss: 0.0397 - acc: 0.9865
Epoch 314/500
 - 0s - loss: 0.0419 - acc: 0.9836
Epoch 315/500
 - 0s - loss: 0.0456 - acc: 0.9801
Epoch 316/500
 - 0s - loss: 0.0368 - acc: 0.9848
Epoch 317/500
 - 0s - loss: 0.0386 - acc: 0.9853
Epoch 318/500
 - 0s - loss: 0.0368 - acc: 0.9871
Epoch 319/500
 - 0s - loss: 0.0458 - acc: 0.9848
Epoch 320/500
 - 0s - loss: 0.0387 - acc: 0.9871
Epoch 321/500
 - 0s - loss: 0.0410 - acc: 0.9842
Epoch 322/500
 - 0s - loss: 0.0420 - acc: 0.9848
Epoch 323/500
 - 0s - loss: 0.0369 - acc: 0.9842
Epoch 324/500
 - 0s - loss: 0.0393 - acc: 0.9853
Epoch 325/500
 - 0s - loss: 0.0397 - acc: 0.9836
Epoch 326/500
 - 0s - loss: 0.0460 - acc: 0.9830
Epoch 327/500
 - 0s - loss: 0.0392 - acc: 0.9877
Epoch 328/500
 - 0s - loss: 0.0438 - acc: 0.9859
Epoch 329/500
 - 0s - loss: 0.0393 - acc: 0.9871
Epoch 330/500
 - 0s - loss: 0.0351 - acc: 0.9883
Epoch 331/500
 - 0s - loss: 0.0391 - acc: 0.9848
Epoch 332/500

 - 0s - loss: 0.0391 - acc: 0.9824
Epoch 333/500
 - 0s - loss: 0.0377 - acc: 0.9859
Epoch 334/500
 - 0s - loss: 0.0356 - acc: 0.9889
Epoch 335/500
 - 0s - loss: 0.0416 - acc: 0.9848
Epoch 336/500
 - 0s - loss: 0.0382 - acc: 0.9859
Epoch 337/500
 - 0s - loss: 0.0358 - acc: 0.9853
Epoch 338/500
 - 0s - loss: 0.0406 - acc: 0.9818
Epoch 339/500
 - 0s - loss: 0.0397 - acc: 0.9889
Epoch 340/500
 - 0s - loss: 0.0392 - acc: 0.9842
Epoch 341/500
 - 0s - loss: 0.0403 - acc: 0.9853
Epoch 342/500
 - 0s - loss: 0.0332 - acc: 0.9877
Epoch 343/500
 - 0s - loss: 0.0345 - acc: 0.9883
Epoch 344/500
 - 0s - loss: 0.0379 - acc: 0.9842
Epoch 345/500
 - 0s - loss: 0.0346 - acc: 0.9871
Epoch 346/500
 - 0s - loss: 0.0361 - acc: 0.9859
Epoch 347/500
 - 0s - loss: 0.0351 - acc: 0.9853
Epoch 348/500
 - 0s - loss: 0.0486 - acc: 0.9830
Epoch 349/500
 - 0s - loss: 0.0425 - acc: 0.9836
Epoch 350/500
 - 0s - loss: 0.0458 - acc: 0.9812
Epoch 351/500
 - 0s - loss: 0.0463 - acc: 0.9806
Epoch 352/500
 - 0s - loss: 0.0396 - acc: 0.9853
Epoch 353/500
 - 0s - loss: 0.0392 - acc: 0.9848
Epoch 354/500
 - 0s - loss: 0.0347 - acc: 0.9865
Epoch 355/500
 - 0s - loss: 0.0357 - acc: 0.9859
Epoch 356/500
 - 0s - loss: 0.0397 - acc: 0.9859
Epoch 357/500
 - 0s - loss: 0.0417 - acc: 0.9848
Epoch 358/500
 - 0s - loss: 0.0353 - acc: 0.9865
Epoch 359/500
 - 0s - loss: 0.0370 - acc: 0.9865
Epoch 360/500
 - 0s - loss: 0.0313 - acc: 0.9877
Epoch 361/500
 - 0s - loss: 0.0346 - acc: 0.9871
Epoch 362/500
 - 0s - loss: 0.0388 - acc: 0.9848
Epoch 363/500
 - 0s - loss: 0.0369 - acc: 0.9859
Epoch 364/500
 - 0s - loss: 0.0387 - acc: 0.9848
Epoch 365/500
 - 0s - loss: 0.0339 - acc: 0.9859
Epoch 366/500
 - 0s - loss: 0.0386 - acc: 0.9848
Epoch 367/500
 - 0s - loss: 0.0411 - acc: 0.9818
Epoch 368/500
 - 0s - loss: 0.0382 - acc: 0.9836
Epoch 369/500
 - 0s - loss: 0.0327 - acc: 0.9865
Epoch 370/500
 - 0s - loss: 0.0376 - acc: 0.9836
Epoch 371/500
 - 0s - loss: 0.0419 - acc: 0.9853
Epoch 372/500
 - 0s - loss: 0.0440 - acc: 0.9824
Epoch 373/500
 - 0s - loss: 0.0377 - acc: 0.9859
Epoch 374/500
 - 0s - loss: 0.0341 - acc: 0.9877
Epoch 375/500
 - 0s - loss: 0.0421 - acc: 0.9848
Epoch 376/500
 - 0s - loss: 0.0320 - acc: 0.9883
Epoch 377/500
 - 0s - loss: 0.0318 - acc: 0.9877
Epoch 378/500
 - 0s - loss: 0.0326 - acc: 0.9871
Epoch 379/500
 - 0s - loss: 0.0347 - acc: 0.9883
Epoch 380/500
 - 0s - loss: 0.0335 - acc: 0.9871
Epoch 381/500
 - 0s - loss: 0.0358 - acc: 0.9871
Epoch 382/500
 - 0s - loss: 0.0367 - acc: 0.9859
Epoch 383/500
 - 0s - loss: 0.0312 - acc: 0.9853
Epoch 384/500
 - 0s - loss: 0.0349 - acc: 0.9853
Epoch 385/500
 - 0s - loss: 0.0331 - acc: 0.9859
Epoch 386/500
 - 0s - loss: 0.0332 - acc: 0.9865
Epoch 387/500
 - 0s - loss: 0.0365 - acc: 0.9853
Epoch 388/500
 - 0s - loss: 0.0317 - acc: 0.9865
Epoch 389/500
 - 0s - loss: 0.0347 - acc: 0.9853
Epoch 390/500
 - 0s - loss: 0.0325 - acc: 0.9871
Epoch 391/500
 - 0s - loss: 0.0375 - acc: 0.9859
Epoch 392/500
 - 0s - loss: 0.0345 - acc: 0.9889
Epoch 393/500
 - 0s - loss: 0.0366 - acc: 0.9853
Epoch 394/500
 - 0s - loss: 0.0330 - acc: 0.9871
Epoch 395/500
 - 0s - loss: 0.0319 - acc: 0.9871
Epoch 396/500
 - 0s - loss: 0.0335 - acc: 0.9889
Epoch 397/500
 - 0s - loss: 0.0337 - acc: 0.9889
Epoch 398/500
 - 0s - loss: 0.0368 - acc: 0.9848
Epoch 399/500
 - 0s - loss: 0.0338 - acc: 0.9871
Epoch 400/500
 - 0s - loss: 0.0383 - acc: 0.9859
Epoch 401/500
 - 0s - loss: 0.0331 - acc: 0.9877
Epoch 402/500
 - 0s - loss: 0.0318 - acc: 0.9889
Epoch 403/500
 - 0s - loss: 0.0398 - acc: 0.9842
Epoch 404/500
 - 0s - loss: 0.0381 - acc: 0.9848
Epoch 405/500
 - 0s - loss: 0.0425 - acc: 0.9836
Epoch 406/500
 - 0s - loss: 0.0327 - acc: 0.9871
Epoch 407/500
 - 0s - loss: 0.0349 - acc: 0.9877
Epoch 408/500
 - 0s - loss: 0.0357 - acc: 0.9842
Epoch 409/500
 - 0s - loss: 0.0337 - acc: 0.9871
Epoch 410/500
 - 0s - loss: 0.0300 - acc: 0.9900
Epoch 411/500
 - 0s - loss: 0.0354 - acc: 0.9865
Epoch 412/500
 - 0s - loss: 0.0342 - acc: 0.9865
Epoch 413/500
 - 0s - loss: 0.0308 - acc: 0.9883
Epoch 414/500
 - 0s - loss: 0.0313 - acc: 0.9889
Epoch 415/500
 - 0s - loss: 0.0326 - acc: 0.9859
Epoch 416/500
 - 0s - loss: 0.0317 - acc: 0.9883
Epoch 417/500
 - 0s - loss: 0.0273 - acc: 0.9889
Epoch 418/500
 - 0s - loss: 0.0276 - acc: 0.9889
Epoch 419/500
 - 0s - loss: 0.0322 - acc: 0.9871
Epoch 420/500
 - 0s - loss: 0.0296 - acc: 0.9883
Epoch 421/500
 - 0s - loss: 0.0310 - acc: 0.9900
Epoch 422/500
 - 0s - loss: 0.0356 - acc: 0.9865
Epoch 423/500
 - 0s - loss: 0.0308 - acc: 0.9889
Epoch 424/500
 - 0s - loss: 0.0385 - acc: 0.9848
Epoch 425/500
 - 0s - loss: 0.0325 - acc: 0.9871
Epoch 426/500
 - 0s - loss: 0.0310 - acc: 0.9877
Epoch 427/500
 - 0s - loss: 0.0306 - acc: 0.9871
Epoch 428/500
 - 0s - loss: 0.0367 - acc: 0.9853
Epoch 429/500
 - 0s - loss: 0.0319 - acc: 0.9889
Epoch 430/500
 - 0s - loss: 0.0386 - acc: 0.9836
Epoch 431/500
 - 0s - loss: 0.0306 - acc: 0.9871
Epoch 432/500
 - 0s - loss: 0.0317 - acc: 0.9865
Epoch 433/500
 - 0s - loss: 0.0355 - acc: 0.9865
Epoch 434/500
 - 0s - loss: 0.0327 - acc: 0.9871
Epoch 435/500
 - 0s - loss: 0.0352 - acc: 0.9842
Epoch 436/500
 - 0s - loss: 0.0328 - acc: 0.9900
Epoch 437/500
 - 0s - loss: 0.0309 - acc: 0.9889
Epoch 438/500
 - 0s - loss: 0.0326 - acc: 0.9853
Epoch 439/500
 - 0s - loss: 0.0318 - acc: 0.9877
Epoch 440/500
 - 0s - loss: 0.0324 - acc: 0.9877
Epoch 441/500
 - 0s - loss: 0.0281 - acc: 0.9871
Epoch 442/500
 - 0s - loss: 0.0311 - acc: 0.9883
Epoch 443/500
 - 0s - loss: 0.0333 - acc: 0.9865
Epoch 444/500
 - 0s - loss: 0.0321 - acc: 0.9865
Epoch 445/500
 - 0s - loss: 0.0291 - acc: 0.9848
Epoch 446/500
 - 0s - loss: 0.0313 - acc: 0.9865
Epoch 447/500
 - 0s - loss: 0.0355 - acc: 0.9859
Epoch 448/500
 - 0s - loss: 0.0358 - acc: 0.9865
Epoch 449/500
 - 0s - loss: 0.0298 - acc: 0.9871
Epoch 450/500
 - 0s - loss: 0.0296 - acc: 0.9894
Epoch 451/500
 - 0s - loss: 0.0330 - acc: 0.9853
Epoch 452/500
 - 0s - loss: 0.0336 - acc: 0.9865
Epoch 453/500
 - 0s - loss: 0.0341 - acc: 0.9865
Epoch 454/500
 - 0s - loss: 0.0309 - acc: 0.9836
Epoch 455/500
 - 0s - loss: 0.0309 - acc: 0.9900
Epoch 456/500
 - 0s - loss: 0.0293 - acc: 0.9894
Epoch 457/500
 - 0s - loss: 0.0427 - acc: 0.9859
Epoch 458/500
 - 0s - loss: 0.0336 - acc: 0.9836
Epoch 459/500
 - 0s - loss: 0.0335 - acc: 0.9865
Epoch 460/500
 - 0s - loss: 0.0310 - acc: 0.9883
Epoch 461/500
 - 0s - loss: 0.0294 - acc: 0.9900
Epoch 462/500
 - 0s - loss: 0.0249 - acc: 0.9894
Epoch 463/500
 - 0s - loss: 0.0306 - acc: 0.9853
Epoch 464/500
 - 0s - loss: 0.0287 - acc: 0.9883
Epoch 465/500
 - 0s - loss: 0.0299 - acc: 0.9889
Epoch 466/500
 - 0s - loss: 0.0326 - acc: 0.9871
Epoch 467/500
 - 0s - loss: 0.0359 - acc: 0.9859
Epoch 468/500
 - 0s - loss: 0.0317 - acc: 0.9877
Epoch 469/500
 - 0s - loss: 0.0301 - acc: 0.9871
Epoch 470/500
 - 0s - loss: 0.0295 - acc: 0.9871
Epoch 471/500
 - 0s - loss: 0.0433 - acc: 0.9836
Epoch 472/500
 - 0s - loss: 0.0355 - acc: 0.9830
Epoch 473/500
 - 0s - loss: 0.0367 - acc: 0.9865
Epoch 474/500
 - 0s - loss: 0.0279 - acc: 0.9877
Epoch 475/500
 - 0s - loss: 0.0282 - acc: 0.9883
Epoch 476/500
 - 0s - loss: 0.0303 - acc: 0.9871
Epoch 477/500
 - 0s - loss: 0.0365 - acc: 0.9883
Epoch 478/500
 - 0s - loss: 0.0322 - acc: 0.9877
Epoch 479/500
 - 0s - loss: 0.0288 - acc: 0.9889
Epoch 480/500
 - 0s - loss: 0.0359 - acc: 0.9865
Epoch 481/500
 - 0s - loss: 0.0290 - acc: 0.9877
Epoch 482/500
 - 0s - loss: 0.0293 - acc: 0.9871
Epoch 483/500
 - 0s - loss: 0.0262 - acc: 0.9906
Epoch 484/500
 - 0s - loss: 0.0267 - acc: 0.9877
Epoch 485/500
 - 0s - loss: 0.0289 - acc: 0.9871
Epoch 486/500
 - 0s - loss: 0.0290 - acc: 0.9889
Epoch 487/500
 - 0s - loss: 0.0269 - acc: 0.9889
Epoch 488/500
 - 0s - loss: 0.0282 - acc: 0.9877
Epoch 489/500
 - 0s - loss: 0.0291 - acc: 0.9877
Epoch 490/500
 - 0s - loss: 0.0282 - acc: 0.9883
Epoch 491/500
 - 0s - loss: 0.0299 - acc: 0.9859
Epoch 492/500
 - 0s - loss: 0.0296 - acc: 0.9859
Epoch 493/500
 - 0s - loss: 0.0284 - acc: 0.9883
Epoch 494/500
 - 0s - loss: 0.0270 - acc: 0.9871
Epoch 495/500
 - 0s - loss: 0.0295 - acc: 0.9912
Epoch 496/500
 - 0s - loss: 0.0447 - acc: 0.9818
Epoch 497/500
 - 0s - loss: 0.0366 - acc: 0.9848
Epoch 498/500
 - 0s - loss: 0.0294 - acc: 0.9877
Epoch 499/500
 - 0s - loss: 0.0303 - acc: 0.9889

Epoch 500/500
 - 0s - loss: 0.0278 - acc: 0.9883

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 0.4881 - acc: 0.9209
Normal Neural Network - Loss: 0.4881400749142984, Accuracy: 0.9209138751029968

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Certified' 'Certified' 'Certified' 'Certified' 'Certified'
 'Certified' 'Certified' 'Denied' 'Certified']
Actual Labels: ['Certified', 'Denied', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Denied', 'Certified']