In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'THAILAND']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

THAILAND    740
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    701
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [8]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [9]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [10]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
696,Certified,467,63141,MISSOURI,1750.0,88992.0,THAILAND,H-1B,Master's,5.0
743,Certified,165,95052,CALIFORNIA,46544.0,80000.0,THAILAND,F-1,Master's,11.0
1254,Certified,183,95131,CALIFORNIA,1669.0,109200.0,THAILAND,H-1B,Doctorate,2.0
1277,Certified,203,10020,NEW YORK,3900.0,160000.0,THAILAND,H-1B,Master's,2.0
2443,Certified,189,95670,CALIFORNIA,9.0,23795.0,THAILAND,F-1,None,2.0

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

CALIFORNIA              189
VIRGINIA                 79
WASHINGTON               50
NEW YORK                 42
ILLINOIS                 40
DISTRICT OF COLUMBIA     35
TEXAS                    28
OREGON                   26
MARYLAND                 26
MASSACHUSETTS            19
FLORIDA                  18
PENNSYLVANIA             18
GEORGIA                  16
NORTH CAROLINA           15
NEW JERSEY               10
OHIO                      8
KANSAS                    7
MICHIGAN                  6
MISSOURI                  6
WISCONSIN                 6
MINNESOTA                 5
ARIZONA                   5
INDIANA                   5
TENNESSEE                 4
NORTH DAKOTA              4
NEVADA                    3
IOWA                      3
MAINE                     3
SOUTH DAKOTA              3
HAWAII                    2
OKLAHOMA                  2
RHODE ISLAND              2
CONNECTICUT               2
GUAM                      2
LOUISIANA                 1
IDAHO                     1
UNKNOWN                   1
ALABAMA                   1
KENTUCKY                  1
SOUTH CAROLINA            1
WEST VIRGINIA             1
ALASKA                    1
ARKANSAS                  1
UTAH                      1
NEW HAMPSHIRE             1
MISSISSIPPI               1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
696,Certified,467,63141,MISSOURI,1750.0,88992.0,THAILAND,H-1B,Master's,5.0,MISSOURI
743,Certified,165,95052,CALIFORNIA,46544.0,80000.0,THAILAND,F-1,Master's,11.0,CALIFORNIA
1254,Certified,183,95131,CALIFORNIA,1669.0,109200.0,THAILAND,H-1B,Doctorate,2.0,CALIFORNIA
1277,Certified,203,10020,NEW YORK,3900.0,160000.0,THAILAND,H-1B,Master's,2.0,NEW YORK
2443,Certified,189,95670,CALIFORNIA,9.0,23795.0,THAILAND,F-1,None,2.0,CALIFORNIA

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

WEST         257
SOUTH        126
MIDWEST       81
NORTHEAST     79
OTHER          2
UNKNOWN        1
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      546
DECISION_ELAPSED_DAYS            546
EMPLOYER_POSTAL_CODE             546
EMPLOYER_STATE                   546
EMPLOYER_NUM_EMPLOYEES           546
WAGE_OFFER_FROM_9089             546
COUNTRY_OF_CITIZENSHIP           546
CLASS_OF_ADMISSION               546
FOREIGN_WORKER_INFO_EDUCATION    546
CASE_RECEIVED_DATE_MONTH         546
EMPLOYER_STATES                  546
EMPLOYER_REGIONS                 546
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      193
181-365     147
0-90        141
366-3600     64
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

25001-50000      209
100000-500000    114
75001-100000      90
50001-75000       79
0-25000           53
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

0-50                324
10001-1000000000     84
1001-10000           54
101-500              40
51-100               24
501-1000             19
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      546
DECISION_ELAPSED_DAYS            546
EMPLOYER_POSTAL_CODE             546
EMPLOYER_STATE                   546
EMPLOYER_NUM_EMPLOYEES           546
WAGE_OFFER_FROM_9089             546
COUNTRY_OF_CITIZENSHIP           546
CLASS_OF_ADMISSION               546
FOREIGN_WORKER_INFO_EDUCATION    546
CASE_RECEIVED_DATE_MONTH         546
EMPLOYER_STATES                  546
EMPLOYER_REGIONS                 546
DAY_BINS                         545
WAGE_BINS                        545
EMPLOYEE_BINS                    545
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
696,Certified,1001-10000,75001-100000,MIDWEST,5.0,Master's,H-1B,366-3600
743,Certified,10001-1000000000,75001-100000,WEST,11.0,Master's,F-1,91-180
1254,Certified,1001-10000,100000-500000,WEST,2.0,Doctorate,H-1B,181-365
1277,Certified,1001-10000,100000-500000,NORTHEAST,2.0,Master's,H-1B,181-365
2443,Certified,0-50,0-25000,WEST,2.0,None,F-1,181-365

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
696,Certified,1001-10000,75001-100000,MIDWEST,5.0,Master's,H-1B,366-3600,7,4,4,0,2,2
743,Certified,10001-1000000000,75001-100000,WEST,11.0,Master's,F-1,91-180,4,4,4,5,3,1
1254,Certified,1001-10000,100000-500000,WEST,2.0,Doctorate,H-1B,181-365,7,2,1,5,1,2
1277,Certified,1001-10000,100000-500000,NORTHEAST,2.0,Master's,H-1B,181-365,7,4,1,1,1,2
2443,Certified,0-50,0-25000,WEST,2.0,None,F-1,181-365,4,5,0,5,1,0

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           546
EMPLOYEE_BINS                         546
WAGE_BINS                             546
EMPLOYER_REGIONS                      546
CASE_RECEIVED_DATE_MONTH              546
FOREIGN_WORKER_INFO_EDUCATION         546
CLASS_OF_ADMISSION                    546
DAY_BINS                              546
CLASS_OF_ADMISSION_CODE               546
FOREIGN_WORKER_INFO_EDUCATION_CODE    546
WAGE_BINS_CODE                        546
EMPLOYER_REGIONS_CODE                 546
DAY_BINS_CODE                         546
EMPLOYEE_BINS_CODE                    546
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
696,Certified,2,4,2,4,7,5.0,0
743,Certified,1,4,3,4,4,11.0,5
1254,Certified,2,1,1,2,7,2.0,5
1277,Certified,2,1,1,4,7,2.0,1
2443,Certified,0,0,1,5,4,2.0,5

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int64
WAGE_BINS_CODE                          int64
DAY_BINS_CODE                           int64
FOREIGN_WORKER_INFO_EDUCATION_CODE      int64
CLASS_OF_ADMISSION_CODE                 int64
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int64
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(546, 7) (546,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [53]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 1s - loss: 0.5589 - acc: 0.8166
Epoch 2/500
 - 0s - loss: 0.4377 - acc: 0.8435
Epoch 3/500
 - 0s - loss: 0.4296 - acc: 0.8435
Epoch 4/500
 - 0s - loss: 0.4225 - acc: 0.8435
Epoch 5/500
 - 0s - loss: 0.4182 - acc: 0.8435
Epoch 6/500
 - 0s - loss: 0.4143 - acc: 0.8435
Epoch 7/500
 - 0s - loss: 0.4120 - acc: 0.8435
Epoch 8/500
 - 0s - loss: 0.4068 - acc: 0.8435
Epoch 9/500
 - 0s - loss: 0.4044 - acc: 0.8435
Epoch 10/500
 - 0s - loss: 0.4039 - acc: 0.8435
Epoch 11/500
 - 0s - loss: 0.3999 - acc: 0.8435
Epoch 12/500
 - 0s - loss: 0.3949 - acc: 0.8435
Epoch 13/500
 - 0s - loss: 0.3934 - acc: 0.8435
Epoch 14/500
 - 0s - loss: 0.3893 - acc: 0.8435
Epoch 15/500
 - 0s - loss: 0.3872 - acc: 0.8435
Epoch 16/500
 - 0s - loss: 0.3851 - acc: 0.8435
Epoch 17/500
 - 0s - loss: 0.3839 - acc: 0.8435
Epoch 18/500
 - 0s - loss: 0.3788 - acc: 0.8435
Epoch 19/500
 - 0s - loss: 0.3761 - acc: 0.8435
Epoch 20/500
 - 0s - loss: 0.3718 - acc: 0.8435
Epoch 21/500
 - 0s - loss: 0.3666 - acc: 0.8435
Epoch 22/500
 - 0s - loss: 0.3625 - acc: 0.8435
Epoch 23/500
 - 0s - loss: 0.3610 - acc: 0.8435
Epoch 24/500
 - 0s - loss: 0.3597 - acc: 0.8435
Epoch 25/500
 - 0s - loss: 0.3504 - acc: 0.8460
Epoch 26/500
 - 0s - loss: 0.3468 - acc: 0.8435
Epoch 27/500
 - 0s - loss: 0.3436 - acc: 0.8460
Epoch 28/500
 - 0s - loss: 0.3365 - acc: 0.8435
Epoch 29/500
 - 0s - loss: 0.3319 - acc: 0.8509
Epoch 30/500
 - 0s - loss: 0.3277 - acc: 0.8509
Epoch 31/500
 - 0s - loss: 0.3222 - acc: 0.8509
Epoch 32/500
 - 0s - loss: 0.3162 - acc: 0.8509
Epoch 33/500
 - 0s - loss: 0.3102 - acc: 0.8557
Epoch 34/500
 - 0s - loss: 0.3044 - acc: 0.8557
Epoch 35/500
 - 0s - loss: 0.2998 - acc: 0.8533
Epoch 36/500
 - 0s - loss: 0.2914 - acc: 0.8533
Epoch 37/500
 - 0s - loss: 0.2959 - acc: 0.8582
Epoch 38/500
 - 0s - loss: 0.2814 - acc: 0.8606
Epoch 39/500
 - 0s - loss: 0.2768 - acc: 0.8582
Epoch 40/500
 - 0s - loss: 0.2702 - acc: 0.8680
Epoch 41/500
 - 0s - loss: 0.2660 - acc: 0.8704
Epoch 42/500
 - 0s - loss: 0.2636 - acc: 0.8606
Epoch 43/500
 - 0s - loss: 0.2648 - acc: 0.8949
Epoch 44/500
 - 0s - loss: 0.2524 - acc: 0.8778
Epoch 45/500
 - 0s - loss: 0.2534 - acc: 0.8826
Epoch 46/500
 - 0s - loss: 0.2495 - acc: 0.8851
Epoch 47/500
 - 0s - loss: 0.2383 - acc: 0.8851
Epoch 48/500
 - 0s - loss: 0.2462 - acc: 0.8802
Epoch 49/500
 - 0s - loss: 0.2385 - acc: 0.8973
Epoch 50/500
 - 0s - loss: 0.2307 - acc: 0.8900
Epoch 51/500
 - 0s - loss: 0.2270 - acc: 0.9095
Epoch 52/500
 - 0s - loss: 0.2169 - acc: 0.9046
Epoch 53/500
 - 0s - loss: 0.2123 - acc: 0.8998
Epoch 54/500
 - 0s - loss: 0.2114 - acc: 0.9046
Epoch 55/500
 - 0s - loss: 0.2080 - acc: 0.8973
Epoch 56/500
 - 0s - loss: 0.2027 - acc: 0.9169
Epoch 57/500
 - 0s - loss: 0.2028 - acc: 0.9046
Epoch 58/500
 - 0s - loss: 0.2018 - acc: 0.9193
Epoch 59/500
 - 0s - loss: 0.2000 - acc: 0.9169
Epoch 60/500
 - 0s - loss: 0.1935 - acc: 0.9120
Epoch 61/500
 - 0s - loss: 0.1942 - acc: 0.9144
Epoch 62/500
 - 0s - loss: 0.1928 - acc: 0.9046
Epoch 63/500
 - 0s - loss: 0.1920 - acc: 0.9095
Epoch 64/500
 - 0s - loss: 0.1848 - acc: 0.9340
Epoch 65/500
 - 0s - loss: 0.1834 - acc: 0.9144
Epoch 66/500
 - 0s - loss: 0.1777 - acc: 0.9315
Epoch 67/500
 - 0s - loss: 0.1726 - acc: 0.9364
Epoch 68/500
 - 0s - loss: 0.1697 - acc: 0.9242
Epoch 69/500
 - 0s - loss: 0.1718 - acc: 0.9267
Epoch 70/500
 - 0s - loss: 0.1661 - acc: 0.9462
Epoch 71/500
 - 0s - loss: 0.1709 - acc: 0.9242
Epoch 72/500
 - 0s - loss: 0.1659 - acc: 0.9389
Epoch 73/500
 - 0s - loss: 0.1608 - acc: 0.9438
Epoch 74/500
 - 0s - loss: 0.1621 - acc: 0.9364
Epoch 75/500
 - 0s - loss: 0.1567 - acc: 0.9413
Epoch 76/500
 - 0s - loss: 0.1603 - acc: 0.9438
Epoch 77/500
 - 0s - loss: 0.1600 - acc: 0.9389
Epoch 78/500
 - 0s - loss: 0.1557 - acc: 0.9364
Epoch 79/500
 - 0s - loss: 0.1549 - acc: 0.9438
Epoch 80/500
 - 0s - loss: 0.1499 - acc: 0.9511
Epoch 81/500
 - 0s - loss: 0.1464 - acc: 0.9584
Epoch 82/500
 - 0s - loss: 0.1544 - acc: 0.9364
Epoch 83/500
 - 0s - loss: 0.1509 - acc: 0.9511
Epoch 84/500
 - 0s - loss: 0.1503 - acc: 0.9389
Epoch 85/500
 - 0s - loss: 0.1423 - acc: 0.9560
Epoch 86/500
 - 0s - loss: 0.1393 - acc: 0.9511
Epoch 87/500
 - 0s - loss: 0.1425 - acc: 0.9487
Epoch 88/500
 - 0s - loss: 0.1405 - acc: 0.9487
Epoch 89/500
 - 0s - loss: 0.1399 - acc: 0.9511
Epoch 90/500
 - 0s - loss: 0.1356 - acc: 0.9535
Epoch 91/500
 - 0s - loss: 0.1365 - acc: 0.9584
Epoch 92/500
 - 0s - loss: 0.1350 - acc: 0.9584
Epoch 93/500
 - 0s - loss: 0.1328 - acc: 0.9511
Epoch 94/500
 - 0s - loss: 0.1309 - acc: 0.9609
Epoch 95/500
 - 0s - loss: 0.1317 - acc: 0.9535
Epoch 96/500
 - 0s - loss: 0.1351 - acc: 0.9560
Epoch 97/500
 - 0s - loss: 0.1299 - acc: 0.9560
Epoch 98/500
 - 0s - loss: 0.1240 - acc: 0.9658
Epoch 99/500
 - 0s - loss: 0.1250 - acc: 0.9560
Epoch 100/500
 - 0s - loss: 0.1226 - acc: 0.9633
Epoch 101/500
 - 0s - loss: 0.1243 - acc: 0.9658
Epoch 102/500
 - 0s - loss: 0.1221 - acc: 0.9633
Epoch 103/500
 - 0s - loss: 0.1236 - acc: 0.9560
Epoch 104/500
 - 0s - loss: 0.1321 - acc: 0.9535
Epoch 105/500
 - 0s - loss: 0.1204 - acc: 0.9560
Epoch 106/500
 - 0s - loss: 0.1243 - acc: 0.9633
Epoch 107/500
 - 0s - loss: 0.1173 - acc: 0.9658
Epoch 108/500
 - 0s - loss: 0.1210 - acc: 0.9609
Epoch 109/500
 - 0s - loss: 0.1241 - acc: 0.9560
Epoch 110/500
 - 0s - loss: 0.1179 - acc: 0.9731
Epoch 111/500
 - 0s - loss: 0.1149 - acc: 0.9633
Epoch 112/500
 - 0s - loss: 0.1243 - acc: 0.9438
Epoch 113/500
 - 0s - loss: 0.1107 - acc: 0.9633
Epoch 114/500
 - 0s - loss: 0.1156 - acc: 0.9633
Epoch 115/500
 - 0s - loss: 0.1107 - acc: 0.9682
Epoch 116/500
 - 0s - loss: 0.1073 - acc: 0.9658
Epoch 117/500
 - 0s - loss: 0.1096 - acc: 0.9707
Epoch 118/500
 - 0s - loss: 0.1085 - acc: 0.9584
Epoch 119/500
 - 0s - loss: 0.1122 - acc: 0.9633
Epoch 120/500
 - 0s - loss: 0.1099 - acc: 0.9658
Epoch 121/500
 - 0s - loss: 0.1058 - acc: 0.9682
Epoch 122/500
 - 0s - loss: 0.1039 - acc: 0.9707
Epoch 123/500
 - 0s - loss: 0.0997 - acc: 0.9731
Epoch 124/500
 - 0s - loss: 0.1050 - acc: 0.9707
Epoch 125/500
 - 0s - loss: 0.0991 - acc: 0.9707
Epoch 126/500
 - 0s - loss: 0.1015 - acc: 0.9658
Epoch 127/500
 - 0s - loss: 0.1002 - acc: 0.9682
Epoch 128/500
 - 0s - loss: 0.0991 - acc: 0.9707
Epoch 129/500
 - 0s - loss: 0.0958 - acc: 0.9731
Epoch 130/500
 - 0s - loss: 0.0949 - acc: 0.9707
Epoch 131/500
 - 0s - loss: 0.1010 - acc: 0.9633
Epoch 132/500
 - 0s - loss: 0.0960 - acc: 0.9707
Epoch 133/500
 - 0s - loss: 0.0967 - acc: 0.9731
Epoch 134/500
 - 0s - loss: 0.0939 - acc: 0.9707
Epoch 135/500
 - 0s - loss: 0.0945 - acc: 0.9658
Epoch 136/500
 - 0s - loss: 0.0939 - acc: 0.9682
Epoch 137/500
 - 0s - loss: 0.0948 - acc: 0.9731
Epoch 138/500
 - 0s - loss: 0.0940 - acc: 0.9682
Epoch 139/500
 - 0s - loss: 0.0958 - acc: 0.9682
Epoch 140/500
 - 0s - loss: 0.0912 - acc: 0.9707
Epoch 141/500
 - 0s - loss: 0.0939 - acc: 0.9731
Epoch 142/500
 - 0s - loss: 0.0891 - acc: 0.9682
Epoch 143/500
 - 0s - loss: 0.0881 - acc: 0.9731
Epoch 144/500
 - 0s - loss: 0.0892 - acc: 0.9731
Epoch 145/500
 - 0s - loss: 0.0906 - acc: 0.9756
Epoch 146/500
 - 0s - loss: 0.0861 - acc: 0.9707
Epoch 147/500
 - 0s - loss: 0.0883 - acc: 0.9756
Epoch 148/500
 - 0s - loss: 0.0837 - acc: 0.9731
Epoch 149/500
 - 0s - loss: 0.0856 - acc: 0.9731
Epoch 150/500
 - 0s - loss: 0.0853 - acc: 0.9756
Epoch 151/500
 - 0s - loss: 0.0883 - acc: 0.9756
Epoch 152/500
 - 0s - loss: 0.0930 - acc: 0.9658
Epoch 153/500
 - 0s - loss: 0.0836 - acc: 0.9682
Epoch 154/500
 - 0s - loss: 0.0788 - acc: 0.9756
Epoch 155/500
 - 0s - loss: 0.0828 - acc: 0.9682
Epoch 156/500
 - 0s - loss: 0.0779 - acc: 0.9780
Epoch 157/500
 - 0s - loss: 0.0801 - acc: 0.9756
Epoch 158/500
 - 0s - loss: 0.0792 - acc: 0.9731
Epoch 159/500
 - 0s - loss: 0.0792 - acc: 0.9756
Epoch 160/500
 - 0s - loss: 0.0767 - acc: 0.9731
Epoch 161/500
 - 0s - loss: 0.0756 - acc: 0.9804
Epoch 162/500
 - 0s - loss: 0.0766 - acc: 0.9756
Epoch 163/500
 - 0s - loss: 0.0853 - acc: 0.9731
Epoch 164/500
 - 0s - loss: 0.0912 - acc: 0.9658

Epoch 165/500
 - 0s - loss: 0.0887 - acc: 0.9756
Epoch 166/500
 - 0s - loss: 0.0779 - acc: 0.9756
Epoch 167/500
 - 0s - loss: 0.0735 - acc: 0.9707
Epoch 168/500
 - 0s - loss: 0.0725 - acc: 0.9756
Epoch 169/500
 - 0s - loss: 0.0740 - acc: 0.9756
Epoch 170/500
 - 0s - loss: 0.0723 - acc: 0.9756
Epoch 171/500
 - 0s - loss: 0.0740 - acc: 0.9756
Epoch 172/500
 - 0s - loss: 0.0779 - acc: 0.9682
Epoch 173/500
 - 0s - loss: 0.0738 - acc: 0.9756
Epoch 174/500
 - 0s - loss: 0.0751 - acc: 0.9731
Epoch 175/500
 - 0s - loss: 0.0719 - acc: 0.9658
Epoch 176/500
 - 0s - loss: 0.0688 - acc: 0.9731
Epoch 177/500
 - 0s - loss: 0.0688 - acc: 0.9780
Epoch 178/500
 - 0s - loss: 0.0684 - acc: 0.9756
Epoch 179/500
 - 0s - loss: 0.0668 - acc: 0.9756
Epoch 180/500
 - 0s - loss: 0.0694 - acc: 0.9731
Epoch 181/500
 - 0s - loss: 0.0693 - acc: 0.9731
Epoch 182/500
 - 0s - loss: 0.0685 - acc: 0.9780
Epoch 183/500
 - 0s - loss: 0.0683 - acc: 0.9707
Epoch 184/500
 - 0s - loss: 0.0664 - acc: 0.9756
Epoch 185/500
 - 0s - loss: 0.0682 - acc: 0.9780
Epoch 186/500
 - 0s - loss: 0.0636 - acc: 0.9756
Epoch 187/500
 - 0s - loss: 0.0645 - acc: 0.9707
Epoch 188/500
 - 0s - loss: 0.0666 - acc: 0.9829
Epoch 189/500
 - 0s - loss: 0.0645 - acc: 0.9804
Epoch 190/500
 - 0s - loss: 0.0639 - acc: 0.9756
Epoch 191/500
 - 0s - loss: 0.0685 - acc: 0.9731
Epoch 192/500
 - 0s - loss: 0.0719 - acc: 0.9756
Epoch 193/500
 - 0s - loss: 0.0720 - acc: 0.9804
Epoch 194/500
 - 0s - loss: 0.0650 - acc: 0.9780
Epoch 195/500
 - 0s - loss: 0.0655 - acc: 0.9780
Epoch 196/500
 - 0s - loss: 0.0650 - acc: 0.9731
Epoch 197/500
 - 0s - loss: 0.0620 - acc: 0.9731
Epoch 198/500
 - 0s - loss: 0.0600 - acc: 0.9804
Epoch 199/500
 - 0s - loss: 0.0601 - acc: 0.9780
Epoch 200/500
 - 0s - loss: 0.0603 - acc: 0.9780
Epoch 201/500
 - 0s - loss: 0.0580 - acc: 0.9780
Epoch 202/500
 - 0s - loss: 0.0591 - acc: 0.9829
Epoch 203/500
 - 0s - loss: 0.0582 - acc: 0.9780
Epoch 204/500
 - 0s - loss: 0.0617 - acc: 0.9780
Epoch 205/500
 - 0s - loss: 0.0591 - acc: 0.9780
Epoch 206/500
 - 0s - loss: 0.0642 - acc: 0.9804
Epoch 207/500
 - 0s - loss: 0.0569 - acc: 0.9780
Epoch 208/500
 - 0s - loss: 0.0581 - acc: 0.9780
Epoch 209/500
 - 0s - loss: 0.0559 - acc: 0.9780
Epoch 210/500
 - 0s - loss: 0.0555 - acc: 0.9780
Epoch 211/500
 - 0s - loss: 0.0622 - acc: 0.9780
Epoch 212/500
 - 0s - loss: 0.0620 - acc: 0.9804
Epoch 213/500
 - 0s - loss: 0.0644 - acc: 0.9707
Epoch 214/500
 - 0s - loss: 0.0647 - acc: 0.9780
Epoch 215/500
 - 0s - loss: 0.0585 - acc: 0.9829
Epoch 216/500
 - 0s - loss: 0.0543 - acc: 0.9829
Epoch 217/500
 - 0s - loss: 0.0543 - acc: 0.9780
Epoch 218/500
 - 0s - loss: 0.0621 - acc: 0.9780
Epoch 219/500
 - 0s - loss: 0.0616 - acc: 0.9731
Epoch 220/500
 - 0s - loss: 0.0591 - acc: 0.9682
Epoch 221/500
 - 0s - loss: 0.0565 - acc: 0.9829
Epoch 222/500
 - 0s - loss: 0.0596 - acc: 0.9756
Epoch 223/500
 - 0s - loss: 0.0623 - acc: 0.9804
Epoch 224/500
 - 0s - loss: 0.0569 - acc: 0.9756
Epoch 225/500
 - 0s - loss: 0.0609 - acc: 0.9756
Epoch 226/500
 - 0s - loss: 0.0545 - acc: 0.9780
Epoch 227/500
 - 0s - loss: 0.0528 - acc: 0.9756
Epoch 228/500
 - 0s - loss: 0.0556 - acc: 0.9756
Epoch 229/500
 - 0s - loss: 0.0563 - acc: 0.9756
Epoch 230/500
 - 0s - loss: 0.0488 - acc: 0.9804
Epoch 231/500
 - 0s - loss: 0.0524 - acc: 0.9853
Epoch 232/500
 - 0s - loss: 0.0522 - acc: 0.9780
Epoch 233/500
 - 0s - loss: 0.0545 - acc: 0.9804
Epoch 234/500
 - 0s - loss: 0.0543 - acc: 0.9780
Epoch 235/500
 - 0s - loss: 0.0511 - acc: 0.9804
Epoch 236/500
 - 0s - loss: 0.0535 - acc: 0.9804
Epoch 237/500
 - 0s - loss: 0.0534 - acc: 0.9804
Epoch 238/500
 - 0s - loss: 0.0575 - acc: 0.9780
Epoch 239/500
 - 0s - loss: 0.0491 - acc: 0.9853
Epoch 240/500
 - 0s - loss: 0.0491 - acc: 0.9829
Epoch 241/500
 - 0s - loss: 0.0510 - acc: 0.9780
Epoch 242/500
 - 0s - loss: 0.0498 - acc: 0.9829
Epoch 243/500
 - 0s - loss: 0.0547 - acc: 0.9756
Epoch 244/500
 - 0s - loss: 0.0498 - acc: 0.9829
Epoch 245/500
 - 0s - loss: 0.0479 - acc: 0.9829
Epoch 246/500
 - 0s - loss: 0.0488 - acc: 0.9804
Epoch 247/500
 - 0s - loss: 0.0519 - acc: 0.9829
Epoch 248/500
 - 0s - loss: 0.0492 - acc: 0.9804
Epoch 249/500
 - 0s - loss: 0.0479 - acc: 0.9780
Epoch 250/500
 - 0s - loss: 0.0578 - acc: 0.9756
Epoch 251/500
 - 0s - loss: 0.0573 - acc: 0.9780
Epoch 252/500
 - 0s - loss: 0.0489 - acc: 0.9756
Epoch 253/500
 - 0s - loss: 0.0550 - acc: 0.9731
Epoch 254/500
 - 0s - loss: 0.0510 - acc: 0.9756
Epoch 255/500
 - 0s - loss: 0.0459 - acc: 0.9829
Epoch 256/500
 - 0s - loss: 0.0459 - acc: 0.9804
Epoch 257/500
 - 0s - loss: 0.0480 - acc: 0.9780
Epoch 258/500
 - 0s - loss: 0.0473 - acc: 0.9804
Epoch 259/500
 - 0s - loss: 0.0461 - acc: 0.9853
Epoch 260/500
 - 0s - loss: 0.0496 - acc: 0.9780
Epoch 261/500
 - 0s - loss: 0.0461 - acc: 0.9853
Epoch 262/500
 - 0s - loss: 0.0483 - acc: 0.9829
Epoch 263/500
 - 0s - loss: 0.0499 - acc: 0.9804
Epoch 264/500
 - 0s - loss: 0.0426 - acc: 0.9829
Epoch 265/500
 - 0s - loss: 0.0458 - acc: 0.9804
Epoch 266/500
 - 0s - loss: 0.0461 - acc: 0.9804
Epoch 267/500
 - 0s - loss: 0.0443 - acc: 0.9804
Epoch 268/500
 - 0s - loss: 0.0448 - acc: 0.9829
Epoch 269/500
 - 0s - loss: 0.0405 - acc: 0.9878
Epoch 270/500
 - 0s - loss: 0.0473 - acc: 0.9804
Epoch 271/500
 - 0s - loss: 0.0507 - acc: 0.9804
Epoch 272/500
 - 0s - loss: 0.0443 - acc: 0.9829
Epoch 273/500
 - 0s - loss: 0.0419 - acc: 0.9853
Epoch 274/500
 - 0s - loss: 0.0433 - acc: 0.9804
Epoch 275/500
 - 0s - loss: 0.0413 - acc: 0.9829
Epoch 276/500
 - 0s - loss: 0.0430 - acc: 0.9804
Epoch 277/500
 - 0s - loss: 0.0438 - acc: 0.9804
Epoch 278/500
 - 0s - loss: 0.0415 - acc: 0.9804
Epoch 279/500
 - 0s - loss: 0.0388 - acc: 0.9829
Epoch 280/500
 - 0s - loss: 0.0414 - acc: 0.9829
Epoch 281/500
 - 0s - loss: 0.0407 - acc: 0.9829
Epoch 282/500
 - 0s - loss: 0.0495 - acc: 0.9780
Epoch 283/500
 - 0s - loss: 0.0450 - acc: 0.9804
Epoch 284/500
 - 0s - loss: 0.0433 - acc: 0.9829
Epoch 285/500
 - 0s - loss: 0.0419 - acc: 0.9804
Epoch 286/500
 - 0s - loss: 0.0415 - acc: 0.9829
Epoch 287/500
 - 0s - loss: 0.0430 - acc: 0.9853
Epoch 288/500
 - 0s - loss: 0.0470 - acc: 0.9756
Epoch 289/500
 - 0s - loss: 0.0488 - acc: 0.9756
Epoch 290/500
 - 0s - loss: 0.0442 - acc: 0.9804
Epoch 291/500
 - 0s - loss: 0.0417 - acc: 0.9804
Epoch 292/500
 - 0s - loss: 0.0479 - acc: 0.9780
Epoch 293/500
 - 0s - loss: 0.0402 - acc: 0.9829
Epoch 294/500
 - 0s - loss: 0.0477 - acc: 0.9804
Epoch 295/500
 - 0s - loss: 0.0443 - acc: 0.9804
Epoch 296/500
 - 0s - loss: 0.0400 - acc: 0.9829
Epoch 297/500
 - 0s - loss: 0.0424 - acc: 0.9829
Epoch 298/500
 - 0s - loss: 0.0418 - acc: 0.9829
Epoch 299/500
 - 0s - loss: 0.0428 - acc: 0.9853
Epoch 300/500
 - 0s - loss: 0.0382 - acc: 0.9829
Epoch 301/500
 - 0s - loss: 0.0414 - acc: 0.9780
Epoch 302/500
 - 0s - loss: 0.0423 - acc: 0.9878
Epoch 303/500
 - 0s - loss: 0.0416 - acc: 0.9829
Epoch 304/500
 - 0s - loss: 0.0399 - acc: 0.9853
Epoch 305/500
 - 0s - loss: 0.0421 - acc: 0.9878
Epoch 306/500
 - 0s - loss: 0.0411 - acc: 0.9804
Epoch 307/500
 - 0s - loss: 0.0438 - acc: 0.9853
Epoch 308/500
 - 0s - loss: 0.0433 - acc: 0.9804
Epoch 309/500
 - 0s - loss: 0.0407 - acc: 0.9878
Epoch 310/500
 - 0s - loss: 0.0479 - acc: 0.9804
Epoch 311/500
 - 0s - loss: 0.0684 - acc: 0.9658
Epoch 312/500
 - 0s - loss: 0.0659 - acc: 0.9756
Epoch 313/500
 - 0s - loss: 0.0526 - acc: 0.9780
Epoch 314/500
 - 0s - loss: 0.0455 - acc: 0.9804
Epoch 315/500
 - 0s - loss: 0.0512 - acc: 0.9804
Epoch 316/500
 - 0s - loss: 0.0525 - acc: 0.9804
Epoch 317/500
 - 0s - loss: 0.0466 - acc: 0.9829
Epoch 318/500
 - 0s - loss: 0.0420 - acc: 0.9878
Epoch 319/500
 - 0s - loss: 0.0451 - acc: 0.9853
Epoch 320/500
 - 0s - loss: 0.0506 - acc: 0.9731
Epoch 321/500
 - 0s - loss: 0.0438 - acc: 0.9780
Epoch 322/500
 - 0s - loss: 0.0451 - acc: 0.9829
Epoch 323/500
 - 0s - loss: 0.0362 - acc: 0.9829
Epoch 324/500
 - 0s - loss: 0.0350 - acc: 0.9878
Epoch 325/500
 - 0s - loss: 0.0385 - acc: 0.9829
Epoch 326/500
 - 0s - loss: 0.0364 - acc: 0.9780
Epoch 327/500
 - 0s - loss: 0.0386 - acc: 0.9829
Epoch 328/500
 - 0s - loss: 0.0478 - acc: 0.9756
Epoch 329/500
 - 0s - loss: 0.0448 - acc: 0.9756
Epoch 330/500
 - 0s - loss: 0.0356 - acc: 0.9853
Epoch 331/500
 - 0s - loss: 0.0362 - acc: 0.9829
Epoch 332/500
 - 0s - loss: 0.0355 - acc: 0.9829

Epoch 333/500
 - 0s - loss: 0.0350 - acc: 0.9878
Epoch 334/500
 - 0s - loss: 0.0330 - acc: 0.9853
Epoch 335/500
 - 0s - loss: 0.0374 - acc: 0.9829
Epoch 336/500
 - 0s - loss: 0.0346 - acc: 0.9829
Epoch 337/500
 - 0s - loss: 0.0368 - acc: 0.9829
Epoch 338/500
 - 0s - loss: 0.0362 - acc: 0.9878
Epoch 339/500
 - 0s - loss: 0.0336 - acc: 0.9853
Epoch 340/500
 - 0s - loss: 0.0344 - acc: 0.9878
Epoch 341/500
 - 0s - loss: 0.0410 - acc: 0.9829
Epoch 342/500
 - 0s - loss: 0.0347 - acc: 0.9853
Epoch 343/500
 - 0s - loss: 0.0336 - acc: 0.9878
Epoch 344/500
 - 0s - loss: 0.0350 - acc: 0.9853
Epoch 345/500
 - 0s - loss: 0.0331 - acc: 0.9902
Epoch 346/500
 - 0s - loss: 0.0373 - acc: 0.9878
Epoch 347/500
 - 0s - loss: 0.0408 - acc: 0.9829
Epoch 348/500
 - 0s - loss: 0.0366 - acc: 0.9829
Epoch 349/500
 - 0s - loss: 0.0476 - acc: 0.9756
Epoch 350/500
 - 0s - loss: 0.0577 - acc: 0.9756
Epoch 351/500
 - 0s - loss: 0.0417 - acc: 0.9829
Epoch 352/500
 - 0s - loss: 0.0404 - acc: 0.9853
Epoch 353/500
 - 0s - loss: 0.0348 - acc: 0.9804
Epoch 354/500
 - 0s - loss: 0.0336 - acc: 0.9878
Epoch 355/500
 - 0s - loss: 0.0367 - acc: 0.9853
Epoch 356/500
 - 0s - loss: 0.0314 - acc: 0.9853
Epoch 357/500
 - 0s - loss: 0.0401 - acc: 0.9756
Epoch 358/500
 - 0s - loss: 0.0465 - acc: 0.9804
Epoch 359/500
 - 0s - loss: 0.0334 - acc: 0.9878
Epoch 360/500
 - 0s - loss: 0.0330 - acc: 0.9829
Epoch 361/500
 - 0s - loss: 0.0327 - acc: 0.9878
Epoch 362/500
 - 0s - loss: 0.0334 - acc: 0.9878
Epoch 363/500
 - 0s - loss: 0.0304 - acc: 0.9902
Epoch 364/500
 - 0s - loss: 0.0323 - acc: 0.9878
Epoch 365/500
 - 0s - loss: 0.0365 - acc: 0.9804
Epoch 366/500
 - 0s - loss: 0.0373 - acc: 0.9804
Epoch 367/500
 - 0s - loss: 0.0356 - acc: 0.9853
Epoch 368/500
 - 0s - loss: 0.0341 - acc: 0.9853
Epoch 369/500
 - 0s - loss: 0.0387 - acc: 0.9829
Epoch 370/500
 - 0s - loss: 0.0498 - acc: 0.9804
Epoch 371/500
 - 0s - loss: 0.0359 - acc: 0.9853
Epoch 372/500
 - 0s - loss: 0.0408 - acc: 0.9756
Epoch 373/500
 - 0s - loss: 0.0313 - acc: 0.9853
Epoch 374/500
 - 0s - loss: 0.0320 - acc: 0.9829
Epoch 375/500
 - 0s - loss: 0.0329 - acc: 0.9878
Epoch 376/500
 - 0s - loss: 0.0326 - acc: 0.9853
Epoch 377/500
 - 0s - loss: 0.0333 - acc: 0.9878
Epoch 378/500
 - 0s - loss: 0.0314 - acc: 0.9829
Epoch 379/500
 - 0s - loss: 0.0285 - acc: 0.9878
Epoch 380/500
 - 0s - loss: 0.0301 - acc: 0.9853
Epoch 381/500
 - 0s - loss: 0.0298 - acc: 0.9902
Epoch 382/500
 - 0s - loss: 0.0307 - acc: 0.9902
Epoch 383/500
 - 0s - loss: 0.0302 - acc: 0.9878
Epoch 384/500
 - 0s - loss: 0.0299 - acc: 0.9878
Epoch 385/500
 - 0s - loss: 0.0318 - acc: 0.9853
Epoch 386/500
 - 0s - loss: 0.0306 - acc: 0.9829
Epoch 387/500
 - 0s - loss: 0.0380 - acc: 0.9804
Epoch 388/500
 - 0s - loss: 0.0336 - acc: 0.9829
Epoch 389/500
 - 0s - loss: 0.0360 - acc: 0.9878
Epoch 390/500
 - 0s - loss: 0.0355 - acc: 0.9878
Epoch 391/500
 - 0s - loss: 0.0321 - acc: 0.9878
Epoch 392/500
 - 0s - loss: 0.0318 - acc: 0.9878
Epoch 393/500
 - 0s - loss: 0.0298 - acc: 0.9878
Epoch 394/500
 - 0s - loss: 0.0407 - acc: 0.9829
Epoch 395/500
 - 0s - loss: 0.0345 - acc: 0.9878
Epoch 396/500
 - 0s - loss: 0.0334 - acc: 0.9853
Epoch 397/500
 - 0s - loss: 0.0306 - acc: 0.9878
Epoch 398/500
 - 0s - loss: 0.0323 - acc: 0.9853
Epoch 399/500
 - 0s - loss: 0.0393 - acc: 0.9804
Epoch 400/500
 - 0s - loss: 0.0344 - acc: 0.9878
Epoch 401/500
 - 0s - loss: 0.0287 - acc: 0.9878
Epoch 402/500
 - 0s - loss: 0.0296 - acc: 0.9853
Epoch 403/500
 - 0s - loss: 0.0335 - acc: 0.9853
Epoch 404/500
 - 0s - loss: 0.0320 - acc: 0.9902
Epoch 405/500
 - 0s - loss: 0.0343 - acc: 0.9853
Epoch 406/500
 - 0s - loss: 0.0326 - acc: 0.9853
Epoch 407/500
 - 0s - loss: 0.0360 - acc: 0.9829
Epoch 408/500
 - 0s - loss: 0.0429 - acc: 0.9829
Epoch 409/500
 - 0s - loss: 0.0399 - acc: 0.9878
Epoch 410/500
 - 0s - loss: 0.0530 - acc: 0.9707
Epoch 411/500
 - 0s - loss: 0.0312 - acc: 0.9853
Epoch 412/500
 - 0s - loss: 0.0386 - acc: 0.9853
Epoch 413/500
 - 0s - loss: 0.0435 - acc: 0.9780
Epoch 414/500
 - 0s - loss: 0.0374 - acc: 0.9853
Epoch 415/500
 - 0s - loss: 0.0323 - acc: 0.9829
Epoch 416/500
 - 0s - loss: 0.0394 - acc: 0.9829
Epoch 417/500
 - 0s - loss: 0.0316 - acc: 0.9853
Epoch 418/500
 - 0s - loss: 0.0281 - acc: 0.9902
Epoch 419/500
 - 0s - loss: 0.0312 - acc: 0.9853
Epoch 420/500
 - 0s - loss: 0.0296 - acc: 0.9878
Epoch 421/500
 - 0s - loss: 0.0334 - acc: 0.9804
Epoch 422/500
 - 0s - loss: 0.0283 - acc: 0.9902
Epoch 423/500
 - 0s - loss: 0.0323 - acc: 0.9878
Epoch 424/500
 - 0s - loss: 0.0391 - acc: 0.9804
Epoch 425/500
 - 0s - loss: 0.0358 - acc: 0.9780
Epoch 426/500
 - 0s - loss: 0.0311 - acc: 0.9878
Epoch 427/500
 - 0s - loss: 0.0354 - acc: 0.9853
Epoch 428/500
 - 0s - loss: 0.0336 - acc: 0.9902
Epoch 429/500
 - 0s - loss: 0.0289 - acc: 0.9902
Epoch 430/500
 - 0s - loss: 0.0319 - acc: 0.9853
Epoch 431/500
 - 0s - loss: 0.0324 - acc: 0.9853
Epoch 432/500
 - 0s - loss: 0.0324 - acc: 0.9878
Epoch 433/500
 - 0s - loss: 0.0412 - acc: 0.9829
Epoch 434/500
 - 0s - loss: 0.0362 - acc: 0.9804
Epoch 435/500
 - 0s - loss: 0.0315 - acc: 0.9902
Epoch 436/500
 - 0s - loss: 0.0293 - acc: 0.9902
Epoch 437/500
 - 0s - loss: 0.0390 - acc: 0.9853
Epoch 438/500
 - 0s - loss: 0.0353 - acc: 0.9853
Epoch 439/500
 - 0s - loss: 0.0273 - acc: 0.9902
Epoch 440/500
 - 0s - loss: 0.0309 - acc: 0.9902
Epoch 441/500
 - 0s - loss: 0.0280 - acc: 0.9902
Epoch 442/500
 - 0s - loss: 0.0286 - acc: 0.9902
Epoch 443/500
 - 0s - loss: 0.0291 - acc: 0.9878
Epoch 444/500
 - 0s - loss: 0.0302 - acc: 0.9804
Epoch 445/500
 - 0s - loss: 0.0272 - acc: 0.9902
Epoch 446/500
 - 0s - loss: 0.0331 - acc: 0.9878
Epoch 447/500
 - 0s - loss: 0.0272 - acc: 0.9878
Epoch 448/500
 - 0s - loss: 0.0268 - acc: 0.9902
Epoch 449/500
 - 0s - loss: 0.0278 - acc: 0.9829
Epoch 450/500
 - 0s - loss: 0.0296 - acc: 0.9878
Epoch 451/500
 - 0s - loss: 0.0262 - acc: 0.9878
Epoch 452/500
 - 0s - loss: 0.0270 - acc: 0.9853
Epoch 453/500
 - 0s - loss: 0.0324 - acc: 0.9853
Epoch 454/500
 - 0s - loss: 0.0282 - acc: 0.9853
Epoch 455/500
 - 0s - loss: 0.0287 - acc: 0.9878
Epoch 456/500
 - 0s - loss: 0.0298 - acc: 0.9804
Epoch 457/500
 - 0s - loss: 0.0267 - acc: 0.9902
Epoch 458/500
 - 0s - loss: 0.0279 - acc: 0.9902
Epoch 459/500
 - 0s - loss: 0.0305 - acc: 0.9878
Epoch 460/500
 - 0s - loss: 0.0312 - acc: 0.9804
Epoch 461/500
 - 0s - loss: 0.0300 - acc: 0.9878
Epoch 462/500
 - 0s - loss: 0.0277 - acc: 0.9878
Epoch 463/500
 - 0s - loss: 0.0250 - acc: 0.9902
Epoch 464/500
 - 0s - loss: 0.0259 - acc: 0.9902
Epoch 465/500
 - 0s - loss: 0.0305 - acc: 0.9829
Epoch 466/500
 - 0s - loss: 0.0273 - acc: 0.9853
Epoch 467/500
 - 0s - loss: 0.0264 - acc: 0.9902
Epoch 468/500
 - 0s - loss: 0.0284 - acc: 0.9853
Epoch 469/500
 - 0s - loss: 0.0290 - acc: 0.9902
Epoch 470/500
 - 0s - loss: 0.0376 - acc: 0.9829
Epoch 471/500
 - 0s - loss: 0.0271 - acc: 0.9853
Epoch 472/500
 - 0s - loss: 0.0290 - acc: 0.9853
Epoch 473/500
 - 0s - loss: 0.0267 - acc: 0.9878
Epoch 474/500
 - 0s - loss: 0.0270 - acc: 0.9804
Epoch 475/500
 - 0s - loss: 0.0272 - acc: 0.9878
Epoch 476/500
 - 0s - loss: 0.0325 - acc: 0.9853
Epoch 477/500
 - 0s - loss: 0.0300 - acc: 0.9902
Epoch 478/500
 - 0s - loss: 0.0294 - acc: 0.9902
Epoch 479/500
 - 0s - loss: 0.0335 - acc: 0.9829
Epoch 480/500
 - 0s - loss: 0.0332 - acc: 0.9878
Epoch 481/500
 - 0s - loss: 0.0398 - acc: 0.9853
Epoch 482/500
 - 0s - loss: 0.0428 - acc: 0.9853
Epoch 483/500
 - 0s - loss: 0.0378 - acc: 0.9756
Epoch 484/500
 - 0s - loss: 0.0410 - acc: 0.9853
Epoch 485/500
 - 0s - loss: 0.0457 - acc: 0.9731
Epoch 486/500
 - 0s - loss: 0.0356 - acc: 0.9878
Epoch 487/500
 - 0s - loss: 0.0330 - acc: 0.9902
Epoch 488/500
 - 0s - loss: 0.0287 - acc: 0.9829
Epoch 489/500
 - 0s - loss: 0.0362 - acc: 0.9804
Epoch 490/500
 - 0s - loss: 0.0308 - acc: 0.9853
Epoch 491/500
 - 0s - loss: 0.0280 - acc: 0.9878
Epoch 492/500
 - 0s - loss: 0.0321 - acc: 0.9829
Epoch 493/500
 - 0s - loss: 0.0358 - acc: 0.9878
Epoch 494/500
 - 0s - loss: 0.0389 - acc: 0.9804
Epoch 495/500
 - 0s - loss: 0.0259 - acc: 0.9902
Epoch 496/500
 - 0s - loss: 0.0271 - acc: 0.9878
Epoch 497/500
 - 0s - loss: 0.0294 - acc: 0.9853
Epoch 498/500
 - 0s - loss: 0.0292 - acc: 0.9902
Epoch 499/500
 - 0s - loss: 0.0273 - acc: 0.9878
Epoch 500/500

 - 0s - loss: 0.0268 - acc: 0.9878

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 1.4192 - acc: 0.8175
Normal Neural Network - Loss: 1.4191976559423183, Accuracy: 0.8175182342529297

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Certified' 'Denied' 'Certified' 'Certified' 'Certified'
 'Certified' 'Certified' 'Certified' 'Certified']
Actual Labels: ['Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Denied']