In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'UNITED KINGDOM']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

UNITED KINGDOM    2809
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    2707
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [8]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [9]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [10]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
345,Certified,538,28273,NORTH CAROLINA,25000.0,95389.0,UNITED KINGDOM,H-1B,None,1.0
457,Certified,495,10001,NEW YORK,12.0,54080.0,UNITED KINGDOM,H-1B,Master's,1.0
466,Certified,587,92630,CALIFORNIA,3134.0,99590.0,UNITED KINGDOM,H-1B,Bachelor's,10.0
552,Certified,235,94103,CALIFORNIA,1800.0,128000.0,UNITED KINGDOM,H-1B,Master's,9.0
557,Certified,171,60606,ILLINOIS,81.0,180000.0,UNITED KINGDOM,L-1,Bachelor's,11.0

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

CALIFORNIA              701
NEW YORK                477
TEXAS                   201
FLORIDA                 177
WASHINGTON              118
ILLINOIS                111
NEW JERSEY              105
MASSACHUSETTS            89
PENNSYLVANIA             66
NORTH CAROLINA           56
CONNECTICUT              55
MICHIGAN                 53
VIRGINIA                 51
GEORGIA                  49
OHIO                     40
COLORADO                 32
MARYLAND                 27
WISCONSIN                24
DISTRICT OF COLUMBIA     22
KANSAS                   20
ARIZONA                  18
INDIANA                  17
OREGON                   15
MISSOURI                 15
MINNESOTA                14
SOUTH CAROLINA           14
LOUISIANA                13
TENNESSEE                12
NEW HAMPSHIRE            10
ARKANSAS                 10
UTAH                      9
ALABAMA                   9
IOWA                      8
KENTUCKY                  8
NEBRASKA                  8
RHODE ISLAND              7
NEVADA                    7
NEW MEXICO                7
DELAWARE                  6
OKLAHOMA                  5
SOUTH DAKOTA              3
MONTANA                   3
UNKNOWN                   3
ALASKA                    2
MAINE                     2
MISSISSIPPI               2
HAWAII                    2
NORTH DAKOTA              1
WEST VIRGINIA             1
WYOMING                   1
IDAHO                     1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
345,Certified,538,28273,NORTH CAROLINA,25000.0,95389.0,UNITED KINGDOM,H-1B,None,1.0,NORTH CAROLINA
457,Certified,495,10001,NEW YORK,12.0,54080.0,UNITED KINGDOM,H-1B,Master's,1.0,NEW YORK
466,Certified,587,92630,CALIFORNIA,3134.0,99590.0,UNITED KINGDOM,H-1B,Bachelor's,10.0,CALIFORNIA
552,Certified,235,94103,CALIFORNIA,1800.0,128000.0,UNITED KINGDOM,H-1B,Master's,9.0,CALIFORNIA
557,Certified,171,60606,ILLINOIS,81.0,180000.0,UNITED KINGDOM,L-1,Bachelor's,11.0,ILLINOIS

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

WEST         855
NORTHEAST    784
SOUTH        610
MIDWEST      292
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      2541
DECISION_ELAPSED_DAYS            2541
EMPLOYER_POSTAL_CODE             2541
EMPLOYER_STATE                   2541
EMPLOYER_NUM_EMPLOYEES           2541
WAGE_OFFER_FROM_9089             2541
COUNTRY_OF_CITIZENSHIP           2541
CLASS_OF_ADMISSION               2541
FOREIGN_WORKER_INFO_EDUCATION    2541
CASE_RECEIVED_DATE_MONTH         2541
EMPLOYER_STATES                  2541
EMPLOYER_REGIONS                 2541
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      1024
0-90         704
181-365      542
366-3600     267
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

100000-500000    1575
75001-100000      472
50001-75000       327
25001-50000       154
0-25000            10
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

10001-1000000000    701
0-50                569
1001-10000          547
101-500             406
501-1000            167
51-100              147
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      2541
DECISION_ELAPSED_DAYS            2541
EMPLOYER_POSTAL_CODE             2541
EMPLOYER_STATE                   2541
EMPLOYER_NUM_EMPLOYEES           2541
WAGE_OFFER_FROM_9089             2541
COUNTRY_OF_CITIZENSHIP           2541
CLASS_OF_ADMISSION               2541
FOREIGN_WORKER_INFO_EDUCATION    2541
CASE_RECEIVED_DATE_MONTH         2541
EMPLOYER_STATES                  2541
EMPLOYER_REGIONS                 2541
DAY_BINS                         2537
WAGE_BINS                        2538
EMPLOYEE_BINS                    2537
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
345,Certified,10001-1000000000,75001-100000,SOUTH,1.0,None,H-1B,366-3600
457,Certified,0-50,50001-75000,NORTHEAST,1.0,Master's,H-1B,366-3600
466,Certified,1001-10000,75001-100000,WEST,10.0,Bachelor's,H-1B,366-3600
552,Certified,1001-10000,100000-500000,WEST,9.0,Master's,H-1B,181-365
557,Certified,51-100,100000-500000,MIDWEST,11.0,Bachelor's,L-1,91-180

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
345,Certified,10001-1000000000,75001-100000,SOUTH,1.0,None,H-1B,366-3600,8,5,4,2,2,1
457,Certified,0-50,50001-75000,NORTHEAST,1.0,Master's,H-1B,366-3600,8,4,3,1,2,0
466,Certified,1001-10000,75001-100000,WEST,10.0,Bachelor's,H-1B,366-3600,8,1,4,3,2,2
552,Certified,1001-10000,100000-500000,WEST,9.0,Master's,H-1B,181-365,8,4,1,3,1,2
557,Certified,51-100,100000-500000,MIDWEST,11.0,Bachelor's,L-1,91-180,16,1,1,0,3,5

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           2541
EMPLOYEE_BINS                         2541
WAGE_BINS                             2541
EMPLOYER_REGIONS                      2541
CASE_RECEIVED_DATE_MONTH              2541
FOREIGN_WORKER_INFO_EDUCATION         2541
CLASS_OF_ADMISSION                    2541
DAY_BINS                              2541
CLASS_OF_ADMISSION_CODE               2541
FOREIGN_WORKER_INFO_EDUCATION_CODE    2541
WAGE_BINS_CODE                        2541
EMPLOYER_REGIONS_CODE                 2541
DAY_BINS_CODE                         2541
EMPLOYEE_BINS_CODE                    2541
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
345,Certified,1,4,2,5,8,1.0,2
457,Certified,0,3,2,4,8,1.0,1
466,Certified,2,4,2,1,8,10.0,3
552,Certified,2,1,1,4,8,9.0,3
557,Certified,5,1,3,1,16,11.0,0

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int64
WAGE_BINS_CODE                          int64
DAY_BINS_CODE                           int64
FOREIGN_WORKER_INFO_EDUCATION_CODE      int64
CLASS_OF_ADMISSION_CODE                 int64
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int64
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(2541, 7) (2541,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [53]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 1s - loss: 0.3968 - acc: 0.8719
Epoch 2/500
 - 0s - loss: 0.3302 - acc: 0.8987
Epoch 3/500
 - 0s - loss: 0.3211 - acc: 0.8987
Epoch 4/500
 - 0s - loss: 0.3135 - acc: 0.8987
Epoch 5/500
 - 0s - loss: 0.3084 - acc: 0.8987
Epoch 6/500
 - 0s - loss: 0.2994 - acc: 0.8987
Epoch 7/500
 - 0s - loss: 0.2954 - acc: 0.8987
Epoch 8/500
 - 0s - loss: 0.2901 - acc: 0.8987
Epoch 9/500
 - 0s - loss: 0.2845 - acc: 0.8987
Epoch 10/500
 - 0s - loss: 0.2800 - acc: 0.8987
Epoch 11/500
 - 0s - loss: 0.2757 - acc: 0.8987
Epoch 12/500
 - 0s - loss: 0.2707 - acc: 0.8987
Epoch 13/500
 - 0s - loss: 0.2665 - acc: 0.8982
Epoch 14/500
 - 0s - loss: 0.2616 - acc: 0.8992
Epoch 15/500
 - 0s - loss: 0.2608 - acc: 0.8997
Epoch 16/500
 - 0s - loss: 0.2557 - acc: 0.9018
Epoch 17/500
 - 0s - loss: 0.2511 - acc: 0.8997
Epoch 18/500
 - 0s - loss: 0.2488 - acc: 0.9008
Epoch 19/500
 - 0s - loss: 0.2448 - acc: 0.9050
Epoch 20/500
 - 0s - loss: 0.2418 - acc: 0.9029
Epoch 21/500
 - 0s - loss: 0.2394 - acc: 0.9050
Epoch 22/500
 - 0s - loss: 0.2379 - acc: 0.9092
Epoch 23/500
 - 0s - loss: 0.2340 - acc: 0.9071
Epoch 24/500
 - 0s - loss: 0.2389 - acc: 0.9071
Epoch 25/500
 - 0s - loss: 0.2323 - acc: 0.9087
Epoch 26/500
 - 0s - loss: 0.2292 - acc: 0.9118
Epoch 27/500
 - 0s - loss: 0.2294 - acc: 0.9087
Epoch 28/500
 - 0s - loss: 0.2321 - acc: 0.9076
Epoch 29/500
 - 0s - loss: 0.2243 - acc: 0.9087
Epoch 30/500
 - 0s - loss: 0.2204 - acc: 0.9139
Epoch 31/500
 - 0s - loss: 0.2241 - acc: 0.9144
Epoch 32/500
 - 0s - loss: 0.2221 - acc: 0.9108
Epoch 33/500
 - 0s - loss: 0.2201 - acc: 0.9129
Epoch 34/500
 - 0s - loss: 0.2162 - acc: 0.9181
Epoch 35/500
 - 0s - loss: 0.2191 - acc: 0.9139
Epoch 36/500
 - 0s - loss: 0.2152 - acc: 0.9150
Epoch 37/500
 - 0s - loss: 0.2134 - acc: 0.9139
Epoch 38/500
 - 0s - loss: 0.2161 - acc: 0.9144
Epoch 39/500
 - 0s - loss: 0.2126 - acc: 0.9202
Epoch 40/500
 - 0s - loss: 0.2093 - acc: 0.9197
Epoch 41/500
 - 0s - loss: 0.2119 - acc: 0.9186
Epoch 42/500
 - 0s - loss: 0.2095 - acc: 0.9213
Epoch 43/500
 - 0s - loss: 0.2078 - acc: 0.9213
Epoch 44/500
 - 0s - loss: 0.2079 - acc: 0.9218
Epoch 45/500
 - 0s - loss: 0.2061 - acc: 0.9213
Epoch 46/500
 - 0s - loss: 0.2068 - acc: 0.9176
Epoch 47/500
 - 0s - loss: 0.2049 - acc: 0.9192
Epoch 48/500
 - 0s - loss: 0.2053 - acc: 0.9228
Epoch 49/500
 - 0s - loss: 0.1984 - acc: 0.9228
Epoch 50/500
 - 0s - loss: 0.2038 - acc: 0.9207
Epoch 51/500
 - 0s - loss: 0.2006 - acc: 0.9249
Epoch 52/500
 - 0s - loss: 0.1991 - acc: 0.9244
Epoch 53/500
 - 0s - loss: 0.2047 - acc: 0.9197
Epoch 54/500
 - 0s - loss: 0.1968 - acc: 0.9239
Epoch 55/500
 - 0s - loss: 0.1970 - acc: 0.9239
Epoch 56/500
 - 0s - loss: 0.1928 - acc: 0.9260
Epoch 57/500
 - 0s - loss: 0.1954 - acc: 0.9228
Epoch 58/500
 - 0s - loss: 0.1924 - acc: 0.9202
Epoch 59/500
 - 0s - loss: 0.1920 - acc: 0.9260
Epoch 60/500
 - 0s - loss: 0.1902 - acc: 0.9255
Epoch 61/500
 - 0s - loss: 0.1893 - acc: 0.9270
Epoch 62/500
 - 0s - loss: 0.1889 - acc: 0.9276
Epoch 63/500
 - 0s - loss: 0.1871 - acc: 0.9276
Epoch 64/500
 - 0s - loss: 0.1901 - acc: 0.9281
Epoch 65/500
 - 0s - loss: 0.1838 - acc: 0.9297
Epoch 66/500
 - 0s - loss: 0.1818 - acc: 0.9349
Epoch 67/500
 - 0s - loss: 0.1857 - acc: 0.9286
Epoch 68/500
 - 0s - loss: 0.1819 - acc: 0.9328
Epoch 69/500
 - 0s - loss: 0.1820 - acc: 0.9339
Epoch 70/500
 - 0s - loss: 0.1816 - acc: 0.9323
Epoch 71/500
 - 0s - loss: 0.1795 - acc: 0.9318
Epoch 72/500
 - 0s - loss: 0.1775 - acc: 0.9297
Epoch 73/500
 - 0s - loss: 0.1763 - acc: 0.9312
Epoch 74/500
 - 0s - loss: 0.1752 - acc: 0.9333
Epoch 75/500
 - 0s - loss: 0.1766 - acc: 0.9302
Epoch 76/500
 - 0s - loss: 0.1745 - acc: 0.9349
Epoch 77/500
 - 0s - loss: 0.1737 - acc: 0.9365
Epoch 78/500
 - 0s - loss: 0.1728 - acc: 0.9344
Epoch 79/500
 - 0s - loss: 0.1721 - acc: 0.9370
Epoch 80/500
 - 0s - loss: 0.1711 - acc: 0.9360
Epoch 81/500
 - 0s - loss: 0.1744 - acc: 0.9354
Epoch 82/500
 - 0s - loss: 0.1682 - acc: 0.9381
Epoch 83/500
 - 0s - loss: 0.1642 - acc: 0.9428
Epoch 84/500
 - 0s - loss: 0.1673 - acc: 0.9370
Epoch 85/500
 - 0s - loss: 0.1661 - acc: 0.9370
Epoch 86/500
 - 0s - loss: 0.1629 - acc: 0.9396
Epoch 87/500
 - 0s - loss: 0.1622 - acc: 0.9375
Epoch 88/500
 - 0s - loss: 0.1688 - acc: 0.9381
Epoch 89/500
 - 0s - loss: 0.1626 - acc: 0.9391
Epoch 90/500
 - 0s - loss: 0.1599 - acc: 0.9396
Epoch 91/500
 - 0s - loss: 0.1613 - acc: 0.9386
Epoch 92/500
 - 0s - loss: 0.1641 - acc: 0.9381
Epoch 93/500
 - 0s - loss: 0.1602 - acc: 0.9449
Epoch 94/500
 - 0s - loss: 0.1550 - acc: 0.9428
Epoch 95/500
 - 0s - loss: 0.1611 - acc: 0.9423
Epoch 96/500
 - 0s - loss: 0.1603 - acc: 0.9386
Epoch 97/500
 - 0s - loss: 0.1546 - acc: 0.9449
Epoch 98/500
 - 0s - loss: 0.1525 - acc: 0.9465
Epoch 99/500
 - 0s - loss: 0.1523 - acc: 0.9423
Epoch 100/500
 - 0s - loss: 0.1524 - acc: 0.9444
Epoch 101/500
 - 0s - loss: 0.1529 - acc: 0.9438
Epoch 102/500
 - 0s - loss: 0.1481 - acc: 0.9496
Epoch 103/500
 - 0s - loss: 0.1485 - acc: 0.9449
Epoch 104/500
 - 0s - loss: 0.1471 - acc: 0.9470
Epoch 105/500
 - 0s - loss: 0.1481 - acc: 0.9486
Epoch 106/500
 - 0s - loss: 0.1437 - acc: 0.9486
Epoch 107/500
 - 0s - loss: 0.1455 - acc: 0.9465
Epoch 108/500
 - 0s - loss: 0.1459 - acc: 0.9496
Epoch 109/500
 - 0s - loss: 0.1427 - acc: 0.9496
Epoch 110/500
 - 0s - loss: 0.1475 - acc: 0.9449
Epoch 111/500
 - 0s - loss: 0.1454 - acc: 0.9444
Epoch 112/500
 - 0s - loss: 0.1505 - acc: 0.9459
Epoch 113/500
 - 0s - loss: 0.1418 - acc: 0.9528
Epoch 114/500
 - 0s - loss: 0.1432 - acc: 0.9486
Epoch 115/500
 - 0s - loss: 0.1389 - acc: 0.9543
Epoch 116/500
 - 0s - loss: 0.1372 - acc: 0.9522
Epoch 117/500
 - 0s - loss: 0.1363 - acc: 0.9522
Epoch 118/500
 - 0s - loss: 0.1348 - acc: 0.9549
Epoch 119/500
 - 0s - loss: 0.1345 - acc: 0.9554
Epoch 120/500
 - 0s - loss: 0.1368 - acc: 0.9496
Epoch 121/500
 - 0s - loss: 0.1353 - acc: 0.9470
Epoch 122/500
 - 0s - loss: 0.1373 - acc: 0.9491
Epoch 123/500
 - 0s - loss: 0.1301 - acc: 0.9507
Epoch 124/500
 - 0s - loss: 0.1319 - acc: 0.9543
Epoch 125/500
 - 0s - loss: 0.1319 - acc: 0.9543
Epoch 126/500
 - 0s - loss: 0.1327 - acc: 0.9475
Epoch 127/500
 - 0s - loss: 0.1275 - acc: 0.9543
Epoch 128/500
 - 0s - loss: 0.1270 - acc: 0.9533
Epoch 129/500
 - 0s - loss: 0.1308 - acc: 0.9496
Epoch 130/500
 - 0s - loss: 0.1297 - acc: 0.9538
Epoch 131/500
 - 0s - loss: 0.1255 - acc: 0.9591
Epoch 132/500
 - 0s - loss: 0.1256 - acc: 0.9564
Epoch 133/500
 - 0s - loss: 0.1226 - acc: 0.9591
Epoch 134/500
 - 0s - loss: 0.1246 - acc: 0.9543
Epoch 135/500
 - 0s - loss: 0.1256 - acc: 0.9559
Epoch 136/500
 - 0s - loss: 0.1214 - acc: 0.9596
Epoch 137/500
 - 0s - loss: 0.1309 - acc: 0.9528
Epoch 138/500
 - 0s - loss: 0.1216 - acc: 0.9580
Epoch 139/500
 - 0s - loss: 0.1154 - acc: 0.9654
Epoch 140/500
 - 0s - loss: 0.1206 - acc: 0.9612
Epoch 141/500
 - 0s - loss: 0.1193 - acc: 0.9543
Epoch 142/500
 - 0s - loss: 0.1174 - acc: 0.9585
Epoch 143/500
 - 0s - loss: 0.1137 - acc: 0.9622
Epoch 144/500
 - 0s - loss: 0.1118 - acc: 0.9627
Epoch 145/500
 - 0s - loss: 0.1191 - acc: 0.9564
Epoch 146/500
 - 0s - loss: 0.1188 - acc: 0.9591
Epoch 147/500
 - 0s - loss: 0.1179 - acc: 0.9601
Epoch 148/500
 - 0s - loss: 0.1127 - acc: 0.9601
Epoch 149/500
 - 0s - loss: 0.1106 - acc: 0.9659
Epoch 150/500
 - 0s - loss: 0.1124 - acc: 0.9606
Epoch 151/500
 - 0s - loss: 0.1127 - acc: 0.9633
Epoch 152/500
 - 0s - loss: 0.1121 - acc: 0.9585
Epoch 153/500
 - 0s - loss: 0.1103 - acc: 0.9606
Epoch 154/500
 - 0s - loss: 0.1119 - acc: 0.9622
Epoch 155/500
 - 0s - loss: 0.1110 - acc: 0.9627
Epoch 156/500
 - 0s - loss: 0.1157 - acc: 0.9606
Epoch 157/500
 - 0s - loss: 0.1087 - acc: 0.9633
Epoch 158/500
 - 0s - loss: 0.1051 - acc: 0.9633
Epoch 159/500
 - 0s - loss: 0.1047 - acc: 0.9648
Epoch 160/500
 - 0s - loss: 0.1019 - acc: 0.9659
Epoch 161/500
 - 0s - loss: 0.1029 - acc: 0.9664
Epoch 162/500
 - 0s - loss: 0.1049 - acc: 0.9648
Epoch 163/500
 - 0s - loss: 0.1036 - acc: 0.9638
Epoch 164/500
 - 0s - loss: 0.1042 - acc: 0.9654

Epoch 165/500
 - 0s - loss: 0.1031 - acc: 0.9643
Epoch 166/500
 - 0s - loss: 0.1006 - acc: 0.9680
Epoch 167/500
 - 0s - loss: 0.1016 - acc: 0.9664
Epoch 168/500
 - 0s - loss: 0.0986 - acc: 0.9648
Epoch 169/500
 - 0s - loss: 0.1003 - acc: 0.9685
Epoch 170/500
 - 0s - loss: 0.0983 - acc: 0.9690
Epoch 171/500
 - 0s - loss: 0.0970 - acc: 0.9675
Epoch 172/500
 - 0s - loss: 0.0994 - acc: 0.9680
Epoch 173/500
 - 0s - loss: 0.1004 - acc: 0.9680
Epoch 174/500
 - 0s - loss: 0.1003 - acc: 0.9638
Epoch 175/500
 - 0s - loss: 0.0906 - acc: 0.9711
Epoch 176/500
 - 0s - loss: 0.0969 - acc: 0.9675
Epoch 177/500
 - 0s - loss: 0.0960 - acc: 0.9633
Epoch 178/500
 - 0s - loss: 0.0928 - acc: 0.9722
Epoch 179/500
 - 0s - loss: 0.0922 - acc: 0.9717
Epoch 180/500
 - 0s - loss: 0.1025 - acc: 0.9648
Epoch 181/500
 - 0s - loss: 0.0973 - acc: 0.9648
Epoch 182/500
 - 0s - loss: 0.0955 - acc: 0.9696
Epoch 183/500
 - 0s - loss: 0.0924 - acc: 0.9696
Epoch 184/500
 - 0s - loss: 0.0933 - acc: 0.9669
Epoch 185/500
 - 0s - loss: 0.0928 - acc: 0.9690
Epoch 186/500
 - 0s - loss: 0.0900 - acc: 0.9717
Epoch 187/500
 - 0s - loss: 0.0932 - acc: 0.9669
Epoch 188/500
 - 0s - loss: 0.0840 - acc: 0.9743
Epoch 189/500
 - 0s - loss: 0.0852 - acc: 0.9727
Epoch 190/500
 - 0s - loss: 0.0898 - acc: 0.9690
Epoch 191/500
 - 0s - loss: 0.0873 - acc: 0.9743
Epoch 192/500
 - 0s - loss: 0.0863 - acc: 0.9685
Epoch 193/500
 - 0s - loss: 0.0901 - acc: 0.9696
Epoch 194/500
 - 0s - loss: 0.0962 - acc: 0.9591
Epoch 195/500
 - 0s - loss: 0.0849 - acc: 0.9706
Epoch 196/500
 - 0s - loss: 0.0856 - acc: 0.9759
Epoch 197/500
 - 0s - loss: 0.0848 - acc: 0.9722
Epoch 198/500
 - 0s - loss: 0.0843 - acc: 0.9701
Epoch 199/500
 - 0s - loss: 0.0798 - acc: 0.9759
Epoch 200/500
 - 0s - loss: 0.0799 - acc: 0.9743
Epoch 201/500
 - 0s - loss: 0.0800 - acc: 0.9764
Epoch 202/500
 - 0s - loss: 0.0816 - acc: 0.9732
Epoch 203/500
 - 0s - loss: 0.0814 - acc: 0.9706
Epoch 204/500
 - 0s - loss: 0.0793 - acc: 0.9769
Epoch 205/500
 - 0s - loss: 0.0812 - acc: 0.9738
Epoch 206/500
 - 0s - loss: 0.0800 - acc: 0.9738
Epoch 207/500
 - 0s - loss: 0.0767 - acc: 0.9748
Epoch 208/500
 - 0s - loss: 0.0819 - acc: 0.9717
Epoch 209/500
 - 0s - loss: 0.0754 - acc: 0.9769
Epoch 210/500
 - 0s - loss: 0.0757 - acc: 0.9764
Epoch 211/500
 - 0s - loss: 0.0805 - acc: 0.9743
Epoch 212/500
 - 0s - loss: 0.0767 - acc: 0.9759
Epoch 213/500
 - 0s - loss: 0.0743 - acc: 0.9717
Epoch 214/500
 - 0s - loss: 0.0736 - acc: 0.9717
Epoch 215/500
 - 0s - loss: 0.0776 - acc: 0.9769
Epoch 216/500
 - 0s - loss: 0.0728 - acc: 0.9774
Epoch 217/500
 - 0s - loss: 0.0750 - acc: 0.9759
Epoch 218/500
 - 0s - loss: 0.0732 - acc: 0.9748
Epoch 219/500
 - 0s - loss: 0.0710 - acc: 0.9748
Epoch 220/500
 - 0s - loss: 0.0728 - acc: 0.9738
Epoch 221/500
 - 0s - loss: 0.0706 - acc: 0.9774
Epoch 222/500
 - 0s - loss: 0.0758 - acc: 0.9769
Epoch 223/500
 - 0s - loss: 0.0710 - acc: 0.9801
Epoch 224/500
 - 0s - loss: 0.0681 - acc: 0.9785
Epoch 225/500
 - 0s - loss: 0.0713 - acc: 0.9780
Epoch 226/500
 - 0s - loss: 0.0711 - acc: 0.9774
Epoch 227/500
 - 0s - loss: 0.0692 - acc: 0.9748
Epoch 228/500
 - 0s - loss: 0.0734 - acc: 0.9738
Epoch 229/500
 - 0s - loss: 0.0702 - acc: 0.9722
Epoch 230/500
 - 0s - loss: 0.0701 - acc: 0.9764
Epoch 231/500
 - 0s - loss: 0.0697 - acc: 0.9748
Epoch 232/500
 - 0s - loss: 0.0693 - acc: 0.9769
Epoch 233/500
 - 0s - loss: 0.0626 - acc: 0.9795
Epoch 234/500
 - 0s - loss: 0.0760 - acc: 0.9764
Epoch 235/500
 - 0s - loss: 0.0661 - acc: 0.9790
Epoch 236/500
 - 0s - loss: 0.0694 - acc: 0.9738
Epoch 237/500
 - 0s - loss: 0.0653 - acc: 0.9780
Epoch 238/500
 - 0s - loss: 0.0659 - acc: 0.9785
Epoch 239/500
 - 0s - loss: 0.0641 - acc: 0.9795
Epoch 240/500
 - 0s - loss: 0.0648 - acc: 0.9774
Epoch 241/500
 - 0s - loss: 0.0628 - acc: 0.9806
Epoch 242/500
 - 0s - loss: 0.0666 - acc: 0.9759
Epoch 243/500
 - 0s - loss: 0.0596 - acc: 0.9822
Epoch 244/500
 - 0s - loss: 0.0626 - acc: 0.9785
Epoch 245/500
 - 0s - loss: 0.0619 - acc: 0.9811
Epoch 246/500
 - 0s - loss: 0.0618 - acc: 0.9801
Epoch 247/500
 - 0s - loss: 0.0612 - acc: 0.9811
Epoch 248/500
 - 0s - loss: 0.0635 - acc: 0.9774
Epoch 249/500
 - 0s - loss: 0.0615 - acc: 0.9795
Epoch 250/500
 - 0s - loss: 0.0599 - acc: 0.9816
Epoch 251/500
 - 0s - loss: 0.0605 - acc: 0.9801
Epoch 252/500
 - 0s - loss: 0.0615 - acc: 0.9801
Epoch 253/500
 - 0s - loss: 0.0643 - acc: 0.9764
Epoch 254/500
 - 0s - loss: 0.0632 - acc: 0.9801
Epoch 255/500
 - 0s - loss: 0.0600 - acc: 0.9811
Epoch 256/500
 - 0s - loss: 0.0606 - acc: 0.9827
Epoch 257/500
 - 0s - loss: 0.0586 - acc: 0.9827
Epoch 258/500
 - 0s - loss: 0.0640 - acc: 0.9780
Epoch 259/500
 - 0s - loss: 0.0588 - acc: 0.9822
Epoch 260/500
 - 0s - loss: 0.0578 - acc: 0.9816
Epoch 261/500
 - 0s - loss: 0.0559 - acc: 0.9811
Epoch 262/500
 - 0s - loss: 0.0554 - acc: 0.9811
Epoch 263/500
 - 0s - loss: 0.0552 - acc: 0.9843
Epoch 264/500
 - 0s - loss: 0.0597 - acc: 0.9795
Epoch 265/500
 - 0s - loss: 0.0573 - acc: 0.9795
Epoch 266/500
 - 0s - loss: 0.0562 - acc: 0.9795
Epoch 267/500
 - 0s - loss: 0.0548 - acc: 0.9816
Epoch 268/500
 - 0s - loss: 0.0554 - acc: 0.9811
Epoch 269/500
 - 0s - loss: 0.0556 - acc: 0.9795
Epoch 270/500
 - 0s - loss: 0.0529 - acc: 0.9806
Epoch 271/500
 - 0s - loss: 0.0524 - acc: 0.9837
Epoch 272/500
 - 0s - loss: 0.0551 - acc: 0.9816
Epoch 273/500
 - 0s - loss: 0.0529 - acc: 0.9811
Epoch 274/500
 - 0s - loss: 0.0560 - acc: 0.9811
Epoch 275/500
 - 0s - loss: 0.0575 - acc: 0.9806
Epoch 276/500
 - 0s - loss: 0.0488 - acc: 0.9858
Epoch 277/500
 - 0s - loss: 0.0522 - acc: 0.9811
Epoch 278/500
 - 0s - loss: 0.0489 - acc: 0.9874
Epoch 279/500
 - 0s - loss: 0.0549 - acc: 0.9790
Epoch 280/500
 - 0s - loss: 0.0561 - acc: 0.9827
Epoch 281/500
 - 0s - loss: 0.0519 - acc: 0.9822
Epoch 282/500
 - 0s - loss: 0.0602 - acc: 0.9801
Epoch 283/500
 - 0s - loss: 0.0519 - acc: 0.9837
Epoch 284/500
 - 0s - loss: 0.0503 - acc: 0.9827
Epoch 285/500
 - 0s - loss: 0.0541 - acc: 0.9848
Epoch 286/500
 - 0s - loss: 0.0519 - acc: 0.9848
Epoch 287/500
 - 0s - loss: 0.0554 - acc: 0.9827
Epoch 288/500
 - 0s - loss: 0.0538 - acc: 0.9806
Epoch 289/500
 - 0s - loss: 0.0483 - acc: 0.9832
Epoch 290/500
 - 0s - loss: 0.0478 - acc: 0.9827
Epoch 291/500
 - 0s - loss: 0.0466 - acc: 0.9843
Epoch 292/500
 - 0s - loss: 0.0462 - acc: 0.9853
Epoch 293/500
 - 0s - loss: 0.0455 - acc: 0.9864
Epoch 294/500
 - 0s - loss: 0.0469 - acc: 0.9848
Epoch 295/500
 - 0s - loss: 0.0450 - acc: 0.9858
Epoch 296/500
 - 0s - loss: 0.0476 - acc: 0.9832
Epoch 297/500
 - 0s - loss: 0.0454 - acc: 0.9837
Epoch 298/500
 - 0s - loss: 0.0459 - acc: 0.9827
Epoch 299/500
 - 0s - loss: 0.0465 - acc: 0.9843
Epoch 300/500
 - 0s - loss: 0.0492 - acc: 0.9827
Epoch 301/500
 - 0s - loss: 0.0457 - acc: 0.9822
Epoch 302/500
 - 0s - loss: 0.0441 - acc: 0.9858
Epoch 303/500
 - 0s - loss: 0.0556 - acc: 0.9806
Epoch 304/500
 - 0s - loss: 0.0501 - acc: 0.9822
Epoch 305/500
 - 0s - loss: 0.0537 - acc: 0.9827
Epoch 306/500
 - 0s - loss: 0.0540 - acc: 0.9806
Epoch 307/500
 - 0s - loss: 0.0554 - acc: 0.9801
Epoch 308/500
 - 0s - loss: 0.0472 - acc: 0.9832
Epoch 309/500
 - 0s - loss: 0.0441 - acc: 0.9853
Epoch 310/500
 - 0s - loss: 0.0426 - acc: 0.9848
Epoch 311/500
 - 0s - loss: 0.0422 - acc: 0.9869
Epoch 312/500
 - 0s - loss: 0.0401 - acc: 0.9890
Epoch 313/500
 - 0s - loss: 0.0480 - acc: 0.9832
Epoch 314/500
 - 0s - loss: 0.0462 - acc: 0.9832
Epoch 315/500
 - 0s - loss: 0.0467 - acc: 0.9848
Epoch 316/500
 - 0s - loss: 0.0447 - acc: 0.9822
Epoch 317/500
 - 0s - loss: 0.0428 - acc: 0.9837
Epoch 318/500
 - 0s - loss: 0.0476 - acc: 0.9832
Epoch 319/500
 - 0s - loss: 0.0449 - acc: 0.9837
Epoch 320/500
 - 0s - loss: 0.0407 - acc: 0.9858
Epoch 321/500
 - 0s - loss: 0.0390 - acc: 0.9885
Epoch 322/500
 - 0s - loss: 0.0434 - acc: 0.9837
Epoch 323/500
 - 1s - loss: 0.0426 - acc: 0.9874
Epoch 324/500
 - 0s - loss: 0.0420 - acc: 0.9864
Epoch 325/500
 - 0s - loss: 0.0472 - acc: 0.9837
Epoch 326/500
 - 0s - loss: 0.0454 - acc: 0.9837
Epoch 327/500
 - 0s - loss: 0.0410 - acc: 0.9869
Epoch 328/500
 - 0s - loss: 0.0430 - acc: 0.9816
Epoch 329/500
 - 0s - loss: 0.0433 - acc: 0.9874
Epoch 330/500
 - 0s - loss: 0.0405 - acc: 0.9853
Epoch 331/500
 - 0s - loss: 0.0382 - acc: 0.9885
Epoch 332/500

 - 0s - loss: 0.0428 - acc: 0.9858
Epoch 333/500
 - 0s - loss: 0.0433 - acc: 0.9837
Epoch 334/500
 - 0s - loss: 0.0435 - acc: 0.9858
Epoch 335/500
 - 0s - loss: 0.0403 - acc: 0.9864
Epoch 336/500
 - 0s - loss: 0.0427 - acc: 0.9869
Epoch 337/500
 - 0s - loss: 0.0457 - acc: 0.9837
Epoch 338/500
 - 0s - loss: 0.0449 - acc: 0.9853
Epoch 339/500
 - 0s - loss: 0.0410 - acc: 0.9858
Epoch 340/500
 - 0s - loss: 0.0398 - acc: 0.9874
Epoch 341/500
 - 0s - loss: 0.0369 - acc: 0.9874
Epoch 342/500
 - 0s - loss: 0.0423 - acc: 0.9843
Epoch 343/500
 - 0s - loss: 0.0441 - acc: 0.9848
Epoch 344/500
 - 0s - loss: 0.0433 - acc: 0.9848
Epoch 345/500
 - 0s - loss: 0.0403 - acc: 0.9869
Epoch 346/500
 - 0s - loss: 0.0371 - acc: 0.9874
Epoch 347/500
 - 0s - loss: 0.0395 - acc: 0.9869
Epoch 348/500
 - 0s - loss: 0.0412 - acc: 0.9906
Epoch 349/500
 - 0s - loss: 0.0398 - acc: 0.9900
Epoch 350/500
 - 0s - loss: 0.0432 - acc: 0.9858
Epoch 351/500
 - 0s - loss: 0.0425 - acc: 0.9848
Epoch 352/500
 - 0s - loss: 0.0358 - acc: 0.9900
Epoch 353/500
 - 0s - loss: 0.0418 - acc: 0.9879
Epoch 354/500
 - 0s - loss: 0.0377 - acc: 0.9879
Epoch 355/500
 - 0s - loss: 0.0380 - acc: 0.9890
Epoch 356/500
 - 0s - loss: 0.0389 - acc: 0.9879
Epoch 357/500
 - 0s - loss: 0.0384 - acc: 0.9848
Epoch 358/500
 - 0s - loss: 0.0391 - acc: 0.9864
Epoch 359/500
 - 0s - loss: 0.0414 - acc: 0.9832
Epoch 360/500
 - 0s - loss: 0.0531 - acc: 0.9801
Epoch 361/500
 - 0s - loss: 0.0421 - acc: 0.9864
Epoch 362/500
 - 0s - loss: 0.0388 - acc: 0.9879
Epoch 363/500
 - 0s - loss: 0.0378 - acc: 0.9879
Epoch 364/500
 - 0s - loss: 0.0388 - acc: 0.9864
Epoch 365/500
 - 0s - loss: 0.0380 - acc: 0.9879
Epoch 366/500
 - 0s - loss: 0.0364 - acc: 0.9853
Epoch 367/500
 - 0s - loss: 0.0357 - acc: 0.9879
Epoch 368/500
 - 0s - loss: 0.0356 - acc: 0.9890
Epoch 369/500
 - 0s - loss: 0.0395 - acc: 0.9848
Epoch 370/500
 - 0s - loss: 0.0362 - acc: 0.9885
Epoch 371/500
 - 0s - loss: 0.0339 - acc: 0.9874
Epoch 372/500
 - 0s - loss: 0.0371 - acc: 0.9890
Epoch 373/500
 - 0s - loss: 0.0461 - acc: 0.9837
Epoch 374/500
 - 0s - loss: 0.0378 - acc: 0.9874
Epoch 375/500
 - 0s - loss: 0.0336 - acc: 0.9890
Epoch 376/500
 - 0s - loss: 0.0357 - acc: 0.9890
Epoch 377/500
 - 0s - loss: 0.0364 - acc: 0.9890
Epoch 378/500
 - 0s - loss: 0.0376 - acc: 0.9848
Epoch 379/500
 - 0s - loss: 0.0370 - acc: 0.9895
Epoch 380/500
 - 0s - loss: 0.0380 - acc: 0.9858
Epoch 381/500
 - 0s - loss: 0.0394 - acc: 0.9858
Epoch 382/500
 - 0s - loss: 0.0348 - acc: 0.9890
Epoch 383/500
 - 0s - loss: 0.0387 - acc: 0.9853
Epoch 384/500
 - 0s - loss: 0.0385 - acc: 0.9858
Epoch 385/500
 - 0s - loss: 0.0353 - acc: 0.9874
Epoch 386/500
 - 0s - loss: 0.0350 - acc: 0.9869
Epoch 387/500
 - 0s - loss: 0.0353 - acc: 0.9890
Epoch 388/500
 - 0s - loss: 0.0360 - acc: 0.9864
Epoch 389/500
 - 0s - loss: 0.0376 - acc: 0.9864
Epoch 390/500
 - 0s - loss: 0.0371 - acc: 0.9837
Epoch 391/500
 - 0s - loss: 0.0371 - acc: 0.9837
Epoch 392/500
 - 0s - loss: 0.0338 - acc: 0.9864
Epoch 393/500
 - 0s - loss: 0.0349 - acc: 0.9906
Epoch 394/500
 - 0s - loss: 0.0345 - acc: 0.9890
Epoch 395/500
 - 0s - loss: 0.0359 - acc: 0.9853
Epoch 396/500
 - 0s - loss: 0.0378 - acc: 0.9874
Epoch 397/500
 - 0s - loss: 0.0359 - acc: 0.9843
Epoch 398/500
 - 0s - loss: 0.0349 - acc: 0.9864
Epoch 399/500
 - 0s - loss: 0.0379 - acc: 0.9848
Epoch 400/500
 - 0s - loss: 0.0364 - acc: 0.9895
Epoch 401/500
 - 0s - loss: 0.0384 - acc: 0.9848
Epoch 402/500
 - 0s - loss: 0.0347 - acc: 0.9890
Epoch 403/500
 - 0s - loss: 0.0334 - acc: 0.9895
Epoch 404/500
 - 0s - loss: 0.0336 - acc: 0.9890
Epoch 405/500
 - 0s - loss: 0.0316 - acc: 0.9890
Epoch 406/500
 - 0s - loss: 0.0342 - acc: 0.9879
Epoch 407/500
 - 0s - loss: 0.0338 - acc: 0.9885
Epoch 408/500
 - 0s - loss: 0.0320 - acc: 0.9879
Epoch 409/500
 - 0s - loss: 0.0336 - acc: 0.9874
Epoch 410/500
 - 0s - loss: 0.0309 - acc: 0.9890
Epoch 411/500
 - 0s - loss: 0.0365 - acc: 0.9869
Epoch 412/500
 - 0s - loss: 0.0356 - acc: 0.9879
Epoch 413/500
 - 0s - loss: 0.0323 - acc: 0.9874
Epoch 414/500
 - 0s - loss: 0.0390 - acc: 0.9848
Epoch 415/500
 - 0s - loss: 0.0333 - acc: 0.9879
Epoch 416/500
 - 0s - loss: 0.0356 - acc: 0.9874
Epoch 417/500
 - 0s - loss: 0.0345 - acc: 0.9864
Epoch 418/500
 - 0s - loss: 0.0390 - acc: 0.9869
Epoch 419/500
 - 0s - loss: 0.0309 - acc: 0.9879
Epoch 420/500
 - 0s - loss: 0.0285 - acc: 0.9906
Epoch 421/500
 - 0s - loss: 0.0340 - acc: 0.9848
Epoch 422/500
 - 0s - loss: 0.0388 - acc: 0.9848
Epoch 423/500
 - 0s - loss: 0.0334 - acc: 0.9864
Epoch 424/500
 - 0s - loss: 0.0340 - acc: 0.9864
Epoch 425/500
 - 0s - loss: 0.0311 - acc: 0.9885
Epoch 426/500
 - 0s - loss: 0.0311 - acc: 0.9885
Epoch 427/500
 - 0s - loss: 0.0335 - acc: 0.9890
Epoch 428/500
 - 0s - loss: 0.0331 - acc: 0.9864
Epoch 429/500
 - 0s - loss: 0.0346 - acc: 0.9895
Epoch 430/500
 - 0s - loss: 0.0345 - acc: 0.9864
Epoch 431/500
 - 0s - loss: 0.0350 - acc: 0.9843
Epoch 432/500
 - 0s - loss: 0.0343 - acc: 0.9879
Epoch 433/500
 - 0s - loss: 0.0345 - acc: 0.9869
Epoch 434/500
 - 0s - loss: 0.0509 - acc: 0.9822
Epoch 435/500
 - 0s - loss: 0.0370 - acc: 0.9869
Epoch 436/500
 - 0s - loss: 0.0343 - acc: 0.9879
Epoch 437/500
 - 0s - loss: 0.0341 - acc: 0.9885
Epoch 438/500
 - 0s - loss: 0.0310 - acc: 0.9885
Epoch 439/500
 - 0s - loss: 0.0294 - acc: 0.9890
Epoch 440/500
 - 0s - loss: 0.0310 - acc: 0.9885
Epoch 441/500
 - 0s - loss: 0.0313 - acc: 0.9906
Epoch 442/500
 - 0s - loss: 0.0310 - acc: 0.9890
Epoch 443/500
 - 0s - loss: 0.0269 - acc: 0.9900
Epoch 444/500
 - 0s - loss: 0.0301 - acc: 0.9895
Epoch 445/500
 - 0s - loss: 0.0373 - acc: 0.9864
Epoch 446/500
 - 0s - loss: 0.0286 - acc: 0.9916
Epoch 447/500
 - 0s - loss: 0.0278 - acc: 0.9916
Epoch 448/500
 - 0s - loss: 0.0365 - acc: 0.9853
Epoch 449/500
 - 0s - loss: 0.0302 - acc: 0.9885
Epoch 450/500
 - 0s - loss: 0.0314 - acc: 0.9895
Epoch 451/500
 - 0s - loss: 0.0326 - acc: 0.9869
Epoch 452/500
 - 0s - loss: 0.0356 - acc: 0.9864
Epoch 453/500
 - 0s - loss: 0.0357 - acc: 0.9885
Epoch 454/500
 - 0s - loss: 0.0305 - acc: 0.9890
Epoch 455/500
 - 0s - loss: 0.0336 - acc: 0.9853
Epoch 456/500
 - 0s - loss: 0.0355 - acc: 0.9890
Epoch 457/500
 - 0s - loss: 0.0381 - acc: 0.9848
Epoch 458/500
 - 0s - loss: 0.0329 - acc: 0.9874
Epoch 459/500
 - 0s - loss: 0.0305 - acc: 0.9895
Epoch 460/500
 - 0s - loss: 0.0318 - acc: 0.9885
Epoch 461/500
 - 0s - loss: 0.0278 - acc: 0.9885
Epoch 462/500
 - 0s - loss: 0.0273 - acc: 0.9906
Epoch 463/500
 - 0s - loss: 0.0286 - acc: 0.9890
Epoch 464/500
 - 0s - loss: 0.0352 - acc: 0.9848
Epoch 465/500
 - 0s - loss: 0.0396 - acc: 0.9827
Epoch 466/500
 - 0s - loss: 0.0272 - acc: 0.9900
Epoch 467/500
 - 0s - loss: 0.0295 - acc: 0.9874
Epoch 468/500
 - 0s - loss: 0.0313 - acc: 0.9864
Epoch 469/500
 - 0s - loss: 0.0367 - acc: 0.9853
Epoch 470/500
 - 0s - loss: 0.0324 - acc: 0.9879
Epoch 471/500
 - 0s - loss: 0.0312 - acc: 0.9869
Epoch 472/500
 - 0s - loss: 0.0283 - acc: 0.9900
Epoch 473/500
 - 0s - loss: 0.0314 - acc: 0.9879
Epoch 474/500
 - 0s - loss: 0.0374 - acc: 0.9858
Epoch 475/500
 - 0s - loss: 0.0330 - acc: 0.9853
Epoch 476/500
 - 0s - loss: 0.0287 - acc: 0.9885
Epoch 477/500
 - 0s - loss: 0.0331 - acc: 0.9869
Epoch 478/500
 - 0s - loss: 0.0314 - acc: 0.9874
Epoch 479/500
 - 0s - loss: 0.0292 - acc: 0.9885
Epoch 480/500
 - 0s - loss: 0.0306 - acc: 0.9879
Epoch 481/500
 - 0s - loss: 0.0286 - acc: 0.9890
Epoch 482/500
 - 0s - loss: 0.0307 - acc: 0.9874
Epoch 483/500
 - 0s - loss: 0.0302 - acc: 0.9853
Epoch 484/500
 - 0s - loss: 0.0301 - acc: 0.9890
Epoch 485/500
 - 0s - loss: 0.0349 - acc: 0.9848
Epoch 486/500
 - 0s - loss: 0.0290 - acc: 0.9911
Epoch 487/500
 - 0s - loss: 0.0296 - acc: 0.9869
Epoch 488/500
 - 0s - loss: 0.0279 - acc: 0.9895
Epoch 489/500
 - 0s - loss: 0.0251 - acc: 0.9895
Epoch 490/500
 - 0s - loss: 0.0327 - acc: 0.9879
Epoch 491/500
 - 0s - loss: 0.0295 - acc: 0.9890
Epoch 492/500
 - 0s - loss: 0.0364 - acc: 0.9879
Epoch 493/500
 - 0s - loss: 0.0314 - acc: 0.9874
Epoch 494/500
 - 0s - loss: 0.0298 - acc: 0.9900
Epoch 495/500
 - 0s - loss: 0.0303 - acc: 0.9890
Epoch 496/500
 - 0s - loss: 0.0296 - acc: 0.9900
Epoch 497/500
 - 0s - loss: 0.0297 - acc: 0.9879
Epoch 498/500
 - 0s - loss: 0.0297 - acc: 0.9879
Epoch 499/500
 - 0s - loss: 0.0286 - acc: 0.9879

Epoch 500/500
 - 0s - loss: 0.0265 - acc: 0.9890

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 0.6804 - acc: 0.8915
Normal Neural Network - Loss: 0.6803590593472967, Accuracy: 0.8915094137191772

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Certified' 'Certified' 'Certified' 'Certified' 'Certified'
 'Certified' 'Certified' 'Certified' 'Certified']
Actual Labels: ['Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Denied', 'Denied', 'Denied', 'Certified', 'Certified']