In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [13]:
data['CLASS_OF_ADMISSION'].value_counts()

H-1B          163774
L-1            15279
F-1            13753
Not in USA      8346
TN              3878
E-2             3159
B-2             2735
EWI             1118
J-1              959
E-3              811
F-2              731
H-2B             724
O-1              690
H-4              640
B-1              580
Parolee          520
TPS              468
L-2              420
E-1              397
H-1B1            296
H-2A             202
P-1              150
A1/A2            134
J-2               97
R-1               92
G-4               71
I                 65
VWT               40
H-3               35
P-3               35
G-5               34
M-1               30
C-1               25
O-2               24
H-1A              22
A-3               21
O-3               14
G-1               13
VWB               13
TD                13
C-3                9
R-2                8
P-4                6
V-2                5
D-1                5
M-2                3
Q                  3
U-1                1
V-1                1
T-1                1
K-1                1
P-2                1
Name: CLASS_OF_ADMISSION, dtype: int64

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'ARGENTINA']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

ARGENTINA    800
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    777
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [9]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [10]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [11]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
308,Certified,472,60606,ILLINOIS,1017.0,106330.0,ARGENTINA,H-1B,None,5.0
899,Certified,188,47907,INDIANA,19000.0,87924.0,ARGENTINA,H-1B,Doctorate,2.0
989,Certified,223,15220,PENNSYLVANIA,12.0,105664.0,ARGENTINA,H-1B,Bachelor's,1.0
1286,Certified,199,10016,NEW YORK,130.0,177403.0,ARGENTINA,H-1B,Bachelor's,3.0
1438,Certified,170,27617,NORTH CAROLINA,350.0,134000.0,ARGENTINA,H-1B,Master's,11.0

In [12]:
data4['FOREIGN_WORKER_INFO_EDUCATION'].value_counts()

Bachelor's     338
Master's       145
None           124
Doctorate       59
Other           54
High School     38
Associate's     13
Name: FOREIGN_WORKER_INFO_EDUCATION, dtype: int64

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

FLORIDA                 194
CALIFORNIA              171
NEW YORK                 92
TEXAS                    47
ILLINOIS                 29
MASSACHUSETTS            24
WASHINGTON               23
NEW JERSEY               22
VIRGINIA                 21
MARYLAND                 14
PENNSYLVANIA             14
MICHIGAN                 11
NORTH CAROLINA           11
MISSOURI                  9
NEVADA                    8
GEORGIA                   8
COLORADO                  8
CONNECTICUT               7
UTAH                      6
MINNESOTA                 6
INDIANA                   5
DISTRICT OF COLUMBIA      5
ARIZONA                   4
KANSAS                    4
OHIO                      4
ARKANSAS                  4
PUERTO RICO               4
OKLAHOMA                  3
NEW MEXICO                2
KENTUCKY                  2
RHODE ISLAND              2
LOUISIANA                 2
TENNESSEE                 2
IOWA                      2
SOUTH DAKOTA              1
SOUTH CAROLINA            1
WISCONSIN                 1
VERMONT                   1
ALABAMA                   1
NEBRASKA                  1
IDAHO                     1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
308,Certified,472,60606,ILLINOIS,1017.0,106330.0,ARGENTINA,H-1B,None,5.0,ILLINOIS
899,Certified,188,47907,INDIANA,19000.0,87924.0,ARGENTINA,H-1B,Doctorate,2.0,INDIANA
989,Certified,223,15220,PENNSYLVANIA,12.0,105664.0,ARGENTINA,H-1B,Bachelor's,1.0,PENNSYLVANIA
1286,Certified,199,10016,NEW YORK,130.0,177403.0,ARGENTINA,H-1B,Bachelor's,3.0,NEW YORK
1438,Certified,170,27617,NORTH CAROLINA,350.0,134000.0,ARGENTINA,H-1B,Master's,11.0,NORTH CAROLINA

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

SOUTH        265
WEST         211
NORTHEAST    148
MIDWEST       70
OTHER          3
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      697
DECISION_ELAPSED_DAYS            697
EMPLOYER_POSTAL_CODE             697
EMPLOYER_STATE                   697
EMPLOYER_NUM_EMPLOYEES           697
WAGE_OFFER_FROM_9089             697
COUNTRY_OF_CITIZENSHIP           697
CLASS_OF_ADMISSION               697
FOREIGN_WORKER_INFO_EDUCATION    697
CASE_RECEIVED_DATE_MONTH         697
EMPLOYER_STATES                  697
EMPLOYER_REGIONS                 697
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      272
0-90        184
181-365     179
366-3600     61
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

100000-500000    329
75001-100000     126
50001-75000      119
25001-50000      115
0-25000            8
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

0-50                232
10001-1000000000    201
1001-10000          108
101-500              88
501-1000             37
51-100               31
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      697
DECISION_ELAPSED_DAYS            697
EMPLOYER_POSTAL_CODE             697
EMPLOYER_STATE                   697
EMPLOYER_NUM_EMPLOYEES           697
WAGE_OFFER_FROM_9089             697
COUNTRY_OF_CITIZENSHIP           697
CLASS_OF_ADMISSION               697
FOREIGN_WORKER_INFO_EDUCATION    697
CASE_RECEIVED_DATE_MONTH         697
EMPLOYER_STATES                  697
EMPLOYER_REGIONS                 697
DAY_BINS                         696
WAGE_BINS                        697
EMPLOYEE_BINS                    697
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
308,Certified,1001-10000,100000-500000,MIDWEST,5.0,None,H-1B,366-3600
899,Certified,10001-1000000000,75001-100000,MIDWEST,2.0,Doctorate,H-1B,181-365
989,Certified,0-50,100000-500000,NORTHEAST,1.0,Bachelor's,H-1B,181-365
1286,Certified,101-500,100000-500000,NORTHEAST,3.0,Bachelor's,H-1B,181-365
1438,Certified,101-500,100000-500000,SOUTH,11.0,Master's,H-1B,91-180

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
308,Certified,1001-10000,100000-500000,MIDWEST,5.0,None,H-1B,366-3600,9,5,1,0,2,2
899,Certified,10001-1000000000,75001-100000,MIDWEST,2.0,Doctorate,H-1B,181-365,9,2,4,0,1,1
989,Certified,0-50,100000-500000,NORTHEAST,1.0,Bachelor's,H-1B,181-365,9,1,1,1,1,0
1286,Certified,101-500,100000-500000,NORTHEAST,3.0,Bachelor's,H-1B,181-365,9,1,1,1,1,3
1438,Certified,101-500,100000-500000,SOUTH,11.0,Master's,H-1B,91-180,9,4,1,3,3,3

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           697
EMPLOYEE_BINS                         697
WAGE_BINS                             697
EMPLOYER_REGIONS                      697
CASE_RECEIVED_DATE_MONTH              697
FOREIGN_WORKER_INFO_EDUCATION         697
CLASS_OF_ADMISSION                    697
DAY_BINS                              697
CLASS_OF_ADMISSION_CODE               697
FOREIGN_WORKER_INFO_EDUCATION_CODE    697
WAGE_BINS_CODE                        697
EMPLOYER_REGIONS_CODE                 697
DAY_BINS_CODE                         697
EMPLOYEE_BINS_CODE                    697
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
308,Certified,2,1,2,5,9,5.0,0
899,Certified,1,4,1,2,9,2.0,0
989,Certified,0,1,1,1,9,1.0,1
1286,Certified,3,1,1,1,9,3.0,1
1438,Certified,3,1,3,4,9,11.0,3

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int64
WAGE_BINS_CODE                          int64
DAY_BINS_CODE                           int64
FOREIGN_WORKER_INFO_EDUCATION_CODE      int64
CLASS_OF_ADMISSION_CODE                 int64
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int64
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(697, 7) (697,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [53]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 1s - loss: 0.4806 - acc: 0.8736
Epoch 2/500
 - 0s - loss: 0.3917 - acc: 0.8755
Epoch 3/500
 - 0s - loss: 0.3826 - acc: 0.8755
Epoch 4/500
 - 0s - loss: 0.3738 - acc: 0.8755
Epoch 5/500
 - 0s - loss: 0.3652 - acc: 0.8755
Epoch 6/500
 - 0s - loss: 0.3585 - acc: 0.8755
Epoch 7/500
 - 0s - loss: 0.3537 - acc: 0.8755
Epoch 8/500
 - 0s - loss: 0.3488 - acc: 0.8755
Epoch 9/500
 - 0s - loss: 0.3437 - acc: 0.8755
Epoch 10/500
 - 0s - loss: 0.3417 - acc: 0.8755
Epoch 11/500
 - 0s - loss: 0.3351 - acc: 0.8755
Epoch 12/500
 - 0s - loss: 0.3339 - acc: 0.8755
Epoch 13/500
 - 0s - loss: 0.3272 - acc: 0.8755
Epoch 14/500
 - 0s - loss: 0.3225 - acc: 0.8755
Epoch 15/500
 - 0s - loss: 0.3199 - acc: 0.8755
Epoch 16/500
 - 0s - loss: 0.3165 - acc: 0.8755
Epoch 17/500
 - 0s - loss: 0.3111 - acc: 0.8755
Epoch 18/500
 - 0s - loss: 0.3069 - acc: 0.8755
Epoch 19/500
 - 0s - loss: 0.3048 - acc: 0.8755
Epoch 20/500
 - 0s - loss: 0.3031 - acc: 0.8755
Epoch 21/500
 - 0s - loss: 0.2956 - acc: 0.8755
Epoch 22/500
 - 0s - loss: 0.2962 - acc: 0.8755
Epoch 23/500
 - 0s - loss: 0.3055 - acc: 0.8755
Epoch 24/500
 - 0s - loss: 0.2995 - acc: 0.8755
Epoch 25/500
 - 0s - loss: 0.2890 - acc: 0.8736
Epoch 26/500
 - 0s - loss: 0.2877 - acc: 0.8774
Epoch 27/500
 - 0s - loss: 0.2812 - acc: 0.8851
Epoch 28/500
 - 0s - loss: 0.2820 - acc: 0.8793
Epoch 29/500
 - 0s - loss: 0.2816 - acc: 0.8851
Epoch 30/500
 - 0s - loss: 0.2727 - acc: 0.8793
Epoch 31/500
 - 0s - loss: 0.2729 - acc: 0.8851
Epoch 32/500
 - 0s - loss: 0.2684 - acc: 0.8870
Epoch 33/500
 - 0s - loss: 0.2628 - acc: 0.8851
Epoch 34/500
 - 0s - loss: 0.2648 - acc: 0.8851
Epoch 35/500
 - 0s - loss: 0.2608 - acc: 0.8851
Epoch 36/500
 - 0s - loss: 0.2597 - acc: 0.8851
Epoch 37/500
 - 0s - loss: 0.2557 - acc: 0.8889
Epoch 38/500
 - 0s - loss: 0.2571 - acc: 0.8889
Epoch 39/500
 - 0s - loss: 0.2521 - acc: 0.8851
Epoch 40/500
 - 0s - loss: 0.2496 - acc: 0.8927
Epoch 41/500
 - 0s - loss: 0.2495 - acc: 0.8851
Epoch 42/500
 - 0s - loss: 0.2461 - acc: 0.8870
Epoch 43/500
 - 0s - loss: 0.2431 - acc: 0.8946
Epoch 44/500
 - 0s - loss: 0.2415 - acc: 0.8946
Epoch 45/500
 - 0s - loss: 0.2369 - acc: 0.9023
Epoch 46/500
 - 0s - loss: 0.2357 - acc: 0.9023
Epoch 47/500
 - 0s - loss: 0.2428 - acc: 0.8831
Epoch 48/500
 - 0s - loss: 0.2343 - acc: 0.8946
Epoch 49/500
 - 0s - loss: 0.2282 - acc: 0.8985
Epoch 50/500
 - 0s - loss: 0.2291 - acc: 0.9023
Epoch 51/500
 - 0s - loss: 0.2246 - acc: 0.9023
Epoch 52/500
 - 0s - loss: 0.2224 - acc: 0.8966
Epoch 53/500
 - 0s - loss: 0.2183 - acc: 0.9004
Epoch 54/500
 - 0s - loss: 0.2182 - acc: 0.9100
Epoch 55/500
 - 0s - loss: 0.2207 - acc: 0.8946
Epoch 56/500
 - 0s - loss: 0.2281 - acc: 0.9023
Epoch 57/500
 - 0s - loss: 0.2141 - acc: 0.9061
Epoch 58/500
 - 0s - loss: 0.2131 - acc: 0.9080
Epoch 59/500
 - 0s - loss: 0.2105 - acc: 0.9100
Epoch 60/500
 - 0s - loss: 0.2054 - acc: 0.9119
Epoch 61/500
 - 0s - loss: 0.2070 - acc: 0.9080
Epoch 62/500
 - 0s - loss: 0.2068 - acc: 0.9023
Epoch 63/500
 - 0s - loss: 0.2018 - acc: 0.9119
Epoch 64/500
 - 0s - loss: 0.1989 - acc: 0.9195
Epoch 65/500
 - 0s - loss: 0.2074 - acc: 0.9138
Epoch 66/500
 - 0s - loss: 0.1967 - acc: 0.9138
Epoch 67/500
 - 0s - loss: 0.1973 - acc: 0.8946
Epoch 68/500
 - 0s - loss: 0.1937 - acc: 0.9100
Epoch 69/500
 - 0s - loss: 0.1869 - acc: 0.9138
Epoch 70/500
 - 0s - loss: 0.1897 - acc: 0.9119
Epoch 71/500
 - 0s - loss: 0.1869 - acc: 0.9234
Epoch 72/500
 - 0s - loss: 0.1857 - acc: 0.9100
Epoch 73/500
 - 0s - loss: 0.1874 - acc: 0.9195
Epoch 74/500
 - 0s - loss: 0.1859 - acc: 0.9157
Epoch 75/500
 - 0s - loss: 0.1812 - acc: 0.9215
Epoch 76/500
 - 0s - loss: 0.1789 - acc: 0.9195
Epoch 77/500
 - 0s - loss: 0.1816 - acc: 0.9215
Epoch 78/500
 - 0s - loss: 0.1764 - acc: 0.9195
Epoch 79/500
 - 0s - loss: 0.1732 - acc: 0.9215
Epoch 80/500
 - 0s - loss: 0.1736 - acc: 0.9195
Epoch 81/500
 - 0s - loss: 0.1693 - acc: 0.9195
Epoch 82/500
 - 0s - loss: 0.1700 - acc: 0.9253
Epoch 83/500
 - 0s - loss: 0.1684 - acc: 0.9215
Epoch 84/500
 - 0s - loss: 0.1799 - acc: 0.9061
Epoch 85/500
 - 0s - loss: 0.1696 - acc: 0.9157
Epoch 86/500
 - 0s - loss: 0.1645 - acc: 0.9215
Epoch 87/500
 - 0s - loss: 0.1594 - acc: 0.9253
Epoch 88/500
 - 0s - loss: 0.1619 - acc: 0.9234
Epoch 89/500
 - 0s - loss: 0.1769 - acc: 0.9176
Epoch 90/500
 - 0s - loss: 0.1658 - acc: 0.9291
Epoch 91/500
 - 0s - loss: 0.1594 - acc: 0.9291
Epoch 92/500
 - 0s - loss: 0.1580 - acc: 0.9272
Epoch 93/500
 - 0s - loss: 0.1509 - acc: 0.9272
Epoch 94/500
 - 0s - loss: 0.1540 - acc: 0.9310
Epoch 95/500
 - 0s - loss: 0.1538 - acc: 0.9215
Epoch 96/500
 - 0s - loss: 0.1492 - acc: 0.9272
Epoch 97/500
 - 0s - loss: 0.1483 - acc: 0.9330
Epoch 98/500
 - 0s - loss: 0.1488 - acc: 0.9253
Epoch 99/500
 - 0s - loss: 0.1462 - acc: 0.9330
Epoch 100/500
 - 0s - loss: 0.1482 - acc: 0.9406
Epoch 101/500
 - 0s - loss: 0.1407 - acc: 0.9349
Epoch 102/500
 - 0s - loss: 0.1480 - acc: 0.9310
Epoch 103/500
 - 0s - loss: 0.1467 - acc: 0.9330
Epoch 104/500
 - 0s - loss: 0.1453 - acc: 0.9349
Epoch 105/500
 - 0s - loss: 0.1469 - acc: 0.9387
Epoch 106/500
 - 0s - loss: 0.1379 - acc: 0.9406
Epoch 107/500
 - 0s - loss: 0.1350 - acc: 0.9425
Epoch 108/500
 - 0s - loss: 0.1377 - acc: 0.9425
Epoch 109/500
 - 0s - loss: 0.1476 - acc: 0.9368
Epoch 110/500
 - 0s - loss: 0.1425 - acc: 0.9387
Epoch 111/500
 - 0s - loss: 0.1293 - acc: 0.9444
Epoch 112/500
 - 0s - loss: 0.1321 - acc: 0.9406
Epoch 113/500
 - 0s - loss: 0.1299 - acc: 0.9483
Epoch 114/500
 - 0s - loss: 0.1308 - acc: 0.9406
Epoch 115/500
 - 0s - loss: 0.1392 - acc: 0.9310
Epoch 116/500
 - 0s - loss: 0.1262 - acc: 0.9483
Epoch 117/500
 - 0s - loss: 0.1332 - acc: 0.9387
Epoch 118/500
 - 0s - loss: 0.1413 - acc: 0.9349
Epoch 119/500
 - 0s - loss: 0.1223 - acc: 0.9444
Epoch 120/500
 - 0s - loss: 0.1255 - acc: 0.9502
Epoch 121/500
 - 0s - loss: 0.1185 - acc: 0.9444
Epoch 122/500
 - 0s - loss: 0.1204 - acc: 0.9483
Epoch 123/500
 - 0s - loss: 0.1230 - acc: 0.9483
Epoch 124/500
 - 0s - loss: 0.1178 - acc: 0.9521
Epoch 125/500
 - 0s - loss: 0.1261 - acc: 0.9464
Epoch 126/500
 - 0s - loss: 0.1188 - acc: 0.9483
Epoch 127/500
 - 0s - loss: 0.1167 - acc: 0.9502
Epoch 128/500
 - 0s - loss: 0.1110 - acc: 0.9559
Epoch 129/500
 - 0s - loss: 0.1271 - acc: 0.9483
Epoch 130/500
 - 0s - loss: 0.1128 - acc: 0.9540
Epoch 131/500
 - 0s - loss: 0.1109 - acc: 0.9444
Epoch 132/500
 - 0s - loss: 0.1109 - acc: 0.9521
Epoch 133/500
 - 0s - loss: 0.1079 - acc: 0.9559
Epoch 134/500
 - 0s - loss: 0.1066 - acc: 0.9559
Epoch 135/500
 - 0s - loss: 0.1124 - acc: 0.9521
Epoch 136/500
 - 0s - loss: 0.1045 - acc: 0.9636
Epoch 137/500
 - 0s - loss: 0.1030 - acc: 0.9559
Epoch 138/500
 - 0s - loss: 0.1034 - acc: 0.9444
Epoch 139/500
 - 0s - loss: 0.1042 - acc: 0.9617
Epoch 140/500
 - 0s - loss: 0.1114 - acc: 0.9579
Epoch 141/500
 - 0s - loss: 0.1040 - acc: 0.9617
Epoch 142/500
 - 0s - loss: 0.0974 - acc: 0.9598
Epoch 143/500
 - 0s - loss: 0.1033 - acc: 0.9559
Epoch 144/500
 - 0s - loss: 0.0989 - acc: 0.9559
Epoch 145/500
 - 0s - loss: 0.0950 - acc: 0.9655
Epoch 146/500
 - 0s - loss: 0.0960 - acc: 0.9617
Epoch 147/500
 - 0s - loss: 0.0934 - acc: 0.9636
Epoch 148/500
 - 0s - loss: 0.0942 - acc: 0.9636
Epoch 149/500
 - 0s - loss: 0.0986 - acc: 0.9559
Epoch 150/500
 - 0s - loss: 0.0934 - acc: 0.9617
Epoch 151/500
 - 0s - loss: 0.0879 - acc: 0.9674
Epoch 152/500
 - 0s - loss: 0.0943 - acc: 0.9579
Epoch 153/500
 - 0s - loss: 0.0914 - acc: 0.9674
Epoch 154/500
 - 0s - loss: 0.0847 - acc: 0.9751
Epoch 155/500
 - 0s - loss: 0.0831 - acc: 0.9655
Epoch 156/500
 - 0s - loss: 0.0893 - acc: 0.9713
Epoch 157/500
 - 0s - loss: 0.0826 - acc: 0.9751
Epoch 158/500
 - 0s - loss: 0.0844 - acc: 0.9674
Epoch 159/500
 - 0s - loss: 0.0867 - acc: 0.9617
Epoch 160/500
 - 0s - loss: 0.0845 - acc: 0.9598
Epoch 161/500
 - 0s - loss: 0.0826 - acc: 0.9674
Epoch 162/500
 - 0s - loss: 0.0855 - acc: 0.9674
Epoch 163/500
 - 0s - loss: 0.0838 - acc: 0.9732
Epoch 164/500
 - 0s - loss: 0.0822 - acc: 0.9674

Epoch 165/500
 - 0s - loss: 0.0822 - acc: 0.9693
Epoch 166/500
 - 0s - loss: 0.0798 - acc: 0.9713
Epoch 167/500
 - 0s - loss: 0.0786 - acc: 0.9713
Epoch 168/500
 - 0s - loss: 0.0795 - acc: 0.9674
Epoch 169/500
 - 0s - loss: 0.0753 - acc: 0.9732
Epoch 170/500
 - 0s - loss: 0.0866 - acc: 0.9713
Epoch 171/500
 - 0s - loss: 0.0716 - acc: 0.9789
Epoch 172/500
 - 0s - loss: 0.0731 - acc: 0.9732
Epoch 173/500
 - 0s - loss: 0.0738 - acc: 0.9751
Epoch 174/500
 - 0s - loss: 0.0741 - acc: 0.9732
Epoch 175/500
 - 0s - loss: 0.0767 - acc: 0.9770
Epoch 176/500
 - 0s - loss: 0.0707 - acc: 0.9770
Epoch 177/500
 - 0s - loss: 0.0745 - acc: 0.9751
Epoch 178/500
 - 0s - loss: 0.0688 - acc: 0.9770
Epoch 179/500
 - 0s - loss: 0.0704 - acc: 0.9751
Epoch 180/500
 - 0s - loss: 0.0786 - acc: 0.9713
Epoch 181/500
 - 0s - loss: 0.0711 - acc: 0.9732
Epoch 182/500
 - 0s - loss: 0.0668 - acc: 0.9808
Epoch 183/500
 - 0s - loss: 0.0655 - acc: 0.9770
Epoch 184/500
 - 0s - loss: 0.0654 - acc: 0.9808
Epoch 185/500
 - 0s - loss: 0.0671 - acc: 0.9808
Epoch 186/500
 - 0s - loss: 0.0695 - acc: 0.9770
Epoch 187/500
 - 0s - loss: 0.0624 - acc: 0.9770
Epoch 188/500
 - 0s - loss: 0.0616 - acc: 0.9828
Epoch 189/500
 - 0s - loss: 0.0678 - acc: 0.9732
Epoch 190/500
 - 0s - loss: 0.0598 - acc: 0.9828
Epoch 191/500
 - 0s - loss: 0.0588 - acc: 0.9789
Epoch 192/500
 - 0s - loss: 0.0783 - acc: 0.9713
Epoch 193/500
 - 0s - loss: 0.0731 - acc: 0.9751
Epoch 194/500
 - 0s - loss: 0.0647 - acc: 0.9828
Epoch 195/500
 - 0s - loss: 0.0697 - acc: 0.9732
Epoch 196/500
 - 0s - loss: 0.0565 - acc: 0.9828
Epoch 197/500
 - 0s - loss: 0.0638 - acc: 0.9713
Epoch 198/500
 - 0s - loss: 0.0574 - acc: 0.9866
Epoch 199/500
 - 0s - loss: 0.0556 - acc: 0.9866
Epoch 200/500
 - 0s - loss: 0.0547 - acc: 0.9847
Epoch 201/500
 - 0s - loss: 0.0540 - acc: 0.9885
Epoch 202/500
 - 0s - loss: 0.0613 - acc: 0.9808
Epoch 203/500
 - 0s - loss: 0.0693 - acc: 0.9732
Epoch 204/500
 - 0s - loss: 0.0598 - acc: 0.9789
Epoch 205/500
 - 0s - loss: 0.0539 - acc: 0.9885
Epoch 206/500
 - 0s - loss: 0.0514 - acc: 0.9866
Epoch 207/500
 - 0s - loss: 0.0490 - acc: 0.9866
Epoch 208/500
 - 0s - loss: 0.0519 - acc: 0.9885
Epoch 209/500
 - 0s - loss: 0.0781 - acc: 0.9636
Epoch 210/500
 - 0s - loss: 0.0670 - acc: 0.9713
Epoch 211/500
 - 0s - loss: 0.0580 - acc: 0.9866
Epoch 212/500
 - 0s - loss: 0.0527 - acc: 0.9866
Epoch 213/500
 - 0s - loss: 0.0530 - acc: 0.9808
Epoch 214/500
 - 0s - loss: 0.0468 - acc: 0.9885
Epoch 215/500
 - 0s - loss: 0.0563 - acc: 0.9828
Epoch 216/500
 - 0s - loss: 0.0480 - acc: 0.9866
Epoch 217/500
 - 0s - loss: 0.0476 - acc: 0.9866
Epoch 218/500
 - 0s - loss: 0.0472 - acc: 0.9904
Epoch 219/500
 - 0s - loss: 0.0474 - acc: 0.9885
Epoch 220/500
 - 0s - loss: 0.0452 - acc: 0.9847
Epoch 221/500
 - 0s - loss: 0.0533 - acc: 0.9789
Epoch 222/500
 - 0s - loss: 0.0503 - acc: 0.9847
Epoch 223/500
 - 0s - loss: 0.0446 - acc: 0.9866
Epoch 224/500
 - 0s - loss: 0.0477 - acc: 0.9885
Epoch 225/500
 - 0s - loss: 0.0442 - acc: 0.9923
Epoch 226/500
 - 0s - loss: 0.0506 - acc: 0.9828
Epoch 227/500
 - 0s - loss: 0.0476 - acc: 0.9808
Epoch 228/500
 - 0s - loss: 0.0451 - acc: 0.9885
Epoch 229/500
 - 0s - loss: 0.0486 - acc: 0.9866
Epoch 230/500
 - 0s - loss: 0.0456 - acc: 0.9866
Epoch 231/500
 - 0s - loss: 0.0413 - acc: 0.9904
Epoch 232/500
 - 0s - loss: 0.0419 - acc: 0.9904
Epoch 233/500
 - 0s - loss: 0.0481 - acc: 0.9866
Epoch 234/500
 - 0s - loss: 0.0612 - acc: 0.9732
Epoch 235/500
 - 0s - loss: 0.0517 - acc: 0.9847
Epoch 236/500
 - 0s - loss: 0.0511 - acc: 0.9828
Epoch 237/500
 - 0s - loss: 0.0473 - acc: 0.9866
Epoch 238/500
 - 0s - loss: 0.0476 - acc: 0.9866
Epoch 239/500
 - 0s - loss: 0.0372 - acc: 0.9943
Epoch 240/500
 - 0s - loss: 0.0416 - acc: 0.9885
Epoch 241/500
 - 0s - loss: 0.0510 - acc: 0.9847
Epoch 242/500
 - 0s - loss: 0.0424 - acc: 0.9904
Epoch 243/500
 - 0s - loss: 0.0527 - acc: 0.9751
Epoch 244/500
 - 0s - loss: 0.0396 - acc: 0.9943
Epoch 245/500
 - 0s - loss: 0.0368 - acc: 0.9866
Epoch 246/500
 - 0s - loss: 0.0390 - acc: 0.9923
Epoch 247/500
 - 0s - loss: 0.0359 - acc: 0.9904
Epoch 248/500
 - 0s - loss: 0.0342 - acc: 0.9923
Epoch 249/500
 - 0s - loss: 0.0358 - acc: 0.9923
Epoch 250/500
 - 0s - loss: 0.0357 - acc: 0.9904
Epoch 251/500
 - 0s - loss: 0.0338 - acc: 0.9943
Epoch 252/500
 - 0s - loss: 0.0327 - acc: 0.9923
Epoch 253/500
 - 0s - loss: 0.0395 - acc: 0.9904
Epoch 254/500
 - 0s - loss: 0.0373 - acc: 0.9904
Epoch 255/500
 - 0s - loss: 0.0386 - acc: 0.9885
Epoch 256/500
 - 0s - loss: 0.0370 - acc: 0.9904
Epoch 257/500
 - 0s - loss: 0.0394 - acc: 0.9923
Epoch 258/500
 - 0s - loss: 0.0333 - acc: 0.9923
Epoch 259/500
 - 0s - loss: 0.0342 - acc: 0.9904
Epoch 260/500
 - 0s - loss: 0.0316 - acc: 0.9923
Epoch 261/500
 - 0s - loss: 0.0385 - acc: 0.9885
Epoch 262/500
 - 0s - loss: 0.0366 - acc: 0.9923
Epoch 263/500
 - 0s - loss: 0.0333 - acc: 0.9943
Epoch 264/500
 - 0s - loss: 0.0448 - acc: 0.9828
Epoch 265/500
 - 0s - loss: 0.0384 - acc: 0.9885
Epoch 266/500
 - 0s - loss: 0.0311 - acc: 0.9904
Epoch 267/500
 - 0s - loss: 0.0329 - acc: 0.9885
Epoch 268/500
 - 0s - loss: 0.0290 - acc: 0.9923
Epoch 269/500
 - 0s - loss: 0.0319 - acc: 0.9943
Epoch 270/500
 - 0s - loss: 0.0312 - acc: 0.9923
Epoch 271/500
 - 0s - loss: 0.0316 - acc: 0.9923
Epoch 272/500
 - 0s - loss: 0.0358 - acc: 0.9885
Epoch 273/500
 - 0s - loss: 0.0399 - acc: 0.9866
Epoch 274/500
 - 0s - loss: 0.0358 - acc: 0.9904
Epoch 275/500
 - 0s - loss: 0.0320 - acc: 0.9904
Epoch 276/500
 - 0s - loss: 0.0312 - acc: 0.9943
Epoch 277/500
 - 0s - loss: 0.0282 - acc: 0.9943
Epoch 278/500
 - 0s - loss: 0.0296 - acc: 0.9904
Epoch 279/500
 - 0s - loss: 0.0269 - acc: 0.9943
Epoch 280/500
 - 0s - loss: 0.0259 - acc: 0.9923
Epoch 281/500
 - 0s - loss: 0.0303 - acc: 0.9904
Epoch 282/500
 - 0s - loss: 0.0322 - acc: 0.9923
Epoch 283/500
 - 0s - loss: 0.0248 - acc: 0.9962
Epoch 284/500
 - 0s - loss: 0.0286 - acc: 0.9923
Epoch 285/500
 - 0s - loss: 0.0253 - acc: 0.9943
Epoch 286/500
 - 0s - loss: 0.0308 - acc: 0.9904
Epoch 287/500
 - 0s - loss: 0.0372 - acc: 0.9866
Epoch 288/500
 - 0s - loss: 0.0342 - acc: 0.9904
Epoch 289/500
 - 0s - loss: 0.0289 - acc: 0.9943
Epoch 290/500
 - 0s - loss: 0.0254 - acc: 0.9962
Epoch 291/500
 - 0s - loss: 0.0269 - acc: 0.9923
Epoch 292/500
 - 0s - loss: 0.0252 - acc: 0.9943
Epoch 293/500
 - 0s - loss: 0.0231 - acc: 0.9943
Epoch 294/500
 - 0s - loss: 0.0252 - acc: 0.9943
Epoch 295/500
 - 0s - loss: 0.0239 - acc: 0.9904
Epoch 296/500
 - 0s - loss: 0.0364 - acc: 0.9885
Epoch 297/500
 - 0s - loss: 0.0494 - acc: 0.9789
Epoch 298/500
 - 0s - loss: 0.0315 - acc: 0.9904
Epoch 299/500
 - 0s - loss: 0.0316 - acc: 0.9923
Epoch 300/500
 - 0s - loss: 0.0353 - acc: 0.9923
Epoch 301/500
 - 0s - loss: 0.0260 - acc: 0.9943
Epoch 302/500
 - 0s - loss: 0.0249 - acc: 0.9923
Epoch 303/500
 - 0s - loss: 0.0303 - acc: 0.9885
Epoch 304/500
 - 0s - loss: 0.0238 - acc: 0.9962
Epoch 305/500
 - 0s - loss: 0.0242 - acc: 0.9923
Epoch 306/500
 - 0s - loss: 0.0240 - acc: 0.9923
Epoch 307/500
 - 0s - loss: 0.0233 - acc: 0.9943
Epoch 308/500
 - 0s - loss: 0.0216 - acc: 0.9943
Epoch 309/500
 - 0s - loss: 0.0226 - acc: 0.9923
Epoch 310/500
 - 0s - loss: 0.0227 - acc: 0.9923
Epoch 311/500
 - 0s - loss: 0.0212 - acc: 0.9923
Epoch 312/500
 - 0s - loss: 0.0197 - acc: 0.9943
Epoch 313/500
 - 0s - loss: 0.0205 - acc: 0.9943
Epoch 314/500
 - 0s - loss: 0.0208 - acc: 0.9923
Epoch 315/500
 - 0s - loss: 0.0215 - acc: 0.9904
Epoch 316/500
 - 0s - loss: 0.0198 - acc: 0.9923
Epoch 317/500
 - 0s - loss: 0.0217 - acc: 0.9904
Epoch 318/500
 - 0s - loss: 0.0189 - acc: 0.9962
Epoch 319/500
 - 0s - loss: 0.0216 - acc: 0.9943
Epoch 320/500
 - 0s - loss: 0.0270 - acc: 0.9923
Epoch 321/500
 - 0s - loss: 0.0223 - acc: 0.9923
Epoch 322/500
 - 0s - loss: 0.0216 - acc: 0.9904
Epoch 323/500
 - 0s - loss: 0.0206 - acc: 0.9943
Epoch 324/500
 - 0s - loss: 0.0191 - acc: 0.9923
Epoch 325/500
 - 0s - loss: 0.0185 - acc: 0.9923
Epoch 326/500
 - 0s - loss: 0.0191 - acc: 0.9943
Epoch 327/500
 - 0s - loss: 0.0200 - acc: 0.9923
Epoch 328/500
 - 0s - loss: 0.0199 - acc: 0.9943
Epoch 329/500
 - 0s - loss: 0.0211 - acc: 0.9885
Epoch 330/500
 - 0s - loss: 0.0186 - acc: 0.9923
Epoch 331/500
 - 0s - loss: 0.0200 - acc: 0.9943
Epoch 332/500

 - 0s - loss: 0.0191 - acc: 0.9943
Epoch 333/500
 - 0s - loss: 0.0254 - acc: 0.9923
Epoch 334/500
 - 0s - loss: 0.0208 - acc: 0.9904
Epoch 335/500
 - 0s - loss: 0.0306 - acc: 0.9904
Epoch 336/500
 - 0s - loss: 0.0204 - acc: 0.9962
Epoch 337/500
 - 0s - loss: 0.0225 - acc: 0.9904
Epoch 338/500
 - 0s - loss: 0.0277 - acc: 0.9923
Epoch 339/500
 - 0s - loss: 0.0209 - acc: 0.9962
Epoch 340/500
 - 0s - loss: 0.0273 - acc: 0.9923
Epoch 341/500
 - 0s - loss: 0.0201 - acc: 0.9904
Epoch 342/500
 - 0s - loss: 0.0193 - acc: 0.9923
Epoch 343/500
 - 0s - loss: 0.0199 - acc: 0.9923
Epoch 344/500
 - 0s - loss: 0.0321 - acc: 0.9923
Epoch 345/500
 - 0s - loss: 0.0294 - acc: 0.9885
Epoch 346/500
 - 0s - loss: 0.0212 - acc: 0.9923
Epoch 347/500
 - 0s - loss: 0.0200 - acc: 0.9923
Epoch 348/500
 - 0s - loss: 0.0184 - acc: 0.9943
Epoch 349/500
 - 0s - loss: 0.0179 - acc: 0.9923
Epoch 350/500
 - 0s - loss: 0.0181 - acc: 0.9943
Epoch 351/500
 - 0s - loss: 0.0203 - acc: 0.9923
Epoch 352/500
 - 0s - loss: 0.0191 - acc: 0.9943
Epoch 353/500
 - 0s - loss: 0.0216 - acc: 0.9923
Epoch 354/500
 - 0s - loss: 0.0202 - acc: 0.9923
Epoch 355/500
 - 0s - loss: 0.0182 - acc: 0.9904
Epoch 356/500
 - 0s - loss: 0.0190 - acc: 0.9962
Epoch 357/500
 - 0s - loss: 0.0187 - acc: 0.9904
Epoch 358/500
 - 0s - loss: 0.0161 - acc: 0.9962
Epoch 359/500
 - 0s - loss: 0.0186 - acc: 0.9943
Epoch 360/500
 - 0s - loss: 0.0174 - acc: 0.9923
Epoch 361/500
 - 0s - loss: 0.0195 - acc: 0.9923
Epoch 362/500
 - 0s - loss: 0.0242 - acc: 0.9904
Epoch 363/500
 - 0s - loss: 0.0192 - acc: 0.9943
Epoch 364/500
 - 0s - loss: 0.0252 - acc: 0.9923
Epoch 365/500
 - 0s - loss: 0.0209 - acc: 0.9923
Epoch 366/500
 - 0s - loss: 0.0171 - acc: 0.9904
Epoch 367/500
 - 0s - loss: 0.0173 - acc: 0.9943
Epoch 368/500
 - 0s - loss: 0.0174 - acc: 0.9943
Epoch 369/500
 - 0s - loss: 0.0212 - acc: 0.9904
Epoch 370/500
 - 0s - loss: 0.0171 - acc: 0.9943
Epoch 371/500
 - 0s - loss: 0.0284 - acc: 0.9923
Epoch 372/500
 - 0s - loss: 0.0258 - acc: 0.9904
Epoch 373/500
 - 0s - loss: 0.0215 - acc: 0.9923
Epoch 374/500
 - 0s - loss: 0.0166 - acc: 0.9943
Epoch 375/500
 - 0s - loss: 0.0187 - acc: 0.9885
Epoch 376/500
 - 0s - loss: 0.0172 - acc: 0.9943
Epoch 377/500
 - 0s - loss: 0.0183 - acc: 0.9923
Epoch 378/500
 - 0s - loss: 0.0209 - acc: 0.9923
Epoch 379/500
 - 0s - loss: 0.0148 - acc: 0.9943
Epoch 380/500
 - 0s - loss: 0.0197 - acc: 0.9962
Epoch 381/500
 - 0s - loss: 0.0209 - acc: 0.9923
Epoch 382/500
 - 0s - loss: 0.0229 - acc: 0.9904
Epoch 383/500
 - 0s - loss: 0.0194 - acc: 0.9943
Epoch 384/500
 - 0s - loss: 0.0179 - acc: 0.9943
Epoch 385/500
 - 0s - loss: 0.0172 - acc: 0.9962
Epoch 386/500
 - 0s - loss: 0.0165 - acc: 0.9923
Epoch 387/500
 - 0s - loss: 0.0201 - acc: 0.9923
Epoch 388/500
 - 0s - loss: 0.0148 - acc: 0.9904
Epoch 389/500
 - 0s - loss: 0.0164 - acc: 0.9904
Epoch 390/500
 - 0s - loss: 0.0157 - acc: 0.9962
Epoch 391/500
 - 0s - loss: 0.0194 - acc: 0.9943
Epoch 392/500
 - 0s - loss: 0.0172 - acc: 0.9943
Epoch 393/500
 - 0s - loss: 0.0187 - acc: 0.9923
Epoch 394/500
 - 0s - loss: 0.0229 - acc: 0.9923
Epoch 395/500
 - 0s - loss: 0.0163 - acc: 0.9962
Epoch 396/500
 - 0s - loss: 0.0231 - acc: 0.9943
Epoch 397/500
 - 0s - loss: 0.0220 - acc: 0.9904
Epoch 398/500
 - 0s - loss: 0.0200 - acc: 0.9923
Epoch 399/500
 - 0s - loss: 0.0225 - acc: 0.9943
Epoch 400/500
 - 0s - loss: 0.0172 - acc: 0.9943
Epoch 401/500
 - 0s - loss: 0.0163 - acc: 0.9943
Epoch 402/500
 - 0s - loss: 0.0173 - acc: 0.9923
Epoch 403/500
 - 0s - loss: 0.0134 - acc: 0.9962
Epoch 404/500
 - 0s - loss: 0.0147 - acc: 0.9923
Epoch 405/500
 - 0s - loss: 0.0260 - acc: 0.9885
Epoch 406/500
 - 0s - loss: 0.0161 - acc: 0.9943
Epoch 407/500
 - 0s - loss: 0.0171 - acc: 0.9923
Epoch 408/500
 - 0s - loss: 0.0223 - acc: 0.9943
Epoch 409/500
 - 0s - loss: 0.0181 - acc: 0.9943
Epoch 410/500
 - 0s - loss: 0.0194 - acc: 0.9923
Epoch 411/500
 - 0s - loss: 0.0197 - acc: 0.9885
Epoch 412/500
 - 0s - loss: 0.0338 - acc: 0.9904
Epoch 413/500
 - 0s - loss: 0.0184 - acc: 0.9943
Epoch 414/500
 - 0s - loss: 0.0161 - acc: 0.9923
Epoch 415/500
 - 0s - loss: 0.0165 - acc: 0.9923
Epoch 416/500
 - 0s - loss: 0.0138 - acc: 0.9962
Epoch 417/500
 - 0s - loss: 0.0159 - acc: 0.9962
Epoch 418/500
 - 0s - loss: 0.0285 - acc: 0.9923
Epoch 419/500
 - 0s - loss: 0.0225 - acc: 0.9885
Epoch 420/500
 - 0s - loss: 0.0265 - acc: 0.9923
Epoch 421/500
 - 0s - loss: 0.0336 - acc: 0.9847
Epoch 422/500
 - 0s - loss: 0.0276 - acc: 0.9904
Epoch 423/500
 - 0s - loss: 0.0211 - acc: 0.9923
Epoch 424/500
 - 0s - loss: 0.0174 - acc: 0.9943
Epoch 425/500
 - 0s - loss: 0.0237 - acc: 0.9923
Epoch 426/500
 - 0s - loss: 0.0196 - acc: 0.9943
Epoch 427/500
 - 0s - loss: 0.0142 - acc: 0.9923
Epoch 428/500
 - 0s - loss: 0.0140 - acc: 0.9904
Epoch 429/500
 - 0s - loss: 0.0159 - acc: 0.9943
Epoch 430/500
 - 0s - loss: 0.0148 - acc: 0.9943
Epoch 431/500
 - 0s - loss: 0.0117 - acc: 0.9943
Epoch 432/500
 - 0s - loss: 0.0123 - acc: 0.9923
Epoch 433/500
 - 0s - loss: 0.0128 - acc: 0.9943
Epoch 434/500
 - 0s - loss: 0.0141 - acc: 0.9943
Epoch 435/500
 - 0s - loss: 0.0130 - acc: 0.9943
Epoch 436/500
 - 0s - loss: 0.0137 - acc: 0.9943
Epoch 437/500
 - 0s - loss: 0.0123 - acc: 0.9943
Epoch 438/500
 - 0s - loss: 0.0124 - acc: 0.9923
Epoch 439/500
 - 0s - loss: 0.0114 - acc: 0.9923
Epoch 440/500
 - 0s - loss: 0.0116 - acc: 0.9943
Epoch 441/500
 - 0s - loss: 0.0121 - acc: 0.9962
Epoch 442/500
 - 0s - loss: 0.0153 - acc: 0.9923
Epoch 443/500
 - 0s - loss: 0.0155 - acc: 0.9923
Epoch 444/500
 - 0s - loss: 0.0141 - acc: 0.9962
Epoch 445/500
 - 0s - loss: 0.0128 - acc: 0.9923
Epoch 446/500
 - 0s - loss: 0.0130 - acc: 0.9962
Epoch 447/500
 - 0s - loss: 0.0167 - acc: 0.9923
Epoch 448/500
 - 0s - loss: 0.0127 - acc: 0.9923
Epoch 449/500
 - 0s - loss: 0.0116 - acc: 0.9943
Epoch 450/500
 - 0s - loss: 0.0162 - acc: 0.9943
Epoch 451/500
 - 0s - loss: 0.0127 - acc: 0.9962
Epoch 452/500
 - 0s - loss: 0.0168 - acc: 0.9923
Epoch 453/500
 - 0s - loss: 0.0177 - acc: 0.9943
Epoch 454/500
 - 0s - loss: 0.0194 - acc: 0.9943
Epoch 455/500
 - 0s - loss: 0.0150 - acc: 0.9943
Epoch 456/500
 - 0s - loss: 0.0185 - acc: 0.9923
Epoch 457/500
 - 0s - loss: 0.0213 - acc: 0.9923
Epoch 458/500
 - 0s - loss: 0.0291 - acc: 0.9866
Epoch 459/500
 - 0s - loss: 0.0469 - acc: 0.9885
Epoch 460/500
 - 0s - loss: 0.0287 - acc: 0.9885
Epoch 461/500
 - 0s - loss: 0.0262 - acc: 0.9904
Epoch 462/500
 - 0s - loss: 0.0184 - acc: 0.9923
Epoch 463/500
 - 0s - loss: 0.0131 - acc: 0.9943
Epoch 464/500
 - 0s - loss: 0.0131 - acc: 0.9962
Epoch 465/500
 - 0s - loss: 0.0170 - acc: 0.9923
Epoch 466/500
 - 0s - loss: 0.0141 - acc: 0.9923
Epoch 467/500
 - 0s - loss: 0.0134 - acc: 0.9962
Epoch 468/500
 - 0s - loss: 0.0132 - acc: 0.9943
Epoch 469/500
 - 0s - loss: 0.0124 - acc: 0.9923
Epoch 470/500
 - 0s - loss: 0.0118 - acc: 0.9943
Epoch 471/500
 - 0s - loss: 0.0209 - acc: 0.9923
Epoch 472/500
 - 0s - loss: 0.0131 - acc: 0.9962
Epoch 473/500
 - 0s - loss: 0.0124 - acc: 0.9923
Epoch 474/500
 - 0s - loss: 0.0201 - acc: 0.9943
Epoch 475/500
 - 0s - loss: 0.0141 - acc: 0.9943
Epoch 476/500
 - 0s - loss: 0.0175 - acc: 0.9943
Epoch 477/500
 - 0s - loss: 0.0126 - acc: 0.9943
Epoch 478/500
 - 0s - loss: 0.0107 - acc: 0.9962
Epoch 479/500
 - 0s - loss: 0.0114 - acc: 0.9923
Epoch 480/500
 - 0s - loss: 0.0102 - acc: 0.9923
Epoch 481/500
 - 0s - loss: 0.0111 - acc: 0.9943
Epoch 482/500
 - 0s - loss: 0.0096 - acc: 0.9943
Epoch 483/500
 - 0s - loss: 0.0117 - acc: 0.9904
Epoch 484/500
 - 0s - loss: 0.0123 - acc: 0.9943
Epoch 485/500
 - 0s - loss: 0.0127 - acc: 0.9962
Epoch 486/500
 - 0s - loss: 0.0116 - acc: 0.9943
Epoch 487/500
 - 0s - loss: 0.0105 - acc: 0.9943
Epoch 488/500
 - 0s - loss: 0.0133 - acc: 0.9943
Epoch 489/500
 - 0s - loss: 0.0163 - acc: 0.9943
Epoch 490/500
 - 0s - loss: 0.0117 - acc: 0.9962
Epoch 491/500
 - 0s - loss: 0.0125 - acc: 0.9943
Epoch 492/500
 - 0s - loss: 0.0114 - acc: 0.9962
Epoch 493/500
 - 0s - loss: 0.0137 - acc: 0.9943
Epoch 494/500
 - 0s - loss: 0.0291 - acc: 0.9904
Epoch 495/500
 - 0s - loss: 0.0301 - acc: 0.9904
Epoch 496/500
 - 0s - loss: 0.0143 - acc: 0.9962
Epoch 497/500
 - 0s - loss: 0.0119 - acc: 0.9962
Epoch 498/500
 - 0s - loss: 0.0118 - acc: 0.9962
Epoch 499/500
 - 0s - loss: 0.0132 - acc: 0.9962

Epoch 500/500
 - 0s - loss: 0.0119 - acc: 0.9923

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 1.0276 - acc: 0.8571
Normal Neural Network - Loss: 1.0276024775845665, Accuracy: 0.8571428656578064

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Certified' 'Certified' 'Certified' 'Certified' 'Certified'
 'Denied' 'Certified' 'Certified' 'Certified']
Actual Labels: ['Denied', 'Certified', 'Certified', 'Denied', 'Certified', 'Certified', 'Denied', 'Certified', 'Denied', 'Certified']