In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'COLOMBIA']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

COLOMBIA    1089
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    1029
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [8]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [9]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [10]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
38,Certified,552,75204,TEXAS,13300.0,87550.0,COLOMBIA,H-1B,Master's,10.0
461,Certified,462,94043,CALIFORNIA,53861.0,107000.0,COLOMBIA,L-1,Bachelor's,4.0
472,Certified,537,15317,PENNSYLVANIA,63.0,100000.0,COLOMBIA,H-1B,Bachelor's,1.0
678,Certified,456,20009,DISTRICT OF COLUMBIA,279.0,40000.0,COLOMBIA,H-1B,Bachelor's,6.0
760,Certified,179,77092-8501,TEXAS,29280.0,49100.0,COLOMBIA,H-1B,Bachelor's,10.0

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

FLORIDA                 273
TEXAS                   141
CALIFORNIA              106
NEW YORK                 90
GEORGIA                  42
NEW JERSEY               37
ILLINOIS                 37
NORTH CAROLINA           33
VIRGINIA                 29
MASSACHUSETTS            24
PENNSYLVANIA             16
WASHINGTON               15
TENNESSEE                13
OHIO                     12
SOUTH CAROLINA           12
CONNECTICUT              11
MINNESOTA                11
INDIANA                  11
DISTRICT OF COLUMBIA      9
MICHIGAN                  9
COLORADO                  8
LOUISIANA                 7
MARYLAND                  7
PUERTO RICO               7
WISCONSIN                 7
OKLAHOMA                  6
MISSOURI                  6
KANSAS                    6
NEVADA                    4
UTAH                      4
NEW MEXICO                4
KENTUCKY                  3
ARKANSAS                  3
ALABAMA                   3
RHODE ISLAND              2
IOWA                      2
ARIZONA                   2
NEBRASKA                  2
IDAHO                     2
WEST VIRGINIA             2
DELAWARE                  2
MONTANA                   1
VERMONT                   1
WYOMING                   1
UNKNOWN                   1
MISSISSIPPI               1
OREGON                    1
SOUTH DAKOTA              1
MAINE                     1
HAWAII                    1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
38,Certified,552,75204,TEXAS,13300.0,87550.0,COLOMBIA,H-1B,Master's,10.0,TEXAS
461,Certified,462,94043,CALIFORNIA,53861.0,107000.0,COLOMBIA,L-1,Bachelor's,4.0,CALIFORNIA
472,Certified,537,15317,PENNSYLVANIA,63.0,100000.0,COLOMBIA,H-1B,Bachelor's,1.0,PENNSYLVANIA
678,Certified,456,20009,DISTRICT OF COLUMBIA,279.0,40000.0,COLOMBIA,H-1B,Bachelor's,6.0,DISTRICT OF COLUMBIA
760,Certified,179,77092-8501,TEXAS,29280.0,49100.0,COLOMBIA,H-1B,Bachelor's,10.0,TEXAS

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

SOUTH        520
NORTHEAST    174
WEST         142
MIDWEST      101
OTHER          6
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      943
DECISION_ELAPSED_DAYS            943
EMPLOYER_POSTAL_CODE             943
EMPLOYER_STATE                   943
EMPLOYER_NUM_EMPLOYEES           943
WAGE_OFFER_FROM_9089             943
COUNTRY_OF_CITIZENSHIP           943
CLASS_OF_ADMISSION               943
FOREIGN_WORKER_INFO_EDUCATION    943
CASE_RECEIVED_DATE_MONTH         943
EMPLOYER_STATES                  943
EMPLOYER_REGIONS                 943
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      333
0-90        255
181-365     242
366-3600    111
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

100000-500000    339
50001-75000      207
25001-50000      195
75001-100000     169
0-25000           32
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

0-50                343
10001-1000000000    185
1001-10000          182
101-500             128
501-1000             53
51-100               48
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      943
DECISION_ELAPSED_DAYS            943
EMPLOYER_POSTAL_CODE             943
EMPLOYER_STATE                   943
EMPLOYER_NUM_EMPLOYEES           943
WAGE_OFFER_FROM_9089             943
COUNTRY_OF_CITIZENSHIP           943
CLASS_OF_ADMISSION               943
FOREIGN_WORKER_INFO_EDUCATION    943
CASE_RECEIVED_DATE_MONTH         943
EMPLOYER_STATES                  943
EMPLOYER_REGIONS                 943
DAY_BINS                         941
WAGE_BINS                        942
EMPLOYEE_BINS                    939
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
38,Certified,10001-1000000000,75001-100000,SOUTH,10.0,Master's,H-1B,366-3600
461,Certified,10001-1000000000,100000-500000,WEST,4.0,Bachelor's,L-1,366-3600
472,Certified,51-100,75001-100000,NORTHEAST,1.0,Bachelor's,H-1B,366-3600
678,Certified,101-500,25001-50000,SOUTH,6.0,Bachelor's,H-1B,366-3600
760,Certified,10001-1000000000,25001-50000,SOUTH,10.0,Bachelor's,H-1B,91-180

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
38,Certified,10001-1000000000,75001-100000,SOUTH,10.0,Master's,H-1B,366-3600,12,4,4,3,2,1
461,Certified,10001-1000000000,100000-500000,WEST,4.0,Bachelor's,L-1,366-3600,17,1,1,4,2,1
472,Certified,51-100,75001-100000,NORTHEAST,1.0,Bachelor's,H-1B,366-3600,12,1,4,1,2,5
678,Certified,101-500,25001-50000,SOUTH,6.0,Bachelor's,H-1B,366-3600,12,1,2,3,2,3
760,Certified,10001-1000000000,25001-50000,SOUTH,10.0,Bachelor's,H-1B,91-180,12,1,2,3,3,1

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           943
EMPLOYEE_BINS                         943
WAGE_BINS                             943
EMPLOYER_REGIONS                      943
CASE_RECEIVED_DATE_MONTH              943
FOREIGN_WORKER_INFO_EDUCATION         943
CLASS_OF_ADMISSION                    943
DAY_BINS                              943
CLASS_OF_ADMISSION_CODE               943
FOREIGN_WORKER_INFO_EDUCATION_CODE    943
WAGE_BINS_CODE                        943
EMPLOYER_REGIONS_CODE                 943
DAY_BINS_CODE                         943
EMPLOYEE_BINS_CODE                    943
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
38,Certified,1,4,2,4,12,10.0,3
461,Certified,1,1,2,1,17,4.0,4
472,Certified,5,4,2,1,12,1.0,1
678,Certified,3,2,2,1,12,6.0,3
760,Certified,1,2,3,1,12,10.0,3

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int64
WAGE_BINS_CODE                          int64
DAY_BINS_CODE                           int64
FOREIGN_WORKER_INFO_EDUCATION_CODE      int64
CLASS_OF_ADMISSION_CODE                 int64
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int64
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(943, 7) (943,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [53]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 1s - loss: 0.5313 - acc: 0.7836
Epoch 2/500
 - 0s - loss: 0.4521 - acc: 0.8303
Epoch 3/500
 - 0s - loss: 0.4436 - acc: 0.8303
Epoch 4/500
 - 0s - loss: 0.4267 - acc: 0.8303
Epoch 5/500
 - 0s - loss: 0.4213 - acc: 0.8303
Epoch 6/500
 - 0s - loss: 0.4130 - acc: 0.8303
Epoch 7/500
 - 0s - loss: 0.4063 - acc: 0.8303
Epoch 8/500
 - 0s - loss: 0.4018 - acc: 0.8303
Epoch 9/500
 - 0s - loss: 0.3974 - acc: 0.8303
Epoch 10/500
 - 0s - loss: 0.3924 - acc: 0.8289
Epoch 11/500
 - 0s - loss: 0.3862 - acc: 0.8303
Epoch 12/500
 - 0s - loss: 0.3820 - acc: 0.8331
Epoch 13/500
 - 0s - loss: 0.3757 - acc: 0.8345
Epoch 14/500
 - 0s - loss: 0.3807 - acc: 0.8331
Epoch 15/500
 - 0s - loss: 0.3648 - acc: 0.8388
Epoch 16/500
 - 0s - loss: 0.3576 - acc: 0.8402
Epoch 17/500
 - 0s - loss: 0.3541 - acc: 0.8416
Epoch 18/500
 - 0s - loss: 0.3489 - acc: 0.8416
Epoch 19/500
 - 0s - loss: 0.3459 - acc: 0.8472
Epoch 20/500
 - 0s - loss: 0.3392 - acc: 0.8472
Epoch 21/500
 - 0s - loss: 0.3418 - acc: 0.8501
Epoch 22/500
 - 0s - loss: 0.3292 - acc: 0.8515
Epoch 23/500
 - 0s - loss: 0.3267 - acc: 0.8600
Epoch 24/500
 - 0s - loss: 0.3194 - acc: 0.8557
Epoch 25/500
 - 0s - loss: 0.3190 - acc: 0.8656
Epoch 26/500
 - 0s - loss: 0.3171 - acc: 0.8769
Epoch 27/500
 - 0s - loss: 0.3070 - acc: 0.8812
Epoch 28/500
 - 0s - loss: 0.3009 - acc: 0.8784
Epoch 29/500
 - 0s - loss: 0.2957 - acc: 0.8784
Epoch 30/500
 - 0s - loss: 0.2930 - acc: 0.8826
Epoch 31/500
 - 0s - loss: 0.2997 - acc: 0.8755
Epoch 32/500
 - 0s - loss: 0.2931 - acc: 0.8840
Epoch 33/500
 - 0s - loss: 0.2887 - acc: 0.8939
Epoch 34/500
 - 0s - loss: 0.2843 - acc: 0.8727
Epoch 35/500
 - 0s - loss: 0.2891 - acc: 0.8798
Epoch 36/500
 - 0s - loss: 0.2743 - acc: 0.8925
Epoch 37/500
 - 0s - loss: 0.2697 - acc: 0.9010
Epoch 38/500
 - 0s - loss: 0.2695 - acc: 0.9010
Epoch 39/500
 - 0s - loss: 0.2675 - acc: 0.8939
Epoch 40/500
 - 0s - loss: 0.2627 - acc: 0.8953
Epoch 41/500
 - 0s - loss: 0.2589 - acc: 0.9052
Epoch 42/500
 - 0s - loss: 0.2668 - acc: 0.8911
Epoch 43/500
 - 0s - loss: 0.2633 - acc: 0.8939
Epoch 44/500
 - 0s - loss: 0.2801 - acc: 0.8840
Epoch 45/500
 - 0s - loss: 0.2549 - acc: 0.9024
Epoch 46/500
 - 0s - loss: 0.2619 - acc: 0.9038
Epoch 47/500
 - 0s - loss: 0.2529 - acc: 0.8982
Epoch 48/500
 - 0s - loss: 0.2452 - acc: 0.9095
Epoch 49/500
 - 0s - loss: 0.2427 - acc: 0.9038
Epoch 50/500
 - 0s - loss: 0.2391 - acc: 0.9123
Epoch 51/500
 - 0s - loss: 0.2417 - acc: 0.9052
Epoch 52/500
 - 0s - loss: 0.2345 - acc: 0.9066
Epoch 53/500
 - 0s - loss: 0.2358 - acc: 0.9137
Epoch 54/500
 - 0s - loss: 0.2403 - acc: 0.9081
Epoch 55/500
 - 0s - loss: 0.2414 - acc: 0.9066
Epoch 56/500
 - 0s - loss: 0.2343 - acc: 0.9123
Epoch 57/500
 - 0s - loss: 0.2440 - acc: 0.9038
Epoch 58/500
 - 0s - loss: 0.2250 - acc: 0.9109
Epoch 59/500
 - 0s - loss: 0.2393 - acc: 0.9095
Epoch 60/500
 - 0s - loss: 0.2229 - acc: 0.9109
Epoch 61/500
 - 0s - loss: 0.2282 - acc: 0.9052
Epoch 62/500
 - 0s - loss: 0.2346 - acc: 0.9109
Epoch 63/500
 - 0s - loss: 0.2279 - acc: 0.9123
Epoch 64/500
 - 0s - loss: 0.2198 - acc: 0.9109
Epoch 65/500
 - 0s - loss: 0.2171 - acc: 0.9151
Epoch 66/500
 - 0s - loss: 0.2151 - acc: 0.9180
Epoch 67/500
 - 0s - loss: 0.2205 - acc: 0.9081
Epoch 68/500
 - 0s - loss: 0.2129 - acc: 0.9165
Epoch 69/500
 - 0s - loss: 0.2096 - acc: 0.9194
Epoch 70/500
 - 0s - loss: 0.2123 - acc: 0.9151
Epoch 71/500
 - 0s - loss: 0.2198 - acc: 0.9137
Epoch 72/500
 - 0s - loss: 0.2132 - acc: 0.9165
Epoch 73/500
 - 0s - loss: 0.2274 - acc: 0.9038
Epoch 74/500
 - 0s - loss: 0.2124 - acc: 0.9194
Epoch 75/500
 - 0s - loss: 0.2153 - acc: 0.9123
Epoch 76/500
 - 0s - loss: 0.2187 - acc: 0.9109
Epoch 77/500
 - 0s - loss: 0.2090 - acc: 0.9194
Epoch 78/500
 - 0s - loss: 0.2065 - acc: 0.9208
Epoch 79/500
 - 0s - loss: 0.2046 - acc: 0.9180
Epoch 80/500
 - 0s - loss: 0.2083 - acc: 0.9180
Epoch 81/500
 - 0s - loss: 0.2085 - acc: 0.9066
Epoch 82/500
 - 0s - loss: 0.2038 - acc: 0.9151
Epoch 83/500
 - 0s - loss: 0.2016 - acc: 0.9151
Epoch 84/500
 - 0s - loss: 0.1991 - acc: 0.9194
Epoch 85/500
 - 0s - loss: 0.2001 - acc: 0.9137
Epoch 86/500
 - 0s - loss: 0.2004 - acc: 0.9109
Epoch 87/500
 - 0s - loss: 0.2186 - acc: 0.9151
Epoch 88/500
 - 0s - loss: 0.2027 - acc: 0.9151
Epoch 89/500
 - 0s - loss: 0.1950 - acc: 0.9194
Epoch 90/500
 - 0s - loss: 0.1904 - acc: 0.9165
Epoch 91/500
 - 0s - loss: 0.1904 - acc: 0.9279
Epoch 92/500
 - 0s - loss: 0.1860 - acc: 0.9208
Epoch 93/500
 - 0s - loss: 0.1920 - acc: 0.9222
Epoch 94/500
 - 0s - loss: 0.1925 - acc: 0.9151
Epoch 95/500
 - 0s - loss: 0.1997 - acc: 0.9180
Epoch 96/500
 - 0s - loss: 0.1876 - acc: 0.9222
Epoch 97/500
 - 0s - loss: 0.1942 - acc: 0.9137
Epoch 98/500
 - 0s - loss: 0.1987 - acc: 0.9222
Epoch 99/500
 - 0s - loss: 0.1904 - acc: 0.9180
Epoch 100/500
 - 0s - loss: 0.1818 - acc: 0.9208
Epoch 101/500
 - 0s - loss: 0.1774 - acc: 0.9279
Epoch 102/500
 - 0s - loss: 0.1789 - acc: 0.9208
Epoch 103/500
 - 0s - loss: 0.1992 - acc: 0.9123
Epoch 104/500
 - 0s - loss: 0.1826 - acc: 0.9194
Epoch 105/500
 - 0s - loss: 0.1988 - acc: 0.9109
Epoch 106/500
 - 0s - loss: 0.1814 - acc: 0.9208
Epoch 107/500
 - 0s - loss: 0.1985 - acc: 0.9194
Epoch 108/500
 - 0s - loss: 0.1795 - acc: 0.9208
Epoch 109/500
 - 0s - loss: 0.1814 - acc: 0.9250
Epoch 110/500
 - 0s - loss: 0.1754 - acc: 0.9194
Epoch 111/500
 - 0s - loss: 0.1743 - acc: 0.9264
Epoch 112/500
 - 0s - loss: 0.1862 - acc: 0.9066
Epoch 113/500
 - 0s - loss: 0.1971 - acc: 0.9165
Epoch 114/500
 - 0s - loss: 0.1754 - acc: 0.9222
Epoch 115/500
 - 0s - loss: 0.1931 - acc: 0.9194
Epoch 116/500
 - 0s - loss: 0.1773 - acc: 0.9264
Epoch 117/500
 - 0s - loss: 0.1669 - acc: 0.9264
Epoch 118/500
 - 0s - loss: 0.1781 - acc: 0.9250
Epoch 119/500
 - 0s - loss: 0.1665 - acc: 0.9222
Epoch 120/500
 - 0s - loss: 0.1651 - acc: 0.9264
Epoch 121/500
 - 0s - loss: 0.1690 - acc: 0.9264
Epoch 122/500
 - 0s - loss: 0.1615 - acc: 0.9264
Epoch 123/500
 - 0s - loss: 0.1602 - acc: 0.9293
Epoch 124/500
 - 0s - loss: 0.1603 - acc: 0.9279
Epoch 125/500
 - 0s - loss: 0.1633 - acc: 0.9335
Epoch 126/500
 - 0s - loss: 0.1661 - acc: 0.9222
Epoch 127/500
 - 0s - loss: 0.1627 - acc: 0.9293
Epoch 128/500
 - 0s - loss: 0.1872 - acc: 0.9208
Epoch 129/500
 - 0s - loss: 0.1569 - acc: 0.9293
Epoch 130/500
 - 0s - loss: 0.1553 - acc: 0.9321
Epoch 131/500
 - 0s - loss: 0.1523 - acc: 0.9279
Epoch 132/500
 - 0s - loss: 0.1524 - acc: 0.9293
Epoch 133/500
 - 0s - loss: 0.1489 - acc: 0.9378
Epoch 134/500
 - 0s - loss: 0.1521 - acc: 0.9321
Epoch 135/500
 - 0s - loss: 0.1498 - acc: 0.9364
Epoch 136/500
 - 0s - loss: 0.1548 - acc: 0.9293
Epoch 137/500
 - 0s - loss: 0.1615 - acc: 0.9236
Epoch 138/500
 - 0s - loss: 0.1689 - acc: 0.9208
Epoch 139/500
 - 0s - loss: 0.1538 - acc: 0.9307
Epoch 140/500
 - 0s - loss: 0.1498 - acc: 0.9335
Epoch 141/500
 - 0s - loss: 0.1453 - acc: 0.9321
Epoch 142/500
 - 0s - loss: 0.1649 - acc: 0.9208
Epoch 143/500
 - 0s - loss: 0.1498 - acc: 0.9364
Epoch 144/500
 - 0s - loss: 0.1469 - acc: 0.9364
Epoch 145/500
 - 0s - loss: 0.1472 - acc: 0.9293
Epoch 146/500
 - 0s - loss: 0.1448 - acc: 0.9364
Epoch 147/500
 - 0s - loss: 0.1503 - acc: 0.9321
Epoch 148/500
 - 0s - loss: 0.1541 - acc: 0.9307
Epoch 149/500
 - 0s - loss: 0.1431 - acc: 0.9406
Epoch 150/500
 - 0s - loss: 0.1470 - acc: 0.9321
Epoch 151/500
 - 0s - loss: 0.1539 - acc: 0.9378
Epoch 152/500
 - 0s - loss: 0.1392 - acc: 0.9321
Epoch 153/500
 - 0s - loss: 0.1372 - acc: 0.9335
Epoch 154/500
 - 0s - loss: 0.1351 - acc: 0.9335
Epoch 155/500
 - 0s - loss: 0.1374 - acc: 0.9420
Epoch 156/500
 - 0s - loss: 0.1354 - acc: 0.9392
Epoch 157/500
 - 0s - loss: 0.1378 - acc: 0.9349
Epoch 158/500
 - 0s - loss: 0.1365 - acc: 0.9364
Epoch 159/500
 - 0s - loss: 0.1498 - acc: 0.9392
Epoch 160/500
 - 0s - loss: 0.1351 - acc: 0.9420
Epoch 161/500
 - 0s - loss: 0.1353 - acc: 0.9364
Epoch 162/500
 - 0s - loss: 0.1306 - acc: 0.9477
Epoch 163/500
 - 0s - loss: 0.1304 - acc: 0.9448
Epoch 164/500
 - 0s - loss: 0.1358 - acc: 0.9335

Epoch 165/500
 - 0s - loss: 0.1371 - acc: 0.9434
Epoch 166/500
 - 0s - loss: 0.1273 - acc: 0.9434
Epoch 167/500
 - 0s - loss: 0.1403 - acc: 0.9250
Epoch 168/500
 - 0s - loss: 0.1334 - acc: 0.9378
Epoch 169/500
 - 0s - loss: 0.1468 - acc: 0.9349
Epoch 170/500
 - 0s - loss: 0.1368 - acc: 0.9434
Epoch 171/500
 - 0s - loss: 0.1274 - acc: 0.9420
Epoch 172/500
 - 0s - loss: 0.1220 - acc: 0.9463
Epoch 173/500
 - 0s - loss: 0.1254 - acc: 0.9406
Epoch 174/500
 - 0s - loss: 0.1673 - acc: 0.9264
Epoch 175/500
 - 0s - loss: 0.1327 - acc: 0.9392
Epoch 176/500
 - 0s - loss: 0.1246 - acc: 0.9491
Epoch 177/500
 - 0s - loss: 0.1345 - acc: 0.9349
Epoch 178/500
 - 0s - loss: 0.1226 - acc: 0.9505
Epoch 179/500
 - 0s - loss: 0.1256 - acc: 0.9477
Epoch 180/500
 - 0s - loss: 0.1305 - acc: 0.9448
Epoch 181/500
 - 0s - loss: 0.1175 - acc: 0.9491
Epoch 182/500
 - 0s - loss: 0.1174 - acc: 0.9562
Epoch 183/500
 - 0s - loss: 0.1169 - acc: 0.9448
Epoch 184/500
 - 0s - loss: 0.1148 - acc: 0.9562
Epoch 185/500
 - 0s - loss: 0.1179 - acc: 0.9477
Epoch 186/500
 - 0s - loss: 0.1289 - acc: 0.9491
Epoch 187/500
 - 0s - loss: 0.1172 - acc: 0.9576
Epoch 188/500
 - 0s - loss: 0.1168 - acc: 0.9463
Epoch 189/500
 - 0s - loss: 0.1122 - acc: 0.9547
Epoch 190/500
 - 0s - loss: 0.1134 - acc: 0.9533
Epoch 191/500
 - 0s - loss: 0.1138 - acc: 0.9576
Epoch 192/500
 - 0s - loss: 0.1092 - acc: 0.9533
Epoch 193/500
 - 0s - loss: 0.1098 - acc: 0.9505
Epoch 194/500
 - 0s - loss: 0.1100 - acc: 0.9632
Epoch 195/500
 - 0s - loss: 0.1136 - acc: 0.9576
Epoch 196/500
 - 0s - loss: 0.1117 - acc: 0.9477
Epoch 197/500
 - 0s - loss: 0.1092 - acc: 0.9604
Epoch 198/500
 - 0s - loss: 0.1174 - acc: 0.9477
Epoch 199/500
 - 0s - loss: 0.1097 - acc: 0.9562
Epoch 200/500
 - 0s - loss: 0.1061 - acc: 0.9618
Epoch 201/500
 - 0s - loss: 0.1127 - acc: 0.9547
Epoch 202/500
 - 0s - loss: 0.1191 - acc: 0.9533
Epoch 203/500
 - 0s - loss: 0.1224 - acc: 0.9477
Epoch 204/500
 - 0s - loss: 0.1151 - acc: 0.9477
Epoch 205/500
 - 0s - loss: 0.1037 - acc: 0.9576
Epoch 206/500
 - 0s - loss: 0.1029 - acc: 0.9533
Epoch 207/500
 - 0s - loss: 0.1169 - acc: 0.9519
Epoch 208/500
 - 0s - loss: 0.1197 - acc: 0.9519
Epoch 209/500
 - 0s - loss: 0.1087 - acc: 0.9505
Epoch 210/500
 - 0s - loss: 0.1026 - acc: 0.9562
Epoch 211/500
 - 0s - loss: 0.1020 - acc: 0.9576
Epoch 212/500
 - 0s - loss: 0.0985 - acc: 0.9590
Epoch 213/500
 - 0s - loss: 0.0980 - acc: 0.9618
Epoch 214/500
 - 0s - loss: 0.0963 - acc: 0.9689
Epoch 215/500
 - 0s - loss: 0.1007 - acc: 0.9590
Epoch 216/500
 - 0s - loss: 0.1177 - acc: 0.9505
Epoch 217/500
 - 0s - loss: 0.1012 - acc: 0.9590
Epoch 218/500
 - 0s - loss: 0.1058 - acc: 0.9519
Epoch 219/500
 - 0s - loss: 0.0995 - acc: 0.9562
Epoch 220/500
 - 0s - loss: 0.1041 - acc: 0.9562
Epoch 221/500
 - 0s - loss: 0.0959 - acc: 0.9689
Epoch 222/500
 - 0s - loss: 0.0989 - acc: 0.9661
Epoch 223/500
 - 0s - loss: 0.1011 - acc: 0.9562
Epoch 224/500
 - 0s - loss: 0.0993 - acc: 0.9576
Epoch 225/500
 - 0s - loss: 0.0954 - acc: 0.9576
Epoch 226/500
 - 0s - loss: 0.0934 - acc: 0.9632
Epoch 227/500
 - 0s - loss: 0.0967 - acc: 0.9547
Epoch 228/500
 - 0s - loss: 0.1178 - acc: 0.9562
Epoch 229/500
 - 0s - loss: 0.1033 - acc: 0.9547
Epoch 230/500
 - 0s - loss: 0.0915 - acc: 0.9646
Epoch 231/500
 - 0s - loss: 0.0939 - acc: 0.9590
Epoch 232/500
 - 0s - loss: 0.1090 - acc: 0.9547
Epoch 233/500
 - 0s - loss: 0.0976 - acc: 0.9646
Epoch 234/500
 - 0s - loss: 0.1012 - acc: 0.9632
Epoch 235/500
 - 0s - loss: 0.0909 - acc: 0.9646
Epoch 236/500
 - 0s - loss: 0.0861 - acc: 0.9675
Epoch 237/500
 - 0s - loss: 0.0982 - acc: 0.9562
Epoch 238/500
 - 0s - loss: 0.0905 - acc: 0.9618
Epoch 239/500
 - 0s - loss: 0.0921 - acc: 0.9618
Epoch 240/500
 - 0s - loss: 0.0883 - acc: 0.9646
Epoch 241/500
 - 0s - loss: 0.0901 - acc: 0.9646
Epoch 242/500
 - 0s - loss: 0.0822 - acc: 0.9703
Epoch 243/500
 - 0s - loss: 0.0846 - acc: 0.9703
Epoch 244/500
 - 0s - loss: 0.0944 - acc: 0.9576
Epoch 245/500
 - 0s - loss: 0.0879 - acc: 0.9661
Epoch 246/500
 - 0s - loss: 0.0870 - acc: 0.9632
Epoch 247/500
 - 0s - loss: 0.0865 - acc: 0.9646
Epoch 248/500
 - 0s - loss: 0.0908 - acc: 0.9646
Epoch 249/500
 - 0s - loss: 0.0919 - acc: 0.9604
Epoch 250/500
 - 0s - loss: 0.1376 - acc: 0.9406
Epoch 251/500
 - 0s - loss: 0.1091 - acc: 0.9590
Epoch 252/500
 - 0s - loss: 0.0877 - acc: 0.9675
Epoch 253/500
 - 0s - loss: 0.0871 - acc: 0.9661
Epoch 254/500
 - 0s - loss: 0.0815 - acc: 0.9689
Epoch 255/500
 - 0s - loss: 0.0795 - acc: 0.9661
Epoch 256/500
 - 0s - loss: 0.0884 - acc: 0.9632
Epoch 257/500
 - 0s - loss: 0.0880 - acc: 0.9604
Epoch 258/500
 - 0s - loss: 0.0810 - acc: 0.9675
Epoch 259/500
 - 0s - loss: 0.0805 - acc: 0.9717
Epoch 260/500
 - 0s - loss: 0.0789 - acc: 0.9689
Epoch 261/500
 - 0s - loss: 0.0774 - acc: 0.9717
Epoch 262/500
 - 0s - loss: 0.0788 - acc: 0.9717
Epoch 263/500
 - 0s - loss: 0.0783 - acc: 0.9717
Epoch 264/500
 - 0s - loss: 0.0781 - acc: 0.9703
Epoch 265/500
 - 0s - loss: 0.0742 - acc: 0.9788
Epoch 266/500
 - 0s - loss: 0.0778 - acc: 0.9745
Epoch 267/500
 - 0s - loss: 0.0739 - acc: 0.9745
Epoch 268/500
 - 0s - loss: 0.0735 - acc: 0.9717
Epoch 269/500
 - 0s - loss: 0.0813 - acc: 0.9646
Epoch 270/500
 - 0s - loss: 0.0773 - acc: 0.9731
Epoch 271/500
 - 0s - loss: 0.0857 - acc: 0.9661
Epoch 272/500
 - 0s - loss: 0.0749 - acc: 0.9689
Epoch 273/500
 - 0s - loss: 0.0730 - acc: 0.9703
Epoch 274/500
 - 0s - loss: 0.0761 - acc: 0.9788
Epoch 275/500
 - 0s - loss: 0.0746 - acc: 0.9703
Epoch 276/500
 - 0s - loss: 0.0755 - acc: 0.9717
Epoch 277/500
 - 0s - loss: 0.0729 - acc: 0.9703
Epoch 278/500
 - 0s - loss: 0.1091 - acc: 0.9618
Epoch 279/500
 - 0s - loss: 0.0789 - acc: 0.9689
Epoch 280/500
 - 0s - loss: 0.0759 - acc: 0.9703
Epoch 281/500
 - 0s - loss: 0.0689 - acc: 0.9774
Epoch 282/500
 - 0s - loss: 0.0700 - acc: 0.9731
Epoch 283/500
 - 0s - loss: 0.0685 - acc: 0.9774
Epoch 284/500
 - 0s - loss: 0.0805 - acc: 0.9731
Epoch 285/500
 - 0s - loss: 0.0758 - acc: 0.9760
Epoch 286/500
 - 0s - loss: 0.0693 - acc: 0.9745
Epoch 287/500
 - 0s - loss: 0.0704 - acc: 0.9731
Epoch 288/500
 - 0s - loss: 0.0796 - acc: 0.9689
Epoch 289/500
 - 0s - loss: 0.0759 - acc: 0.9731
Epoch 290/500
 - 0s - loss: 0.0731 - acc: 0.9717
Epoch 291/500
 - 0s - loss: 0.0846 - acc: 0.9661
Epoch 292/500
 - 0s - loss: 0.0723 - acc: 0.9788
Epoch 293/500
 - 0s - loss: 0.0664 - acc: 0.9802
Epoch 294/500
 - 0s - loss: 0.0864 - acc: 0.9646
Epoch 295/500
 - 0s - loss: 0.0710 - acc: 0.9745
Epoch 296/500
 - 0s - loss: 0.0752 - acc: 0.9717
Epoch 297/500
 - 0s - loss: 0.0683 - acc: 0.9760
Epoch 298/500
 - 0s - loss: 0.0642 - acc: 0.9788
Epoch 299/500
 - 0s - loss: 0.0673 - acc: 0.9745
Epoch 300/500
 - 0s - loss: 0.0681 - acc: 0.9760
Epoch 301/500
 - 0s - loss: 0.0649 - acc: 0.9802
Epoch 302/500
 - 0s - loss: 0.0706 - acc: 0.9760
Epoch 303/500
 - 0s - loss: 0.0659 - acc: 0.9760
Epoch 304/500
 - 0s - loss: 0.0641 - acc: 0.9802
Epoch 305/500
 - 0s - loss: 0.0651 - acc: 0.9745
Epoch 306/500
 - 0s - loss: 0.0639 - acc: 0.9788
Epoch 307/500
 - 0s - loss: 0.0614 - acc: 0.9802
Epoch 308/500
 - 0s - loss: 0.0611 - acc: 0.9774
Epoch 309/500
 - 0s - loss: 0.0858 - acc: 0.9604
Epoch 310/500
 - 0s - loss: 0.0805 - acc: 0.9745
Epoch 311/500
 - 0s - loss: 0.0695 - acc: 0.9760
Epoch 312/500
 - 0s - loss: 0.0701 - acc: 0.9745
Epoch 313/500
 - 0s - loss: 0.0711 - acc: 0.9774
Epoch 314/500
 - 0s - loss: 0.0701 - acc: 0.9703
Epoch 315/500
 - 0s - loss: 0.0654 - acc: 0.9717
Epoch 316/500
 - 0s - loss: 0.0609 - acc: 0.9788
Epoch 317/500
 - 0s - loss: 0.0598 - acc: 0.9774
Epoch 318/500
 - 0s - loss: 0.0577 - acc: 0.9844
Epoch 319/500
 - 0s - loss: 0.0902 - acc: 0.9703
Epoch 320/500
 - 0s - loss: 0.1095 - acc: 0.9562
Epoch 321/500
 - 0s - loss: 0.0929 - acc: 0.9632
Epoch 322/500
 - 0s - loss: 0.0759 - acc: 0.9717
Epoch 323/500
 - 0s - loss: 0.0786 - acc: 0.9689
Epoch 324/500
 - 0s - loss: 0.0636 - acc: 0.9760
Epoch 325/500
 - 0s - loss: 0.0631 - acc: 0.9802
Epoch 326/500
 - 0s - loss: 0.0616 - acc: 0.9760
Epoch 327/500
 - 0s - loss: 0.0788 - acc: 0.9661
Epoch 328/500
 - 0s - loss: 0.0693 - acc: 0.9802
Epoch 329/500
 - 0s - loss: 0.0711 - acc: 0.9760
Epoch 330/500
 - 0s - loss: 0.0683 - acc: 0.9760
Epoch 331/500
 - 0s - loss: 0.0640 - acc: 0.9731
Epoch 332/500

 - 0s - loss: 0.0599 - acc: 0.9816
Epoch 333/500
 - 0s - loss: 0.0570 - acc: 0.9830
Epoch 334/500
 - 0s - loss: 0.0567 - acc: 0.9788
Epoch 335/500
 - 0s - loss: 0.0548 - acc: 0.9830
Epoch 336/500
 - 0s - loss: 0.0549 - acc: 0.9788
Epoch 337/500
 - 0s - loss: 0.0563 - acc: 0.9830
Epoch 338/500
 - 0s - loss: 0.0685 - acc: 0.9760
Epoch 339/500
 - 0s - loss: 0.0604 - acc: 0.9788
Epoch 340/500
 - 0s - loss: 0.0556 - acc: 0.9816
Epoch 341/500
 - 0s - loss: 0.0558 - acc: 0.9816
Epoch 342/500
 - 0s - loss: 0.1203 - acc: 0.9420
Epoch 343/500
 - 0s - loss: 0.0834 - acc: 0.9618
Epoch 344/500
 - 0s - loss: 0.0770 - acc: 0.9661
Epoch 345/500
 - 0s - loss: 0.0624 - acc: 0.9774
Epoch 346/500
 - 0s - loss: 0.0589 - acc: 0.9816
Epoch 347/500
 - 0s - loss: 0.0593 - acc: 0.9816
Epoch 348/500
 - 0s - loss: 0.0568 - acc: 0.9774
Epoch 349/500
 - 0s - loss: 0.0654 - acc: 0.9760
Epoch 350/500
 - 0s - loss: 0.0589 - acc: 0.9774
Epoch 351/500
 - 0s - loss: 0.0539 - acc: 0.9830
Epoch 352/500
 - 0s - loss: 0.0526 - acc: 0.9816
Epoch 353/500
 - 0s - loss: 0.0512 - acc: 0.9816
Epoch 354/500
 - 0s - loss: 0.0524 - acc: 0.9816
Epoch 355/500
 - 0s - loss: 0.0488 - acc: 0.9844
Epoch 356/500
 - 0s - loss: 0.0529 - acc: 0.9844
Epoch 357/500
 - 0s - loss: 0.0525 - acc: 0.9788
Epoch 358/500
 - 0s - loss: 0.0472 - acc: 0.9873
Epoch 359/500
 - 0s - loss: 0.0482 - acc: 0.9873
Epoch 360/500
 - 0s - loss: 0.0483 - acc: 0.9873
Epoch 361/500
 - 0s - loss: 0.0453 - acc: 0.9844
Epoch 362/500
 - 0s - loss: 0.0482 - acc: 0.9844
Epoch 363/500
 - 0s - loss: 0.0569 - acc: 0.9844
Epoch 364/500
 - 0s - loss: 0.0481 - acc: 0.9844
Epoch 365/500
 - 0s - loss: 0.0504 - acc: 0.9830
Epoch 366/500
 - 0s - loss: 0.0525 - acc: 0.9830
Epoch 367/500
 - 0s - loss: 0.0488 - acc: 0.9859
Epoch 368/500
 - 0s - loss: 0.0468 - acc: 0.9844
Epoch 369/500
 - 0s - loss: 0.0448 - acc: 0.9859
Epoch 370/500
 - 0s - loss: 0.0509 - acc: 0.9844
Epoch 371/500
 - 0s - loss: 0.0561 - acc: 0.9788
Epoch 372/500
 - 0s - loss: 0.0478 - acc: 0.9830
Epoch 373/500
 - 0s - loss: 0.0497 - acc: 0.9816
Epoch 374/500
 - 0s - loss: 0.0498 - acc: 0.9859
Epoch 375/500
 - 0s - loss: 0.0500 - acc: 0.9844
Epoch 376/500
 - 0s - loss: 0.0510 - acc: 0.9859
Epoch 377/500
 - 0s - loss: 0.0469 - acc: 0.9859
Epoch 378/500
 - 0s - loss: 0.0480 - acc: 0.9873
Epoch 379/500
 - 0s - loss: 0.0500 - acc: 0.9859
Epoch 380/500
 - 0s - loss: 0.0452 - acc: 0.9901
Epoch 381/500
 - 0s - loss: 0.0460 - acc: 0.9844
Epoch 382/500
 - 0s - loss: 0.0457 - acc: 0.9844
Epoch 383/500
 - 0s - loss: 0.0528 - acc: 0.9774
Epoch 384/500
 - 0s - loss: 0.0484 - acc: 0.9844
Epoch 385/500
 - 0s - loss: 0.0589 - acc: 0.9774
Epoch 386/500
 - 0s - loss: 0.0552 - acc: 0.9859
Epoch 387/500
 - 0s - loss: 0.0457 - acc: 0.9873
Epoch 388/500
 - 0s - loss: 0.0694 - acc: 0.9760
Epoch 389/500
 - 0s - loss: 0.0556 - acc: 0.9830
Epoch 390/500
 - 0s - loss: 0.0510 - acc: 0.9859
Epoch 391/500
 - 0s - loss: 0.0479 - acc: 0.9859
Epoch 392/500
 - 0s - loss: 0.0483 - acc: 0.9859
Epoch 393/500
 - 0s - loss: 0.0510 - acc: 0.9844
Epoch 394/500
 - 0s - loss: 0.0468 - acc: 0.9830
Epoch 395/500
 - 0s - loss: 0.0480 - acc: 0.9830
Epoch 396/500
 - 0s - loss: 0.0963 - acc: 0.9717
Epoch 397/500
 - 0s - loss: 0.0601 - acc: 0.9760
Epoch 398/500
 - 0s - loss: 0.0735 - acc: 0.9731
Epoch 399/500
 - 0s - loss: 0.0617 - acc: 0.9745
Epoch 400/500
 - 0s - loss: 0.0466 - acc: 0.9859
Epoch 401/500
 - 0s - loss: 0.0689 - acc: 0.9731
Epoch 402/500
 - 0s - loss: 0.0516 - acc: 0.9844
Epoch 403/500
 - 0s - loss: 0.0989 - acc: 0.9632
Epoch 404/500
 - 0s - loss: 0.0716 - acc: 0.9745
Epoch 405/500
 - 0s - loss: 0.0524 - acc: 0.9774
Epoch 406/500
 - 0s - loss: 0.0473 - acc: 0.9859
Epoch 407/500
 - 0s - loss: 0.0452 - acc: 0.9844
Epoch 408/500
 - 0s - loss: 0.0409 - acc: 0.9859
Epoch 409/500
 - 0s - loss: 0.0425 - acc: 0.9887
Epoch 410/500
 - 0s - loss: 0.0477 - acc: 0.9816
Epoch 411/500
 - 0s - loss: 0.0491 - acc: 0.9844
Epoch 412/500
 - 0s - loss: 0.0455 - acc: 0.9830
Epoch 413/500
 - 0s - loss: 0.0402 - acc: 0.9873
Epoch 414/500
 - 0s - loss: 0.0442 - acc: 0.9844
Epoch 415/500
 - 0s - loss: 0.0755 - acc: 0.9703
Epoch 416/500
 - 0s - loss: 0.0599 - acc: 0.9774
Epoch 417/500
 - 0s - loss: 0.0438 - acc: 0.9844
Epoch 418/500
 - 0s - loss: 0.0399 - acc: 0.9887
Epoch 419/500
 - 0s - loss: 0.0405 - acc: 0.9873
Epoch 420/500
 - 0s - loss: 0.0488 - acc: 0.9844
Epoch 421/500
 - 0s - loss: 0.0488 - acc: 0.9859
Epoch 422/500
 - 0s - loss: 0.0422 - acc: 0.9859
Epoch 423/500
 - 0s - loss: 0.0573 - acc: 0.9802
Epoch 424/500
 - 0s - loss: 0.1019 - acc: 0.9519
Epoch 425/500
 - 0s - loss: 0.0610 - acc: 0.9802
Epoch 426/500
 - 0s - loss: 0.0515 - acc: 0.9816
Epoch 427/500
 - 0s - loss: 0.0509 - acc: 0.9788
Epoch 428/500
 - 0s - loss: 0.0437 - acc: 0.9887
Epoch 429/500
 - 0s - loss: 0.0437 - acc: 0.9830
Epoch 430/500
 - 0s - loss: 0.0583 - acc: 0.9760
Epoch 431/500
 - 0s - loss: 0.0427 - acc: 0.9859
Epoch 432/500
 - 0s - loss: 0.0434 - acc: 0.9844
Epoch 433/500
 - 0s - loss: 0.0487 - acc: 0.9844
Epoch 434/500
 - 0s - loss: 0.0403 - acc: 0.9859
Epoch 435/500
 - 0s - loss: 0.0543 - acc: 0.9788
Epoch 436/500
 - 0s - loss: 0.0453 - acc: 0.9859
Epoch 437/500
 - 0s - loss: 0.0397 - acc: 0.9887
Epoch 438/500
 - 0s - loss: 0.0382 - acc: 0.9873
Epoch 439/500
 - 0s - loss: 0.0397 - acc: 0.9873
Epoch 440/500
 - 0s - loss: 0.0446 - acc: 0.9844
Epoch 441/500
 - 0s - loss: 0.0374 - acc: 0.9873
Epoch 442/500
 - 0s - loss: 0.0368 - acc: 0.9859
Epoch 443/500
 - 0s - loss: 0.0376 - acc: 0.9873
Epoch 444/500
 - 0s - loss: 0.0408 - acc: 0.9859
Epoch 445/500
 - 0s - loss: 0.0375 - acc: 0.9859
Epoch 446/500
 - 0s - loss: 0.0359 - acc: 0.9873
Epoch 447/500
 - 0s - loss: 0.0348 - acc: 0.9915
Epoch 448/500
 - 0s - loss: 0.0355 - acc: 0.9901
Epoch 449/500
 - 0s - loss: 0.0364 - acc: 0.9901
Epoch 450/500
 - 0s - loss: 0.0356 - acc: 0.9887
Epoch 451/500
 - 0s - loss: 0.0391 - acc: 0.9859
Epoch 452/500
 - 0s - loss: 0.0381 - acc: 0.9859
Epoch 453/500
 - 0s - loss: 0.0409 - acc: 0.9873
Epoch 454/500
 - 0s - loss: 0.0363 - acc: 0.9887
Epoch 455/500
 - 0s - loss: 0.0350 - acc: 0.9873
Epoch 456/500
 - 0s - loss: 0.0335 - acc: 0.9887
Epoch 457/500
 - 0s - loss: 0.0373 - acc: 0.9844
Epoch 458/500
 - 0s - loss: 0.0398 - acc: 0.9844
Epoch 459/500
 - 0s - loss: 0.0381 - acc: 0.9873
Epoch 460/500
 - 0s - loss: 0.0405 - acc: 0.9873
Epoch 461/500
 - 0s - loss: 0.0385 - acc: 0.9873
Epoch 462/500
 - 0s - loss: 0.0377 - acc: 0.9873
Epoch 463/500
 - 0s - loss: 0.0465 - acc: 0.9859
Epoch 464/500
 - 0s - loss: 0.0359 - acc: 0.9859
Epoch 465/500
 - 0s - loss: 0.0341 - acc: 0.9915
Epoch 466/500
 - 0s - loss: 0.0346 - acc: 0.9873
Epoch 467/500
 - 0s - loss: 0.0388 - acc: 0.9887
Epoch 468/500
 - 0s - loss: 0.0435 - acc: 0.9830
Epoch 469/500
 - 0s - loss: 0.0395 - acc: 0.9830
Epoch 470/500
 - 0s - loss: 0.0369 - acc: 0.9873
Epoch 471/500
 - 0s - loss: 0.0468 - acc: 0.9844
Epoch 472/500
 - 0s - loss: 0.0440 - acc: 0.9844
Epoch 473/500
 - 0s - loss: 0.0398 - acc: 0.9859
Epoch 474/500
 - 0s - loss: 0.0399 - acc: 0.9844
Epoch 475/500
 - 0s - loss: 0.0360 - acc: 0.9915
Epoch 476/500
 - 0s - loss: 0.0370 - acc: 0.9901
Epoch 477/500
 - 0s - loss: 0.0458 - acc: 0.9830
Epoch 478/500
 - 0s - loss: 0.0352 - acc: 0.9859
Epoch 479/500
 - 0s - loss: 0.0345 - acc: 0.9859
Epoch 480/500
 - 0s - loss: 0.0597 - acc: 0.9802
Epoch 481/500
 - 0s - loss: 0.0480 - acc: 0.9774
Epoch 482/500
 - 0s - loss: 0.0404 - acc: 0.9873
Epoch 483/500
 - 0s - loss: 0.0527 - acc: 0.9802
Epoch 484/500
 - 0s - loss: 0.0439 - acc: 0.9844
Epoch 485/500
 - 0s - loss: 0.0369 - acc: 0.9830
Epoch 486/500
 - 0s - loss: 0.0336 - acc: 0.9873
Epoch 487/500
 - 0s - loss: 0.0343 - acc: 0.9859
Epoch 488/500
 - 0s - loss: 0.0510 - acc: 0.9788
Epoch 489/500
 - 0s - loss: 0.0383 - acc: 0.9859
Epoch 490/500
 - 0s - loss: 0.0343 - acc: 0.9901
Epoch 491/500
 - 0s - loss: 0.0321 - acc: 0.9887
Epoch 492/500
 - 0s - loss: 0.0314 - acc: 0.9915
Epoch 493/500
 - 0s - loss: 0.0351 - acc: 0.9873
Epoch 494/500
 - 0s - loss: 0.0303 - acc: 0.9859
Epoch 495/500
 - 0s - loss: 0.0490 - acc: 0.9731
Epoch 496/500
 - 0s - loss: 0.0850 - acc: 0.9661
Epoch 497/500
 - 0s - loss: 0.0450 - acc: 0.9901
Epoch 498/500
 - 0s - loss: 0.0393 - acc: 0.9901
Epoch 499/500
 - 0s - loss: 0.0389 - acc: 0.9859

Epoch 500/500
 - 0s - loss: 0.0348 - acc: 0.9873

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 0.8114 - acc: 0.8475
Normal Neural Network - Loss: 0.8113583265724829, Accuracy: 0.8474576473236084

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Certified' 'Certified' 'Certified' 'Certified' 'Certified'
 'Certified' 'Certified' 'Certified' 'Denied']
Actual Labels: ['Denied', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified']