In [67]:
import pandas as pd
import numpy as np

In [68]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [69]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [70]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'ECUADOR']

In [71]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

ECUADOR    548
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [72]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [73]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    437
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [74]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [75]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [76]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
89,Certified,555,19102,PENNSYLVANIA,3100.0,169250.0,ECUADOR,H-1B,Bachelor's,11.0
100,Certified,744,10014,NEW YORK,10.0,40123.0,ECUADOR,EWI,None,7.0
186,Certified,556,95077,CALIFORNIA,778.0,118331.0,ECUADOR,H-1B,Master's,12.0
262,Certified,495,10019,NEW YORK,3883.0,180294.0,ECUADOR,H-1B,Bachelor's,3.0
1953,Certified,176,75063,TEXAS,520.0,80000.0,ECUADOR,H-1B,Master's,11.0

In [77]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [78]:
data4['EMPLOYER_STATES'].value_counts()

UNKNOWN                 121
NEW YORK                105
NEW JERSEY               44
FLORIDA                  32
CALIFORNIA               20
TEXAS                    15
CONNECTICUT              13
NORTH CAROLINA            9
MARYLAND                  9
VIRGINIA                  8
ILLINOIS                  7
MISSOURI                  6
INDIANA                   5
MASSACHUSETTS             4
WASHINGTON                4
MINNESOTA                 4
IOWA                      3
LOUISIANA                 3
MICHIGAN                  3
TENNESSEE                 3
PENNSYLVANIA              3
RHODE ISLAND              2
NEW MEXICO                2
ARKANSAS                  2
NEBRASKA                  2
KANSAS                    1
DISTRICT OF COLUMBIA      1
OREGON                    1
COLORADO                  1
SOUTH DAKOTA              1
HAWAII                    1
ALABAMA                   1
ARIZONA                   1
Name: EMPLOYER_STATES, dtype: int64

In [79]:
data4['ZIP_CODE'] = data4['EMPLOYER_POSTAL_CODE'].where(data4['EMPLOYER_POSTAL_CODE'].str.len() == 5)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [80]:
data5 = data4.dropna(how='any')

In [81]:
data5.to_excel('../Resources/ML_Ecuador.xlsx', index = False)

In [82]:
data6 = pd.read_csv('../Resources/ML_Ecuador.csv')

In [83]:
data6.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES,ZIP_CODE
0,Certified,105,98121,WA,341400,120000.0,ECUADOR,H-1B,Master's,5,WASHINGTON,98121
1,Certified,143,98103,WA,2400,64688.0,ECUADOR,H-1B,Bachelor's,12,WASHINGTON,98103
2,Certified,435,98052,WASHINGTON,58000,137972.0,ECUADOR,H-1B,Bachelor's,6,WASHINGTON,98052
3,Certified,81,98052,WA,73172,119980.0,ECUADOR,H-1B,Bachelor's,4,WASHINGTON,98052
4,Certified,107,98052,WA,73172,93300.0,ECUADOR,L-1,Bachelor's,2,WASHINGTON,98052

In [84]:
states = []

for row in data6['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data6['EMPLOYER_REGIONS'] = states

In [85]:
data6['EMPLOYER_REGIONS'].value_counts()

NORTHEAST    173
SOUTH         86
MIDWEST       40
WEST          28
OTHER          1
Name: EMPLOYER_REGIONS, dtype: int64

In [86]:
data6.count()

CASE_STATUS                      328
DECISION_ELAPSED_DAYS            328
EMPLOYER_POSTAL_CODE             328
EMPLOYER_STATE                   328
EMPLOYER_NUM_EMPLOYEES           328
WAGE_OFFER_FROM_9089             328
COUNTRY_OF_CITIZENSHIP           328
CLASS_OF_ADMISSION               328
FOREIGN_WORKER_INFO_EDUCATION    328
CASE_RECEIVED_DATE_MONTH         328
EMPLOYER_STATES                  328
ZIP_CODE                         328
EMPLOYER_REGIONS                 328
dtype: int64

In [87]:
data6['DAY_BINS'] = pd.cut(x=data6['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

In [88]:
data6['DAY_BINS'].value_counts()

91-180      97
366-3600    89
181-365     85
0-90        56
Name: DAY_BINS, dtype: int64

In [91]:
data6['WAGE_BINS'] = pd.cut(x=data6['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

In [92]:
data6['WAGE_BINS'].value_counts()

25001-50000      118
50001-75000       67
100000-500000     61
75001-100000      52
0-25000           30
Name: WAGE_BINS, dtype: int64

In [95]:
data6['EMPLOYEE_BINS'] = pd.cut(x=data6['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

In [96]:
data6['EMPLOYEE_BINS'].value_counts()

0-50                183
10001-1000000000     38
1001-10000           38
101-500              38
51-100               17
501-1000             12
Name: EMPLOYEE_BINS, dtype: int64

In [97]:
data6.count()

CASE_STATUS                      328
DECISION_ELAPSED_DAYS            328
EMPLOYER_POSTAL_CODE             328
EMPLOYER_STATE                   328
EMPLOYER_NUM_EMPLOYEES           328
WAGE_OFFER_FROM_9089             328
COUNTRY_OF_CITIZENSHIP           328
CLASS_OF_ADMISSION               328
FOREIGN_WORKER_INFO_EDUCATION    328
CASE_RECEIVED_DATE_MONTH         328
EMPLOYER_STATES                  328
ZIP_CODE                         328
EMPLOYER_REGIONS                 328
DAY_BINS                         327
WAGE_BINS                        328
EMPLOYEE_BINS                    326
dtype: int64

In [98]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [99]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
0,Certified,10001-1000000000,100000-500000,WEST,5,Master's,H-1B,91-180
1,Certified,1001-10000,50001-75000,WEST,12,Bachelor's,H-1B,91-180
2,Certified,10001-1000000000,100000-500000,WEST,6,Bachelor's,H-1B,366-3600
3,Certified,10001-1000000000,100000-500000,WEST,4,Bachelor's,H-1B,0-90
4,Certified,10001-1000000000,75001-100000,WEST,2,Bachelor's,L-1,91-180

In [100]:
data7.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH            int64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [101]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [102]:
data7['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data7['CLASS_OF_ADMISSION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [103]:
data7['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data7['FOREIGN_WORKER_INFO_EDUCATION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [105]:
data7['WAGE_BINS_CODE'] = num_encode.fit_transform(data7['WAGE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [106]:
data7['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data7['EMPLOYER_REGIONS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [111]:
data7['DAY_BINS'] = data7['DAY_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [112]:
data7['DAY_BINS_CODE'] = num_encode.fit_transform(data7['DAY_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [113]:
data7['EMPLOYEE_BINS'] = data7['EMPLOYEE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [114]:
data7['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data7['EMPLOYEE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [115]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
0,Certified,10001-1000000000,100000-500000,WEST,5,Master's,H-1B,91-180,7,4,1,4,3,1
1,Certified,1001-10000,50001-75000,WEST,12,Bachelor's,H-1B,91-180,7,1,3,4,3,2
2,Certified,10001-1000000000,100000-500000,WEST,6,Bachelor's,H-1B,366-3600,7,1,1,4,2,1
3,Certified,10001-1000000000,100000-500000,WEST,4,Bachelor's,H-1B,0-90,7,1,1,4,0,1
4,Certified,10001-1000000000,75001-100000,WEST,2,Bachelor's,L-1,91-180,10,1,4,4,3,1

In [116]:
data7.to_excel('../Resources/ML2_Ecuador.xlsx', index = False)

In [117]:
data7.count()

CASE_STATUS                           328
EMPLOYEE_BINS                         328
WAGE_BINS                             328
EMPLOYER_REGIONS                      328
CASE_RECEIVED_DATE_MONTH              328
FOREIGN_WORKER_INFO_EDUCATION         328
CLASS_OF_ADMISSION                    328
DAY_BINS                              328
CLASS_OF_ADMISSION_CODE               328
FOREIGN_WORKER_INFO_EDUCATION_CODE    328
WAGE_BINS_CODE                        328
EMPLOYER_REGIONS_CODE                 328
DAY_BINS_CODE                         328
EMPLOYEE_BINS_CODE                    328
dtype: int64

In [118]:
data8 = data7[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [119]:
data8.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
0,Certified,1,1,3,4,7,5,4
1,Certified,2,3,3,1,7,12,4
2,Certified,1,1,2,1,7,6,4
3,Certified,1,1,0,1,7,4,4
4,Certified,1,4,3,1,10,2,4

In [141]:
data8.dtypes

CASE_STATUS                           object
EMPLOYEE_BINS_CODE                     int64
WAGE_BINS_CODE                         int64
DAY_BINS_CODE                          int64
FOREIGN_WORKER_INFO_EDUCATION_CODE     int64
CLASS_OF_ADMISSION_CODE                int64
CASE_RECEIVED_DATE_MONTH               int64
EMPLOYER_REGIONS_CODE                  int64
dtype: object

In [142]:
# Assign X (data) and y (target)
X = data8.drop("CASE_STATUS", axis=1)
y = data8["CASE_STATUS"]
print(X.shape, y.shape)

(328, 7) (328,)

In [143]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [144]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [145]:
classifier.fit(X_train, y_train)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [146]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.7560975609756098
Testing Data Score: 0.7804878048780488

In [147]:
predictions = classifier.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   ['Certified' 'Certified' 'Certified' 'Certified' 'Certified' 'Certified'
 'Denied' 'Certified' 'Certified' 'Certified']
First 10 Actual labels: ['Denied', 'Certified', 'Certified', 'Denied', 'Certified', 'Certified', 'Denied', 'Denied', 'Certified', 'Certified']

In [148]:
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

   Prediction     Actual
0   Certified     Denied
1   Certified  Certified
2   Certified  Certified
3   Certified     Denied
4   Certified  Certified
5   Certified  Certified
6      Denied     Denied
7   Certified     Denied
8   Certified  Certified
9   Certified  Certified
10  Certified  Certified
11     Denied     Denied
12  Certified     Denied
13  Certified     Denied
14  Certified  Certified
15  Certified     Denied
16     Denied     Denied
17  Certified  Certified
18  Certified  Certified
19  Certified  Certified
20  Certified  Certified
21  Certified  Certified
22  Certified  Certified
23  Certified     Denied
24  Certified  Certified
25  Certified  Certified
26  Certified  Certified
27  Certified  Certified
28     Denied     Denied
29  Certified     Denied
..        ...        ...
52  Certified  Certified
53  Certified  Certified
54  Certified  Certified
55  Certified  Certified
56  Certified     Denied
57  Certified  Certified
58     Denied  Certified
59  Certified  Certified
60  Certified     Denied
61  Certified  Certified
62  Certified  Certified
63  Certified  Certified
64  Certified  Certified
65  Certified  Certified
66  Certified  Certified
67  Certified     Denied
68  Certified  Certified
69  Certified     Denied
70  Certified     Denied
71  Certified     Denied
72  Certified  Certified
73     Denied     Denied
74  Certified  Certified
75  Certified  Certified
76  Certified  Certified
77  Certified  Certified
78  Certified  Certified
79     Denied     Denied
80  Certified  Certified
81  Certified  Certified

[82 rows x 2 columns]

In [149]:
X = data8.drop("CASE_STATUS", axis=1)
y = data8["CASE_STATUS"]
print(X.shape, y.shape)

(328, 7) (328,)

In [150]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [151]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [152]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [153]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [154]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [155]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [156]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [157]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [162]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

Epoch 1/500
 - 0s - loss: 0.0956 - acc: 0.9512
Epoch 2/500
 - 0s - loss: 0.0880 - acc: 0.9593
Epoch 3/500
 - 0s - loss: 0.0885 - acc: 0.9512
Epoch 4/500
 - 0s - loss: 0.0997 - acc: 0.9512
Epoch 5/500
 - 0s - loss: 0.0992 - acc: 0.9431
Epoch 6/500
 - 0s - loss: 0.0847 - acc: 0.9553
Epoch 7/500
 - 0s - loss: 0.0999 - acc: 0.9553
Epoch 8/500
 - 0s - loss: 0.0929 - acc: 0.9553
Epoch 9/500
 - 0s - loss: 0.0912 - acc: 0.9553
Epoch 10/500
 - 0s - loss: 0.0924 - acc: 0.9553
Epoch 11/500
 - 0s - loss: 0.0892 - acc: 0.9553
Epoch 12/500
 - 0s - loss: 0.0920 - acc: 0.9431
Epoch 13/500
 - 0s - loss: 0.0890 - acc: 0.9553
Epoch 14/500
 - 0s - loss: 0.0906 - acc: 0.9512
Epoch 15/500
 - 0s - loss: 0.0884 - acc: 0.9553
Epoch 16/500
 - 0s - loss: 0.0883 - acc: 0.9512
Epoch 17/500
 - 0s - loss: 0.0913 - acc: 0.9472
Epoch 18/500
 - 0s - loss: 0.0945 - acc: 0.9512
Epoch 19/500
 - 0s - loss: 0.0915 - acc: 0.9593
Epoch 20/500
 - 0s - loss: 0.0894 - acc: 0.9472
Epoch 21/500
 - 0s - loss: 0.1022 - acc: 0.9431
Epoch 22/500
 - 0s - loss: 0.0905 - acc: 0.9472
Epoch 23/500
 - 0s - loss: 0.0879 - acc: 0.9553
Epoch 24/500
 - 0s - loss: 0.0899 - acc: 0.9553
Epoch 25/500
 - 0s - loss: 0.0967 - acc: 0.9512
Epoch 26/500
 - 0s - loss: 0.1107 - acc: 0.9431
Epoch 27/500
 - 0s - loss: 0.1088 - acc: 0.9390
Epoch 28/500
 - 0s - loss: 0.0864 - acc: 0.9593
Epoch 29/500
 - 0s - loss: 0.1095 - acc: 0.9472
Epoch 30/500
 - 0s - loss: 0.1092 - acc: 0.9512
Epoch 31/500
 - 0s - loss: 0.0931 - acc: 0.9553
Epoch 32/500
 - 0s - loss: 0.0908 - acc: 0.9512
Epoch 33/500
 - 0s - loss: 0.0890 - acc: 0.9553
Epoch 34/500
 - 0s - loss: 0.0893 - acc: 0.9593
Epoch 35/500
 - 0s - loss: 0.0892 - acc: 0.9553
Epoch 36/500
 - 0s - loss: 0.0911 - acc: 0.9512
Epoch 37/500
 - 0s - loss: 0.0964 - acc: 0.9553
Epoch 38/500
 - 0s - loss: 0.0922 - acc: 0.9472
Epoch 39/500
 - 0s - loss: 0.0913 - acc: 0.9472
Epoch 40/500
 - 0s - loss: 0.0914 - acc: 0.9472
Epoch 41/500
 - 0s - loss: 0.1002 - acc: 0.9390
Epoch 42/500
 - 0s - loss: 0.0887 - acc: 0.9472
Epoch 43/500
 - 0s - loss: 0.0887 - acc: 0.9512
Epoch 44/500
 - 0s - loss: 0.0907 - acc: 0.9553
Epoch 45/500
 - 0s - loss: 0.0954 - acc: 0.9472
Epoch 46/500
 - 0s - loss: 0.0928 - acc: 0.9634
Epoch 47/500
 - 0s - loss: 0.0873 - acc: 0.9472
Epoch 48/500
 - 0s - loss: 0.0943 - acc: 0.9512
Epoch 49/500
 - 0s - loss: 0.0913 - acc: 0.9553
Epoch 50/500
 - 0s - loss: 0.0895 - acc: 0.9472
Epoch 51/500
 - 0s - loss: 0.0901 - acc: 0.9472
Epoch 52/500
 - 0s - loss: 0.0902 - acc: 0.9472
Epoch 53/500
 - 0s - loss: 0.0896 - acc: 0.9553
Epoch 54/500
 - 0s - loss: 0.0887 - acc: 0.9553
Epoch 55/500
 - 0s - loss: 0.0879 - acc: 0.9553
Epoch 56/500
 - 0s - loss: 0.0956 - acc: 0.9512
Epoch 57/500
 - 0s - loss: 0.0966 - acc: 0.9431
Epoch 58/500
 - 0s - loss: 0.0902 - acc: 0.9593
Epoch 59/500
 - 0s - loss: 0.0922 - acc: 0.9553
Epoch 60/500
 - 0s - loss: 0.0968 - acc: 0.9472
Epoch 61/500
 - 0s - loss: 0.0842 - acc: 0.9553
Epoch 62/500
 - 0s - loss: 0.0912 - acc: 0.9512
Epoch 63/500
 - 0s - loss: 0.0866 - acc: 0.9472
Epoch 64/500
 - 0s - loss: 0.0884 - acc: 0.9472
Epoch 65/500
 - 0s - loss: 0.0908 - acc: 0.9553
Epoch 66/500
 - 0s - loss: 0.0910 - acc: 0.9512
Epoch 67/500
 - 0s - loss: 0.1035 - acc: 0.9472
Epoch 68/500
 - 0s - loss: 0.1043 - acc: 0.9431
Epoch 69/500
 - 0s - loss: 0.0880 - acc: 0.9593
Epoch 70/500
 - 0s - loss: 0.0947 - acc: 0.9553
Epoch 71/500
 - 0s - loss: 0.1018 - acc: 0.9431
Epoch 72/500
 - 0s - loss: 0.0886 - acc: 0.9512
Epoch 73/500
 - 0s - loss: 0.0885 - acc: 0.9472
Epoch 74/500
 - 0s - loss: 0.0902 - acc: 0.9512
Epoch 75/500
 - 0s - loss: 0.0937 - acc: 0.9512
Epoch 76/500
 - 0s - loss: 0.1030 - acc: 0.9431
Epoch 77/500
 - 0s - loss: 0.0921 - acc: 0.9512
Epoch 78/500
 - 0s - loss: 0.0873 - acc: 0.9553
Epoch 79/500
 - 0s - loss: 0.0922 - acc: 0.9512
Epoch 80/500
 - 0s - loss: 0.0828 - acc: 0.9553
Epoch 81/500
 - 0s - loss: 0.1004 - acc: 0.9472
Epoch 82/500
 - 0s - loss: 0.0978 - acc: 0.9472
Epoch 83/500
 - 0s - loss: 0.0878 - acc: 0.9553
Epoch 84/500
 - 0s - loss: 0.0902 - acc: 0.9553
Epoch 85/500
 - 0s - loss: 0.0936 - acc: 0.9553
Epoch 86/500
 - 0s - loss: 0.0934 - acc: 0.9472
Epoch 87/500
 - 0s - loss: 0.0840 - acc: 0.9593
Epoch 88/500
 - 0s - loss: 0.0898 - acc: 0.9553
Epoch 89/500
 - 0s - loss: 0.1009 - acc: 0.9512
Epoch 90/500
 - 0s - loss: 0.1004 - acc: 0.9512
Epoch 91/500
 - 0s - loss: 0.0905 - acc: 0.9512
Epoch 92/500
 - 0s - loss: 0.0925 - acc: 0.9553
Epoch 93/500
 - 0s - loss: 0.0904 - acc: 0.9512
Epoch 94/500
 - 0s - loss: 0.0926 - acc: 0.9512
Epoch 95/500
 - 0s - loss: 0.0876 - acc: 0.9553
Epoch 96/500
 - 0s - loss: 0.1013 - acc: 0.9431
Epoch 97/500
 - 0s - loss: 0.0926 - acc: 0.9512
Epoch 98/500
 - 0s - loss: 0.0939 - acc: 0.9553
Epoch 99/500
 - 0s - loss: 0.0977 - acc: 0.9472
Epoch 100/500
 - 0s - loss: 0.0888 - acc: 0.9431
Epoch 101/500
 - 0s - loss: 0.1003 - acc: 0.9431
Epoch 102/500
 - 0s - loss: 0.0888 - acc: 0.9553
Epoch 103/500
 - 0s - loss: 0.0862 - acc: 0.9634
Epoch 104/500
 - 0s - loss: 0.0856 - acc: 0.9512
Epoch 105/500
 - 0s - loss: 0.0874 - acc: 0.9431
Epoch 106/500
 - 0s - loss: 0.0872 - acc: 0.9553
Epoch 107/500
 - 0s - loss: 0.0914 - acc: 0.9553
Epoch 108/500
 - 0s - loss: 0.0863 - acc: 0.9553
Epoch 109/500
 - 0s - loss: 0.0879 - acc: 0.9553
Epoch 110/500
 - 0s - loss: 0.0935 - acc: 0.9593
Epoch 111/500
 - 0s - loss: 0.0852 - acc: 0.9553
Epoch 112/500
 - 0s - loss: 0.0896 - acc: 0.9512
Epoch 113/500
 - 0s - loss: 0.0898 - acc: 0.9512
Epoch 114/500
 - 0s - loss: 0.0873 - acc: 0.9553
Epoch 115/500
 - 0s - loss: 0.0879 - acc: 0.9593
Epoch 116/500
 - 0s - loss: 0.0847 - acc: 0.9553
Epoch 117/500
 - 0s - loss: 0.0889 - acc: 0.9512
Epoch 118/500
 - 0s - loss: 0.0898 - acc: 0.9553
Epoch 119/500
 - 0s - loss: 0.0858 - acc: 0.9553
Epoch 120/500
 - 0s - loss: 0.0859 - acc: 0.9553
Epoch 121/500
 - 0s - loss: 0.0891 - acc: 0.9593
Epoch 122/500
 - 0s - loss: 0.0887 - acc: 0.9593
Epoch 123/500
 - 0s - loss: 0.0857 - acc: 0.9553
Epoch 124/500
 - 0s - loss: 0.0870 - acc: 0.9553
Epoch 125/500
 - 0s - loss: 0.0919 - acc: 0.9472
Epoch 126/500
 - 0s - loss: 0.0863 - acc: 0.9553
Epoch 127/500
 - 0s - loss: 0.0888 - acc: 0.9512
Epoch 128/500
 - 0s - loss: 0.0849 - acc: 0.9593
Epoch 129/500
 - 0s - loss: 0.0887 - acc: 0.9512
Epoch 130/500
 - 0s - loss: 0.0852 - acc: 0.9553
Epoch 131/500
 - 0s - loss: 0.0861 - acc: 0.9431
Epoch 132/500
 - 0s - loss: 0.0852 - acc: 0.9512
Epoch 133/500
 - 0s - loss: 0.0882 - acc: 0.9431
Epoch 134/500
 - 0s - loss: 0.0892 - acc: 0.9472
Epoch 135/500
 - 0s - loss: 0.0871 - acc: 0.9512
Epoch 136/500
 - 0s - loss: 0.0849 - acc: 0.9472
Epoch 137/500
 - 0s - loss: 0.0880 - acc: 0.9512
Epoch 138/500
 - 0s - loss: 0.1024 - acc: 0.9512
Epoch 139/500
 - 0s - loss: 0.1003 - acc: 0.9431
Epoch 140/500
 - 0s - loss: 0.0876 - acc: 0.9512
Epoch 141/500
 - 0s - loss: 0.0887 - acc: 0.9553
Epoch 142/500
 - 0s - loss: 0.0904 - acc: 0.9472
Epoch 143/500
 - 0s - loss: 0.0871 - acc: 0.9512
Epoch 144/500
 - 0s - loss: 0.0902 - acc: 0.9512
Epoch 145/500
 - 0s - loss: 0.0863 - acc: 0.9472
Epoch 146/500
 - 0s - loss: 0.0852 - acc: 0.9553
Epoch 147/500
 - 0s - loss: 0.0916 - acc: 0.9512
Epoch 148/500
 - 0s - loss: 0.0849 - acc: 0.9634
Epoch 149/500
 - 0s - loss: 0.0889 - acc: 0.9431
Epoch 150/500
 - 0s - loss: 0.0996 - acc: 0.9553
Epoch 151/500
 - 0s - loss: 0.0983 - acc: 0.9553
Epoch 152/500
 - 0s - loss: 0.1231 - acc: 0.9390
Epoch 153/500
 - 0s - loss: 0.0847 - acc: 0.9634
Epoch 154/500
 - 0s - loss: 0.0988 - acc: 0.9472
Epoch 155/500
 - 0s - loss: 0.0950 - acc: 0.9553
Epoch 156/500
 - 0s - loss: 0.0947 - acc: 0.9472
Epoch 157/500
 - 0s - loss: 0.0879 - acc: 0.9512
Epoch 158/500
 - 0s - loss: 0.0917 - acc: 0.9553
Epoch 159/500
 - 0s - loss: 0.0990 - acc: 0.9472
Epoch 160/500
 - 0s - loss: 0.0875 - acc: 0.9553
Epoch 161/500
 - 0s - loss: 0.0940 - acc: 0.9553
Epoch 162/500
 - 0s - loss: 0.0931 - acc: 0.9512
Epoch 163/500
 - 0s - loss: 0.0933 - acc: 0.9472
Epoch 164/500
 - 0s - loss: 0.0896 - acc: 0.9431
Epoch 165/500
 - 0s - loss: 0.0887 - acc: 0.9472
Epoch 166/500
 - 0s - loss: 0.0868 - acc: 0.9553
Epoch 167/500
 - 0s - loss: 0.0872 - acc: 0.9512
Epoch 168/500
 - 0s - loss: 0.0876 - acc: 0.9593
Epoch 169/500
 - 0s - loss: 0.0954 - acc: 0.9512
Epoch 170/500
 - 0s - loss: 0.0858 - acc: 0.9553

Epoch 171/500
 - 0s - loss: 0.0968 - acc: 0.9512
Epoch 172/500
 - 0s - loss: 0.0947 - acc: 0.9553
Epoch 173/500
 - 0s - loss: 0.0956 - acc: 0.9431
Epoch 174/500
 - 0s - loss: 0.0864 - acc: 0.9512
Epoch 175/500
 - 0s - loss: 0.0916 - acc: 0.9553
Epoch 176/500
 - 0s - loss: 0.0904 - acc: 0.9472
Epoch 177/500
 - 0s - loss: 0.0902 - acc: 0.9553
Epoch 178/500
 - 0s - loss: 0.0942 - acc: 0.9553
Epoch 179/500
 - 0s - loss: 0.0918 - acc: 0.9472
Epoch 180/500
 - 0s - loss: 0.0862 - acc: 0.9553
Epoch 181/500
 - 0s - loss: 0.0886 - acc: 0.9472
Epoch 182/500
 - 0s - loss: 0.0874 - acc: 0.9512
Epoch 183/500
 - 0s - loss: 0.0887 - acc: 0.9512
Epoch 184/500
 - 0s - loss: 0.0901 - acc: 0.9553
Epoch 185/500
 - 0s - loss: 0.0916 - acc: 0.9512
Epoch 186/500
 - 0s - loss: 0.0875 - acc: 0.9472
Epoch 187/500
 - 0s - loss: 0.0863 - acc: 0.9512
Epoch 188/500
 - 0s - loss: 0.0870 - acc: 0.9553
Epoch 189/500
 - 0s - loss: 0.0870 - acc: 0.9553
Epoch 190/500
 - 0s - loss: 0.0865 - acc: 0.9512
Epoch 191/500
 - 0s - loss: 0.0822 - acc: 0.9593
Epoch 192/500
 - 0s - loss: 0.0941 - acc: 0.9431
Epoch 193/500
 - 0s - loss: 0.0950 - acc: 0.9553
Epoch 194/500
 - 0s - loss: 0.0953 - acc: 0.9553
Epoch 195/500
 - 0s - loss: 0.0904 - acc: 0.9512
Epoch 196/500
 - 0s - loss: 0.0879 - acc: 0.9472
Epoch 197/500
 - 0s - loss: 0.0873 - acc: 0.9553
Epoch 198/500
 - 0s - loss: 0.0962 - acc: 0.9512
Epoch 199/500
 - 0s - loss: 0.0856 - acc: 0.9593
Epoch 200/500
 - 0s - loss: 0.0859 - acc: 0.9553
Epoch 201/500
 - 0s - loss: 0.0933 - acc: 0.9553
Epoch 202/500
 - 0s - loss: 0.0853 - acc: 0.9553
Epoch 203/500
 - 0s - loss: 0.0903 - acc: 0.9512
Epoch 204/500
 - 0s - loss: 0.0860 - acc: 0.9512
Epoch 205/500
 - 0s - loss: 0.0887 - acc: 0.9431
Epoch 206/500
 - 0s - loss: 0.0862 - acc: 0.9553
Epoch 207/500
 - 0s - loss: 0.0836 - acc: 0.9553
Epoch 208/500
 - 0s - loss: 0.0902 - acc: 0.9553
Epoch 209/500
 - 0s - loss: 0.0879 - acc: 0.9512
Epoch 210/500
 - 0s - loss: 0.0878 - acc: 0.9553
Epoch 211/500
 - 0s - loss: 0.0873 - acc: 0.9593
Epoch 212/500
 - 0s - loss: 0.0852 - acc: 0.9593
Epoch 213/500
 - 0s - loss: 0.0863 - acc: 0.9553
Epoch 214/500
 - 0s - loss: 0.0876 - acc: 0.9512
Epoch 215/500
 - 0s - loss: 0.0846 - acc: 0.9553
Epoch 216/500
 - 0s - loss: 0.0874 - acc: 0.9472
Epoch 217/500
 - 0s - loss: 0.0874 - acc: 0.9553
Epoch 218/500
 - 0s - loss: 0.0860 - acc: 0.9553
Epoch 219/500
 - 0s - loss: 0.0902 - acc: 0.9472
Epoch 220/500
 - 0s - loss: 0.0851 - acc: 0.9553
Epoch 221/500
 - 0s - loss: 0.0891 - acc: 0.9512
Epoch 222/500
 - 0s - loss: 0.0862 - acc: 0.9553
Epoch 223/500
 - 0s - loss: 0.0842 - acc: 0.9553
Epoch 224/500
 - 0s - loss: 0.0877 - acc: 0.9553
Epoch 225/500
 - 0s - loss: 0.0878 - acc: 0.9512
Epoch 226/500
 - 0s - loss: 0.0895 - acc: 0.9553
Epoch 227/500
 - 0s - loss: 0.0966 - acc: 0.9472
Epoch 228/500
 - 0s - loss: 0.0966 - acc: 0.9472
Epoch 229/500
 - 0s - loss: 0.0842 - acc: 0.9553
Epoch 230/500
 - 0s - loss: 0.0895 - acc: 0.9553
Epoch 231/500
 - 0s - loss: 0.0862 - acc: 0.9553
Epoch 232/500
 - 0s - loss: 0.0872 - acc: 0.9512
Epoch 233/500
 - 0s - loss: 0.1012 - acc: 0.9512
Epoch 234/500
 - 0s - loss: 0.0822 - acc: 0.9553
Epoch 235/500
 - 0s - loss: 0.0914 - acc: 0.9431
Epoch 236/500
 - 0s - loss: 0.0852 - acc: 0.9593
Epoch 237/500
 - 0s - loss: 0.0905 - acc: 0.9390
Epoch 238/500
 - 0s - loss: 0.0872 - acc: 0.9512
Epoch 239/500
 - 0s - loss: 0.0923 - acc: 0.9512
Epoch 240/500
 - 0s - loss: 0.0961 - acc: 0.9390
Epoch 241/500
 - 0s - loss: 0.0834 - acc: 0.9553
Epoch 242/500
 - 0s - loss: 0.0935 - acc: 0.9553
Epoch 243/500
 - 0s - loss: 0.0848 - acc: 0.9512
Epoch 244/500
 - 0s - loss: 0.0869 - acc: 0.9512
Epoch 245/500
 - 0s - loss: 0.0938 - acc: 0.9390
Epoch 246/500
 - 0s - loss: 0.0848 - acc: 0.9512
Epoch 247/500
 - 0s - loss: 0.0872 - acc: 0.9553
Epoch 248/500
 - 0s - loss: 0.0828 - acc: 0.9553
Epoch 249/500
 - 0s - loss: 0.0890 - acc: 0.9553
Epoch 250/500
 - 0s - loss: 0.0863 - acc: 0.9512
Epoch 251/500
 - 0s - loss: 0.0870 - acc: 0.9431
Epoch 252/500
 - 0s - loss: 0.0880 - acc: 0.9593
Epoch 253/500
 - 0s - loss: 0.0841 - acc: 0.9553
Epoch 254/500
 - 0s - loss: 0.0887 - acc: 0.9512
Epoch 255/500
 - 0s - loss: 0.0936 - acc: 0.9512
Epoch 256/500
 - 0s - loss: 0.0898 - acc: 0.9390
Epoch 257/500
 - 0s - loss: 0.0890 - acc: 0.9472
Epoch 258/500
 - 0s - loss: 0.0912 - acc: 0.9431
Epoch 259/500
 - 0s - loss: 0.0967 - acc: 0.9472
Epoch 260/500
 - 0s - loss: 0.0888 - acc: 0.9472
Epoch 261/500
 - 0s - loss: 0.0848 - acc: 0.9512
Epoch 262/500
 - 0s - loss: 0.0840 - acc: 0.9512
Epoch 263/500
 - 0s - loss: 0.0878 - acc: 0.9512
Epoch 264/500
 - 0s - loss: 0.0841 - acc: 0.9472
Epoch 265/500
 - 0s - loss: 0.0861 - acc: 0.9553
Epoch 266/500
 - 0s - loss: 0.0828 - acc: 0.9553
Epoch 267/500
 - 0s - loss: 0.0848 - acc: 0.9553
Epoch 268/500
 - 0s - loss: 0.0870 - acc: 0.9472
Epoch 269/500
 - 0s - loss: 0.0905 - acc: 0.9472
Epoch 270/500
 - 0s - loss: 0.0861 - acc: 0.9593
Epoch 271/500
 - 0s - loss: 0.0870 - acc: 0.9553
Epoch 272/500
 - 0s - loss: 0.0930 - acc: 0.9512
Epoch 273/500
 - 0s - loss: 0.0914 - acc: 0.9431
Epoch 274/500
 - 0s - loss: 0.0876 - acc: 0.9472
Epoch 275/500
 - 0s - loss: 0.0900 - acc: 0.9553
Epoch 276/500
 - 0s - loss: 0.0910 - acc: 0.9512
Epoch 277/500
 - 0s - loss: 0.0950 - acc: 0.9553
Epoch 278/500
 - 0s - loss: 0.0886 - acc: 0.9431
Epoch 279/500
 - 0s - loss: 0.0861 - acc: 0.9512
Epoch 280/500
 - 0s - loss: 0.0888 - acc: 0.9431
Epoch 281/500
 - 0s - loss: 0.0875 - acc: 0.9431
Epoch 282/500
 - 0s - loss: 0.0877 - acc: 0.9553
Epoch 283/500
 - 0s - loss: 0.0841 - acc: 0.9553
Epoch 284/500
 - 0s - loss: 0.0871 - acc: 0.9634
Epoch 285/500
 - 0s - loss: 0.0916 - acc: 0.9512
Epoch 286/500
 - 0s - loss: 0.0863 - acc: 0.9553
Epoch 287/500
 - 0s - loss: 0.0897 - acc: 0.9512
Epoch 288/500
 - 0s - loss: 0.0845 - acc: 0.9512
Epoch 289/500
 - 0s - loss: 0.0898 - acc: 0.9390
Epoch 290/500
 - 0s - loss: 0.0990 - acc: 0.9472
Epoch 291/500
 - 0s - loss: 0.0852 - acc: 0.9512
Epoch 292/500
 - 0s - loss: 0.0885 - acc: 0.9512
Epoch 293/500
 - 0s - loss: 0.0896 - acc: 0.9472
Epoch 294/500
 - 0s - loss: 0.1003 - acc: 0.9390
Epoch 295/500
 - 0s - loss: 0.0905 - acc: 0.9553
Epoch 296/500
 - 0s - loss: 0.0866 - acc: 0.9512
Epoch 297/500
 - 0s - loss: 0.0842 - acc: 0.9512
Epoch 298/500
 - 0s - loss: 0.0861 - acc: 0.9553
Epoch 299/500
 - 0s - loss: 0.0846 - acc: 0.9553
Epoch 300/500
 - 0s - loss: 0.0893 - acc: 0.9553
Epoch 301/500
 - 0s - loss: 0.0851 - acc: 0.9472
Epoch 302/500
 - 0s - loss: 0.0876 - acc: 0.9512
Epoch 303/500
 - 0s - loss: 0.0884 - acc: 0.9512
Epoch 304/500
 - 0s - loss: 0.0824 - acc: 0.9512
Epoch 305/500
 - 0s - loss: 0.0936 - acc: 0.9553
Epoch 306/500
 - 0s - loss: 0.0870 - acc: 0.9553
Epoch 307/500
 - 0s - loss: 0.0844 - acc: 0.9512
Epoch 308/500
 - 0s - loss: 0.0878 - acc: 0.9512
Epoch 309/500
 - 0s - loss: 0.0876 - acc: 0.9512
Epoch 310/500
 - 0s - loss: 0.0872 - acc: 0.9512
Epoch 311/500
 - 0s - loss: 0.0878 - acc: 0.9512
Epoch 312/500
 - 0s - loss: 0.0887 - acc: 0.9472
Epoch 313/500
 - 0s - loss: 0.0840 - acc: 0.9472
Epoch 314/500
 - 0s - loss: 0.0835 - acc: 0.9512
Epoch 315/500
 - 0s - loss: 0.0951 - acc: 0.9431
Epoch 316/500
 - 0s - loss: 0.0932 - acc: 0.9431
Epoch 317/500
 - 0s - loss: 0.0804 - acc: 0.9512
Epoch 318/500
 - 0s - loss: 0.1008 - acc: 0.9472
Epoch 319/500
 - 0s - loss: 0.1061 - acc: 0.9472
Epoch 320/500
 - 0s - loss: 0.0883 - acc: 0.9553
Epoch 321/500
 - 0s - loss: 0.0887 - acc: 0.9553
Epoch 322/500
 - 0s - loss: 0.0869 - acc: 0.9512
Epoch 323/500
 - 0s - loss: 0.0906 - acc: 0.9553
Epoch 324/500
 - 0s - loss: 0.0855 - acc: 0.9512
Epoch 325/500
 - 0s - loss: 0.0838 - acc: 0.9593
Epoch 326/500
 - 0s - loss: 0.0842 - acc: 0.9553
Epoch 327/500
 - 0s - loss: 0.0917 - acc: 0.9431
Epoch 328/500
 - 0s - loss: 0.0878 - acc: 0.9472
Epoch 329/500
 - 0s - loss: 0.0866 - acc: 0.9553
Epoch 330/500
 - 0s - loss: 0.0846 - acc: 0.9472
Epoch 331/500
 - 0s - loss: 0.0845 - acc: 0.9512
Epoch 332/500
 - 0s - loss: 0.0867 - acc: 0.9512
Epoch 333/500
 - 0s - loss: 0.0873 - acc: 0.9553
Epoch 334/500
 - 0s - loss: 0.0906 - acc: 0.9512
Epoch 335/500
 - 0s - loss: 0.0847 - acc: 0.9472
Epoch 336/500
 - 0s - loss: 0.0896 - acc: 0.9553
Epoch 337/500
 - 0s - loss: 0.0866 - acc: 0.9472
Epoch 338/500

 - 0s - loss: 0.0867 - acc: 0.9512
Epoch 339/500
 - 0s - loss: 0.0868 - acc: 0.9512
Epoch 340/500
 - 0s - loss: 0.0885 - acc: 0.9512
Epoch 341/500
 - 0s - loss: 0.0859 - acc: 0.9472
Epoch 342/500
 - 0s - loss: 0.0886 - acc: 0.9472
Epoch 343/500
 - 0s - loss: 0.0871 - acc: 0.9390
Epoch 344/500
 - 0s - loss: 0.0882 - acc: 0.9472
Epoch 345/500
 - 0s - loss: 0.0880 - acc: 0.9512
Epoch 346/500
 - 0s - loss: 0.0866 - acc: 0.9512
Epoch 347/500
 - 0s - loss: 0.0841 - acc: 0.9553
Epoch 348/500
 - 0s - loss: 0.0899 - acc: 0.9390
Epoch 349/500
 - 0s - loss: 0.0913 - acc: 0.9512
Epoch 350/500
 - 0s - loss: 0.0865 - acc: 0.9472
Epoch 351/500
 - 0s - loss: 0.0870 - acc: 0.9472
Epoch 352/500
 - 0s - loss: 0.0842 - acc: 0.9553
Epoch 353/500
 - 0s - loss: 0.0908 - acc: 0.9512
Epoch 354/500
 - 0s - loss: 0.0892 - acc: 0.9512
Epoch 355/500
 - 0s - loss: 0.0861 - acc: 0.9512
Epoch 356/500
 - 0s - loss: 0.0854 - acc: 0.9472
Epoch 357/500
 - 0s - loss: 0.0821 - acc: 0.9512
Epoch 358/500
 - 0s - loss: 0.0865 - acc: 0.9512
Epoch 359/500
 - 0s - loss: 0.0878 - acc: 0.9512
Epoch 360/500
 - 0s - loss: 0.0832 - acc: 0.9512
Epoch 361/500
 - 0s - loss: 0.0874 - acc: 0.9593
Epoch 362/500
 - 0s - loss: 0.0873 - acc: 0.9512
Epoch 363/500
 - 0s - loss: 0.0862 - acc: 0.9593
Epoch 364/500
 - 0s - loss: 0.0882 - acc: 0.9553
Epoch 365/500
 - 0s - loss: 0.0865 - acc: 0.9512
Epoch 366/500
 - 0s - loss: 0.0907 - acc: 0.9553
Epoch 367/500
 - 0s - loss: 0.0889 - acc: 0.9512
Epoch 368/500
 - 0s - loss: 0.0880 - acc: 0.9431
Epoch 369/500
 - 0s - loss: 0.0869 - acc: 0.9512
Epoch 370/500
 - 0s - loss: 0.0928 - acc: 0.9472
Epoch 371/500
 - 0s - loss: 0.0907 - acc: 0.9553
Epoch 372/500
 - 0s - loss: 0.0956 - acc: 0.9431
Epoch 373/500
 - 0s - loss: 0.0916 - acc: 0.9553
Epoch 374/500
 - 0s - loss: 0.0860 - acc: 0.9553
Epoch 375/500
 - 0s - loss: 0.0869 - acc: 0.9553
Epoch 376/500
 - 0s - loss: 0.0853 - acc: 0.9553
Epoch 377/500
 - 0s - loss: 0.0918 - acc: 0.9431
Epoch 378/500
 - 0s - loss: 0.0946 - acc: 0.9553
Epoch 379/500
 - 0s - loss: 0.0836 - acc: 0.9553
Epoch 380/500
 - 0s - loss: 0.0927 - acc: 0.9553
Epoch 381/500
 - 0s - loss: 0.0922 - acc: 0.9512
Epoch 382/500
 - 0s - loss: 0.0894 - acc: 0.9472
Epoch 383/500
 - 0s - loss: 0.0860 - acc: 0.9390
Epoch 384/500
 - 0s - loss: 0.0866 - acc: 0.9472
Epoch 385/500
 - 0s - loss: 0.0846 - acc: 0.9553
Epoch 386/500
 - 0s - loss: 0.0870 - acc: 0.9512
Epoch 387/500
 - 0s - loss: 0.0836 - acc: 0.9472
Epoch 388/500
 - 0s - loss: 0.0885 - acc: 0.9553
Epoch 389/500
 - 0s - loss: 0.0921 - acc: 0.9512
Epoch 390/500
 - 0s - loss: 0.0852 - acc: 0.9553
Epoch 391/500
 - 0s - loss: 0.0840 - acc: 0.9553
Epoch 392/500
 - 0s - loss: 0.0865 - acc: 0.9512
Epoch 393/500
 - 0s - loss: 0.0898 - acc: 0.9512
Epoch 394/500
 - 0s - loss: 0.0877 - acc: 0.9553
Epoch 395/500
 - 0s - loss: 0.0905 - acc: 0.9553
Epoch 396/500
 - 0s - loss: 0.0845 - acc: 0.9553
Epoch 397/500
 - 0s - loss: 0.0849 - acc: 0.9512
Epoch 398/500
 - 0s - loss: 0.0867 - acc: 0.9593
Epoch 399/500
 - 0s - loss: 0.0846 - acc: 0.9593
Epoch 400/500
 - 0s - loss: 0.0890 - acc: 0.9431
Epoch 401/500
 - 0s - loss: 0.0854 - acc: 0.9472
Epoch 402/500
 - 0s - loss: 0.0851 - acc: 0.9512
Epoch 403/500
 - 0s - loss: 0.0866 - acc: 0.9512
Epoch 404/500
 - 0s - loss: 0.0862 - acc: 0.9472
Epoch 405/500
 - 0s - loss: 0.0831 - acc: 0.9512
Epoch 406/500
 - 0s - loss: 0.0823 - acc: 0.9512
Epoch 407/500
 - 0s - loss: 0.0854 - acc: 0.9512
Epoch 408/500
 - 0s - loss: 0.0856 - acc: 0.9472
Epoch 409/500
 - 0s - loss: 0.0856 - acc: 0.9553
Epoch 410/500
 - 0s - loss: 0.0828 - acc: 0.9593
Epoch 411/500
 - 0s - loss: 0.0858 - acc: 0.9512
Epoch 412/500
 - 0s - loss: 0.0879 - acc: 0.9512
Epoch 413/500
 - 0s - loss: 0.0906 - acc: 0.9553
Epoch 414/500
 - 0s - loss: 0.0825 - acc: 0.9512
Epoch 415/500
 - 0s - loss: 0.0882 - acc: 0.9472
Epoch 416/500
 - 0s - loss: 0.0851 - acc: 0.9472
Epoch 417/500
 - 0s - loss: 0.0880 - acc: 0.9512
Epoch 418/500
 - 0s - loss: 0.0849 - acc: 0.9593
Epoch 419/500
 - 0s - loss: 0.0834 - acc: 0.9512
Epoch 420/500
 - 0s - loss: 0.0849 - acc: 0.9512
Epoch 421/500
 - 0s - loss: 0.0835 - acc: 0.9553
Epoch 422/500
 - 0s - loss: 0.0849 - acc: 0.9512
Epoch 423/500
 - 0s - loss: 0.0834 - acc: 0.9472
Epoch 424/500
 - 0s - loss: 0.0858 - acc: 0.9512
Epoch 425/500
 - 0s - loss: 0.0900 - acc: 0.9472
Epoch 426/500
 - 0s - loss: 0.0880 - acc: 0.9512
Epoch 427/500
 - 0s - loss: 0.0867 - acc: 0.9553
Epoch 428/500
 - 0s - loss: 0.0843 - acc: 0.9553
Epoch 429/500
 - 0s - loss: 0.0909 - acc: 0.9512
Epoch 430/500
 - 0s - loss: 0.0880 - acc: 0.9431
Epoch 431/500
 - 0s - loss: 0.0882 - acc: 0.9553
Epoch 432/500
 - 0s - loss: 0.0889 - acc: 0.9512
Epoch 433/500
 - 0s - loss: 0.0909 - acc: 0.9553
Epoch 434/500
 - 0s - loss: 0.0852 - acc: 0.9512
Epoch 435/500
 - 0s - loss: 0.0948 - acc: 0.9431
Epoch 436/500
 - 0s - loss: 0.0904 - acc: 0.9553
Epoch 437/500
 - 0s - loss: 0.0859 - acc: 0.9512
Epoch 438/500
 - 0s - loss: 0.0856 - acc: 0.9512
Epoch 439/500
 - 0s - loss: 0.0835 - acc: 0.9472
Epoch 440/500
 - 0s - loss: 0.0873 - acc: 0.9431
Epoch 441/500
 - 0s - loss: 0.0868 - acc: 0.9593
Epoch 442/500
 - 0s - loss: 0.0829 - acc: 0.9553
Epoch 443/500
 - 0s - loss: 0.0861 - acc: 0.9553
Epoch 444/500
 - 0s - loss: 0.0847 - acc: 0.9553
Epoch 445/500
 - 0s - loss: 0.0841 - acc: 0.9553
Epoch 446/500
 - 0s - loss: 0.0811 - acc: 0.9472
Epoch 447/500
 - 0s - loss: 0.0892 - acc: 0.9472
Epoch 448/500
 - 0s - loss: 0.0828 - acc: 0.9512
Epoch 449/500
 - 0s - loss: 0.0889 - acc: 0.9431
Epoch 450/500
 - 0s - loss: 0.0846 - acc: 0.9553
Epoch 451/500
 - 0s - loss: 0.0854 - acc: 0.9553
Epoch 452/500
 - 0s - loss: 0.0878 - acc: 0.9512
Epoch 453/500
 - 0s - loss: 0.0924 - acc: 0.9553
Epoch 454/500
 - 0s - loss: 0.0838 - acc: 0.9553
Epoch 455/500
 - 0s - loss: 0.0950 - acc: 0.9512
Epoch 456/500
 - 0s - loss: 0.0872 - acc: 0.9512
Epoch 457/500
 - 0s - loss: 0.0866 - acc: 0.9593
Epoch 458/500
 - 0s - loss: 0.0858 - acc: 0.9512
Epoch 459/500
 - 0s - loss: 0.0882 - acc: 0.9553
Epoch 460/500
 - 0s - loss: 0.0833 - acc: 0.9553
Epoch 461/500
 - 0s - loss: 0.0812 - acc: 0.9512
Epoch 462/500
 - 0s - loss: 0.0874 - acc: 0.9553
Epoch 463/500
 - 0s - loss: 0.0883 - acc: 0.9472
Epoch 464/500
 - 0s - loss: 0.0850 - acc: 0.9472
Epoch 465/500
 - 0s - loss: 0.0858 - acc: 0.9553
Epoch 466/500
 - 0s - loss: 0.0840 - acc: 0.9553
Epoch 467/500
 - 0s - loss: 0.0934 - acc: 0.9431
Epoch 468/500
 - 0s - loss: 0.0927 - acc: 0.9553
Epoch 469/500
 - 0s - loss: 0.0884 - acc: 0.9593
Epoch 470/500
 - 0s - loss: 0.0880 - acc: 0.9553
Epoch 471/500
 - 0s - loss: 0.0909 - acc: 0.9553
Epoch 472/500
 - 0s - loss: 0.0858 - acc: 0.9593
Epoch 473/500
 - 0s - loss: 0.0864 - acc: 0.9431
Epoch 474/500
 - 0s - loss: 0.0854 - acc: 0.9553
Epoch 475/500
 - 0s - loss: 0.0904 - acc: 0.9472
Epoch 476/500
 - 0s - loss: 0.0826 - acc: 0.9593
Epoch 477/500
 - 0s - loss: 0.0843 - acc: 0.9553
Epoch 478/500
 - 0s - loss: 0.0875 - acc: 0.9553
Epoch 479/500
 - 0s - loss: 0.0879 - acc: 0.9431
Epoch 480/500
 - 0s - loss: 0.0815 - acc: 0.9512
Epoch 481/500
 - 0s - loss: 0.0848 - acc: 0.9553
Epoch 482/500
 - 0s - loss: 0.0842 - acc: 0.9512
Epoch 483/500
 - 0s - loss: 0.0904 - acc: 0.9553
Epoch 484/500
 - 0s - loss: 0.0898 - acc: 0.9512
Epoch 485/500
 - 0s - loss: 0.0838 - acc: 0.9553
Epoch 486/500
 - 0s - loss: 0.0873 - acc: 0.9553
Epoch 487/500
 - 0s - loss: 0.0841 - acc: 0.9431
Epoch 488/500
 - 0s - loss: 0.0979 - acc: 0.9472
Epoch 489/500
 - 0s - loss: 0.0854 - acc: 0.9512
Epoch 490/500
 - 0s - loss: 0.0879 - acc: 0.9553
Epoch 491/500
 - 0s - loss: 0.0855 - acc: 0.9553
Epoch 492/500
 - 0s - loss: 0.0909 - acc: 0.9553
Epoch 493/500
 - 0s - loss: 0.0929 - acc: 0.9431
Epoch 494/500
 - 0s - loss: 0.0865 - acc: 0.9512
Epoch 495/500
 - 0s - loss: 0.1014 - acc: 0.9472
Epoch 496/500
 - 0s - loss: 0.0905 - acc: 0.9553
Epoch 497/500
 - 0s - loss: 0.0929 - acc: 0.9593
Epoch 498/500
 - 0s - loss: 0.0863 - acc: 0.9593
Epoch 499/500
 - 0s - loss: 0.0932 - acc: 0.9512
Epoch 500/500
 - 0s - loss: 0.1046 - acc: 0.9512

In [163]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 2.8993 - acc: 0.6585
Normal Neural Network - Loss: 2.8993123566232075, Accuracy: 0.6585366129875183

In [164]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [165]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Denied' 'Certified' 'Certified' 'Certified' 'Certified' 'Certified'
 'Certified' 'Certified' 'Denied' 'Certified']
Actual Labels: ['Denied', 'Denied', 'Denied', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified']