In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'HUNGARY']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

HUNGARY    207
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    200
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [8]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [9]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [10]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
650,Certified,470,06880,CONNECTICUT,0.0,24835.0,HUNGARY,B-2,Other,5.0
1970,Certified,231,10036,NEW YORK,55794.0,130000.0,HUNGARY,L-1,Bachelor's,1.0
2816,Certified,528,11201,NEW YORK,135000.0,45530.0,HUNGARY,H-1B,Master's,1.0
4238,Certified,192,60022,ILLINOIS,0.0,30202.0,HUNGARY,J-1,Master's,1.0
5062,Certified,195,06830,CONNECTICUT,194.0,145000.0,HUNGARY,L-1,Bachelor's,2.0

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

CALIFORNIA              43
NEW YORK                31
PENNSYLVANIA            20
TEXAS                   17
MASSACHUSETTS           15
FLORIDA                 12
ILLINOIS                10
WASHINGTON              10
NEW JERSEY               7
CONNECTICUT              7
MICHIGAN                 6
VIRGINIA                 3
OHIO                     3
MONTANA                  2
SOUTH CAROLINA           2
DISTRICT OF COLUMBIA     2
MARYLAND                 2
HAWAII                   1
NEVADA                   1
NORTH CAROLINA           1
LOUISIANA                1
NEW HAMPSHIRE            1
MISSOURI                 1
OREGON                   1
UTAH                     1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
650,Certified,470,06880,CONNECTICUT,0.0,24835.0,HUNGARY,B-2,Other,5.0,CONNECTICUT
1970,Certified,231,10036,NEW YORK,55794.0,130000.0,HUNGARY,L-1,Bachelor's,1.0,NEW YORK
2816,Certified,528,11201,NEW YORK,135000.0,45530.0,HUNGARY,H-1B,Master's,1.0,NEW YORK
4238,Certified,192,60022,ILLINOIS,0.0,30202.0,HUNGARY,J-1,Master's,1.0,ILLINOIS
5062,Certified,195,06830,CONNECTICUT,194.0,145000.0,HUNGARY,L-1,Bachelor's,2.0,CONNECTICUT

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

NORTHEAST    72
WEST         53
SOUTH        36
MIDWEST      18
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      179
DECISION_ELAPSED_DAYS            179
EMPLOYER_POSTAL_CODE             179
EMPLOYER_STATE                   179
EMPLOYER_NUM_EMPLOYEES           179
WAGE_OFFER_FROM_9089             179
COUNTRY_OF_CITIZENSHIP           179
CLASS_OF_ADMISSION               179
FOREIGN_WORKER_INFO_EDUCATION    179
CASE_RECEIVED_DATE_MONTH         179
EMPLOYER_STATES                  179
EMPLOYER_REGIONS                 179
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      75
0-90        53
181-365     35
366-3600    15
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

100000-500000    77
75001-100000     53
50001-75000      30
25001-50000      16
0-25000           2
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

1001-10000          59
0-50                41
10001-1000000000    40
101-500             19
501-1000            10
51-100               8
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      179
DECISION_ELAPSED_DAYS            179
EMPLOYER_POSTAL_CODE             179
EMPLOYER_STATE                   179
EMPLOYER_NUM_EMPLOYEES           179
WAGE_OFFER_FROM_9089             179
COUNTRY_OF_CITIZENSHIP           179
CLASS_OF_ADMISSION               179
FOREIGN_WORKER_INFO_EDUCATION    179
CASE_RECEIVED_DATE_MONTH         179
EMPLOYER_STATES                  179
EMPLOYER_REGIONS                 179
DAY_BINS                         178
WAGE_BINS                        178
EMPLOYEE_BINS                    177
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
650,Certified,NaN,0-25000,NORTHEAST,5.0,Other,B-2,366-3600
1970,Certified,10001-1000000000,100000-500000,NORTHEAST,1.0,Bachelor's,L-1,181-365
2816,Certified,10001-1000000000,25001-50000,NORTHEAST,1.0,Master's,H-1B,366-3600
4238,Certified,NaN,25001-50000,MIDWEST,1.0,Master's,J-1,181-365
5062,Certified,101-500,100000-500000,NORTHEAST,2.0,Bachelor's,L-1,181-365

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
650,Certified,nan,0-25000,NORTHEAST,5.0,Other,B-2,366-3600,1,6,0,1,2,6
1970,Certified,10001-1000000000,100000-500000,NORTHEAST,1.0,Bachelor's,L-1,181-365,7,1,1,1,1,1
2816,Certified,10001-1000000000,25001-50000,NORTHEAST,1.0,Master's,H-1B,366-3600,4,4,2,1,2,1
4238,Certified,nan,25001-50000,MIDWEST,1.0,Master's,J-1,181-365,5,4,2,0,1,6
5062,Certified,101-500,100000-500000,NORTHEAST,2.0,Bachelor's,L-1,181-365,7,1,1,1,1,3

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           179
EMPLOYEE_BINS                         179
WAGE_BINS                             179
EMPLOYER_REGIONS                      179
CASE_RECEIVED_DATE_MONTH              179
FOREIGN_WORKER_INFO_EDUCATION         179
CLASS_OF_ADMISSION                    179
DAY_BINS                              179
CLASS_OF_ADMISSION_CODE               179
FOREIGN_WORKER_INFO_EDUCATION_CODE    179
WAGE_BINS_CODE                        179
EMPLOYER_REGIONS_CODE                 179
DAY_BINS_CODE                         179
EMPLOYEE_BINS_CODE                    179
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
650,Certified,6,0,2,6,1,5.0,1
1970,Certified,1,1,1,1,7,1.0,1
2816,Certified,1,2,2,4,4,1.0,1
4238,Certified,6,2,1,4,5,1.0,0
5062,Certified,3,1,1,1,7,2.0,1

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int32
WAGE_BINS_CODE                          int32
DAY_BINS_CODE                           int32
FOREIGN_WORKER_INFO_EDUCATION_CODE      int32
CLASS_OF_ADMISSION_CODE                 int32
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int32
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(179, 7) (179,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int32, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [53]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From C:\Users\kathleen.buckingham\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 1s - loss: 0.7862 - acc: 0.1343
Epoch 2/500
 - 0s - loss: 0.6274 - acc: 0.8881
Epoch 3/500
 - 0s - loss: 0.5134 - acc: 0.9030
Epoch 4/500
 - 0s - loss: 0.4297 - acc: 0.9030
Epoch 5/500
 - 0s - loss: 0.3658 - acc: 0.9030
Epoch 6/500
 - 0s - loss: 0.3280 - acc: 0.9030
Epoch 7/500
 - 0s - loss: 0.3211 - acc: 0.9030
Epoch 8/500
 - 0s - loss: 0.3154 - acc: 0.9030
Epoch 9/500
 - 0s - loss: 0.3142 - acc: 0.9030
Epoch 10/500
 - 0s - loss: 0.3129 - acc: 0.9030
Epoch 11/500
 - 0s - loss: 0.3113 - acc: 0.9030
Epoch 12/500
 - 0s - loss: 0.3106 - acc: 0.9030
Epoch 13/500
 - 0s - loss: 0.3094 - acc: 0.9030
Epoch 14/500
 - 0s - loss: 0.3077 - acc: 0.9030
Epoch 15/500
 - 0s - loss: 0.3064 - acc: 0.9030
Epoch 16/500
 - 0s - loss: 0.3058 - acc: 0.9030
Epoch 17/500
 - 0s - loss: 0.3044 - acc: 0.9030
Epoch 18/500
 - 0s - loss: 0.3022 - acc: 0.9030
Epoch 19/500
 - 0s - loss: 0.3010 - acc: 0.9030
Epoch 20/500
 - 0s - loss: 0.2997 - acc: 0.9030
Epoch 21/500
 - 0s - loss: 0.2989 - acc: 0.9030
Epoch 22/500
 - 0s - loss: 0.2987 - acc: 0.9030
Epoch 23/500
 - 0s - loss: 0.2982 - acc: 0.9030
Epoch 24/500
 - 0s - loss: 0.2995 - acc: 0.9030
Epoch 25/500
 - 0s - loss: 0.2973 - acc: 0.9030
Epoch 26/500
 - 0s - loss: 0.2942 - acc: 0.9030
Epoch 27/500
 - 0s - loss: 0.2910 - acc: 0.9030
Epoch 28/500
 - 0s - loss: 0.2898 - acc: 0.9030
Epoch 29/500
 - 0s - loss: 0.2876 - acc: 0.9030
Epoch 30/500
 - 0s - loss: 0.2858 - acc: 0.9030
Epoch 31/500
 - 0s - loss: 0.2857 - acc: 0.9030
Epoch 32/500
 - 0s - loss: 0.2850 - acc: 0.9030
Epoch 33/500
 - 0s - loss: 0.2815 - acc: 0.9030
Epoch 34/500
 - 0s - loss: 0.2799 - acc: 0.9030
Epoch 35/500
 - 0s - loss: 0.2783 - acc: 0.9030
Epoch 36/500
 - 0s - loss: 0.2770 - acc: 0.9030
Epoch 37/500
 - 0s - loss: 0.2747 - acc: 0.9030
Epoch 38/500
 - 0s - loss: 0.2728 - acc: 0.9030
Epoch 39/500
 - 0s - loss: 0.2727 - acc: 0.9030
Epoch 40/500
 - 0s - loss: 0.2729 - acc: 0.9030
Epoch 41/500
 - 0s - loss: 0.2694 - acc: 0.9030
Epoch 42/500
 - 0s - loss: 0.2671 - acc: 0.9030
Epoch 43/500
 - 0s - loss: 0.2656 - acc: 0.9030
Epoch 44/500
 - 0s - loss: 0.2629 - acc: 0.9030
Epoch 45/500
 - 0s - loss: 0.2622 - acc: 0.9030
Epoch 46/500
 - 0s - loss: 0.2611 - acc: 0.9030
Epoch 47/500
 - 0s - loss: 0.2591 - acc: 0.9030
Epoch 48/500
 - 0s - loss: 0.2565 - acc: 0.9030
Epoch 49/500
 - 0s - loss: 0.2529 - acc: 0.9030
Epoch 50/500
 - 0s - loss: 0.2528 - acc: 0.9030
Epoch 51/500
 - 0s - loss: 0.2497 - acc: 0.9030
Epoch 52/500
 - 0s - loss: 0.2470 - acc: 0.9104
Epoch 53/500
 - 0s - loss: 0.2454 - acc: 0.9104
Epoch 54/500
 - 0s - loss: 0.2446 - acc: 0.9179
Epoch 55/500
 - 0s - loss: 0.2426 - acc: 0.9179
Epoch 56/500
 - 0s - loss: 0.2393 - acc: 0.9179
Epoch 57/500
 - 0s - loss: 0.2369 - acc: 0.9179
Epoch 58/500
 - 0s - loss: 0.2347 - acc: 0.9179
Epoch 59/500
 - 0s - loss: 0.2309 - acc: 0.9179
Epoch 60/500
 - 0s - loss: 0.2289 - acc: 0.9179
Epoch 61/500
 - 0s - loss: 0.2284 - acc: 0.9179
Epoch 62/500
 - 0s - loss: 0.2247 - acc: 0.9179
Epoch 63/500
 - 0s - loss: 0.2224 - acc: 0.9179
Epoch 64/500
 - 0s - loss: 0.2204 - acc: 0.9179
Epoch 65/500
 - 0s - loss: 0.2180 - acc: 0.9179
Epoch 66/500
 - 0s - loss: 0.2160 - acc: 0.9179
Epoch 67/500
 - 0s - loss: 0.2154 - acc: 0.9179
Epoch 68/500
 - 0s - loss: 0.2126 - acc: 0.9254
Epoch 69/500
 - 0s - loss: 0.2098 - acc: 0.9254
Epoch 70/500
 - 0s - loss: 0.2074 - acc: 0.9179
Epoch 71/500
 - 0s - loss: 0.2052 - acc: 0.9179
Epoch 72/500
 - 0s - loss: 0.2026 - acc: 0.9179
Epoch 73/500
 - 0s - loss: 0.2003 - acc: 0.9179
Epoch 74/500
 - 0s - loss: 0.1973 - acc: 0.9179
Epoch 75/500
 - 0s - loss: 0.1939 - acc: 0.9179
Epoch 76/500
 - 0s - loss: 0.1926 - acc: 0.9179
Epoch 77/500
 - 0s - loss: 0.1898 - acc: 0.9254
Epoch 78/500
 - 0s - loss: 0.1881 - acc: 0.9179
Epoch 79/500
 - 0s - loss: 0.1848 - acc: 0.9179
Epoch 80/500
 - 0s - loss: 0.1843 - acc: 0.9179
Epoch 81/500
 - 0s - loss: 0.1803 - acc: 0.9179
Epoch 82/500
 - 0s - loss: 0.1782 - acc: 0.9254
Epoch 83/500
 - 0s - loss: 0.1757 - acc: 0.9254
Epoch 84/500
 - 0s - loss: 0.1748 - acc: 0.9179
Epoch 85/500
 - 0s - loss: 0.1734 - acc: 0.9179
Epoch 86/500
 - 0s - loss: 0.1672 - acc: 0.9403
Epoch 87/500
 - 0s - loss: 0.1704 - acc: 0.9478
Epoch 88/500
 - 0s - loss: 0.1677 - acc: 0.9403
Epoch 89/500
 - 0s - loss: 0.1649 - acc: 0.9328
Epoch 90/500
 - 0s - loss: 0.1620 - acc: 0.9403
Epoch 91/500
 - 0s - loss: 0.1588 - acc: 0.9403
Epoch 92/500
 - 0s - loss: 0.1565 - acc: 0.9403
Epoch 93/500
 - 0s - loss: 0.1561 - acc: 0.9328
Epoch 94/500
 - 0s - loss: 0.1530 - acc: 0.9403
Epoch 95/500
 - 0s - loss: 0.1500 - acc: 0.9403
Epoch 96/500
 - 0s - loss: 0.1478 - acc: 0.9403
Epoch 97/500
 - 0s - loss: 0.1475 - acc: 0.9403
Epoch 98/500
 - 0s - loss: 0.1447 - acc: 0.9403
Epoch 99/500
 - 0s - loss: 0.1450 - acc: 0.9552
Epoch 100/500
 - 0s - loss: 0.1489 - acc: 0.9552
Epoch 101/500
 - 0s - loss: 0.1409 - acc: 0.9627
Epoch 102/500
 - 0s - loss: 0.1389 - acc: 0.9478
Epoch 103/500
 - 0s - loss: 0.1352 - acc: 0.9552
Epoch 104/500
 - 0s - loss: 0.1337 - acc: 0.9627
Epoch 105/500
 - 0s - loss: 0.1315 - acc: 0.9627
Epoch 106/500
 - 0s - loss: 0.1308 - acc: 0.9627
Epoch 107/500
 - 0s - loss: 0.1288 - acc: 0.9627
Epoch 108/500
 - 0s - loss: 0.1258 - acc: 0.9627
Epoch 109/500
 - 0s - loss: 0.1233 - acc: 0.9627
Epoch 110/500
 - 0s - loss: 0.1238 - acc: 0.9701
Epoch 111/500
 - 0s - loss: 0.1208 - acc: 0.9552
Epoch 112/500
 - 0s - loss: 0.1209 - acc: 0.9627
Epoch 113/500
 - 0s - loss: 0.1211 - acc: 0.9478
Epoch 114/500
 - 0s - loss: 0.1139 - acc: 0.9627
Epoch 115/500
 - 0s - loss: 0.1155 - acc: 0.9776
Epoch 116/500
 - 0s - loss: 0.1139 - acc: 0.9701
Epoch 117/500
 - 0s - loss: 0.1103 - acc: 0.9701
Epoch 118/500
 - 0s - loss: 0.1077 - acc: 0.9701
Epoch 119/500
 - 0s - loss: 0.1054 - acc: 0.9701
Epoch 120/500
 - 0s - loss: 0.1018 - acc: 0.9701
Epoch 121/500
 - 0s - loss: 0.1011 - acc: 0.9701
Epoch 122/500
 - 0s - loss: 0.1002 - acc: 0.9627
Epoch 123/500
 - 0s - loss: 0.0971 - acc: 0.9627
Epoch 124/500
 - 0s - loss: 0.0960 - acc: 0.9776
Epoch 125/500
 - 0s - loss: 0.0937 - acc: 0.9776
Epoch 126/500
 - 0s - loss: 0.0922 - acc: 0.9701
Epoch 127/500
 - 0s - loss: 0.0918 - acc: 0.9851
Epoch 128/500
 - 0s - loss: 0.0903 - acc: 0.9851
Epoch 129/500
 - 0s - loss: 0.0870 - acc: 0.9776
Epoch 130/500
 - 0s - loss: 0.0881 - acc: 0.9701
Epoch 131/500
 - 0s - loss: 0.0850 - acc: 0.9776
Epoch 132/500
 - 0s - loss: 0.0843 - acc: 0.9776
Epoch 133/500
 - 0s - loss: 0.0799 - acc: 0.9851
Epoch 134/500
 - 0s - loss: 0.0807 - acc: 0.9776
Epoch 135/500
 - 0s - loss: 0.0790 - acc: 0.9776
Epoch 136/500
 - 0s - loss: 0.0773 - acc: 0.9776
Epoch 137/500
 - 0s - loss: 0.0783 - acc: 0.9851
Epoch 138/500
 - 0s - loss: 0.0735 - acc: 0.9851
Epoch 139/500
 - 0s - loss: 0.0730 - acc: 0.9851
Epoch 140/500
 - 0s - loss: 0.0696 - acc: 0.9851
Epoch 141/500
 - 0s - loss: 0.0754 - acc: 0.9701
Epoch 142/500
 - 0s - loss: 0.0729 - acc: 0.9851
Epoch 143/500
 - 0s - loss: 0.0692 - acc: 0.9851
Epoch 144/500
 - 0s - loss: 0.0674 - acc: 0.9851
Epoch 145/500
 - 0s - loss: 0.0689 - acc: 0.9776
Epoch 146/500
 - 0s - loss: 0.0676 - acc: 0.9701
Epoch 147/500
 - 0s - loss: 0.0632 - acc: 0.9776
Epoch 148/500
 - 0s - loss: 0.0617 - acc: 0.9776
Epoch 149/500
 - 0s - loss: 0.0603 - acc: 0.9925
Epoch 150/500
 - 0s - loss: 0.0594 - acc: 0.9851
Epoch 151/500
 - 0s - loss: 0.0582 - acc: 0.9851
Epoch 152/500
 - 0s - loss: 0.0571 - acc: 0.9851
Epoch 153/500
 - 0s - loss: 0.0574 - acc: 0.9851
Epoch 154/500
 - 0s - loss: 0.0574 - acc: 0.9776
Epoch 155/500
 - 0s - loss: 0.0587 - acc: 0.9776
Epoch 156/500
 - 0s - loss: 0.0547 - acc: 0.9851
Epoch 157/500
 - 0s - loss: 0.0528 - acc: 0.9925
Epoch 158/500
 - 0s - loss: 0.0517 - acc: 0.9925
Epoch 159/500
 - 0s - loss: 0.0505 - acc: 0.9925
Epoch 160/500
 - 0s - loss: 0.0502 - acc: 0.9925
Epoch 161/500
 - 0s - loss: 0.0485 - acc: 0.9925
Epoch 162/500
 - 0s - loss: 0.0483 - acc: 0.9925
Epoch 163/500
 - 0s - loss: 0.0474 - acc: 0.9925
Epoch 164/500
 - 0s - loss: 0.0474 - acc: 0.9925

Epoch 165/500
 - 0s - loss: 0.0464 - acc: 0.9925
Epoch 166/500
 - 0s - loss: 0.0508 - acc: 0.9851
Epoch 167/500
 - 0s - loss: 0.0457 - acc: 0.9925
Epoch 168/500
 - 0s - loss: 0.0480 - acc: 0.9925
Epoch 169/500
 - 0s - loss: 0.0489 - acc: 0.9851
Epoch 170/500
 - 0s - loss: 0.0567 - acc: 0.9851
Epoch 171/500
 - 0s - loss: 0.0478 - acc: 0.9851
Epoch 172/500
 - 0s - loss: 0.0466 - acc: 0.9925
Epoch 173/500
 - 0s - loss: 0.0451 - acc: 0.9851
Epoch 174/500
 - 0s - loss: 0.0470 - acc: 0.9851
Epoch 175/500
 - 0s - loss: 0.0435 - acc: 0.9851
Epoch 176/500
 - 0s - loss: 0.0401 - acc: 0.9851
Epoch 177/500
 - 0s - loss: 0.0388 - acc: 0.9851
Epoch 178/500
 - 0s - loss: 0.0387 - acc: 0.9925
Epoch 179/500
 - 0s - loss: 0.0378 - acc: 0.9925
Epoch 180/500
 - 0s - loss: 0.0381 - acc: 1.0000
Epoch 181/500
 - 0s - loss: 0.0398 - acc: 1.0000
Epoch 182/500
 - 0s - loss: 0.0375 - acc: 1.0000
Epoch 183/500
 - 0s - loss: 0.0403 - acc: 0.9925
Epoch 184/500
 - 0s - loss: 0.0372 - acc: 0.9925
Epoch 185/500
 - 0s - loss: 0.0354 - acc: 0.9851
Epoch 186/500
 - 0s - loss: 0.0348 - acc: 0.9925
Epoch 187/500
 - 0s - loss: 0.0331 - acc: 0.9925
Epoch 188/500
 - 0s - loss: 0.0330 - acc: 0.9851
Epoch 189/500
 - 0s - loss: 0.0323 - acc: 1.0000
Epoch 190/500
 - 0s - loss: 0.0308 - acc: 0.9925
Epoch 191/500
 - 0s - loss: 0.0353 - acc: 0.9851
Epoch 192/500
 - 0s - loss: 0.0343 - acc: 0.9851
Epoch 193/500
 - 0s - loss: 0.0329 - acc: 1.0000
Epoch 194/500
 - 0s - loss: 0.0313 - acc: 1.0000
Epoch 195/500
 - 0s - loss: 0.0302 - acc: 1.0000
Epoch 196/500
 - 0s - loss: 0.0298 - acc: 1.0000
Epoch 197/500
 - 0s - loss: 0.0280 - acc: 1.0000
Epoch 198/500
 - 0s - loss: 0.0287 - acc: 1.0000
Epoch 199/500
 - 0s - loss: 0.0279 - acc: 1.0000
Epoch 200/500
 - 0s - loss: 0.0269 - acc: 1.0000
Epoch 201/500
 - 0s - loss: 0.0277 - acc: 1.0000
Epoch 202/500
 - 0s - loss: 0.0265 - acc: 1.0000
Epoch 203/500
 - 0s - loss: 0.0264 - acc: 1.0000
Epoch 204/500
 - 0s - loss: 0.0259 - acc: 1.0000
Epoch 205/500
 - 0s - loss: 0.0252 - acc: 1.0000
Epoch 206/500
 - 0s - loss: 0.0259 - acc: 1.0000
Epoch 207/500
 - 0s - loss: 0.0243 - acc: 1.0000
Epoch 208/500
 - 0s - loss: 0.0262 - acc: 1.0000
Epoch 209/500
 - 0s - loss: 0.0252 - acc: 1.0000
Epoch 210/500
 - 0s - loss: 0.0252 - acc: 1.0000
Epoch 211/500
 - 0s - loss: 0.0251 - acc: 1.0000
Epoch 212/500
 - 0s - loss: 0.0244 - acc: 1.0000
Epoch 213/500
 - 0s - loss: 0.0252 - acc: 0.9925
Epoch 214/500
 - 0s - loss: 0.0237 - acc: 1.0000
Epoch 215/500
 - 0s - loss: 0.0229 - acc: 1.0000
Epoch 216/500
 - 0s - loss: 0.0254 - acc: 0.9925
Epoch 217/500
 - 0s - loss: 0.0272 - acc: 0.9925
Epoch 218/500
 - 0s - loss: 0.0260 - acc: 0.9925
Epoch 219/500
 - 0s - loss: 0.0219 - acc: 1.0000
Epoch 220/500
 - 0s - loss: 0.0217 - acc: 1.0000
Epoch 221/500
 - 0s - loss: 0.0264 - acc: 0.9925
Epoch 222/500
 - 0s - loss: 0.0272 - acc: 0.9925
Epoch 223/500
 - 0s - loss: 0.0250 - acc: 0.9925
Epoch 224/500
 - 0s - loss: 0.0223 - acc: 1.0000
Epoch 225/500
 - 0s - loss: 0.0206 - acc: 1.0000
Epoch 226/500
 - 0s - loss: 0.0214 - acc: 1.0000
Epoch 227/500
 - 0s - loss: 0.0214 - acc: 0.9925
Epoch 228/500
 - 0s - loss: 0.0250 - acc: 0.9925
Epoch 229/500
 - 0s - loss: 0.0230 - acc: 0.9925
Epoch 230/500
 - 0s - loss: 0.0216 - acc: 0.9925
Epoch 231/500
 - 0s - loss: 0.0201 - acc: 0.9925
Epoch 232/500
 - 0s - loss: 0.0199 - acc: 0.9925
Epoch 233/500
 - 0s - loss: 0.0193 - acc: 0.9925
Epoch 234/500
 - 0s - loss: 0.0183 - acc: 1.0000
Epoch 235/500
 - 0s - loss: 0.0189 - acc: 1.0000
Epoch 236/500
 - 0s - loss: 0.0210 - acc: 0.9925
Epoch 237/500
 - 0s - loss: 0.0201 - acc: 0.9925
Epoch 238/500
 - 0s - loss: 0.0185 - acc: 0.9925
Epoch 239/500
 - 0s - loss: 0.0185 - acc: 0.9925
Epoch 240/500
 - 0s - loss: 0.0179 - acc: 1.0000
Epoch 241/500
 - 0s - loss: 0.0171 - acc: 1.0000
Epoch 242/500
 - 0s - loss: 0.0174 - acc: 1.0000
Epoch 243/500
 - 0s - loss: 0.0169 - acc: 1.0000
Epoch 244/500
 - 0s - loss: 0.0167 - acc: 1.0000
Epoch 245/500
 - 0s - loss: 0.0160 - acc: 1.0000
Epoch 246/500
 - 0s - loss: 0.0157 - acc: 1.0000
Epoch 247/500
 - 0s - loss: 0.0165 - acc: 1.0000
Epoch 248/500
 - 0s - loss: 0.0166 - acc: 1.0000
Epoch 249/500
 - 0s - loss: 0.0156 - acc: 1.0000
Epoch 250/500
 - 0s - loss: 0.0156 - acc: 1.0000
Epoch 251/500
 - 0s - loss: 0.0151 - acc: 1.0000
Epoch 252/500
 - 0s - loss: 0.0149 - acc: 1.0000
Epoch 253/500
 - 0s - loss: 0.0150 - acc: 1.0000
Epoch 254/500
 - 0s - loss: 0.0151 - acc: 1.0000
Epoch 255/500
 - 0s - loss: 0.0146 - acc: 1.0000
Epoch 256/500
 - 0s - loss: 0.0143 - acc: 1.0000
Epoch 257/500
 - 0s - loss: 0.0141 - acc: 1.0000
Epoch 258/500
 - 0s - loss: 0.0148 - acc: 1.0000
Epoch 259/500
 - 0s - loss: 0.0157 - acc: 1.0000
Epoch 260/500
 - 0s - loss: 0.0143 - acc: 1.0000
Epoch 261/500
 - 0s - loss: 0.0246 - acc: 0.9925
Epoch 262/500
 - 0s - loss: 0.0172 - acc: 0.9925
Epoch 263/500
 - 0s - loss: 0.0298 - acc: 0.9925
Epoch 264/500
 - 0s - loss: 0.0280 - acc: 0.9925
Epoch 265/500
 - 0s - loss: 0.0218 - acc: 0.9925
Epoch 266/500
 - 0s - loss: 0.0195 - acc: 0.9925
Epoch 267/500
 - 0s - loss: 0.0159 - acc: 1.0000
Epoch 268/500
 - 0s - loss: 0.0152 - acc: 1.0000
Epoch 269/500
 - 0s - loss: 0.0150 - acc: 1.0000
Epoch 270/500
 - 0s - loss: 0.0140 - acc: 1.0000
Epoch 271/500
 - 0s - loss: 0.0137 - acc: 1.0000
Epoch 272/500
 - 0s - loss: 0.0124 - acc: 1.0000
Epoch 273/500
 - 0s - loss: 0.0127 - acc: 1.0000
Epoch 274/500
 - 0s - loss: 0.0127 - acc: 1.0000
Epoch 275/500
 - 0s - loss: 0.0158 - acc: 0.9925
Epoch 276/500
 - 0s - loss: 0.0156 - acc: 0.9925
Epoch 277/500
 - 0s - loss: 0.0131 - acc: 0.9925
Epoch 278/500
 - 0s - loss: 0.0119 - acc: 1.0000
Epoch 279/500
 - 0s - loss: 0.0119 - acc: 1.0000
Epoch 280/500
 - 0s - loss: 0.0121 - acc: 1.0000
Epoch 281/500
 - 0s - loss: 0.0120 - acc: 1.0000
Epoch 282/500
 - 0s - loss: 0.0121 - acc: 1.0000
Epoch 283/500
 - 0s - loss: 0.0115 - acc: 1.0000
Epoch 284/500
 - 0s - loss: 0.0118 - acc: 1.0000
Epoch 285/500
 - 0s - loss: 0.0116 - acc: 1.0000
Epoch 286/500
 - 0s - loss: 0.0112 - acc: 1.0000
Epoch 287/500
 - 0s - loss: 0.0110 - acc: 1.0000
Epoch 288/500
 - 0s - loss: 0.0113 - acc: 1.0000
Epoch 289/500
 - 0s - loss: 0.0101 - acc: 1.0000
Epoch 290/500
 - 0s - loss: 0.0143 - acc: 0.9925
Epoch 291/500
 - 0s - loss: 0.0132 - acc: 0.9925
Epoch 292/500
 - 0s - loss: 0.0118 - acc: 1.0000
Epoch 293/500
 - 0s - loss: 0.0112 - acc: 1.0000
Epoch 294/500
 - 0s - loss: 0.0110 - acc: 1.0000
Epoch 295/500
 - 0s - loss: 0.0145 - acc: 0.9925
Epoch 296/500
 - 0s - loss: 0.0168 - acc: 0.9925
Epoch 297/500
 - 0s - loss: 0.0122 - acc: 0.9925
Epoch 298/500
 - 0s - loss: 0.0158 - acc: 0.9925
Epoch 299/500
 - 0s - loss: 0.0196 - acc: 0.9925
Epoch 300/500
 - 0s - loss: 0.0156 - acc: 0.9925
Epoch 301/500
 - 0s - loss: 0.0125 - acc: 1.0000
Epoch 302/500
 - 0s - loss: 0.0115 - acc: 1.0000
Epoch 303/500
 - 0s - loss: 0.0108 - acc: 1.0000
Epoch 304/500
 - 0s - loss: 0.0102 - acc: 1.0000
Epoch 305/500
 - 0s - loss: 0.0103 - acc: 1.0000
Epoch 306/500
 - 0s - loss: 0.0105 - acc: 1.0000
Epoch 307/500
 - 0s - loss: 0.0098 - acc: 1.0000
Epoch 308/500
 - 0s - loss: 0.0096 - acc: 1.0000
Epoch 309/500
 - 0s - loss: 0.0096 - acc: 1.0000
Epoch 310/500
 - 0s - loss: 0.0097 - acc: 1.0000
Epoch 311/500
 - 0s - loss: 0.0096 - acc: 1.0000
Epoch 312/500
 - 0s - loss: 0.0101 - acc: 1.0000
Epoch 313/500
 - 0s - loss: 0.0121 - acc: 0.9925
Epoch 314/500
 - 0s - loss: 0.0097 - acc: 1.0000
Epoch 315/500
 - 0s - loss: 0.0098 - acc: 1.0000
Epoch 316/500
 - 0s - loss: 0.0099 - acc: 1.0000
Epoch 317/500
 - 0s - loss: 0.0095 - acc: 1.0000
Epoch 318/500
 - 0s - loss: 0.0092 - acc: 1.0000
Epoch 319/500
 - 0s - loss: 0.0094 - acc: 1.0000
Epoch 320/500
 - 0s - loss: 0.0090 - acc: 1.0000
Epoch 321/500
 - 0s - loss: 0.0092 - acc: 1.0000
Epoch 322/500
 - 0s - loss: 0.0088 - acc: 1.0000
Epoch 323/500
 - 0s - loss: 0.0088 - acc: 1.0000
Epoch 324/500
 - 0s - loss: 0.0088 - acc: 1.0000
Epoch 325/500
 - 0s - loss: 0.0087 - acc: 1.0000
Epoch 326/500
 - 0s - loss: 0.0087 - acc: 1.0000
Epoch 327/500
 - 0s - loss: 0.0088 - acc: 1.0000
Epoch 328/500
 - 0s - loss: 0.0085 - acc: 1.0000
Epoch 329/500
 - 0s - loss: 0.0083 - acc: 1.0000
Epoch 330/500
 - 0s - loss: 0.0086 - acc: 1.0000
Epoch 331/500
 - 0s - loss: 0.0085 - acc: 1.0000
Epoch 332/500
 - 0s - loss: 0.0084 - acc: 1.0000

Epoch 333/500
 - 0s - loss: 0.0083 - acc: 1.0000
Epoch 334/500
 - 0s - loss: 0.0082 - acc: 1.0000
Epoch 335/500
 - 0s - loss: 0.0083 - acc: 1.0000
Epoch 336/500
 - 0s - loss: 0.0082 - acc: 1.0000
Epoch 337/500
 - 0s - loss: 0.0081 - acc: 1.0000
Epoch 338/500
 - 0s - loss: 0.0084 - acc: 1.0000
Epoch 339/500
 - 0s - loss: 0.0081 - acc: 1.0000
Epoch 340/500
 - 0s - loss: 0.0080 - acc: 1.0000
Epoch 341/500
 - 0s - loss: 0.0078 - acc: 1.0000
Epoch 342/500
 - 0s - loss: 0.0078 - acc: 1.0000
Epoch 343/500
 - 0s - loss: 0.0077 - acc: 1.0000
Epoch 344/500
 - 0s - loss: 0.0078 - acc: 1.0000
Epoch 345/500
 - 0s - loss: 0.0082 - acc: 1.0000
Epoch 346/500
 - 0s - loss: 0.0076 - acc: 1.0000
Epoch 347/500
 - 0s - loss: 0.0079 - acc: 1.0000
Epoch 348/500
 - 0s - loss: 0.0077 - acc: 1.0000
Epoch 349/500
 - 0s - loss: 0.0075 - acc: 1.0000
Epoch 350/500
 - 0s - loss: 0.0077 - acc: 1.0000
Epoch 351/500
 - 0s - loss: 0.0076 - acc: 1.0000
Epoch 352/500
 - 0s - loss: 0.0074 - acc: 1.0000
Epoch 353/500
 - 0s - loss: 0.0075 - acc: 1.0000
Epoch 354/500
 - 0s - loss: 0.0075 - acc: 1.0000
Epoch 355/500
 - 0s - loss: 0.0077 - acc: 1.0000
Epoch 356/500
 - 0s - loss: 0.0073 - acc: 1.0000
Epoch 357/500
 - 0s - loss: 0.0074 - acc: 1.0000
Epoch 358/500
 - 0s - loss: 0.0075 - acc: 1.0000
Epoch 359/500
 - 0s - loss: 0.0075 - acc: 1.0000
Epoch 360/500
 - 0s - loss: 0.0076 - acc: 1.0000
Epoch 361/500
 - 0s - loss: 0.0073 - acc: 1.0000
Epoch 362/500
 - 0s - loss: 0.0073 - acc: 1.0000
Epoch 363/500
 - 0s - loss: 0.0074 - acc: 1.0000
Epoch 364/500
 - 0s - loss: 0.0070 - acc: 1.0000
Epoch 365/500
 - 0s - loss: 0.0073 - acc: 1.0000
Epoch 366/500
 - 0s - loss: 0.0070 - acc: 1.0000
Epoch 367/500
 - 0s - loss: 0.0069 - acc: 1.0000
Epoch 368/500
 - 0s - loss: 0.0070 - acc: 1.0000
Epoch 369/500
 - 0s - loss: 0.0068 - acc: 1.0000
Epoch 370/500
 - 0s - loss: 0.0069 - acc: 1.0000
Epoch 371/500
 - 0s - loss: 0.0069 - acc: 1.0000
Epoch 372/500
 - 0s - loss: 0.0069 - acc: 1.0000
Epoch 373/500
 - 0s - loss: 0.0073 - acc: 1.0000
Epoch 374/500
 - 0s - loss: 0.0068 - acc: 1.0000
Epoch 375/500
 - 0s - loss: 0.0068 - acc: 1.0000
Epoch 376/500
 - 0s - loss: 0.0068 - acc: 1.0000
Epoch 377/500
 - 0s - loss: 0.0068 - acc: 1.0000
Epoch 378/500
 - 0s - loss: 0.0065 - acc: 1.0000
Epoch 379/500
 - 0s - loss: 0.0067 - acc: 1.0000
Epoch 380/500
 - 0s - loss: 0.0066 - acc: 1.0000
Epoch 381/500
 - 0s - loss: 0.0066 - acc: 1.0000
Epoch 382/500
 - 0s - loss: 0.0063 - acc: 1.0000
Epoch 383/500
 - 0s - loss: 0.0064 - acc: 1.0000
Epoch 384/500
 - 0s - loss: 0.0065 - acc: 1.0000
Epoch 385/500
 - 0s - loss: 0.0065 - acc: 1.0000
Epoch 386/500
 - 0s - loss: 0.0064 - acc: 1.0000
Epoch 387/500
 - 0s - loss: 0.0065 - acc: 1.0000
Epoch 388/500
 - 0s - loss: 0.0062 - acc: 1.0000
Epoch 389/500
 - 0s - loss: 0.0062 - acc: 1.0000
Epoch 390/500
 - 0s - loss: 0.0063 - acc: 1.0000
Epoch 391/500
 - 0s - loss: 0.0065 - acc: 1.0000
Epoch 392/500
 - 0s - loss: 0.0064 - acc: 1.0000
Epoch 393/500
 - 0s - loss: 0.0089 - acc: 0.9925
Epoch 394/500
 - 0s - loss: 0.0099 - acc: 0.9925
Epoch 395/500
 - 0s - loss: 0.0074 - acc: 1.0000
Epoch 396/500
 - 0s - loss: 0.0060 - acc: 1.0000
Epoch 397/500
 - 0s - loss: 0.0062 - acc: 1.0000
Epoch 398/500
 - 0s - loss: 0.0061 - acc: 1.0000
Epoch 399/500
 - 0s - loss: 0.0101 - acc: 0.9925
Epoch 400/500
 - 0s - loss: 0.0089 - acc: 0.9925
Epoch 401/500
 - 0s - loss: 0.0064 - acc: 1.0000
Epoch 402/500
 - 0s - loss: 0.0069 - acc: 1.0000
Epoch 403/500
 - 0s - loss: 0.0062 - acc: 1.0000
Epoch 404/500
 - 0s - loss: 0.0058 - acc: 1.0000
Epoch 405/500
 - 0s - loss: 0.0062 - acc: 1.0000
Epoch 406/500
 - 0s - loss: 0.0063 - acc: 1.0000
Epoch 407/500
 - 0s - loss: 0.0083 - acc: 0.9925
Epoch 408/500
 - 0s - loss: 0.0068 - acc: 1.0000
Epoch 409/500
 - 0s - loss: 0.0057 - acc: 1.0000
Epoch 410/500
 - 0s - loss: 0.0060 - acc: 1.0000
Epoch 411/500
 - 0s - loss: 0.0059 - acc: 1.0000
Epoch 412/500
 - 0s - loss: 0.0062 - acc: 1.0000
Epoch 413/500
 - 0s - loss: 0.0055 - acc: 1.0000
Epoch 414/500
 - 0s - loss: 0.0058 - acc: 1.0000
Epoch 415/500
 - 0s - loss: 0.0054 - acc: 1.0000
Epoch 416/500
 - 0s - loss: 0.0055 - acc: 1.0000
Epoch 417/500
 - 0s - loss: 0.0056 - acc: 1.0000
Epoch 418/500
 - 0s - loss: 0.0055 - acc: 1.0000
Epoch 419/500
 - 0s - loss: 0.0061 - acc: 1.0000
Epoch 420/500
 - 0s - loss: 0.0058 - acc: 1.0000
Epoch 421/500
 - 0s - loss: 0.0053 - acc: 1.0000
Epoch 422/500
 - 0s - loss: 0.0054 - acc: 1.0000
Epoch 423/500
 - 0s - loss: 0.0053 - acc: 1.0000
Epoch 424/500
 - 0s - loss: 0.0052 - acc: 1.0000
Epoch 425/500
 - 0s - loss: 0.0055 - acc: 1.0000
Epoch 426/500
 - 0s - loss: 0.0057 - acc: 1.0000
Epoch 427/500
 - 0s - loss: 0.0055 - acc: 1.0000
Epoch 428/500
 - 0s - loss: 0.0052 - acc: 1.0000
Epoch 429/500
 - 0s - loss: 0.0092 - acc: 0.9925
Epoch 430/500
 - 0s - loss: 0.0100 - acc: 0.9925
Epoch 431/500
 - 0s - loss: 0.0042 - acc: 1.0000
Epoch 432/500
 - 0s - loss: 0.0294 - acc: 0.9925
Epoch 433/500
 - 0s - loss: 0.0214 - acc: 0.9925
Epoch 434/500
 - 0s - loss: 0.0196 - acc: 0.9925
Epoch 435/500
 - 0s - loss: 0.0069 - acc: 1.0000
Epoch 436/500
 - 0s - loss: 0.0068 - acc: 1.0000
Epoch 437/500
 - 0s - loss: 0.0088 - acc: 1.0000
Epoch 438/500
 - 0s - loss: 0.0083 - acc: 1.0000
Epoch 439/500
 - 0s - loss: 0.0070 - acc: 1.0000
Epoch 440/500
 - 0s - loss: 0.0123 - acc: 0.9925
Epoch 441/500
 - 0s - loss: 0.0063 - acc: 1.0000
Epoch 442/500
 - 0s - loss: 0.0180 - acc: 0.9925
Epoch 443/500
 - 0s - loss: 0.0124 - acc: 0.9925
Epoch 444/500
 - 0s - loss: 0.0078 - acc: 1.0000
Epoch 445/500
 - 0s - loss: 0.0075 - acc: 1.0000
Epoch 446/500
 - 0s - loss: 0.0066 - acc: 1.0000
Epoch 447/500
 - 0s - loss: 0.0056 - acc: 1.0000
Epoch 448/500
 - 0s - loss: 0.0053 - acc: 1.0000
Epoch 449/500
 - 0s - loss: 0.0050 - acc: 1.0000
Epoch 450/500
 - 0s - loss: 0.0070 - acc: 1.0000
Epoch 451/500
 - 0s - loss: 0.0064 - acc: 1.0000
Epoch 452/500
 - 0s - loss: 0.0050 - acc: 1.0000
Epoch 453/500
 - 0s - loss: 0.0052 - acc: 1.0000
Epoch 454/500
 - 0s - loss: 0.0050 - acc: 1.0000
Epoch 455/500
 - 0s - loss: 0.0048 - acc: 1.0000
Epoch 456/500
 - 0s - loss: 0.0048 - acc: 1.0000
Epoch 457/500
 - 0s - loss: 0.0046 - acc: 1.0000
Epoch 458/500
 - 0s - loss: 0.0046 - acc: 1.0000
Epoch 459/500
 - 0s - loss: 0.0045 - acc: 1.0000
Epoch 460/500
 - 0s - loss: 0.0049 - acc: 1.0000
Epoch 461/500
 - 0s - loss: 0.0046 - acc: 1.0000
Epoch 462/500
 - 0s - loss: 0.0044 - acc: 1.0000
Epoch 463/500
 - 0s - loss: 0.0045 - acc: 1.0000
Epoch 464/500
 - 0s - loss: 0.0044 - acc: 1.0000
Epoch 465/500
 - 0s - loss: 0.0044 - acc: 1.0000
Epoch 466/500
 - 0s - loss: 0.0043 - acc: 1.0000
Epoch 467/500
 - 0s - loss: 0.0044 - acc: 1.0000
Epoch 468/500
 - 0s - loss: 0.0044 - acc: 1.0000
Epoch 469/500
 - 0s - loss: 0.0048 - acc: 1.0000
Epoch 470/500
 - 0s - loss: 0.0046 - acc: 1.0000
Epoch 471/500
 - 0s - loss: 0.0065 - acc: 1.0000
Epoch 472/500
 - 0s - loss: 0.0068 - acc: 1.0000
Epoch 473/500
 - 0s - loss: 0.0057 - acc: 1.0000
Epoch 474/500
 - 0s - loss: 0.0041 - acc: 1.0000
Epoch 475/500
 - 0s - loss: 0.0048 - acc: 1.0000
Epoch 476/500
 - 0s - loss: 0.0055 - acc: 1.0000
Epoch 477/500
 - 0s - loss: 0.0076 - acc: 0.9925
Epoch 478/500
 - 0s - loss: 0.0061 - acc: 1.0000
Epoch 479/500
 - 0s - loss: 0.0047 - acc: 1.0000
Epoch 480/500
 - 0s - loss: 0.0043 - acc: 1.0000
Epoch 481/500
 - 0s - loss: 0.0043 - acc: 1.0000
Epoch 482/500
 - 0s - loss: 0.0042 - acc: 1.0000
Epoch 483/500
 - 0s - loss: 0.0043 - acc: 1.0000
Epoch 484/500
 - 0s - loss: 0.0041 - acc: 1.0000
Epoch 485/500
 - 0s - loss: 0.0040 - acc: 1.0000
Epoch 486/500
 - 0s - loss: 0.0046 - acc: 1.0000
Epoch 487/500
 - 0s - loss: 0.0053 - acc: 1.0000
Epoch 488/500
 - 0s - loss: 0.0045 - acc: 1.0000
Epoch 489/500
 - 0s - loss: 0.0040 - acc: 1.0000
Epoch 490/500
 - 0s - loss: 0.0039 - acc: 1.0000
Epoch 491/500
 - 0s - loss: 0.0043 - acc: 1.0000
Epoch 492/500
 - 0s - loss: 0.0040 - acc: 1.0000
Epoch 493/500
 - 0s - loss: 0.0040 - acc: 1.0000
Epoch 494/500
 - 0s - loss: 0.0040 - acc: 1.0000
Epoch 495/500
 - 0s - loss: 0.0040 - acc: 1.0000
Epoch 496/500
 - 0s - loss: 0.0039 - acc: 1.0000
Epoch 497/500
 - 0s - loss: 0.0038 - acc: 1.0000
Epoch 498/500
 - 0s - loss: 0.0039 - acc: 1.0000
Epoch 499/500
 - 0s - loss: 0.0044 - acc: 1.0000
Epoch 500/500
 - 0s - loss: 0.0070 - acc: 0.9925

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 0.8502 - acc: 0.8444
Normal Neural Network - Loss: 0.8501697136296167, Accuracy: 0.8444444537162781

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Certified' 'Certified' 'Certified' 'Denied' 'Certified'
 'Certified' 'Certified' 'Certified' 'Certified']
Actual Labels: ['Certified', 'Certified', 'Certified', 'Denied', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified']