In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'NIGERIA']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

NIGERIA    646
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    595
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [8]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [9]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [10]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
1096,Certified,206,27157-1035,NORTH CAROLINA,4800.0,190000.0,NIGERIA,H-1B,Other,1.0
1656,Certified,192,10577,NEW YORK,16700.0,89000.0,NIGERIA,H-1B,Bachelor's,1.0
1694,Certified,206,94043,CALIFORNIA,47756.0,105000.0,NIGERIA,H-1B,Bachelor's,1.0
2140,Certified,175,20164,VIRGINIA,25.0,84323.0,NIGERIA,NaN,Master's,11.0
2167,Certified,152,75601,TEXAS,2248.0,83000.0,NIGERIA,H-1B,Master's,11.0

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

CALIFORNIA              101
TEXAS                    80
NEW YORK                 37
WASHINGTON               37
PENNSYLVANIA             36
NEW JERSEY               27
ILLINOIS                 23
MASSACHUSETTS            20
INDIANA                  20
FLORIDA                  16
VIRGINIA                 15
GEORGIA                  15
OHIO                     14
MARYLAND                 14
NORTH CAROLINA           12
OKLAHOMA                 11
ARIZONA                  10
MICHIGAN                 10
CONNECTICUT              10
MINNESOTA                 9
WISCONSIN                 9
MISSOURI                  9
TENNESSEE                 8
KENTUCKY                  6
IOWA                      5
DISTRICT OF COLUMBIA      5
COLORADO                  3
NEW MEXICO                3
KANSAS                    3
ARKANSAS                  3
ALABAMA                   3
SOUTH DAKOTA              2
DELAWARE                  2
SOUTH CAROLINA            2
NORTH DAKOTA              2
OREGON                    2
WEST VIRGINIA             2
IDAHO                     2
LOUISIANA                 1
NEBRASKA                  1
RHODE ISLAND              1
VERMONT                   1
NEW HAMPSHIRE             1
MAINE                     1
UTAH                      1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
1096,Certified,206,27157-1035,NORTH CAROLINA,4800.0,190000.0,NIGERIA,H-1B,Other,1.0,NORTH CAROLINA
1656,Certified,192,10577,NEW YORK,16700.0,89000.0,NIGERIA,H-1B,Bachelor's,1.0,NEW YORK
1694,Certified,206,94043,CALIFORNIA,47756.0,105000.0,NIGERIA,H-1B,Bachelor's,1.0,CALIFORNIA
2167,Certified,152,75601,TEXAS,2248.0,83000.0,NIGERIA,H-1B,Master's,11.0,TEXAS
2219,Certified,165,75201,TEXAS,152000.0,108846.0,NIGERIA,H-1B,Master's,10.0,TEXAS

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

SOUTH        184
WEST         154
NORTHEAST    131
MIDWEST      106
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      575
DECISION_ELAPSED_DAYS            575
EMPLOYER_POSTAL_CODE             575
EMPLOYER_STATE                   575
EMPLOYER_NUM_EMPLOYEES           575
WAGE_OFFER_FROM_9089             575
COUNTRY_OF_CITIZENSHIP           575
CLASS_OF_ADMISSION               575
FOREIGN_WORKER_INFO_EDUCATION    575
CASE_RECEIVED_DATE_MONTH         575
EMPLOYER_STATES                  575
EMPLOYER_REGIONS                 575
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      251
0-90        161
181-365     112
366-3600     51
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

100000-500000    252
75001-100000     184
50001-75000      102
25001-50000       34
0-25000            3
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

10001-1000000000    193
1001-10000          136
0-50                104
101-500              70
501-1000             53
51-100               19
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      575
DECISION_ELAPSED_DAYS            575
EMPLOYER_POSTAL_CODE             575
EMPLOYER_STATE                   575
EMPLOYER_NUM_EMPLOYEES           575
WAGE_OFFER_FROM_9089             575
COUNTRY_OF_CITIZENSHIP           575
CLASS_OF_ADMISSION               575
FOREIGN_WORKER_INFO_EDUCATION    575
CASE_RECEIVED_DATE_MONTH         575
EMPLOYER_STATES                  575
EMPLOYER_REGIONS                 575
DAY_BINS                         575
WAGE_BINS                        575
EMPLOYEE_BINS                    575
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
1096,Certified,1001-10000,100000-500000,SOUTH,1.0,Other,H-1B,181-365
1656,Certified,10001-1000000000,75001-100000,NORTHEAST,1.0,Bachelor's,H-1B,181-365
1694,Certified,10001-1000000000,100000-500000,WEST,1.0,Bachelor's,H-1B,181-365
2167,Certified,1001-10000,75001-100000,SOUTH,11.0,Master's,H-1B,91-180
2219,Certified,10001-1000000000,100000-500000,SOUTH,10.0,Master's,H-1B,91-180

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
1096,Certified,1001-10000,100000-500000,SOUTH,1.0,Other,H-1B,181-365,3,6,1,2,1,2
1656,Certified,10001-1000000000,75001-100000,NORTHEAST,1.0,Bachelor's,H-1B,181-365,3,1,4,1,1,1
1694,Certified,10001-1000000000,100000-500000,WEST,1.0,Bachelor's,H-1B,181-365,3,1,1,3,1,1
2167,Certified,1001-10000,75001-100000,SOUTH,11.0,Master's,H-1B,91-180,3,4,4,2,3,2
2219,Certified,10001-1000000000,100000-500000,SOUTH,10.0,Master's,H-1B,91-180,3,4,1,2,3,1

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           575
EMPLOYEE_BINS                         575
WAGE_BINS                             575
EMPLOYER_REGIONS                      575
CASE_RECEIVED_DATE_MONTH              575
FOREIGN_WORKER_INFO_EDUCATION         575
CLASS_OF_ADMISSION                    575
DAY_BINS                              575
CLASS_OF_ADMISSION_CODE               575
FOREIGN_WORKER_INFO_EDUCATION_CODE    575
WAGE_BINS_CODE                        575
EMPLOYER_REGIONS_CODE                 575
DAY_BINS_CODE                         575
EMPLOYEE_BINS_CODE                    575
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
1096,Certified,2,1,1,6,3,1.0,2
1656,Certified,1,4,1,1,3,1.0,1
1694,Certified,1,1,1,1,3,1.0,3
2167,Certified,2,4,3,4,3,11.0,2
2219,Certified,1,1,3,4,3,10.0,2

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int64
WAGE_BINS_CODE                          int64
DAY_BINS_CODE                           int64
FOREIGN_WORKER_INFO_EDUCATION_CODE      int64
CLASS_OF_ADMISSION_CODE                 int64
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int64
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(575, 7) (575,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [53]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 1s - loss: 0.5086 - acc: 0.8631
Epoch 2/500
 - 0s - loss: 0.2952 - acc: 0.9188
Epoch 3/500
 - 0s - loss: 0.2768 - acc: 0.9188
Epoch 4/500
 - 0s - loss: 0.2673 - acc: 0.9188
Epoch 5/500
 - 0s - loss: 0.2629 - acc: 0.9188
Epoch 6/500
 - 0s - loss: 0.2578 - acc: 0.9188
Epoch 7/500
 - 0s - loss: 0.2535 - acc: 0.9188
Epoch 8/500
 - 0s - loss: 0.2512 - acc: 0.9188
Epoch 9/500
 - 0s - loss: 0.2456 - acc: 0.9188
Epoch 10/500
 - 0s - loss: 0.2417 - acc: 0.9188
Epoch 11/500
 - 0s - loss: 0.2370 - acc: 0.9188
Epoch 12/500
 - 0s - loss: 0.2332 - acc: 0.9188
Epoch 13/500
 - 0s - loss: 0.2291 - acc: 0.9188
Epoch 14/500
 - 0s - loss: 0.2250 - acc: 0.9188
Epoch 15/500
 - 0s - loss: 0.2242 - acc: 0.9188
Epoch 16/500
 - 0s - loss: 0.2183 - acc: 0.9188
Epoch 17/500
 - 0s - loss: 0.2142 - acc: 0.9188
Epoch 18/500
 - 0s - loss: 0.2108 - acc: 0.9188
Epoch 19/500
 - 0s - loss: 0.2069 - acc: 0.9188
Epoch 20/500
 - 0s - loss: 0.2033 - acc: 0.9188
Epoch 21/500
 - 0s - loss: 0.2003 - acc: 0.9188
Epoch 22/500
 - 0s - loss: 0.1973 - acc: 0.9188
Epoch 23/500
 - 0s - loss: 0.1935 - acc: 0.9188
Epoch 24/500
 - 0s - loss: 0.1894 - acc: 0.9188
Epoch 25/500
 - 0s - loss: 0.1872 - acc: 0.9188
Epoch 26/500
 - 0s - loss: 0.1833 - acc: 0.9188
Epoch 27/500
 - 0s - loss: 0.1792 - acc: 0.9188
Epoch 28/500
 - 0s - loss: 0.1778 - acc: 0.9234
Epoch 29/500
 - 0s - loss: 0.1737 - acc: 0.9234
Epoch 30/500
 - 0s - loss: 0.1702 - acc: 0.9258
Epoch 31/500
 - 0s - loss: 0.1691 - acc: 0.9211
Epoch 32/500
 - 0s - loss: 0.1716 - acc: 0.9304
Epoch 33/500
 - 0s - loss: 0.1633 - acc: 0.9281
Epoch 34/500
 - 0s - loss: 0.1577 - acc: 0.9327
Epoch 35/500
 - 0s - loss: 0.1551 - acc: 0.9327
Epoch 36/500
 - 0s - loss: 0.1570 - acc: 0.9327
Epoch 37/500
 - 0s - loss: 0.1529 - acc: 0.9327
Epoch 38/500
 - 0s - loss: 0.1505 - acc: 0.9327
Epoch 39/500
 - 0s - loss: 0.1511 - acc: 0.9420
Epoch 40/500
 - 0s - loss: 0.1468 - acc: 0.9304
Epoch 41/500
 - 0s - loss: 0.1399 - acc: 0.9490
Epoch 42/500
 - 0s - loss: 0.1382 - acc: 0.9443
Epoch 43/500
 - 0s - loss: 0.1350 - acc: 0.9443
Epoch 44/500
 - 0s - loss: 0.1316 - acc: 0.9466
Epoch 45/500
 - 0s - loss: 0.1303 - acc: 0.9536
Epoch 46/500
 - 0s - loss: 0.1298 - acc: 0.9327
Epoch 47/500
 - 0s - loss: 0.1332 - acc: 0.9466
Epoch 48/500
 - 0s - loss: 0.1245 - acc: 0.9466
Epoch 49/500
 - 0s - loss: 0.1258 - acc: 0.9513
Epoch 50/500
 - 0s - loss: 0.1209 - acc: 0.9513
Epoch 51/500
 - 0s - loss: 0.1181 - acc: 0.9513
Epoch 52/500
 - 0s - loss: 0.1206 - acc: 0.9466
Epoch 53/500
 - 0s - loss: 0.1171 - acc: 0.9559
Epoch 54/500
 - 0s - loss: 0.1128 - acc: 0.9443
Epoch 55/500
 - 0s - loss: 0.1114 - acc: 0.9606
Epoch 56/500
 - 0s - loss: 0.1086 - acc: 0.9559
Epoch 57/500
 - 0s - loss: 0.1062 - acc: 0.9606
Epoch 58/500
 - 0s - loss: 0.1055 - acc: 0.9513
Epoch 59/500
 - 0s - loss: 0.1019 - acc: 0.9582
Epoch 60/500
 - 0s - loss: 0.1058 - acc: 0.9606
Epoch 61/500
 - 0s - loss: 0.1068 - acc: 0.9559
Epoch 62/500
 - 0s - loss: 0.0999 - acc: 0.9536
Epoch 63/500
 - 0s - loss: 0.1025 - acc: 0.9582
Epoch 64/500
 - 0s - loss: 0.1077 - acc: 0.9606
Epoch 65/500
 - 0s - loss: 0.0979 - acc: 0.9559
Epoch 66/500
 - 0s - loss: 0.0961 - acc: 0.9629
Epoch 67/500
 - 0s - loss: 0.0904 - acc: 0.9606
Epoch 68/500
 - 0s - loss: 0.0935 - acc: 0.9675
Epoch 69/500
 - 0s - loss: 0.0971 - acc: 0.9559
Epoch 70/500
 - 0s - loss: 0.0874 - acc: 0.9606
Epoch 71/500
 - 0s - loss: 0.0876 - acc: 0.9606
Epoch 72/500
 - 0s - loss: 0.0850 - acc: 0.9768
Epoch 73/500
 - 0s - loss: 0.0855 - acc: 0.9629
Epoch 74/500
 - 0s - loss: 0.0852 - acc: 0.9745
Epoch 75/500
 - 0s - loss: 0.0859 - acc: 0.9582
Epoch 76/500
 - 0s - loss: 0.0817 - acc: 0.9791
Epoch 77/500
 - 0s - loss: 0.0779 - acc: 0.9722
Epoch 78/500
 - 0s - loss: 0.0817 - acc: 0.9629
Epoch 79/500
 - 0s - loss: 0.0809 - acc: 0.9791
Epoch 80/500
 - 0s - loss: 0.0767 - acc: 0.9698
Epoch 81/500
 - 0s - loss: 0.0819 - acc: 0.9722
Epoch 82/500
 - 0s - loss: 0.0746 - acc: 0.9745
Epoch 83/500
 - 0s - loss: 0.0725 - acc: 0.9745
Epoch 84/500
 - 0s - loss: 0.0772 - acc: 0.9698
Epoch 85/500
 - 0s - loss: 0.0707 - acc: 0.9861
Epoch 86/500
 - 0s - loss: 0.0719 - acc: 0.9698
Epoch 87/500
 - 0s - loss: 0.0733 - acc: 0.9722
Epoch 88/500
 - 0s - loss: 0.0717 - acc: 0.9745
Epoch 89/500
 - 0s - loss: 0.0737 - acc: 0.9814
Epoch 90/500
 - 0s - loss: 0.0702 - acc: 0.9698
Epoch 91/500
 - 0s - loss: 0.0663 - acc: 0.9745
Epoch 92/500
 - 0s - loss: 0.0661 - acc: 0.9722
Epoch 93/500
 - 0s - loss: 0.0670 - acc: 0.9838
Epoch 94/500
 - 0s - loss: 0.0657 - acc: 0.9675
Epoch 95/500
 - 0s - loss: 0.0661 - acc: 0.9791
Epoch 96/500
 - 0s - loss: 0.0704 - acc: 0.9722
Epoch 97/500
 - 0s - loss: 0.0659 - acc: 0.9675
Epoch 98/500
 - 0s - loss: 0.0742 - acc: 0.9722
Epoch 99/500
 - 0s - loss: 0.0607 - acc: 0.9745
Epoch 100/500
 - 0s - loss: 0.0817 - acc: 0.9675
Epoch 101/500
 - 0s - loss: 0.0631 - acc: 0.9814
Epoch 102/500
 - 0s - loss: 0.0564 - acc: 0.9791
Epoch 103/500
 - 0s - loss: 0.0571 - acc: 0.9814
Epoch 104/500
 - 0s - loss: 0.0560 - acc: 0.9814
Epoch 105/500
 - 0s - loss: 0.0591 - acc: 0.9768
Epoch 106/500
 - 0s - loss: 0.0590 - acc: 0.9814
Epoch 107/500
 - 0s - loss: 0.0568 - acc: 0.9838
Epoch 108/500
 - 0s - loss: 0.0540 - acc: 0.9768
Epoch 109/500
 - 0s - loss: 0.0523 - acc: 0.9814
Epoch 110/500
 - 0s - loss: 0.0539 - acc: 0.9814
Epoch 111/500
 - 0s - loss: 0.0543 - acc: 0.9768
Epoch 112/500
 - 0s - loss: 0.0518 - acc: 0.9768
Epoch 113/500
 - 0s - loss: 0.0506 - acc: 0.9791
Epoch 114/500
 - 0s - loss: 0.0493 - acc: 0.9838
Epoch 115/500
 - 0s - loss: 0.0474 - acc: 0.9838
Epoch 116/500
 - 0s - loss: 0.0469 - acc: 0.9791
Epoch 117/500
 - 0s - loss: 0.0486 - acc: 0.9838
Epoch 118/500
 - 0s - loss: 0.0452 - acc: 0.9838
Epoch 119/500
 - 0s - loss: 0.0461 - acc: 0.9814
Epoch 120/500
 - 0s - loss: 0.0485 - acc: 0.9814
Epoch 121/500
 - 0s - loss: 0.0456 - acc: 0.9838
Epoch 122/500
 - 0s - loss: 0.0456 - acc: 0.9814
Epoch 123/500
 - 0s - loss: 0.0468 - acc: 0.9791
Epoch 124/500
 - 0s - loss: 0.0453 - acc: 0.9814
Epoch 125/500
 - 0s - loss: 0.0467 - acc: 0.9814
Epoch 126/500
 - 0s - loss: 0.0476 - acc: 0.9838
Epoch 127/500
 - 0s - loss: 0.0430 - acc: 0.9838
Epoch 128/500
 - 0s - loss: 0.0415 - acc: 0.9861
Epoch 129/500
 - 0s - loss: 0.0428 - acc: 0.9838
Epoch 130/500
 - 0s - loss: 0.0427 - acc: 0.9814
Epoch 131/500
 - 0s - loss: 0.0464 - acc: 0.9838
Epoch 132/500
 - 0s - loss: 0.0420 - acc: 0.9838
Epoch 133/500
 - 0s - loss: 0.0398 - acc: 0.9838
Epoch 134/500
 - 0s - loss: 0.0409 - acc: 0.9838
Epoch 135/500
 - 0s - loss: 0.0388 - acc: 0.9838
Epoch 136/500
 - 0s - loss: 0.0371 - acc: 0.9861
Epoch 137/500
 - 0s - loss: 0.0375 - acc: 0.9861
Epoch 138/500
 - 0s - loss: 0.0371 - acc: 0.9861
Epoch 139/500
 - 0s - loss: 0.0370 - acc: 0.9861
Epoch 140/500
 - 0s - loss: 0.0350 - acc: 0.9861
Epoch 141/500
 - 0s - loss: 0.0359 - acc: 0.9861
Epoch 142/500
 - 0s - loss: 0.0374 - acc: 0.9884
Epoch 143/500
 - 0s - loss: 0.0391 - acc: 0.9814
Epoch 144/500
 - 0s - loss: 0.0326 - acc: 0.9861
Epoch 145/500
 - 0s - loss: 0.0318 - acc: 0.9884
Epoch 146/500
 - 0s - loss: 0.0330 - acc: 0.9861
Epoch 147/500
 - 0s - loss: 0.0330 - acc: 0.9884
Epoch 148/500
 - 0s - loss: 0.0333 - acc: 0.9861
Epoch 149/500
 - 0s - loss: 0.0350 - acc: 0.9884
Epoch 150/500
 - 0s - loss: 0.0376 - acc: 0.9838
Epoch 151/500
 - 0s - loss: 0.0322 - acc: 0.9884
Epoch 152/500
 - 0s - loss: 0.0334 - acc: 0.9884
Epoch 153/500
 - 0s - loss: 0.0344 - acc: 0.9838
Epoch 154/500
 - 0s - loss: 0.0430 - acc: 0.9861
Epoch 155/500
 - 0s - loss: 0.0531 - acc: 0.9814
Epoch 156/500
 - 0s - loss: 0.0335 - acc: 0.9884
Epoch 157/500
 - 0s - loss: 0.0304 - acc: 0.9907
Epoch 158/500
 - 0s - loss: 0.0332 - acc: 0.9907
Epoch 159/500
 - 0s - loss: 0.0306 - acc: 0.9884
Epoch 160/500
 - 0s - loss: 0.0297 - acc: 0.9861
Epoch 161/500
 - 0s - loss: 0.0310 - acc: 0.9884
Epoch 162/500
 - 0s - loss: 0.0288 - acc: 0.9884
Epoch 163/500
 - 0s - loss: 0.0264 - acc: 0.9884
Epoch 164/500
 - 0s - loss: 0.0298 - acc: 0.9884

Epoch 165/500
 - 0s - loss: 0.0285 - acc: 0.9907
Epoch 166/500
 - 0s - loss: 0.0309 - acc: 0.9861
Epoch 167/500
 - 0s - loss: 0.0304 - acc: 0.9861
Epoch 168/500
 - 0s - loss: 0.0278 - acc: 0.9907
Epoch 169/500
 - 0s - loss: 0.0258 - acc: 0.9884
Epoch 170/500
 - 0s - loss: 0.0268 - acc: 0.9907
Epoch 171/500
 - 0s - loss: 0.0295 - acc: 0.9884
Epoch 172/500
 - 0s - loss: 0.0274 - acc: 0.9884
Epoch 173/500
 - 0s - loss: 0.0269 - acc: 0.9907
Epoch 174/500
 - 0s - loss: 0.0266 - acc: 0.9861
Epoch 175/500
 - 0s - loss: 0.0309 - acc: 0.9861
Epoch 176/500
 - 0s - loss: 0.0300 - acc: 0.9838
Epoch 177/500
 - 0s - loss: 0.0260 - acc: 0.9930
Epoch 178/500
 - 0s - loss: 0.0264 - acc: 0.9884
Epoch 179/500
 - 0s - loss: 0.0304 - acc: 0.9907
Epoch 180/500
 - 0s - loss: 0.0251 - acc: 0.9884
Epoch 181/500
 - 0s - loss: 0.0210 - acc: 0.9930
Epoch 182/500
 - 0s - loss: 0.0231 - acc: 0.9907
Epoch 183/500
 - 0s - loss: 0.0241 - acc: 0.9884
Epoch 184/500
 - 0s - loss: 0.0236 - acc: 0.9930
Epoch 185/500
 - 0s - loss: 0.0225 - acc: 0.9907
Epoch 186/500
 - 0s - loss: 0.0226 - acc: 0.9884
Epoch 187/500
 - 0s - loss: 0.0220 - acc: 0.9907
Epoch 188/500
 - 0s - loss: 0.0218 - acc: 0.9907
Epoch 189/500
 - 0s - loss: 0.0211 - acc: 0.9930
Epoch 190/500
 - 0s - loss: 0.0215 - acc: 0.9907
Epoch 191/500
 - 0s - loss: 0.0208 - acc: 0.9884
Epoch 192/500
 - 0s - loss: 0.0212 - acc: 0.9930
Epoch 193/500
 - 0s - loss: 0.0199 - acc: 0.9930
Epoch 194/500
 - 0s - loss: 0.0236 - acc: 0.9907
Epoch 195/500
 - 0s - loss: 0.0215 - acc: 0.9907
Epoch 196/500
 - 0s - loss: 0.0204 - acc: 0.9930
Epoch 197/500
 - 0s - loss: 0.0244 - acc: 0.9907
Epoch 198/500
 - 0s - loss: 0.0203 - acc: 0.9907
Epoch 199/500
 - 0s - loss: 0.0196 - acc: 0.9884
Epoch 200/500
 - 0s - loss: 0.0181 - acc: 0.9930
Epoch 201/500
 - 0s - loss: 0.0208 - acc: 0.9930
Epoch 202/500
 - 0s - loss: 0.0230 - acc: 0.9884
Epoch 203/500
 - 0s - loss: 0.0214 - acc: 0.9907
Epoch 204/500
 - 0s - loss: 0.0228 - acc: 0.9930
Epoch 205/500
 - 0s - loss: 0.0189 - acc: 0.9930
Epoch 206/500
 - 0s - loss: 0.0192 - acc: 0.9930
Epoch 207/500
 - 0s - loss: 0.0194 - acc: 0.9907
Epoch 208/500
 - 0s - loss: 0.0184 - acc: 0.9884
Epoch 209/500
 - 0s - loss: 0.0180 - acc: 0.9954
Epoch 210/500
 - 0s - loss: 0.0189 - acc: 0.9884
Epoch 211/500
 - 0s - loss: 0.0199 - acc: 0.9884
Epoch 212/500
 - 0s - loss: 0.0191 - acc: 0.9930
Epoch 213/500
 - 0s - loss: 0.0201 - acc: 0.9907
Epoch 214/500
 - 0s - loss: 0.0180 - acc: 0.9930
Epoch 215/500
 - 0s - loss: 0.0186 - acc: 0.9884
Epoch 216/500
 - 0s - loss: 0.0188 - acc: 0.9907
Epoch 217/500
 - 0s - loss: 0.0251 - acc: 0.9907
Epoch 218/500
 - 0s - loss: 0.0170 - acc: 0.9954
Epoch 219/500
 - 0s - loss: 0.0188 - acc: 0.9930
Epoch 220/500
 - 0s - loss: 0.0192 - acc: 0.9907
Epoch 221/500
 - 0s - loss: 0.0177 - acc: 0.9884
Epoch 222/500
 - 0s - loss: 0.0186 - acc: 0.9930
Epoch 223/500
 - 0s - loss: 0.0198 - acc: 0.9930
Epoch 224/500
 - 0s - loss: 0.0283 - acc: 0.9861
Epoch 225/500
 - 0s - loss: 0.0168 - acc: 0.9954
Epoch 226/500
 - 0s - loss: 0.0163 - acc: 0.9954
Epoch 227/500
 - 0s - loss: 0.0161 - acc: 0.9954
Epoch 228/500
 - 0s - loss: 0.0166 - acc: 0.9930
Epoch 229/500
 - 0s - loss: 0.0150 - acc: 0.9930
Epoch 230/500
 - 0s - loss: 0.0156 - acc: 0.9930
Epoch 231/500
 - 0s - loss: 0.0154 - acc: 0.9930
Epoch 232/500
 - 0s - loss: 0.0146 - acc: 0.9930
Epoch 233/500
 - 0s - loss: 0.0151 - acc: 0.9954
Epoch 234/500
 - 0s - loss: 0.0150 - acc: 0.9954
Epoch 235/500
 - 0s - loss: 0.0167 - acc: 0.9907
Epoch 236/500
 - 0s - loss: 0.0168 - acc: 0.9907
Epoch 237/500
 - 0s - loss: 0.0170 - acc: 0.9907
Epoch 238/500
 - 0s - loss: 0.0160 - acc: 0.9930
Epoch 239/500
 - 0s - loss: 0.0152 - acc: 0.9930
Epoch 240/500
 - 0s - loss: 0.0174 - acc: 0.9930
Epoch 241/500
 - 0s - loss: 0.0198 - acc: 0.9907
Epoch 242/500
 - 0s - loss: 0.0233 - acc: 0.9884
Epoch 243/500
 - 0s - loss: 0.0233 - acc: 0.9884
Epoch 244/500
 - 0s - loss: 0.0208 - acc: 0.9930
Epoch 245/500
 - 0s - loss: 0.0167 - acc: 0.9907
Epoch 246/500
 - 0s - loss: 0.0152 - acc: 0.9930
Epoch 247/500
 - 0s - loss: 0.0148 - acc: 0.9907
Epoch 248/500
 - 0s - loss: 0.0161 - acc: 0.9930
Epoch 249/500
 - 0s - loss: 0.0137 - acc: 0.9954
Epoch 250/500
 - 0s - loss: 0.0157 - acc: 0.9930
Epoch 251/500
 - 0s - loss: 0.0157 - acc: 0.9930
Epoch 252/500
 - 0s - loss: 0.0154 - acc: 0.9930
Epoch 253/500
 - 0s - loss: 0.0151 - acc: 0.9907
Epoch 254/500
 - 0s - loss: 0.0131 - acc: 0.9954
Epoch 255/500
 - 0s - loss: 0.0131 - acc: 0.9907
Epoch 256/500
 - 0s - loss: 0.0132 - acc: 0.9930
Epoch 257/500
 - 0s - loss: 0.0154 - acc: 0.9884
Epoch 258/500
 - 0s - loss: 0.0140 - acc: 0.9930
Epoch 259/500
 - 0s - loss: 0.0148 - acc: 0.9930
Epoch 260/500
 - 0s - loss: 0.0166 - acc: 0.9954
Epoch 261/500
 - 0s - loss: 0.0141 - acc: 0.9954
Epoch 262/500
 - 0s - loss: 0.0163 - acc: 0.9907
Epoch 263/500
 - 0s - loss: 0.0142 - acc: 0.9907
Epoch 264/500
 - 0s - loss: 0.0163 - acc: 0.9954
Epoch 265/500
 - 0s - loss: 0.0132 - acc: 0.9930
Epoch 266/500
 - 0s - loss: 0.0138 - acc: 0.9954
Epoch 267/500
 - 0s - loss: 0.0148 - acc: 0.9930
Epoch 268/500
 - 0s - loss: 0.0158 - acc: 0.9907
Epoch 269/500
 - 0s - loss: 0.0178 - acc: 0.9930
Epoch 270/500
 - 0s - loss: 0.0151 - acc: 0.9930
Epoch 271/500
 - 0s - loss: 0.0174 - acc: 0.9954
Epoch 272/500
 - 0s - loss: 0.0141 - acc: 0.9954
Epoch 273/500
 - 0s - loss: 0.0152 - acc: 0.9930
Epoch 274/500
 - 0s - loss: 0.0123 - acc: 0.9954
Epoch 275/500
 - 0s - loss: 0.0147 - acc: 0.9907
Epoch 276/500
 - 0s - loss: 0.0142 - acc: 0.9930
Epoch 277/500
 - 0s - loss: 0.0159 - acc: 0.9954
Epoch 278/500
 - 0s - loss: 0.0204 - acc: 0.9930
Epoch 279/500
 - 0s - loss: 0.0165 - acc: 0.9977
Epoch 280/500
 - 0s - loss: 0.0138 - acc: 0.9954
Epoch 281/500
 - 0s - loss: 0.0140 - acc: 0.9954
Epoch 282/500
 - 0s - loss: 0.0131 - acc: 0.9954
Epoch 283/500
 - 0s - loss: 0.0111 - acc: 0.9954
Epoch 284/500
 - 0s - loss: 0.0121 - acc: 0.9954
Epoch 285/500
 - 0s - loss: 0.0126 - acc: 0.9954
Epoch 286/500
 - 0s - loss: 0.0130 - acc: 0.9907
Epoch 287/500
 - 0s - loss: 0.0136 - acc: 0.9954
Epoch 288/500
 - 0s - loss: 0.0117 - acc: 0.9907
Epoch 289/500
 - 0s - loss: 0.0136 - acc: 0.9930
Epoch 290/500
 - 0s - loss: 0.0119 - acc: 0.9954
Epoch 291/500
 - 0s - loss: 0.0134 - acc: 0.9930
Epoch 292/500
 - 0s - loss: 0.0119 - acc: 0.9954
Epoch 293/500
 - 0s - loss: 0.0116 - acc: 0.9954
Epoch 294/500
 - 0s - loss: 0.0132 - acc: 0.9954
Epoch 295/500
 - 0s - loss: 0.0119 - acc: 0.9930
Epoch 296/500
 - 0s - loss: 0.0136 - acc: 0.9930
Epoch 297/500
 - 0s - loss: 0.0117 - acc: 0.9930
Epoch 298/500
 - 0s - loss: 0.0113 - acc: 0.9954
Epoch 299/500
 - 0s - loss: 0.0111 - acc: 0.9907
Epoch 300/500
 - 0s - loss: 0.0110 - acc: 0.9907
Epoch 301/500
 - 0s - loss: 0.0119 - acc: 0.9930
Epoch 302/500
 - 0s - loss: 0.0133 - acc: 0.9907
Epoch 303/500
 - 0s - loss: 0.0250 - acc: 0.9884
Epoch 304/500
 - 0s - loss: 0.0260 - acc: 0.9907
Epoch 305/500
 - 0s - loss: 0.0184 - acc: 0.9884
Epoch 306/500
 - 0s - loss: 0.0123 - acc: 0.9954
Epoch 307/500
 - 0s - loss: 0.0144 - acc: 0.9930
Epoch 308/500
 - 0s - loss: 0.0139 - acc: 0.9954
Epoch 309/500
 - 0s - loss: 0.0141 - acc: 0.9954
Epoch 310/500
 - 0s - loss: 0.0127 - acc: 0.9954
Epoch 311/500
 - 0s - loss: 0.0131 - acc: 0.9930
Epoch 312/500
 - 0s - loss: 0.0117 - acc: 0.9954
Epoch 313/500
 - 0s - loss: 0.0103 - acc: 0.9954
Epoch 314/500
 - 0s - loss: 0.0106 - acc: 0.9954
Epoch 315/500
 - 0s - loss: 0.0120 - acc: 0.9907
Epoch 316/500
 - 0s - loss: 0.0109 - acc: 0.9907
Epoch 317/500
 - 0s - loss: 0.0133 - acc: 0.9930
Epoch 318/500
 - 0s - loss: 0.0107 - acc: 0.9954
Epoch 319/500
 - 0s - loss: 0.0156 - acc: 0.9930
Epoch 320/500
 - 0s - loss: 0.0138 - acc: 0.9930
Epoch 321/500
 - 0s - loss: 0.0117 - acc: 0.9930
Epoch 322/500
 - 0s - loss: 0.0122 - acc: 0.9907
Epoch 323/500
 - 0s - loss: 0.0099 - acc: 0.9954
Epoch 324/500
 - 0s - loss: 0.0127 - acc: 0.9930
Epoch 325/500
 - 0s - loss: 0.0110 - acc: 0.9954
Epoch 326/500
 - 0s - loss: 0.0125 - acc: 0.9930
Epoch 327/500
 - 0s - loss: 0.0146 - acc: 0.9954
Epoch 328/500
 - 0s - loss: 0.0122 - acc: 0.9930
Epoch 329/500
 - 0s - loss: 0.0126 - acc: 0.9954
Epoch 330/500
 - 0s - loss: 0.0124 - acc: 0.9930
Epoch 331/500
 - 0s - loss: 0.0096 - acc: 0.9954
Epoch 332/500
 - 0s - loss: 0.0112 - acc: 0.9930

Epoch 333/500
 - 0s - loss: 0.0104 - acc: 0.9930
Epoch 334/500
 - 0s - loss: 0.0098 - acc: 0.9954
Epoch 335/500
 - 0s - loss: 0.0102 - acc: 0.9954
Epoch 336/500
 - 0s - loss: 0.0112 - acc: 0.9930
Epoch 337/500
 - 0s - loss: 0.0101 - acc: 0.9954
Epoch 338/500
 - 0s - loss: 0.0128 - acc: 0.9930
Epoch 339/500
 - 0s - loss: 0.0116 - acc: 0.9954
Epoch 340/500
 - 0s - loss: 0.0136 - acc: 0.9954
Epoch 341/500
 - 0s - loss: 0.0130 - acc: 0.9954
Epoch 342/500
 - 0s - loss: 0.0127 - acc: 0.9907
Epoch 343/500
 - 0s - loss: 0.0095 - acc: 0.9930
Epoch 344/500
 - 0s - loss: 0.0134 - acc: 0.9907
Epoch 345/500
 - 0s - loss: 0.0123 - acc: 0.9930
Epoch 346/500
 - 0s - loss: 0.0101 - acc: 0.9954
Epoch 347/500
 - 0s - loss: 0.0108 - acc: 0.9954
Epoch 348/500
 - 0s - loss: 0.0138 - acc: 0.9907
Epoch 349/500
 - 0s - loss: 0.0106 - acc: 0.9954
Epoch 350/500
 - 0s - loss: 0.0108 - acc: 0.9954
Epoch 351/500
 - 0s - loss: 0.0127 - acc: 0.9930
Epoch 352/500
 - 0s - loss: 0.0122 - acc: 0.9930
Epoch 353/500
 - 0s - loss: 0.0107 - acc: 0.9930
Epoch 354/500
 - 0s - loss: 0.0133 - acc: 0.9930
Epoch 355/500
 - 0s - loss: 0.0114 - acc: 0.9930
Epoch 356/500
 - 0s - loss: 0.0116 - acc: 0.9930
Epoch 357/500
 - 0s - loss: 0.0129 - acc: 0.9907
Epoch 358/500
 - 0s - loss: 0.0100 - acc: 0.9930
Epoch 359/500
 - 0s - loss: 0.0106 - acc: 0.9930
Epoch 360/500
 - 0s - loss: 0.0104 - acc: 0.9954
Epoch 361/500
 - 0s - loss: 0.0114 - acc: 0.9930
Epoch 362/500
 - 0s - loss: 0.0109 - acc: 0.9930
Epoch 363/500
 - 0s - loss: 0.0095 - acc: 0.9954
Epoch 364/500
 - 0s - loss: 0.0094 - acc: 0.9954
Epoch 365/500
 - 0s - loss: 0.0125 - acc: 0.9954
Epoch 366/500
 - 0s - loss: 0.0120 - acc: 0.9954
Epoch 367/500
 - 0s - loss: 0.0103 - acc: 0.9930
Epoch 368/500
 - 0s - loss: 0.0119 - acc: 0.9954
Epoch 369/500
 - 0s - loss: 0.0180 - acc: 0.9930
Epoch 370/500
 - 0s - loss: 0.0299 - acc: 0.9861
Epoch 371/500
 - 0s - loss: 0.0229 - acc: 0.9884
Epoch 372/500
 - 0s - loss: 0.0207 - acc: 0.9930
Epoch 373/500
 - 0s - loss: 0.0576 - acc: 0.9814
Epoch 374/500
 - 0s - loss: 0.0394 - acc: 0.9814
Epoch 375/500
 - 0s - loss: 0.0185 - acc: 0.9930
Epoch 376/500
 - 0s - loss: 0.0267 - acc: 0.9884
Epoch 377/500
 - 0s - loss: 0.0159 - acc: 0.9907
Epoch 378/500
 - 0s - loss: 0.0194 - acc: 0.9907
Epoch 379/500
 - 0s - loss: 0.0127 - acc: 0.9954
Epoch 380/500
 - 0s - loss: 0.0130 - acc: 0.9930
Epoch 381/500
 - 0s - loss: 0.0126 - acc: 0.9954
Epoch 382/500
 - 0s - loss: 0.0132 - acc: 0.9954
Epoch 383/500
 - 0s - loss: 0.0101 - acc: 0.9954
Epoch 384/500
 - 0s - loss: 0.0102 - acc: 0.9907
Epoch 385/500
 - 0s - loss: 0.0114 - acc: 0.9954
Epoch 386/500
 - 0s - loss: 0.0093 - acc: 0.9907
Epoch 387/500
 - 0s - loss: 0.0107 - acc: 0.9954
Epoch 388/500
 - 0s - loss: 0.0118 - acc: 0.9907
Epoch 389/500
 - 0s - loss: 0.0097 - acc: 0.9954
Epoch 390/500
 - 0s - loss: 0.0092 - acc: 0.9930
Epoch 391/500
 - 0s - loss: 0.0117 - acc: 0.9954
Epoch 392/500
 - 0s - loss: 0.0138 - acc: 0.9907
Epoch 393/500
 - 0s - loss: 0.0105 - acc: 0.9930
Epoch 394/500
 - 0s - loss: 0.0090 - acc: 0.9930
Epoch 395/500
 - 0s - loss: 0.0101 - acc: 0.9907
Epoch 396/500
 - 0s - loss: 0.0098 - acc: 0.9930
Epoch 397/500
 - 0s - loss: 0.0091 - acc: 0.9954
Epoch 398/500
 - 0s - loss: 0.0111 - acc: 0.9930
Epoch 399/500
 - 0s - loss: 0.0115 - acc: 0.9930
Epoch 400/500
 - 0s - loss: 0.0099 - acc: 0.9930
Epoch 401/500
 - 0s - loss: 0.0099 - acc: 0.9954
Epoch 402/500
 - 0s - loss: 0.0090 - acc: 0.9907
Epoch 403/500
 - 0s - loss: 0.0098 - acc: 0.9907
Epoch 404/500
 - 0s - loss: 0.0110 - acc: 0.9930
Epoch 405/500
 - 0s - loss: 0.0095 - acc: 0.9954
Epoch 406/500
 - 0s - loss: 0.0098 - acc: 0.9954
Epoch 407/500
 - 0s - loss: 0.0086 - acc: 0.9954
Epoch 408/500
 - 0s - loss: 0.0108 - acc: 0.9954
Epoch 409/500
 - 0s - loss: 0.0104 - acc: 0.9930
Epoch 410/500
 - 0s - loss: 0.0088 - acc: 0.9954
Epoch 411/500
 - 0s - loss: 0.0091 - acc: 0.9930
Epoch 412/500
 - 0s - loss: 0.0081 - acc: 0.9954
Epoch 413/500
 - 0s - loss: 0.0101 - acc: 0.9954
Epoch 414/500
 - 0s - loss: 0.0097 - acc: 0.9954
Epoch 415/500
 - 0s - loss: 0.0094 - acc: 0.9954
Epoch 416/500
 - 0s - loss: 0.0102 - acc: 0.9954
Epoch 417/500
 - 0s - loss: 0.0113 - acc: 0.9954
Epoch 418/500
 - 0s - loss: 0.0112 - acc: 0.9930
Epoch 419/500
 - 0s - loss: 0.0125 - acc: 0.9907
Epoch 420/500
 - 0s - loss: 0.0127 - acc: 0.9954
Epoch 421/500
 - 0s - loss: 0.0098 - acc: 0.9954
Epoch 422/500
 - 0s - loss: 0.0099 - acc: 0.9930
Epoch 423/500
 - 0s - loss: 0.0084 - acc: 0.9930
Epoch 424/500
 - 0s - loss: 0.0111 - acc: 0.9954
Epoch 425/500
 - 0s - loss: 0.0093 - acc: 0.9954
Epoch 426/500
 - 0s - loss: 0.0086 - acc: 0.9954
Epoch 427/500
 - 0s - loss: 0.0108 - acc: 0.9907
Epoch 428/500
 - 0s - loss: 0.0106 - acc: 0.9954
Epoch 429/500
 - 0s - loss: 0.0099 - acc: 0.9907
Epoch 430/500
 - 0s - loss: 0.0094 - acc: 0.9907
Epoch 431/500
 - 0s - loss: 0.0095 - acc: 0.9930
Epoch 432/500
 - 0s - loss: 0.0088 - acc: 0.9954
Epoch 433/500
 - 0s - loss: 0.0082 - acc: 0.9954
Epoch 434/500
 - 0s - loss: 0.0095 - acc: 0.9930
Epoch 435/500
 - 0s - loss: 0.0087 - acc: 0.9954
Epoch 436/500
 - 0s - loss: 0.0096 - acc: 0.9954
Epoch 437/500
 - 0s - loss: 0.0106 - acc: 0.9930
Epoch 438/500
 - 0s - loss: 0.0109 - acc: 0.9907
Epoch 439/500
 - 0s - loss: 0.0126 - acc: 0.9930
Epoch 440/500
 - 0s - loss: 0.0127 - acc: 0.9954
Epoch 441/500
 - 0s - loss: 0.0100 - acc: 0.9930
Epoch 442/500
 - 0s - loss: 0.0093 - acc: 0.9930
Epoch 443/500
 - 0s - loss: 0.0089 - acc: 0.9954
Epoch 444/500
 - 0s - loss: 0.0105 - acc: 0.9930
Epoch 445/500
 - 0s - loss: 0.0082 - acc: 0.9954
Epoch 446/500
 - 0s - loss: 0.0117 - acc: 0.9930
Epoch 447/500
 - 0s - loss: 0.0098 - acc: 0.9954
Epoch 448/500
 - 0s - loss: 0.0101 - acc: 0.9930
Epoch 449/500
 - 0s - loss: 0.0099 - acc: 0.9930
Epoch 450/500
 - 0s - loss: 0.0095 - acc: 0.9930
Epoch 451/500
 - 0s - loss: 0.0090 - acc: 0.9907
Epoch 452/500
 - 0s - loss: 0.0091 - acc: 0.9907
Epoch 453/500
 - 0s - loss: 0.0084 - acc: 0.9930
Epoch 454/500
 - 0s - loss: 0.0093 - acc: 0.9907
Epoch 455/500
 - 0s - loss: 0.0093 - acc: 0.9930
Epoch 456/500
 - 0s - loss: 0.0090 - acc: 0.9930
Epoch 457/500
 - 0s - loss: 0.0087 - acc: 0.9954
Epoch 458/500
 - 0s - loss: 0.0086 - acc: 0.9954
Epoch 459/500
 - 0s - loss: 0.0083 - acc: 0.9930
Epoch 460/500
 - 0s - loss: 0.0077 - acc: 0.9954
Epoch 461/500
 - 0s - loss: 0.0092 - acc: 0.9930
Epoch 462/500
 - 0s - loss: 0.0090 - acc: 0.9930
Epoch 463/500
 - 0s - loss: 0.0113 - acc: 0.9930
Epoch 464/500
 - 0s - loss: 0.0091 - acc: 0.9930
Epoch 465/500
 - 0s - loss: 0.0092 - acc: 0.9954
Epoch 466/500
 - 0s - loss: 0.0124 - acc: 0.9907
Epoch 467/500
 - 0s - loss: 0.0115 - acc: 0.9930
Epoch 468/500
 - 0s - loss: 0.0101 - acc: 0.9930
Epoch 469/500
 - 0s - loss: 0.0107 - acc: 0.9930
Epoch 470/500
 - 0s - loss: 0.0094 - acc: 0.9930
Epoch 471/500
 - 0s - loss: 0.0104 - acc: 0.9930
Epoch 472/500
 - 0s - loss: 0.0090 - acc: 0.9930
Epoch 473/500
 - 0s - loss: 0.0104 - acc: 0.9954
Epoch 474/500
 - 0s - loss: 0.0096 - acc: 0.9954
Epoch 475/500
 - 0s - loss: 0.0085 - acc: 0.9930
Epoch 476/500
 - 0s - loss: 0.0085 - acc: 0.9954
Epoch 477/500
 - 0s - loss: 0.0105 - acc: 0.9954
Epoch 478/500
 - 0s - loss: 0.0104 - acc: 0.9954
Epoch 479/500
 - 0s - loss: 0.0081 - acc: 0.9954
Epoch 480/500
 - 0s - loss: 0.0101 - acc: 0.9930
Epoch 481/500
 - 0s - loss: 0.0091 - acc: 0.9954
Epoch 482/500
 - 0s - loss: 0.0092 - acc: 0.9907
Epoch 483/500
 - 0s - loss: 0.0097 - acc: 0.9954
Epoch 484/500
 - 0s - loss: 0.0094 - acc: 0.9954
Epoch 485/500
 - 0s - loss: 0.0091 - acc: 0.9907
Epoch 486/500
 - 0s - loss: 0.0090 - acc: 0.9907
Epoch 487/500
 - 0s - loss: 0.0095 - acc: 0.9954
Epoch 488/500
 - 0s - loss: 0.0101 - acc: 0.9907
Epoch 489/500
 - 0s - loss: 0.0076 - acc: 0.9954
Epoch 490/500
 - 0s - loss: 0.0088 - acc: 0.9954
Epoch 491/500
 - 0s - loss: 0.0117 - acc: 0.9954
Epoch 492/500
 - 0s - loss: 0.0130 - acc: 0.9930
Epoch 493/500
 - 0s - loss: 0.0126 - acc: 0.9907
Epoch 494/500
 - 0s - loss: 0.0089 - acc: 0.9954
Epoch 495/500
 - 0s - loss: 0.0092 - acc: 0.9930
Epoch 496/500
 - 0s - loss: 0.0097 - acc: 0.9954
Epoch 497/500
 - 0s - loss: 0.0082 - acc: 0.9930
Epoch 498/500
 - 0s - loss: 0.0084 - acc: 0.9930
Epoch 499/500
 - 0s - loss: 0.0091 - acc: 0.9907
Epoch 500/500

 - 0s - loss: 0.0077 - acc: 0.9954

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 0.8611 - acc: 0.9167
Normal Neural Network - Loss: 0.8611293103959825, Accuracy: 0.9166666865348816

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Certified' 'Certified' 'Certified' 'Certified' 'Certified'
 'Certified' 'Certified' 'Certified' 'Denied']
Actual Labels: ['Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified']