In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Resources/certified_denied.csv')

In [3]:
data.head()

,Unnamed: 0,Unnamed: 1,CASE_NUMBER,DECISION_DATE,CASE_STATUS,CASE_RECEIVED_DATE,DECISION_ELAPSED_DAYS,DECISION_ELAPSED_YEARS,EMPLOYER_NAME,EMPLOYER_CITY,...,FW_INFO_POSTAL_CODE,COUNTRY_OF_CITIZENSHIP,FW_INFO_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,FW_INFO_EDUCATION_OTHER,DECISION_DATE_YEAR,DECISION_DATE_MONTH,CASE_RECEIVED_DATE_YEAR,CASE_RECEIVED_DATE_MONTH
0,NaN,25,A-14246-03533,2015-06-22,Certified,2014-12-19,185,0.506849,"CITRIX SYSTEMS, INC.",FORT LAUDERDALE,...,1973-03-30 00:00:00,CHINA,CHINA,H-1B,Master's,NaN,2015,6,2014.0,12.0
1,NaN,28,A-14198-89806,2015-04-06,Certified,2014-07-18,262,0.717808,COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION,COLLEGE STATION,...,75063,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,4,2014.0,7.0
2,NaN,35,A-14222-96825,2015-06-24,Certified,2014-12-11,195,0.534247,SAT SOLUTIONS LLC,MONROE,...,75001,INDIA,INDIA,H-1B,Bachelor's,NaN,2015,6,2014.0,12.0
3,NaN,61,A-13216-85505,2015-05-29,Certified,2013-08-05,662,1.813699,"KOCH FOODS OF ALABAMA, LLC",MONTGOMERY,...,210001,CHINA,CHINA,NaN,Associate's,NaN,2015,5,2013.0,8.0
4,NaN,63,A-13179-76467,2015-04-20,Certified,2013-06-28,661,1.810959,FARROKH ERFAN,GAITHERSBURG,...,NaN,IRAN,IRAN,NaN,Bachelor's,NaN,2015,4,2013.0,6.0

In [4]:
data2 = data.loc[data['COUNTRY_OF_CITIZENSHIP'] == 'PERU']

In [5]:
data2['COUNTRY_OF_CITIZENSHIP'].value_counts()

PERU    498
Name: COUNTRY_OF_CITIZENSHIP, dtype: int64

In [6]:
data3 = data2.loc[data2['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']

In [7]:
data3['WAGE_OFFER_UNIT_OF_PAY_9089'].value_counts()

Year    453
Name: WAGE_OFFER_UNIT_OF_PAY_9089, dtype: int64

In [8]:
data3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CASE_NUMBER', 'DECISION_DATE',
       'CASE_STATUS', 'CASE_RECEIVED_DATE', 'DECISION_ELAPSED_DAYS',
       'DECISION_ELAPSED_YEARS', 'EMPLOYER_NAME', 'EMPLOYER_CITY',
       'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_NUM_EMPLOYEES',
       'AGENT_FIRM_NAME', 'AGENT_CITY', 'AGENT_STATE', 'PW_SOC_CODE',
       'PW_SOC_TITLE', 'PW_AMOUNT_9089', 'WAGE_OFFER_FROM_9089',
       'WAGE_OFFER_UNIT_OF_PAY_9089', 'JOB_INFO_WORK_CITY',
       'JOB_INFO_WORK_STATE', 'JOB_INFO_WORK_POSTAL_CODE',
       'JOB_INFO_JOB_TITLE', 'JOB_INFO_EDUCATION', 'JOB_INFO_EDUCATION_OTHER',
       'FOREIGN_WORKER_INFO_CITY', 'FOREIGN_WORKER_INFO_STATE',
       'FW_INFO_POSTAL_CODE', 'COUNTRY_OF_CITIZENSHIP',
       'FW_INFO_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION',
       'FOREIGN_WORKER_INFO_EDUCATION', 'FW_INFO_EDUCATION_OTHER',
       'DECISION_DATE_YEAR', 'DECISION_DATE_MONTH', 'CASE_RECEIVED_DATE_YEAR',
       'CASE_RECEIVED_DATE_MONTH'],
      dtype='object')

In [9]:
data4 = data3[[
    'CASE_STATUS',
    'DECISION_ELAPSED_DAYS',
    'EMPLOYER_POSTAL_CODE',
    'EMPLOYER_STATE',
    'EMPLOYER_NUM_EMPLOYEES',
    'WAGE_OFFER_FROM_9089',
    'COUNTRY_OF_CITIZENSHIP',
    'CLASS_OF_ADMISSION',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CASE_RECEIVED_DATE_MONTH'
]]

In [10]:
data4.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH
626,Certified,465,34116,FLORIDA,12.0,53290.00,PERU,NaN,High School,6.0
1111,Certified,166,35294-1280,ALABAMA,18000.0,279999.96,PERU,H-1B,Other,10.0
1284,Certified,198,87102,NEW MEXICO,2876.0,187199.00,PERU,H-1B,Other,3.0
1530,Certified,210,98109,WASHINGTON,117300.0,110000.00,PERU,H-1B,Master's,1.0
1987,Certified,186,01237,MASSACHUSETTS,900.0,36650.00,PERU,NaN,Bachelor's,3.0

In [11]:
states = []

for row in data4['EMPLOYER_STATE']:
    if row == "ME":
        states.append("MAINE")
    elif row == "NH":
        states.append("NEW HAMPSHIRE")
    elif row == "VT":
        states.append("VERMONT")
    elif row == "MA":
        states.append("MASSACHUSETTS")
    elif row == "RI":
        states.append("RHODE ISLAND")
    elif row == "CT":
        states.append("CONNECTICUT")
    elif row == "NY":
        states.append("NEW YORK")
    elif row == "NJ":
        states.append("NEW JERSEY")
    elif row == "PA":
        states.append("PENNSYLVANIA")
    elif row == "DE":
        states.append("DELAWARE")
    elif row == "MD":
        states.append("MARYLAND")
    elif row == "DC":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VA":
        states.append("VIRGINIA")
    elif row == "WV":
        states.append("WEST VIRGINIA")
    elif row == "NC":
        states.append("NORTH CAROLINA")
    elif row == "SC":
        states.append("SOUTH CAROLINA")
    elif row == "GA":
        states.append("GEORGIA")
    elif row == "FL":
        states.append("FLORIDA")
    elif row == "AL":
        states.append("ALABAMA")
    elif row == "TN":
        states.append("TENNESSEE")
    elif row == "TENNESSE":
        states.append("TENNESSEE")
    elif row == "KY":
        states.append("KENTUCKY")
    elif row == "OH":
        states.append("OHIO")
    elif row == "MI":
        states.append("MICHIGAN")
    elif row == "IN":
        states.append("INDIANA")
    elif row == "MS":
        states.append("MISSISSIPPI")
    elif row == "IL":
        states.append("ILLINOIS")
    elif row == "WI":
        states.append("WISCONSIN")
    elif row == "MN":
        states.append("MINNESOTA")
    elif row == "IA":
        states.append("IOWA")
    elif row == "MO":
        states.append("MISSOURI")
    elif row == "AR":
        states.append("ARKANSAS")
    elif row == "LA":
        states.append("LOUISIANA")
    elif row == "ND":
        states.append("NORTH DAKOTA")
    elif row == "SD":
        states.append("SOUTH DAKOTA")
    elif row == "NE":
        states.append("NEBRASKA")
    elif row == "KS":
        states.append("KANSAS")
    elif row == "OK":
        states.append("OKLAHOMA")
    elif row == "TX":
        states.append("TEXAS")
    elif row == "MT":
        states.append("MONTANA")
    elif row == "WY":
        states.append("WYOMING")
    elif row == "CO":
        states.append("COLORADO")
    elif row == "NM":
        states.append("NEW MEXICO")
    elif row == "ID":
        states.append("IDAHO")
    elif row == "UT":
        states.append("UTAH")
    elif row == "AZ":
        states.append("ARIZONA")
    elif row == "WA":
        states.append("WASHINGTON")
    elif row == "OR":
        states.append("OREGON")
    elif row == "NV":
        states.append("NEVADA")
    elif row == "CA":
        states.append("CALIFORNIA")
    elif row == "AK":
        states.append("ALASKA")
    elif row == "HI":
        states.append("HAWAII")
    elif row == "PR":
        states.append("PUERTO RICO")
    elif row == "MP":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VI":
        states.append("VIRGIN ISLANDS")
    elif row == "GU":
        states.append("GUAM")
    elif row == "NEW HAMPSHIRE":
        states.append("NEW HAMPSHIRE")
    elif row == "VERMONT":
        states.append("VERMONT")
    elif row == "MASSACHUSETTS":
        states.append("MASSACHUSETTS")
    elif row == "RHODE ISLAND":
        states.append("RHODE ISLAND")
    elif row == "CONNECTICUT":
        states.append("CONNECTICUT")
    elif row == "NEW YORK":
        states.append("NEW YORK")
    elif row == "NEW JERSEY":
        states.append("NEW JERSEY")
    elif row == "PENNSYLVANIA":
        states.append("PENNSYLVANIA")
    elif row == "DELAWARE":
        states.append("DELAWARE")
    elif row == "MARYLAND":
        states.append("MARYLAND")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("DISTRICT OF COLUMBIA")
    elif row == "VIRGINIA":
        states.append("VIRGINIA")
    elif row == "WEST VIRGINIA":
        states.append("WEST VIRGINIA")
    elif row == "NORTH CAROLINA":
        states.append("NORTH CAROLINA")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH CAROLINA")
    elif row == "GEORGIA":
        states.append("GEORGIA")
    elif row == "FLORIDA":
        states.append("FLORIDA")
    elif row == "ALABAMA":
        states.append("ALABAMA")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "TENNESSEE":
        states.append("TENNESSEE")
    elif row == "KENTUCKY":
        states.append("KENTUCKY")
    elif row == "OHIO":
        states.append("OHIO")
    elif row == "MICHIGAN":
        states.append("MICHIGAN")
    elif row == "INDIANA":
        states.append("INDIANA")
    elif row == "MISSISSIPPI":
        states.append("MISSISSIPPI")
    elif row == "ILLINOIS":
        states.append("ILLINOIS")
    elif row == "WISCONSIN":
        states.append("WISCONSIN")
    elif row == "MINNESOTA":
        states.append("MINNESOTA")
    elif row == "IOWA":
        states.append("IOWA")
    elif row == "MISSOURI":
        states.append("MISSOURI")
    elif row == "ARKANSAS":
        states.append("ARKANSAS")
    elif row == "LOUISIANA":
        states.append("LOUISIANA")
    elif row == "NORTH DAKOTA":
        states.append("NORTH DAKOTA")
    elif row == "SOUTH DAKOTA":
        states.append("SOUTH DAKOTA")
    elif row == "NEBRASKA":
        states.append("NEBRASKA")
    elif row == "KANSAS":
        states.append("KANSAS")
    elif row == "OKLAHOMA":
        states.append("OKLAHOMA")
    elif row == "TEXAS":
        states.append("TEXAS")
    elif row == "MONTANA":
        states.append("MONTANA")
    elif row == "WYOMING":
        states.append("WYOMING")
    elif row == "COLORADO":
        states.append("COLORADO")
    elif row == "NEW MEXICO":
        states.append("NEW MEXICO")
    elif row == "IDAHO":
        states.append("IDAHO")
    elif row == "UTAH":
        states.append("UTAH")
    elif row == "ARIZONA":
        states.append("ARIZONA")
    elif row == "WASHINGTON":
        states.append("WASHINGTON")
    elif row == "OREGON":
        states.append("OREGON")
    elif row == "NEVADA":
        states.append("NEVADA")
    elif row == "CALIFORNIA":
        states.append("CALIFORNIA")
    elif row == "ALASKA":
        states.append("ALASKA")
    elif row == "HAWAII":
        states.append("HAWAII")
    elif row == "PUERTO RICO":
        states.append("PUERTO RICO")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("NORTHERN MARIANA ISLANDS")
    elif row == "VIRGIN ISLANDS":
        states.append("VIRGIN ISLANDS")
    elif row == "GUAM":
        states.append("GUAM")
    else:
        states.append("UNKNOWN")
        
data4['EMPLOYER_STATES'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:229: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data4['EMPLOYER_STATES'].value_counts()

NEW YORK                58
CALIFORNIA              48
FLORIDA                 48
TEXAS                   42
VIRGINIA                35
ILLINOIS                18
NEW JERSEY              17
MASSACHUSETTS           14
MARYLAND                13
WASHINGTON              12
ARIZONA                 11
GEORGIA                 10
NORTH CAROLINA           9
MICHIGAN                 8
UTAH                     8
PUERTO RICO              7
INDIANA                  6
IOWA                     6
OHIO                     6
WISCONSIN                5
COLORADO                 5
CONNECTICUT              5
MINNESOTA                5
KENTUCKY                 5
ALABAMA                  5
PENNSYLVANIA             4
MISSOURI                 4
ARKANSAS                 4
NEVADA                   3
TENNESSEE                3
LOUISIANA                3
DISTRICT OF COLUMBIA     3
SOUTH CAROLINA           2
MONTANA                  2
OKLAHOMA                 2
HAWAII                   2
WEST VIRGINIA            2
RHODE ISLAND             2
KANSAS                   2
IDAHO                    1
OREGON                   1
UNKNOWN                  1
SOUTH DAKOTA             1
NORTH DAKOTA             1
DELAWARE                 1
NEW MEXICO               1
WYOMING                  1
NEBRASKA                 1
Name: EMPLOYER_STATES, dtype: int64

In [13]:
data5 = data4.dropna(how='any')

In [14]:
data5.head()

,CASE_STATUS,DECISION_ELAPSED_DAYS,EMPLOYER_POSTAL_CODE,EMPLOYER_STATE,EMPLOYER_NUM_EMPLOYEES,WAGE_OFFER_FROM_9089,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_INFO_EDUCATION,CASE_RECEIVED_DATE_MONTH,EMPLOYER_STATES
1111,Certified,166,35294-1280,ALABAMA,18000.0,279999.96,PERU,H-1B,Other,10.0,ALABAMA
1284,Certified,198,87102,NEW MEXICO,2876.0,187199.00,PERU,H-1B,Other,3.0,NEW MEXICO
1530,Certified,210,98109,WASHINGTON,117300.0,110000.00,PERU,H-1B,Master's,1.0,WASHINGTON
2168,Certified,175,85250,ARIZONA,80.0,84660.00,PERU,L-1,Bachelor's,11.0,ARIZONA
2186,Certified,195,07094,NEW JERSEY,31000.0,102400.00,PERU,H-1B,Bachelor's,9.0,NEW JERSEY

In [15]:
states = []

for row in data5['EMPLOYER_STATES']:
    if row == "MAINE":
        states.append("NORTHEAST")
    elif row == "NEW HAMPSHIRE":
        states.append("NORTHEAST")
    elif row == "VERMONT":
        states.append("NORTHEAST")
    elif row == "MASSACHUSETTS":
        states.append("NORTHEAST")
    elif row == "RHODE ISLAND":
        states.append("NORTHEAST")
    elif row == "CONNECTICUT":
        states.append("NORTHEAST")
    elif row == "NEW YORK":
        states.append("NORTHEAST")
    elif row == "NEW JERSEY":
        states.append("NORTHEAST")
    elif row == "PENNSYLVANIA":
        states.append("NORTHEAST")
    elif row == "DELAWARE":
        states.append("SOUTH")
    elif row == "MARYLAND":
        states.append("SOUTH")
    elif row == "DISTRICT OF COLUMBIA":
        states.append("SOUTH")
    elif row == "VIRGINIA":
        states.append("SOUTH")
    elif row == "WEST VIRGINIA":
        states.append("SOUTH")
    elif row == "NORTH CAROLINA":
        states.append("SOUTH")
    elif row == "SOUTH CAROLINA":
        states.append("SOUTH")
    elif row == "GEORGIA":
        states.append("SOUTH")
    elif row == "FLORIDA":
        states.append("SOUTH")
    elif row == "ALABAMA":
        states.append("SOUTH")
    elif row == "TENNESSE":
        states.append("SOUTH")
    elif row == "KENTUCKY":
        states.append("SOUTH")
    elif row == "OHIO":
        states.append("MIDWEST")
    elif row == "MICHIGAN":
        states.append("MIDWEST")
    elif row == "INDIANA":
        states.append("MIDWEST")
    elif row == "MISSISSIPPI":
        states.append("SOUTH")
    elif row == "ILLINOIS":
        states.append("MIDWEST")
    elif row == "WISCONSIN":
        states.append("MIDWEST")
    elif row == "MINNESOTA":
        states.append("MIDWEST")
    elif row == "IOWA":
        states.append("MIDWEST")
    elif row == "MISSOURI":
        states.append("MIDWEST")
    elif row == "ARKANSAS":
        states.append("SOUTH")
    elif row == "LOUISIANA":
        states.append("SOUTH")
    elif row == "NORTH DAKOTA":
        states.append("MIDWEST")
    elif row == "SOUTH DAKOTA":
        states.append("MIDWEST")
    elif row == "NEBRASKA":
        states.append("MIDWEST")
    elif row == "KANSAS":
        states.append("MIDWEST")
    elif row == "OKLAHOMA":
        states.append("SOUTH")
    elif row == "TEXAS":
        states.append("SOUTH")
    elif row == "MONTANA":
        states.append("WEST")
    elif row == "WYOMING":
        states.append("WEST")
    elif row == "COLORADO":
        states.append("WEST")
    elif row == "NEW MEXICO":
        states.append("WEST")
    elif row == "IDAHO":
        states.append("WEST")
    elif row == "UTAH":
        states.append("WEST")
    elif row == "ARIZONA":
        states.append("WEST")
    elif row == "WASHINGTON":
        states.append("WEST")
    elif row == "OREGON":
        states.append("WEST")
    elif row == "NEVADA":
        states.append("WEST")
    elif row == "CALIFORNIA":
        states.append("WEST")
    elif row == "ALASKA":
        states.append("WEST")
    elif row == "HAWAII":
        states.append("WEST")
    elif row == "PUERTO RICO":
        states.append("OTHER")
    elif row == "TENNESSEE":
        states.append("SOUTH")
    elif row == "NORTHERN MARIANA ISLANDS":
        states.append("OTHER")
    elif row == "VIRGIN ISLANDS":
        states.append("OTHER")
    elif row == "GUAM":
        states.append("OTHER")
    else:
        states.append("UNKNOWN")
        
data5['EMPLOYER_REGIONS'] = states

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
data5['EMPLOYER_REGIONS'].value_counts()

SOUTH        162
NORTHEAST     80
WEST          77
MIDWEST       59
OTHER          7
UNKNOWN        1
Name: EMPLOYER_REGIONS, dtype: int64

In [17]:
data5.count()

CASE_STATUS                      386
DECISION_ELAPSED_DAYS            386
EMPLOYER_POSTAL_CODE             386
EMPLOYER_STATE                   386
EMPLOYER_NUM_EMPLOYEES           386
WAGE_OFFER_FROM_9089             386
COUNTRY_OF_CITIZENSHIP           386
CLASS_OF_ADMISSION               386
FOREIGN_WORKER_INFO_EDUCATION    386
CASE_RECEIVED_DATE_MONTH         386
EMPLOYER_STATES                  386
EMPLOYER_REGIONS                 386
dtype: int64

In [18]:
data5['DAY_BINS'] = pd.cut(x=data5['DECISION_ELAPSED_DAYS'], 
                             bins=[0, 90, 180, 365, 3600],
                           labels=['0-90', '91-180', '181-365', '366-3600'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
data5['DAY_BINS'].value_counts()

91-180      154
181-365      98
0-90         85
366-3600     47
Name: DAY_BINS, dtype: int64

In [20]:
data5['WAGE_BINS'] = pd.cut(x=data5['WAGE_OFFER_FROM_9089'], 
                             bins=[0, 25000, 50000, 75000, 100000, 500000],
                           labels=['0-25000', '25001-50000', '50001-75000', '75001-100000', '100000-500000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
data5['WAGE_BINS'].value_counts()

100000-500000    150
50001-75000       85
25001-50000       73
75001-100000      57
0-25000           20
Name: WAGE_BINS, dtype: int64

In [22]:
data5['EMPLOYEE_BINS'] = pd.cut(x=data5['EMPLOYER_NUM_EMPLOYEES'], 
                             bins=[0, 50, 100, 500, 1000, 10000, 1000000000],
                           labels=['0-50', '51-100', '101-500', '501-1000', '1001-10000', '10001-1000000000'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
data5['EMPLOYEE_BINS'].value_counts()

0-50                130
10001-1000000000     80
1001-10000           78
101-500              47
51-100               27
501-1000             22
Name: EMPLOYEE_BINS, dtype: int64

In [24]:
data5.count()

CASE_STATUS                      386
DECISION_ELAPSED_DAYS            386
EMPLOYER_POSTAL_CODE             386
EMPLOYER_STATE                   386
EMPLOYER_NUM_EMPLOYEES           386
WAGE_OFFER_FROM_9089             386
COUNTRY_OF_CITIZENSHIP           386
CLASS_OF_ADMISSION               386
FOREIGN_WORKER_INFO_EDUCATION    386
CASE_RECEIVED_DATE_MONTH         386
EMPLOYER_STATES                  386
EMPLOYER_REGIONS                 386
DAY_BINS                         384
WAGE_BINS                        385
EMPLOYEE_BINS                    384
dtype: int64

In [25]:
data6 = data5[[
    'CASE_STATUS',
    'EMPLOYEE_BINS',
    'WAGE_BINS',
    'EMPLOYER_REGIONS',
    'CASE_RECEIVED_DATE_MONTH',
    'FOREIGN_WORKER_INFO_EDUCATION',
    'CLASS_OF_ADMISSION',
    'DAY_BINS'
]]

In [26]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS
1111,Certified,10001-1000000000,100000-500000,SOUTH,10.0,Other,H-1B,91-180
1284,Certified,1001-10000,100000-500000,WEST,3.0,Other,H-1B,181-365
1530,Certified,10001-1000000000,100000-500000,WEST,1.0,Master's,H-1B,181-365
2168,Certified,51-100,75001-100000,WEST,11.0,Bachelor's,L-1,91-180
2186,Certified,10001-1000000000,100000-500000,NORTHEAST,9.0,Bachelor's,H-1B,181-365

In [27]:
data6.dtypes

CASE_STATUS                        object
EMPLOYEE_BINS                    category
WAGE_BINS                        category
EMPLOYER_REGIONS                   object
CASE_RECEIVED_DATE_MONTH          float64
FOREIGN_WORKER_INFO_EDUCATION      object
CLASS_OF_ADMISSION                 object
DAY_BINS                         category
dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder
num_encode = LabelEncoder()

In [29]:
data6['CLASS_OF_ADMISSION_CODE'] = num_encode.fit_transform(data6['CLASS_OF_ADMISSION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
data6['FOREIGN_WORKER_INFO_EDUCATION_CODE'] = num_encode.fit_transform(data6['FOREIGN_WORKER_INFO_EDUCATION'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
data6['WAGE_BINS'] = data6['WAGE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
data6['WAGE_BINS_CODE'] = num_encode.fit_transform(data6['WAGE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [33]:
data6['EMPLOYER_REGIONS_CODE'] = num_encode.fit_transform(data6['EMPLOYER_REGIONS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
data6['DAY_BINS'] = data6['DAY_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data6['DAY_BINS_CODE'] = num_encode.fit_transform(data6['DAY_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
data6['EMPLOYEE_BINS'] = data6['EMPLOYEE_BINS'].astype(str)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
data6['EMPLOYEE_BINS_CODE'] = num_encode.fit_transform(data6['EMPLOYEE_BINS'])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
data6.head()

,CASE_STATUS,EMPLOYEE_BINS,WAGE_BINS,EMPLOYER_REGIONS,CASE_RECEIVED_DATE_MONTH,FOREIGN_WORKER_INFO_EDUCATION,CLASS_OF_ADMISSION,DAY_BINS,CLASS_OF_ADMISSION_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,WAGE_BINS_CODE,EMPLOYER_REGIONS_CODE,DAY_BINS_CODE,EMPLOYEE_BINS_CODE
1111,Certified,10001-1000000000,100000-500000,SOUTH,10.0,Other,H-1B,91-180,8,6,1,3,3,1
1284,Certified,1001-10000,100000-500000,WEST,3.0,Other,H-1B,181-365,8,6,1,5,1,2
1530,Certified,10001-1000000000,100000-500000,WEST,1.0,Master's,H-1B,181-365,8,4,1,5,1,1
2168,Certified,51-100,75001-100000,WEST,11.0,Bachelor's,L-1,91-180,13,1,4,5,3,5
2186,Certified,10001-1000000000,100000-500000,NORTHEAST,9.0,Bachelor's,H-1B,181-365,8,1,1,1,1,1

In [39]:
# data7.to_excel('../Resources/ML2_Philippenes.xlsx', index = False)

In [40]:
data6.count()

CASE_STATUS                           386
EMPLOYEE_BINS                         386
WAGE_BINS                             386
EMPLOYER_REGIONS                      386
CASE_RECEIVED_DATE_MONTH              386
FOREIGN_WORKER_INFO_EDUCATION         386
CLASS_OF_ADMISSION                    386
DAY_BINS                              386
CLASS_OF_ADMISSION_CODE               386
FOREIGN_WORKER_INFO_EDUCATION_CODE    386
WAGE_BINS_CODE                        386
EMPLOYER_REGIONS_CODE                 386
DAY_BINS_CODE                         386
EMPLOYEE_BINS_CODE                    386
dtype: int64

In [41]:
data7 = data6[[
    'CASE_STATUS',
    'EMPLOYEE_BINS_CODE',
    'WAGE_BINS_CODE',
    'DAY_BINS_CODE',
    'FOREIGN_WORKER_INFO_EDUCATION_CODE',
    'CLASS_OF_ADMISSION_CODE',
    'CASE_RECEIVED_DATE_MONTH',
    'EMPLOYER_REGIONS_CODE'
]]

In [42]:
data7.head()

,CASE_STATUS,EMPLOYEE_BINS_CODE,WAGE_BINS_CODE,DAY_BINS_CODE,FOREIGN_WORKER_INFO_EDUCATION_CODE,CLASS_OF_ADMISSION_CODE,CASE_RECEIVED_DATE_MONTH,EMPLOYER_REGIONS_CODE
1111,Certified,1,1,3,6,8,10.0,3
1284,Certified,2,1,1,6,8,3.0,5
1530,Certified,1,1,1,4,8,1.0,5
2168,Certified,5,4,3,1,13,11.0,5
2186,Certified,1,1,1,1,8,9.0,1

In [43]:
data7.dtypes

CASE_STATUS                            object
EMPLOYEE_BINS_CODE                      int64
WAGE_BINS_CODE                          int64
DAY_BINS_CODE                           int64
FOREIGN_WORKER_INFO_EDUCATION_CODE      int64
CLASS_OF_ADMISSION_CODE                 int64
CASE_RECEIVED_DATE_MONTH              float64
EMPLOYER_REGIONS_CODE                   int64
dtype: object

In [44]:
X = data7.drop("CASE_STATUS", axis=1)
y = data7["CASE_STATUS"]
print(X.shape, y.shape)

(386, 7) (386,)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)

In [47]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [48]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [49]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=7))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [52]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [53]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=500,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From /anaconda3/envs/PythonData/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/500
 - 1s - loss: 0.5446 - acc: 0.8408
Epoch 2/500
 - 0s - loss: 0.4482 - acc: 0.8408
Epoch 3/500
 - 0s - loss: 0.4409 - acc: 0.8408
Epoch 4/500
 - 0s - loss: 0.4353 - acc: 0.8408
Epoch 5/500
 - 0s - loss: 0.4233 - acc: 0.8408
Epoch 6/500
 - 0s - loss: 0.4196 - acc: 0.8408
Epoch 7/500
 - 0s - loss: 0.4170 - acc: 0.8408
Epoch 8/500
 - 0s - loss: 0.4115 - acc: 0.8408
Epoch 9/500
 - 0s - loss: 0.4074 - acc: 0.8408
Epoch 10/500
 - 0s - loss: 0.4034 - acc: 0.8408
Epoch 11/500
 - 0s - loss: 0.3993 - acc: 0.8408
Epoch 12/500
 - 0s - loss: 0.3955 - acc: 0.8408
Epoch 13/500
 - 0s - loss: 0.3913 - acc: 0.8408
Epoch 14/500
 - 0s - loss: 0.3935 - acc: 0.8408
Epoch 15/500
 - 0s - loss: 0.3940 - acc: 0.8408
Epoch 16/500
 - 0s - loss: 0.3881 - acc: 0.8408
Epoch 17/500
 - 0s - loss: 0.3820 - acc: 0.8408
Epoch 18/500
 - 0s - loss: 0.3857 - acc: 0.8408
Epoch 19/500
 - 0s - loss: 0.3798 - acc: 0.8408
Epoch 20/500
 - 0s - loss: 0.3763 - acc: 0.8408
Epoch 21/500
 - 0s - loss: 0.3727 - acc: 0.8408
Epoch 22/500
 - 0s - loss: 0.3677 - acc: 0.8408
Epoch 23/500
 - 0s - loss: 0.3797 - acc: 0.8408
Epoch 24/500
 - 0s - loss: 0.3765 - acc: 0.8374
Epoch 25/500
 - 0s - loss: 0.3684 - acc: 0.8408
Epoch 26/500
 - 0s - loss: 0.3674 - acc: 0.8408
Epoch 27/500
 - 0s - loss: 0.3561 - acc: 0.8374
Epoch 28/500
 - 0s - loss: 0.3530 - acc: 0.8374
Epoch 29/500
 - 0s - loss: 0.3513 - acc: 0.8408
Epoch 30/500
 - 0s - loss: 0.3544 - acc: 0.8547
Epoch 31/500
 - 0s - loss: 0.3537 - acc: 0.8478
Epoch 32/500
 - 0s - loss: 0.3471 - acc: 0.8408
Epoch 33/500
 - 0s - loss: 0.3427 - acc: 0.8443
Epoch 34/500
 - 0s - loss: 0.3357 - acc: 0.8478
Epoch 35/500
 - 0s - loss: 0.3350 - acc: 0.8408
Epoch 36/500
 - 0s - loss: 0.3340 - acc: 0.8374
Epoch 37/500
 - 0s - loss: 0.3274 - acc: 0.8478
Epoch 38/500
 - 0s - loss: 0.3248 - acc: 0.8478
Epoch 39/500
 - 0s - loss: 0.3225 - acc: 0.8478
Epoch 40/500
 - 0s - loss: 0.3202 - acc: 0.8478
Epoch 41/500
 - 0s - loss: 0.3180 - acc: 0.8478
Epoch 42/500
 - 0s - loss: 0.3130 - acc: 0.8512
Epoch 43/500
 - 0s - loss: 0.3096 - acc: 0.8512
Epoch 44/500
 - 0s - loss: 0.3094 - acc: 0.8512
Epoch 45/500
 - 0s - loss: 0.3180 - acc: 0.8651
Epoch 46/500
 - 0s - loss: 0.3206 - acc: 0.8685
Epoch 47/500
 - 0s - loss: 0.3079 - acc: 0.8478
Epoch 48/500
 - 0s - loss: 0.3052 - acc: 0.8443
Epoch 49/500
 - 0s - loss: 0.2954 - acc: 0.8685
Epoch 50/500
 - 0s - loss: 0.3149 - acc: 0.8685
Epoch 51/500
 - 0s - loss: 0.3054 - acc: 0.8754
Epoch 52/500
 - 0s - loss: 0.2942 - acc: 0.8651
Epoch 53/500
 - 0s - loss: 0.2900 - acc: 0.8581
Epoch 54/500
 - 0s - loss: 0.2864 - acc: 0.8685
Epoch 55/500
 - 0s - loss: 0.2876 - acc: 0.8616
Epoch 56/500
 - 0s - loss: 0.2789 - acc: 0.8616
Epoch 57/500
 - 0s - loss: 0.2777 - acc: 0.8858
Epoch 58/500
 - 0s - loss: 0.2842 - acc: 0.8581
Epoch 59/500
 - 0s - loss: 0.2907 - acc: 0.8616
Epoch 60/500
 - 0s - loss: 0.2939 - acc: 0.8651
Epoch 61/500
 - 0s - loss: 0.2962 - acc: 0.8478
Epoch 62/500
 - 0s - loss: 0.2845 - acc: 0.8616
Epoch 63/500
 - 0s - loss: 0.2719 - acc: 0.8685
Epoch 64/500
 - 0s - loss: 0.2722 - acc: 0.8581
Epoch 65/500
 - 0s - loss: 0.2653 - acc: 0.8685
Epoch 66/500
 - 0s - loss: 0.2610 - acc: 0.8754
Epoch 67/500
 - 0s - loss: 0.2698 - acc: 0.8581
Epoch 68/500
 - 0s - loss: 0.2622 - acc: 0.8893
Epoch 69/500
 - 0s - loss: 0.2548 - acc: 0.8962
Epoch 70/500
 - 0s - loss: 0.2505 - acc: 0.8962
Epoch 71/500
 - 0s - loss: 0.2574 - acc: 0.8685
Epoch 72/500
 - 0s - loss: 0.2506 - acc: 0.8824
Epoch 73/500
 - 0s - loss: 0.2507 - acc: 0.9066
Epoch 74/500
 - 0s - loss: 0.2416 - acc: 0.8997
Epoch 75/500
 - 0s - loss: 0.2482 - acc: 0.8858
Epoch 76/500
 - 0s - loss: 0.2370 - acc: 0.9031
Epoch 77/500
 - 0s - loss: 0.2360 - acc: 0.9031
Epoch 78/500
 - 0s - loss: 0.2331 - acc: 0.9066
Epoch 79/500
 - 0s - loss: 0.2294 - acc: 0.8997
Epoch 80/500
 - 0s - loss: 0.2278 - acc: 0.9031
Epoch 81/500
 - 0s - loss: 0.2239 - acc: 0.9066
Epoch 82/500
 - 0s - loss: 0.2233 - acc: 0.9031
Epoch 83/500
 - 0s - loss: 0.2277 - acc: 0.8997
Epoch 84/500
 - 0s - loss: 0.2232 - acc: 0.9100
Epoch 85/500
 - 0s - loss: 0.2204 - acc: 0.9100
Epoch 86/500
 - 0s - loss: 0.2327 - acc: 0.9031
Epoch 87/500
 - 0s - loss: 0.2140 - acc: 0.9066
Epoch 88/500
 - 0s - loss: 0.2288 - acc: 0.9066
Epoch 89/500
 - 0s - loss: 0.2128 - acc: 0.9066
Epoch 90/500
 - 0s - loss: 0.2100 - acc: 0.9066
Epoch 91/500
 - 0s - loss: 0.2095 - acc: 0.9100
Epoch 92/500
 - 0s - loss: 0.2062 - acc: 0.9066
Epoch 93/500
 - 0s - loss: 0.2009 - acc: 0.9031
Epoch 94/500
 - 0s - loss: 0.2017 - acc: 0.9066
Epoch 95/500
 - 0s - loss: 0.1992 - acc: 0.9066
Epoch 96/500
 - 0s - loss: 0.1932 - acc: 0.9135
Epoch 97/500
 - 0s - loss: 0.1957 - acc: 0.9135
Epoch 98/500
 - 0s - loss: 0.1909 - acc: 0.9100
Epoch 99/500
 - 0s - loss: 0.1931 - acc: 0.9135
Epoch 100/500
 - 0s - loss: 0.1902 - acc: 0.9066
Epoch 101/500
 - 0s - loss: 0.1880 - acc: 0.9031
Epoch 102/500
 - 0s - loss: 0.1839 - acc: 0.9100
Epoch 103/500
 - 0s - loss: 0.1851 - acc: 0.9066
Epoch 104/500
 - 0s - loss: 0.2270 - acc: 0.8824
Epoch 105/500
 - 0s - loss: 0.2795 - acc: 0.8893
Epoch 106/500
 - 0s - loss: 0.2630 - acc: 0.8893
Epoch 107/500
 - 0s - loss: 0.2446 - acc: 0.8962
Epoch 108/500
 - 0s - loss: 0.2092 - acc: 0.8997
Epoch 109/500
 - 0s - loss: 0.1962 - acc: 0.9170
Epoch 110/500
 - 0s - loss: 0.1879 - acc: 0.9204
Epoch 111/500
 - 0s - loss: 0.1823 - acc: 0.9135
Epoch 112/500
 - 0s - loss: 0.1803 - acc: 0.9135
Epoch 113/500
 - 0s - loss: 0.1823 - acc: 0.9100
Epoch 114/500
 - 0s - loss: 0.1774 - acc: 0.9066
Epoch 115/500
 - 0s - loss: 0.1746 - acc: 0.9204
Epoch 116/500
 - 0s - loss: 0.1696 - acc: 0.9239
Epoch 117/500
 - 0s - loss: 0.1680 - acc: 0.9170
Epoch 118/500
 - 0s - loss: 0.1708 - acc: 0.9308
Epoch 119/500
 - 0s - loss: 0.1686 - acc: 0.9204
Epoch 120/500
 - 0s - loss: 0.1616 - acc: 0.9204
Epoch 121/500
 - 0s - loss: 0.1610 - acc: 0.9343
Epoch 122/500
 - 0s - loss: 0.1622 - acc: 0.9204
Epoch 123/500
 - 0s - loss: 0.1572 - acc: 0.9239
Epoch 124/500
 - 0s - loss: 0.1581 - acc: 0.9204
Epoch 125/500
 - 0s - loss: 0.1536 - acc: 0.9273
Epoch 126/500
 - 0s - loss: 0.1561 - acc: 0.9377
Epoch 127/500
 - 0s - loss: 0.1512 - acc: 0.9343
Epoch 128/500
 - 0s - loss: 0.1523 - acc: 0.9239
Epoch 129/500
 - 0s - loss: 0.1498 - acc: 0.9412
Epoch 130/500
 - 0s - loss: 0.1492 - acc: 0.9343
Epoch 131/500
 - 0s - loss: 0.1466 - acc: 0.9481
Epoch 132/500
 - 0s - loss: 0.1470 - acc: 0.9343
Epoch 133/500
 - 0s - loss: 0.1430 - acc: 0.9481
Epoch 134/500
 - 0s - loss: 0.1406 - acc: 0.9516
Epoch 135/500
 - 0s - loss: 0.1399 - acc: 0.9516
Epoch 136/500
 - 0s - loss: 0.1704 - acc: 0.9100
Epoch 137/500
 - 0s - loss: 0.1831 - acc: 0.9170
Epoch 138/500
 - 0s - loss: 0.1817 - acc: 0.9239
Epoch 139/500
 - 0s - loss: 0.1850 - acc: 0.9308
Epoch 140/500
 - 0s - loss: 0.2582 - acc: 0.8858
Epoch 141/500
 - 0s - loss: 0.2229 - acc: 0.9066
Epoch 142/500
 - 0s - loss: 0.2101 - acc: 0.8997
Epoch 143/500
 - 0s - loss: 0.1730 - acc: 0.9273
Epoch 144/500
 - 0s - loss: 0.2390 - acc: 0.9031
Epoch 145/500
 - 0s - loss: 0.2208 - acc: 0.9031
Epoch 146/500
 - 0s - loss: 0.1920 - acc: 0.9066
Epoch 147/500
 - 0s - loss: 0.1637 - acc: 0.9343
Epoch 148/500
 - 0s - loss: 0.1771 - acc: 0.9446
Epoch 149/500
 - 0s - loss: 0.1752 - acc: 0.9170
Epoch 150/500
 - 0s - loss: 0.1771 - acc: 0.9377
Epoch 151/500
 - 0s - loss: 0.1588 - acc: 0.9377
Epoch 152/500
 - 0s - loss: 0.1469 - acc: 0.9343
Epoch 153/500
 - 0s - loss: 0.1429 - acc: 0.9308
Epoch 154/500
 - 0s - loss: 0.1429 - acc: 0.9516
Epoch 155/500
 - 0s - loss: 0.1410 - acc: 0.9516
Epoch 156/500
 - 0s - loss: 0.1417 - acc: 0.9412
Epoch 157/500
 - 0s - loss: 0.1363 - acc: 0.9516
Epoch 158/500
 - 0s - loss: 0.1537 - acc: 0.9412
Epoch 159/500
 - 0s - loss: 0.1361 - acc: 0.9446
Epoch 160/500
 - 0s - loss: 0.1302 - acc: 0.9550
Epoch 161/500
 - 0s - loss: 0.1279 - acc: 0.9585
Epoch 162/500
 - 0s - loss: 0.1254 - acc: 0.9585
Epoch 163/500
 - 0s - loss: 0.1232 - acc: 0.9585
Epoch 164/500
 - 0s - loss: 0.1209 - acc: 0.9585

Epoch 165/500
 - 0s - loss: 0.1198 - acc: 0.9585
Epoch 166/500
 - 0s - loss: 0.1180 - acc: 0.9619
Epoch 167/500
 - 0s - loss: 0.1177 - acc: 0.9654
Epoch 168/500
 - 0s - loss: 0.1188 - acc: 0.9654
Epoch 169/500
 - 0s - loss: 0.1174 - acc: 0.9654
Epoch 170/500
 - 0s - loss: 0.1162 - acc: 0.9585
Epoch 171/500
 - 0s - loss: 0.1131 - acc: 0.9654
Epoch 172/500
 - 0s - loss: 0.1135 - acc: 0.9585
Epoch 173/500
 - 0s - loss: 0.1126 - acc: 0.9654
Epoch 174/500
 - 0s - loss: 0.1098 - acc: 0.9689
Epoch 175/500
 - 0s - loss: 0.1140 - acc: 0.9550
Epoch 176/500
 - 0s - loss: 0.1106 - acc: 0.9689
Epoch 177/500
 - 0s - loss: 0.1078 - acc: 0.9689
Epoch 178/500
 - 0s - loss: 0.1080 - acc: 0.9654
Epoch 179/500
 - 0s - loss: 0.1052 - acc: 0.9723
Epoch 180/500
 - 0s - loss: 0.1346 - acc: 0.9550
Epoch 181/500
 - 0s - loss: 0.1214 - acc: 0.9585
Epoch 182/500
 - 0s - loss: 0.1181 - acc: 0.9550
Epoch 183/500
 - 0s - loss: 0.1102 - acc: 0.9654
Epoch 184/500
 - 0s - loss: 0.1192 - acc: 0.9516
Epoch 185/500
 - 0s - loss: 0.1118 - acc: 0.9550
Epoch 186/500
 - 0s - loss: 0.1095 - acc: 0.9585
Epoch 187/500
 - 0s - loss: 0.1047 - acc: 0.9689
Epoch 188/500
 - 0s - loss: 0.1025 - acc: 0.9654
Epoch 189/500
 - 0s - loss: 0.0992 - acc: 0.9723
Epoch 190/500
 - 0s - loss: 0.0983 - acc: 0.9723
Epoch 191/500
 - 0s - loss: 0.0975 - acc: 0.9723
Epoch 192/500
 - 0s - loss: 0.0968 - acc: 0.9723
Epoch 193/500
 - 0s - loss: 0.0949 - acc: 0.9723
Epoch 194/500
 - 0s - loss: 0.0951 - acc: 0.9723
Epoch 195/500
 - 0s - loss: 0.0941 - acc: 0.9723
Epoch 196/500
 - 0s - loss: 0.1241 - acc: 0.9481
Epoch 197/500
 - 0s - loss: 0.1114 - acc: 0.9585
Epoch 198/500
 - 0s - loss: 0.1085 - acc: 0.9585
Epoch 199/500
 - 0s - loss: 0.0980 - acc: 0.9689
Epoch 200/500
 - 0s - loss: 0.0926 - acc: 0.9723
Epoch 201/500
 - 0s - loss: 0.0907 - acc: 0.9723
Epoch 202/500
 - 0s - loss: 0.0920 - acc: 0.9723
Epoch 203/500
 - 0s - loss: 0.0885 - acc: 0.9758
Epoch 204/500
 - 0s - loss: 0.0895 - acc: 0.9723
Epoch 205/500
 - 0s - loss: 0.0884 - acc: 0.9758
Epoch 206/500
 - 0s - loss: 0.1068 - acc: 0.9585
Epoch 207/500
 - 0s - loss: 0.0985 - acc: 0.9619
Epoch 208/500
 - 0s - loss: 0.0894 - acc: 0.9758
Epoch 209/500
 - 0s - loss: 0.0871 - acc: 0.9689
Epoch 210/500
 - 0s - loss: 0.0850 - acc: 0.9723
Epoch 211/500
 - 0s - loss: 0.0835 - acc: 0.9792
Epoch 212/500
 - 0s - loss: 0.0830 - acc: 0.9792
Epoch 213/500
 - 0s - loss: 0.0825 - acc: 0.9758
Epoch 214/500
 - 0s - loss: 0.1477 - acc: 0.9343
Epoch 215/500
 - 0s - loss: 0.1152 - acc: 0.9619
Epoch 216/500
 - 0s - loss: 0.1161 - acc: 0.9550
Epoch 217/500
 - 0s - loss: 0.0962 - acc: 0.9654
Epoch 218/500
 - 0s - loss: 0.0918 - acc: 0.9758
Epoch 219/500
 - 0s - loss: 0.0884 - acc: 0.9758
Epoch 220/500
 - 0s - loss: 0.1276 - acc: 0.9516
Epoch 221/500
 - 0s - loss: 0.1334 - acc: 0.9446
Epoch 222/500
 - 0s - loss: 0.1306 - acc: 0.9412
Epoch 223/500
 - 0s - loss: 0.0993 - acc: 0.9689
Epoch 224/500
 - 0s - loss: 0.0926 - acc: 0.9619
Epoch 225/500
 - 0s - loss: 0.0881 - acc: 0.9723
Epoch 226/500
 - 0s - loss: 0.1008 - acc: 0.9689
Epoch 227/500
 - 0s - loss: 0.0898 - acc: 0.9723
Epoch 228/500
 - 0s - loss: 0.0874 - acc: 0.9723
Epoch 229/500
 - 0s - loss: 0.0817 - acc: 0.9723
Epoch 230/500
 - 0s - loss: 0.0812 - acc: 0.9723
Epoch 231/500
 - 0s - loss: 0.0874 - acc: 0.9619
Epoch 232/500
 - 0s - loss: 0.0819 - acc: 0.9723
Epoch 233/500
 - 0s - loss: 0.0818 - acc: 0.9723
Epoch 234/500
 - 0s - loss: 0.0772 - acc: 0.9723
Epoch 235/500
 - 0s - loss: 0.0731 - acc: 0.9827
Epoch 236/500
 - 0s - loss: 0.0717 - acc: 0.9827
Epoch 237/500
 - 0s - loss: 0.0739 - acc: 0.9689
Epoch 238/500
 - 0s - loss: 0.0719 - acc: 0.9827
Epoch 239/500
 - 0s - loss: 0.0725 - acc: 0.9792
Epoch 240/500
 - 0s - loss: 0.0677 - acc: 0.9827
Epoch 241/500
 - 0s - loss: 0.0668 - acc: 0.9827
Epoch 242/500
 - 0s - loss: 0.0659 - acc: 0.9827
Epoch 243/500
 - 0s - loss: 0.1340 - acc: 0.9516
Epoch 244/500
 - 0s - loss: 0.1233 - acc: 0.9585
Epoch 245/500
 - 0s - loss: 0.1307 - acc: 0.9343
Epoch 246/500
 - 0s - loss: 0.0887 - acc: 0.9689
Epoch 247/500
 - 0s - loss: 0.0770 - acc: 0.9689
Epoch 248/500
 - 0s - loss: 0.0712 - acc: 0.9792
Epoch 249/500
 - 0s - loss: 0.0679 - acc: 0.9792
Epoch 250/500
 - 0s - loss: 0.0652 - acc: 0.9827
Epoch 251/500
 - 0s - loss: 0.0637 - acc: 0.9827
Epoch 252/500
 - 0s - loss: 0.0635 - acc: 0.9827
Epoch 253/500
 - 0s - loss: 0.0645 - acc: 0.9827
Epoch 254/500
 - 0s - loss: 0.0730 - acc: 0.9723
Epoch 255/500
 - 0s - loss: 0.0778 - acc: 0.9758
Epoch 256/500
 - 0s - loss: 0.0686 - acc: 0.9792
Epoch 257/500
 - 0s - loss: 0.0638 - acc: 0.9862
Epoch 258/500
 - 0s - loss: 0.0938 - acc: 0.9723
Epoch 259/500
 - 0s - loss: 0.0866 - acc: 0.9689
Epoch 260/500
 - 0s - loss: 0.0807 - acc: 0.9689
Epoch 261/500
 - 0s - loss: 0.0677 - acc: 0.9827
Epoch 262/500
 - 0s - loss: 0.0659 - acc: 0.9792
Epoch 263/500
 - 0s - loss: 0.0631 - acc: 0.9827
Epoch 264/500
 - 0s - loss: 0.0602 - acc: 0.9827
Epoch 265/500
 - 0s - loss: 0.0753 - acc: 0.9758
Epoch 266/500
 - 0s - loss: 0.0655 - acc: 0.9792
Epoch 267/500
 - 0s - loss: 0.0579 - acc: 0.9827
Epoch 268/500
 - 0s - loss: 0.0736 - acc: 0.9758
Epoch 269/500
 - 0s - loss: 0.0578 - acc: 0.9827
Epoch 270/500
 - 0s - loss: 0.0604 - acc: 0.9827
Epoch 271/500
 - 0s - loss: 0.0551 - acc: 0.9827
Epoch 272/500
 - 0s - loss: 0.0538 - acc: 0.9827
Epoch 273/500
 - 0s - loss: 0.0515 - acc: 0.9896
Epoch 274/500
 - 0s - loss: 0.0522 - acc: 0.9827
Epoch 275/500
 - 0s - loss: 0.0508 - acc: 0.9827
Epoch 276/500
 - 0s - loss: 0.0952 - acc: 0.9585
Epoch 277/500
 - 0s - loss: 0.0810 - acc: 0.9723
Epoch 278/500
 - 0s - loss: 0.0658 - acc: 0.9827
Epoch 279/500
 - 0s - loss: 0.0598 - acc: 0.9862
Epoch 280/500
 - 0s - loss: 0.0709 - acc: 0.9792
Epoch 281/500
 - 0s - loss: 0.0625 - acc: 0.9827
Epoch 282/500
 - 0s - loss: 0.0606 - acc: 0.9896
Epoch 283/500
 - 0s - loss: 0.1135 - acc: 0.9516
Epoch 284/500
 - 0s - loss: 0.0956 - acc: 0.9689
Epoch 285/500
 - 0s - loss: 0.0672 - acc: 0.9758
Epoch 286/500
 - 0s - loss: 0.0598 - acc: 0.9862
Epoch 287/500
 - 0s - loss: 0.0527 - acc: 0.9862
Epoch 288/500
 - 0s - loss: 0.0472 - acc: 0.9862
Epoch 289/500
 - 0s - loss: 0.0485 - acc: 0.9931
Epoch 290/500
 - 0s - loss: 0.0639 - acc: 0.9792
Epoch 291/500
 - 0s - loss: 0.0573 - acc: 0.9896
Epoch 292/500
 - 0s - loss: 0.0553 - acc: 0.9862
Epoch 293/500
 - 0s - loss: 0.0486 - acc: 0.9896
Epoch 294/500
 - 0s - loss: 0.0467 - acc: 0.9896
Epoch 295/500
 - 0s - loss: 0.0462 - acc: 0.9931
Epoch 296/500
 - 0s - loss: 0.0429 - acc: 0.9931
Epoch 297/500
 - 0s - loss: 0.0436 - acc: 0.9896
Epoch 298/500
 - 0s - loss: 0.0425 - acc: 0.9896
Epoch 299/500
 - 0s - loss: 0.0418 - acc: 0.9931
Epoch 300/500
 - 0s - loss: 0.0421 - acc: 0.9931
Epoch 301/500
 - 0s - loss: 0.0676 - acc: 0.9792
Epoch 302/500
 - 0s - loss: 0.0717 - acc: 0.9827
Epoch 303/500
 - 0s - loss: 0.0647 - acc: 0.9792
Epoch 304/500
 - 0s - loss: 0.0536 - acc: 0.9896
Epoch 305/500
 - 0s - loss: 0.0476 - acc: 0.9896
Epoch 306/500
 - 0s - loss: 0.0474 - acc: 0.9862
Epoch 307/500
 - 0s - loss: 0.0434 - acc: 0.9896
Epoch 308/500
 - 0s - loss: 0.1084 - acc: 0.9654
Epoch 309/500
 - 0s - loss: 0.1036 - acc: 0.9550
Epoch 310/500
 - 0s - loss: 0.0670 - acc: 0.9862
Epoch 311/500
 - 0s - loss: 0.0611 - acc: 0.9827
Epoch 312/500
 - 0s - loss: 0.0539 - acc: 0.9792
Epoch 313/500
 - 0s - loss: 0.0456 - acc: 0.9862
Epoch 314/500
 - 0s - loss: 0.0438 - acc: 0.9896
Epoch 315/500
 - 0s - loss: 0.0417 - acc: 0.9896
Epoch 316/500
 - 0s - loss: 0.0407 - acc: 0.9896
Epoch 317/500
 - 0s - loss: 0.0407 - acc: 0.9931
Epoch 318/500
 - 0s - loss: 0.0443 - acc: 0.9862
Epoch 319/500
 - 0s - loss: 0.0397 - acc: 0.9931
Epoch 320/500
 - 0s - loss: 0.0380 - acc: 0.9931
Epoch 321/500
 - 0s - loss: 0.0398 - acc: 0.9931
Epoch 322/500
 - 0s - loss: 0.0406 - acc: 0.9931
Epoch 323/500
 - 0s - loss: 0.0370 - acc: 0.9931
Epoch 324/500
 - 0s - loss: 0.0362 - acc: 0.9931
Epoch 325/500
 - 0s - loss: 0.0356 - acc: 0.9931
Epoch 326/500
 - 0s - loss: 0.0351 - acc: 0.9896
Epoch 327/500
 - 0s - loss: 0.0349 - acc: 0.9896
Epoch 328/500
 - 0s - loss: 0.0343 - acc: 0.9931
Epoch 329/500
 - 0s - loss: 0.0347 - acc: 0.9931
Epoch 330/500
 - 0s - loss: 0.0338 - acc: 0.9931
Epoch 331/500
 - 0s - loss: 0.0501 - acc: 0.9792
Epoch 332/500
 - 0s - loss: 0.0377 - acc: 0.9931

Epoch 333/500
 - 0s - loss: 0.0385 - acc: 0.9862
Epoch 334/500
 - 0s - loss: 0.0474 - acc: 0.9862
Epoch 335/500
 - 0s - loss: 0.0381 - acc: 0.9965
Epoch 336/500
 - 0s - loss: 0.0373 - acc: 0.9931
Epoch 337/500
 - 0s - loss: 0.0358 - acc: 0.9931
Epoch 338/500
 - 0s - loss: 0.0328 - acc: 0.9931
Epoch 339/500
 - 0s - loss: 0.0327 - acc: 0.9931
Epoch 340/500
 - 0s - loss: 0.0331 - acc: 0.9931
Epoch 341/500
 - 0s - loss: 0.0338 - acc: 0.9931
Epoch 342/500
 - 0s - loss: 0.0309 - acc: 0.9931
Epoch 343/500
 - 0s - loss: 0.0322 - acc: 0.9931
Epoch 344/500
 - 0s - loss: 0.0327 - acc: 0.9931
Epoch 345/500
 - 0s - loss: 0.0316 - acc: 0.9896
Epoch 346/500
 - 0s - loss: 0.0305 - acc: 0.9931
Epoch 347/500
 - 0s - loss: 0.0309 - acc: 0.9931
Epoch 348/500
 - 0s - loss: 0.0307 - acc: 0.9896
Epoch 349/500
 - 0s - loss: 0.0296 - acc: 0.9862
Epoch 350/500
 - 0s - loss: 0.0303 - acc: 0.9896
Epoch 351/500
 - 0s - loss: 0.0292 - acc: 0.9931
Epoch 352/500
 - 0s - loss: 0.0295 - acc: 0.9896
Epoch 353/500
 - 0s - loss: 0.0285 - acc: 0.9896
Epoch 354/500
 - 0s - loss: 0.0286 - acc: 0.9931
Epoch 355/500
 - 0s - loss: 0.0287 - acc: 0.9896
Epoch 356/500
 - 0s - loss: 0.0281 - acc: 0.9931
Epoch 357/500
 - 0s - loss: 0.0278 - acc: 0.9931
Epoch 358/500
 - 0s - loss: 0.0274 - acc: 0.9931
Epoch 359/500
 - 0s - loss: 0.0276 - acc: 0.9931
Epoch 360/500
 - 0s - loss: 0.0307 - acc: 0.9931
Epoch 361/500
 - 0s - loss: 0.0310 - acc: 0.9896
Epoch 362/500
 - 0s - loss: 0.0273 - acc: 0.9965
Epoch 363/500
 - 0s - loss: 0.0323 - acc: 0.9931
Epoch 364/500
 - 0s - loss: 0.0407 - acc: 0.9896
Epoch 365/500
 - 0s - loss: 0.2573 - acc: 0.8962
Epoch 366/500
 - 0s - loss: 0.1976 - acc: 0.9135
Epoch 367/500
 - 0s - loss: 0.0897 - acc: 0.9585
Epoch 368/500
 - 0s - loss: 0.0438 - acc: 0.9827
Epoch 369/500
 - 0s - loss: 0.0500 - acc: 0.9862
Epoch 370/500
 - 0s - loss: 0.0368 - acc: 0.9931
Epoch 371/500
 - 0s - loss: 0.0688 - acc: 0.9689
Epoch 372/500
 - 0s - loss: 0.1589 - acc: 0.9343
Epoch 373/500
 - 0s - loss: 0.1051 - acc: 0.9516
Epoch 374/500
 - 0s - loss: 0.0834 - acc: 0.9516
Epoch 375/500
 - 0s - loss: 0.0632 - acc: 0.9792
Epoch 376/500
 - 0s - loss: 0.0458 - acc: 0.9862
Epoch 377/500
 - 0s - loss: 0.0455 - acc: 0.9827
Epoch 378/500
 - 0s - loss: 0.0435 - acc: 0.9827
Epoch 379/500
 - 0s - loss: 0.0391 - acc: 0.9896
Epoch 380/500
 - 0s - loss: 0.0375 - acc: 0.9862
Epoch 381/500
 - 0s - loss: 0.0363 - acc: 0.9896
Epoch 382/500
 - 0s - loss: 0.0339 - acc: 0.9896
Epoch 383/500
 - 0s - loss: 0.0339 - acc: 0.9896
Epoch 384/500
 - 0s - loss: 0.0539 - acc: 0.9827
Epoch 385/500
 - 0s - loss: 0.0436 - acc: 0.9862
Epoch 386/500
 - 0s - loss: 0.0388 - acc: 0.9896
Epoch 387/500
 - 0s - loss: 0.0333 - acc: 0.9896
Epoch 388/500
 - 0s - loss: 0.0317 - acc: 0.9931
Epoch 389/500
 - 0s - loss: 0.0305 - acc: 0.9896
Epoch 390/500
 - 0s - loss: 0.0298 - acc: 0.9896
Epoch 391/500
 - 0s - loss: 0.0278 - acc: 0.9931
Epoch 392/500
 - 0s - loss: 0.0285 - acc: 0.9896
Epoch 393/500
 - 0s - loss: 0.0452 - acc: 0.9896
Epoch 394/500
 - 0s - loss: 0.0406 - acc: 0.9862
Epoch 395/500
 - 0s - loss: 0.0392 - acc: 0.9896
Epoch 396/500
 - 0s - loss: 0.0329 - acc: 0.9896
Epoch 397/500
 - 0s - loss: 0.0298 - acc: 0.9896
Epoch 398/500
 - 0s - loss: 0.0293 - acc: 0.9862
Epoch 399/500
 - 0s - loss: 0.0282 - acc: 0.9862
Epoch 400/500
 - 0s - loss: 0.0269 - acc: 0.9896
Epoch 401/500
 - 0s - loss: 0.0271 - acc: 0.9896
Epoch 402/500
 - 0s - loss: 0.0266 - acc: 0.9862
Epoch 403/500
 - 0s - loss: 0.0271 - acc: 0.9931
Epoch 404/500
 - 0s - loss: 0.0255 - acc: 0.9896
Epoch 405/500
 - 0s - loss: 0.0257 - acc: 0.9931
Epoch 406/500
 - 0s - loss: 0.0278 - acc: 0.9931
Epoch 407/500
 - 0s - loss: 0.0256 - acc: 0.9931
Epoch 408/500
 - 0s - loss: 0.0269 - acc: 0.9931
Epoch 409/500
 - 0s - loss: 0.0248 - acc: 0.9896
Epoch 410/500
 - 0s - loss: 0.0251 - acc: 0.9862
Epoch 411/500
 - 0s - loss: 0.0238 - acc: 0.9896
Epoch 412/500
 - 0s - loss: 0.0296 - acc: 0.9931
Epoch 413/500
 - 0s - loss: 0.0302 - acc: 0.9931
Epoch 414/500
 - 0s - loss: 0.0300 - acc: 0.9931
Epoch 415/500
 - 0s - loss: 0.0256 - acc: 0.9896
Epoch 416/500
 - 0s - loss: 0.0250 - acc: 0.9896
Epoch 417/500
 - 0s - loss: 0.0264 - acc: 0.9896
Epoch 418/500
 - 0s - loss: 0.0257 - acc: 0.9931
Epoch 419/500
 - 0s - loss: 0.0247 - acc: 0.9931
Epoch 420/500
 - 0s - loss: 0.0244 - acc: 0.9931
Epoch 421/500
 - 0s - loss: 0.0242 - acc: 0.9896
Epoch 422/500
 - 0s - loss: 0.0226 - acc: 0.9931
Epoch 423/500
 - 0s - loss: 0.0219 - acc: 0.9931
Epoch 424/500
 - 0s - loss: 0.0230 - acc: 0.9931
Epoch 425/500
 - 0s - loss: 0.0222 - acc: 0.9896
Epoch 426/500
 - 0s - loss: 0.0228 - acc: 0.9931
Epoch 427/500
 - 0s - loss: 0.0257 - acc: 0.9862
Epoch 428/500
 - 0s - loss: 0.0218 - acc: 0.9896
Epoch 429/500
 - 0s - loss: 0.0221 - acc: 0.9896
Epoch 430/500
 - 0s - loss: 0.0218 - acc: 0.9931
Epoch 431/500
 - 0s - loss: 0.0223 - acc: 0.9896
Epoch 432/500
 - 0s - loss: 0.0225 - acc: 0.9931
Epoch 433/500
 - 0s - loss: 0.0232 - acc: 0.9931
Epoch 434/500
 - 0s - loss: 0.0216 - acc: 0.9931
Epoch 435/500
 - 0s - loss: 0.0212 - acc: 0.9931
Epoch 436/500
 - 0s - loss: 0.0215 - acc: 0.9896
Epoch 437/500
 - 0s - loss: 0.0214 - acc: 0.9896
Epoch 438/500
 - 0s - loss: 0.0209 - acc: 0.9931
Epoch 439/500
 - 0s - loss: 0.0197 - acc: 0.9931
Epoch 440/500
 - 0s - loss: 0.0207 - acc: 0.9931
Epoch 441/500
 - 0s - loss: 0.0193 - acc: 0.9931
Epoch 442/500
 - 0s - loss: 0.0202 - acc: 0.9931
Epoch 443/500
 - 0s - loss: 0.0198 - acc: 0.9931
Epoch 444/500
 - 0s - loss: 0.0206 - acc: 0.9896
Epoch 445/500
 - 0s - loss: 0.0195 - acc: 0.9896
Epoch 446/500
 - 0s - loss: 0.0200 - acc: 0.9896
Epoch 447/500
 - 0s - loss: 0.0207 - acc: 0.9862
Epoch 448/500
 - 0s - loss: 0.0191 - acc: 0.9931
Epoch 449/500
 - 0s - loss: 0.0190 - acc: 0.9931
Epoch 450/500
 - 0s - loss: 0.0194 - acc: 0.9896
Epoch 451/500
 - 0s - loss: 0.0292 - acc: 0.9896
Epoch 452/500
 - 0s - loss: 0.0313 - acc: 0.9896
Epoch 453/500
 - 0s - loss: 0.0196 - acc: 0.9931
Epoch 454/500
 - 0s - loss: 0.0221 - acc: 0.9931
Epoch 455/500
 - 0s - loss: 0.0186 - acc: 0.9931
Epoch 456/500
 - 0s - loss: 0.0204 - acc: 0.9931
Epoch 457/500
 - 0s - loss: 0.0195 - acc: 0.9862
Epoch 458/500
 - 0s - loss: 0.0184 - acc: 0.9931
Epoch 459/500
 - 0s - loss: 0.0248 - acc: 0.9931
Epoch 460/500
 - 0s - loss: 0.0211 - acc: 0.9931
Epoch 461/500
 - 0s - loss: 0.0230 - acc: 0.9931
Epoch 462/500
 - 0s - loss: 0.0197 - acc: 0.9896
Epoch 463/500
 - 0s - loss: 0.0193 - acc: 0.9931
Epoch 464/500
 - 0s - loss: 0.0187 - acc: 0.9896
Epoch 465/500
 - 0s - loss: 0.0181 - acc: 0.9862
Epoch 466/500
 - 0s - loss: 0.0189 - acc: 0.9931
Epoch 467/500
 - 0s - loss: 0.0195 - acc: 0.9896
Epoch 468/500
 - 0s - loss: 0.0181 - acc: 0.9931
Epoch 469/500
 - 0s - loss: 0.0181 - acc: 0.9896
Epoch 470/500
 - 0s - loss: 0.0384 - acc: 0.9827
Epoch 471/500
 - 0s - loss: 0.0308 - acc: 0.9896
Epoch 472/500
 - 0s - loss: 0.0255 - acc: 0.9896
Epoch 473/500
 - 0s - loss: 0.0217 - acc: 0.9862
Epoch 474/500
 - 0s - loss: 0.0185 - acc: 0.9931
Epoch 475/500
 - 0s - loss: 0.0191 - acc: 0.9896
Epoch 476/500
 - 0s - loss: 0.0199 - acc: 0.9931
Epoch 477/500
 - 0s - loss: 0.0222 - acc: 0.9896
Epoch 478/500
 - 0s - loss: 0.0187 - acc: 0.9862
Epoch 479/500
 - 0s - loss: 0.0181 - acc: 0.9931
Epoch 480/500
 - 0s - loss: 0.0182 - acc: 0.9896
Epoch 481/500
 - 0s - loss: 0.0188 - acc: 0.9931
Epoch 482/500
 - 0s - loss: 0.0185 - acc: 0.9896
Epoch 483/500
 - 0s - loss: 0.0189 - acc: 0.9931
Epoch 484/500
 - 0s - loss: 0.0227 - acc: 0.9896
Epoch 485/500
 - 0s - loss: 0.0187 - acc: 0.9896
Epoch 486/500
 - 0s - loss: 0.0179 - acc: 0.9931
Epoch 487/500
 - 0s - loss: 0.0170 - acc: 0.9896
Epoch 488/500
 - 0s - loss: 0.0179 - acc: 0.9931
Epoch 489/500
 - 0s - loss: 0.0167 - acc: 0.9896
Epoch 490/500
 - 0s - loss: 0.0169 - acc: 0.9862
Epoch 491/500
 - 0s - loss: 0.0165 - acc: 0.9931
Epoch 492/500
 - 0s - loss: 0.0175 - acc: 0.9896
Epoch 493/500
 - 0s - loss: 0.0191 - acc: 0.9896
Epoch 494/500
 - 0s - loss: 0.0174 - acc: 0.9862
Epoch 495/500
 - 0s - loss: 0.0172 - acc: 0.9931
Epoch 496/500
 - 0s - loss: 0.0166 - acc: 0.9931
Epoch 497/500
 - 0s - loss: 0.0800 - acc: 0.9654
Epoch 498/500
 - 0s - loss: 0.2514 - acc: 0.9204
Epoch 499/500
 - 0s - loss: 0.1321 - acc: 0.9308
Epoch 500/500

 - 0s - loss: 0.1063 - acc: 0.9585

In [54]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 0s - loss: 0.4214 - acc: 0.8454
Normal Neural Network - Loss: 0.4213842024508211, Accuracy: 0.8453608155250549

In [55]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [56]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['Certified' 'Certified' 'Denied' 'Certified' 'Certified' 'Certified'
 'Denied' 'Certified' 'Certified' 'Certified']
Actual Labels: ['Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Certified', 'Denied', 'Certified', 'Denied', 'Certified']